### ISSUE TITLE
Unchecking Create as draft. Not being respected on Bulk Pull

### ISSUE THREAD

**Issue by aaronware** [10up/distributor#1008]
### Describe the bug

Feature Bulk Pull is not working as expected. When unchecking the "Pull as draft" option the UI reflects the changes however any post type (Posts, Pages, and Products were tested in this scenario) all set the Pulled status as draft.

When pushing a post type the post status is respected.

### Steps to Reproduce

1. Connect 2 sites
2. Visit Remote/Connected Site
3. Visit Bulk Pull area
4. Select a post type and filter
5. Uncheck Create as draft
6. Either use the bulk dropdown or the singular "pull" action to pull the remote post from your external connection.
7. The post will be distributed properly however the post will be set to draft whether the option is checked or not.

### Environment information

- Device: MacBook Pro 2021
- Chrome Latest

### WordPress information

`
### wp-core ###

version: 6.1.1
site_language: en_US
user_language: en_US
timezone: -05:00
permalink: /blog/%postname%
https_status: true
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: production
user_count: 10001
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /public_html
wordpress_size: loading...
uploads_path: /public_html/wp-content/uploads
uploads_size: loading...
themes_path: /public_html/wp-content/themes
themes_size: loading...
plugins_path: /public_html/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (3) ###

advanced-cache.php: true
db.php: true
object-cache.php: true

### wp-active-theme ###

name: REDACTED
version: 1.2.4
author: Linchpin
author_website: https://linchpin.com
parent_theme: none
theme_features: core-block-patterns, block-templates, widgets-block-editor, post-thumbnails, woocommerce, automatic-feed-links, title-tag, html5, editor-styles, editor-style, menus, infinite-scroll, widgets
theme_path: /public_html/wp-content/themes/redacted
auto_update: Disabled

### wp-themes-inactive (1) ###

Twenty Twenty-Two: version: 1.3, author: the WordPress team, Auto-updates disabled

### wp-mu-plugins (1) ###

Object Cache Pro (MU): version: 1.17.0, author: Rhubarb Group

### wp-plugins-active (47) ###

Adspiration Promo Blocks for WordPress By Linchpin: version: 0.5.5, author: Linchpin, Aaron Ware, Auto-updates disabled
Akismet Anti-Spam: version: 5.0.2, author: Automattic, Auto-updates disabled
Courier Notices: version: 1.5.5, author: Linchpin, Auto-updates disabled
Custom Facebook Feed Pro - Extensions: version: 1.7.3, author: Smash Balloon, Auto-updates disabled
Custom Facebook Feed Pro Smash: version: 4.2.6, author: Smash Balloon, Auto-updates disabled
Distributor: version: 1.9.0, author: 10up Inc., Auto-updates disabled
Feeds for YouTube Pro Developer: version: 2.0.6, author: Smash Balloon, Auto-updates disabled
REDACTED Aquatics Functionality: version: 0.2.1, author: Linchpin, Auto-updates disabled
Genesis Blocks Pro: version: 1.8.3, author: WP Engine, Auto-updates disabled
Getwid: version: 1.8.2, author: MotoPress, Auto-updates disabled
GP Auto Login: version: 2.2.2, author: Gravity Wiz, Auto-updates disabled
Gravity Forms: version: 2.6.8, author: Gravity Forms (latest version: 2.6.9), Auto-updates disabled
Gravity Forms Address Enhanced: version: 1.25.0, author: WebAware, Auto-updates disabled
Gravity Forms Advanced Post Creation Add-On: version: 1.3, author: Gravity Forms, Auto-updates disabled
Gravity Forms Chained Selects Add-On: version: 1.5, author: Gravity Forms, Auto-updates disabled
Gravity Forms Multilingual: version: 1.6.3, author: OnTheGoSystems, Auto-updates disabled
Gravity Forms User Registration Add-On: version: 5.0, author: Gravity Forms, Auto-updates disabled
Gravity Perks: version: 2.2.9, author: Gravity Wiz, Auto-updates disabled
Imagify: version: 2.1, author: Imagify – Optimize Images & Convert WebP, Auto-updates disabled
Instagram Feed Pro Developer: version: 6.2, author: Smash Balloon, Auto-updates disabled
Integration for WooCommerce and Salesforce Pro: version: 1.6.1, author: CRM Perks., Auto-updates disabled
Layout Grid: version: 1.8.2, author: Automattic, Auto-updates disabled
Mantle: version: 1.3.18, author: Linchpin, Auto-updates disabled
More Below Block: version: 0.1.0, author: Linchpin, Auto-updates disabled
Qubely - Advanced Gutenberg Blocks: version: 1.8.4, author: Themeum, Auto-updates disabled
Qubely Pro: version: 1.4.1, author: Themeum, Auto-updates disabled
Query Monitor: version: 3.11.1, author: John Blackbourn, Auto-updates disabled
Read Meter - Reading Time & Progress Bar for WordPress.: version: 1.0.6, author: Brainstorm Force, Auto-updates disabled
Shortcode in Menus: version: 3.5.1, author: Gagan Deep Singh, Auto-updates disabled
Smash Balloon Social Wall: version: 1.0.10, author: Smash Balloon, Auto-updates disabled
WooCommerce: version: 7.2.2, author: Automattic (latest version: 7.2.3), Auto-updates disabled
WooCommerce Multilingual & Multicurrency: version: 5.1.1, author: OnTheGoSystems (latest version: 5.1.2), Auto-updates disabled
WooCommerce Variation Swatches and Photos: version: 3.1.6, author: Element Stark, Auto-updates disabled
WP All Import - WooCommerce Import Add-On Pro: version: 3.3.4, author: Soflyy, Auto-updates disabled
WP All Import Pro: version: 4.7.8, author: Soflyy, Auto-updates disabled
WP Gravity Forms Salesforce Pro: version: 1.3.7, author: CRM Perks., Auto-updates disabled
WP Mail SMTP: version: 3.7.0, author: WPForms, Auto-updates disabled
WPML All Import: version: 2.3.0, author: OnTheGoSystems, Auto-updates disabled
WPML Media: version: 2.7.1, author: OnTheGoSystems, Auto-updates disabled
WPML Multilingual CMS: version: 4.5.14, author: OnTheGoSystems, Auto-updates disabled
WPML SEO: version: 2.1.0, author: OnTheGoSystems, Auto-updates disabled
WPML String Translation: version: 3.2.3, author: OnTheGoSystems, Auto-updates disabled
WP Store Locator (Editted for additional functionality): version: 100.0.0, author: Tijmen Smit, Auto-updates disabled
WP Widget in Navigation: version: 3.0.2, author: Yudiz Solutions Pvt. Ltd., Auto-updates disabled
YITH WooCommerce Ajax Product Filter Premium: version: 4.15.0, author: YITH, Auto-updates disabled
Yoast Duplicate Post: version: 4.5, author: Enrico Battocchi & Team Yoast, Auto-updates disabled
Yoast SEO: version: 19.13, author: Team Yoast (latest version: 20.0), Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
imagick_version: 3.6.0
file_uploads: File uploads is turned off
post_max_size: 50M
upload_max_filesize: 50M
max_effective_size: 50 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 31 GB
	imagick::RESOURCETYPE_DISK: 1.844674407371E+19
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 31 GB
	imagick::RESOURCETYPE_MEMORY: 16 GB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HEIC, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.27

### wp-server ###

server_architecture: Linux 4.19.0-22-amd64 x86_64
httpd_software: Apache/2.4.54 (Debian)
php_version: 8.0.24 64bit
php_sapi: fpm-fcgi
max_input_variables: 10000
time_limit: 500
memory_limit: 1024M
max_input_time: 240
upload_max_filesize: 50M
php_post_max_size: 50M
curl_version: 7.64.0 OpenSSL/1.1.1n
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.4.20-MariaDB-1:10.4.20+maria~buster-log
client_version: mysqlnd 8.0.24
max_allowed_packet: 134217728
max_connections: 1200

### wp-constants ###

WP_HOME: REDACTED
WP_SITEURL: REDACTED
WP_CONTENT_DIR: /public_html/wp-content
WP_PLUGIN_DIR: /public_html/wp-content/plugins
WP_MEMORY_LIMIT: 1024M
WP_MAX_MEMORY_LIMIT: 1024M
WP_DEBUG: true
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### objectcache ###

general-status: Connected
general-dropin: Valid
general-license: Valid
general-env: production
general-multisite: No
general-mu: Yes
general-vcs: No
general-host: cloudways
general-eviction-policy: allkeys-lfu
general-compressions: LZF, LZ4, ZSTD
general-basename: redis-cache-pro.php
general-client: RedisCachePro\Clients\PhpRedis
versions-php: 8.0.24
versions-igbinary: 3.2.7
versions-phpredis: 5.3.7
versions-relay: Not installed
versions-redis: 7.0.5
versions-plugin: 1.17.0
versions-dropin: 1.17.0
statistics-redis-memory: 2 GB of 2 GB
statistics-redis-keys: 1873722
groups-global: [
    "analytics",
    "blog-details",
    "blog-id-cache",
    "blog-lookup",
    "blog_meta",
    "global-posts",
    "networks",
    "sites",
    "site-details",
    "site-options",
    "site-transient",
    "rss",
    "users",
    "useremail",
    "userlogins",
    "usermeta",
    "user_meta",
    "userslugs"
]
groups-non-persistent: [
    "counts",
    "plugins",
    "themes",
    "WPML_ST_Package_Factory",
    "wpml-all-meta-product-variation",
    "gf_address_enhanced_country"
]
groups-non-prefetchable: [
    "analytics",
    "userlogins",
    "wc_session_id"
]
config-token: ••••••••001c
config-connector: RedisCachePro\Connectors\PhpRedisConnector
config-cache: RedisCachePro\ObjectCaches\PhpRedisObjectCache
config-logger: RedisCachePro\Loggers\ErrorLogLogger
config-log_levels: emergency, alert, critical, error
config-scheme: tcp
config-host: 127.0.0.1
config-port: 6379
config-database: 0
config-username: null
config-password: null
config-prefix: mdcxftyyad
config-maxttl: null
config-timeout: 2.5s
config-read_timeout: 2.5s
config-retry_interval: 25ms
config-retries: 5
config-backoff: smart
config-persistent: false
config-shared: null
config-async_flush: true
config-group_flush: keys
config-network_flush: all
config-cluster: null
config-cluster_failover: error
config-servers: null
config-replication_strategy: distribute
config-sentinels: null
config-service: null
config-tracer: newrelic
config-serializer: igbinary
config-compression: zstd
config-global_groups: null
config-non_persistent_groups: null
config-non_prefetchable_groups: null
config-prefetch: true
config-split_alloptions: true
config-analytics: {
    "enabled": true,
    "persist": true,
    "retention": 7200,
    "footnote": true
}
config-relay: {
    "cache": true,
    "listeners": false,
    "invalidations": true,
    "allowed": null,
    "ignored": [
        "*:analytics:*"
    ]
}
config-tls_options: null
config-updates: true
config-debug: false
config-save_commands: false
environment-WP_REDIS_DISABLED: 0
environment-OBJECTCACHE_CONFIG: undefined
constants-WP_DEBUG: true
constants-SAVEQUERIES: true
constants-WP_REDIS_DIR: undefined
constants-WP_REDIS_DISABLED: false
constants-WP_REDIS_CONFIG: {
    "token": "••••••••001c",
    "host": "127.0.0.1",
    "port": 6379,
    "database": 0,
    "timeout": 2.5,
    "read_timeout": 2.5,
    "split_alloptions": true,
    "async_flush": true,
    "client": "phpredis",
    "compression": "zstd",
    "serializer": "igbinary",
    "prefetch": true,
    "debug": false,
    "save_commands": false,
    "prefix": "mdcxftyyad"
}

### wp_mail_smtp ###

version: 3.7.0
license_key_type: lite
debug: No debug notices found.
lite_install_date: Aug 17, 2021 @ 10:26am

### distributor ###

0: 1.9.0
1: Yes
2: dev@linchpin.com
3: 
	Override Author Byline: Yes
	Media Handling: Featured image and attached images
4: N/A
5: 
	Hub -> UK: 
- URL: https://REDACTED/wp-json
- Version: 1.9.0
- Status: valid
- Auth method: Username / Password
- Username: REDACTED
- Roles Allowed to Push: editor, author, shop_manager, power_admin
- Additional data: {"errors":[], "can_post":["post", "page", "attachment", "nav_menu_item", "wp_block", "wp_template", "wp_template_part", "wp_navigation", "product", "wpsl_stores", "adspiration_promo", "REDACTED_faq", "REDACTED_pac", "product_registration", "REDACTED_species_sl", "jp_pay_order", "jp_pay_product", "getwid_template_part"], "can_get":["post", "page", "attachment", "nav_menu_item", "wp_block", "wp_template", "wp_template_part", "wp_navigation", "product", "wpsl_stores", "adspiration_promo", "REDACTED_faq", "REDACTED_pac", "product_registration", "REDACTED_species_sl", "jp_pay_order", "jp_pay_product", "getwid_template_part"], "endpoint_suggestion":false, "is_authenticated":"yes"}
	Hub -> USA: 
- URL: https://REDACTED/wp-json
- Version: 1.9.0
- Status: valid
- Auth method: Username / Password
- Username: REDACTED
- Roles Allowed to Push: editor, author, power_admin, translator
- Additional data: {"errors":[], "can_post":["post", "page", "attachment", "nav_menu_item", "wp_block", "wp_template", "wp_template_part", "wp_navigation", "product", "wpsl_stores", "adspiration_promo", "REDACTED_faq", "REDACTED_pac", "product_registration", "REDACTED_species_sl", "jp_pay_order", "jp_pay_product", "getwid_template_part"], "can_get":["post", "page", "attachment", "nav_menu_item", "wp_block", "wp_template", "wp_template_part", "wp_navigation", "product", "wpsl_stores", "adspiration_promo", "REDACTED_faq", "REDACTED_pac", "product_registration", "REDACTED_species_sl", "jp_pay_order", "jp_pay_product", "getwid_template_part"], "endpoint_suggestion":false, "is_authenticated":"yes"}
	Hub -> Canada: 
- URL: https://REDACTED/wp-json
- Version: 1.9.0
- Status: valid
- Auth method: Username / Password
- Username: REDACTED
- Roles Allowed to Push: editor, shop_manager, power_admin
- Additional data: {"errors":[], "can_post":["post", "page", "attachment", "nav_menu_item", "wp_block", "wp_template", "wp_template_part", "wp_navigation", "product", "wpsl_stores", "adspiration_promo", "REDACTED_faq", "REDACTED_pac", "product_registration", "REDACTED_species_sl", "jp_pay_order", "jp_pay_product", "getwid_template_part"], "can_get":["post", "page", "attachment", "nav_menu_item", "wp_block", "wp_template", "wp_template_part", "wp_navigation", "product", "wpsl_stores", "adspiration_promo", "REDACTED_faq", "REDACTED_pac", "product_registration", "REDACTED_species_sl", "jp_pay_order", "jp_pay_product", "getwid_template_part"], "endpoint_suggestion":false, "is_authenticated":"yes"}
`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kirtangajjar** [comment]
@dkotter I tried to reproduce this issue, but I was not able to reproduce it. It's an old issue, so looks like it was fixed along the way?
