### ISSUE TITLE
Inconsistent messages about the deleted original

### ISSUE THREAD

**Issue by cadic** [10up/distributor#1021]
### Describe the bug

On the edit post screen of distributed post, if the original is deleted, the editor notice says:

> This Post was distributed from Source site. However, the original has been deleted.

But in the Distributor menu you see

> This post was distributed from [Source site name](#). [View original](#) 

### Steps to Reproduce

1. Create original post
2. Distribute it to the destination site
3. Delete the original
4. Open distributed copy to edit
5. Read editor notice
6. Hover on "Distributor" top menu item
7. Read the message.
8. The link to Original is 404.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/288381/220591610-5081cfca-3831-45e5-91c9-d4b2b43d5bba.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
This seems a bit related to #1006, so seems worthwhile to include any further simplification/standardization of copy/messages also within 2.0.0.  I might propose the following standardization:
This Post was distributed from [source-site-name](https://source-site-link).  However, the [origin post](https://source-site-link/origin-post-link) has been deleted.

**Comment by peterwilsoncc** [comment]
> This Post was distributed from [source-site-name](https://source-site-link). However, the [origin post](https://source-site-link/origin-post-link) has been deleted.

You've suggested linking to the deleted post here. Was that intentional as the link will throw a 404 error?
