### ISSUE TITLE
Images not distributed in ACF fields like images and gallery

### ISSUE THREAD

**Issue by peprojects** [10up/distributor#1026]
### Describe your question

When distributing a post only the featured image and an image in a ACF WYSIWYG editor are dsitributed. Other images on an ACF gallery and ACF image field are not.

Is there a reason for it?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Closing in favor of #81, please subscribe to that issue for updates on this topic.
