### ISSUE TITLE
@msaidizi and @shockthealien please confirm that you're following the precise steps to [set up External Connections using Application Passwords](https://github.com/10up/distributor#setup-external-connections-using-application-passwords) as these should be the exact steps necessary to create fully functioning non-multisite connections for Distributor.

### ISSUE THREAD

**Issue by Thakurpritika** [10up/distributor#1045]
@msaidizi and @shockthealien please confirm that you're following the precise steps to [set up External Connections using Application Passwords](https://github.com/10up/distributor#setup-external-connections-using-application-passwords) as these should be the exact steps necessary to create fully functioning non-multisite connections for Distributor.

_Originally posted by @jeffpaul in https://github.com/10up/distributor/issues/487#issuecomment-552547818_

**Comment by jeffpaul** [comment]
Closing in favor of #487.
