### ISSUE TITLE
404 when I run the authorisation setup wizard

### ISSUE THREAD

**Issue by weronikasiuda** [10up/distributor#1048]
### Describe your question

Hi,

I've installed the stable version of Distributor between two sites and am attempting to establish a connection.
There are no issues with pulling content from A to B, but I am running into issues when I try to authorise connection from B to A:
- automatic authorisation => clicking "Authorise authorisation" results in 404
- manual authorisation => reported as "limited" despite using admin credentials. Also when I try to pull any content, I see the following error:
- 
Could not pull content from connection due to error.
Sorry, you are not allowed to edit posts in this post type.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Closing in favor of #1050, thanks for the details helping triage this!
