### ISSUE TITLE
Automatic authorisation process fails

### ISSUE THREAD

**Issue by weronikasiuda** [10up/distributor#1050]
### Describe the bug

Hi,

The automatic authorisation process is failing on one of our websites and redirecting to a 404 page on the external site. The issue appeared to be hosting-specific. Having reached out to our hosting provider support, here is their explanation:

Hi there,
 
We've not actively disallowed the plugin, but I think this issue is likely because the link it goes to does *not* collect the siteurl from the database, and instead just assumes the core files are in the webroot. 
 
In this case the link should look like this:

https://example.co.uk/wp/wp-admin/authorize-application.php

Instead of this:

https://example/wp-admin/authorize-application.php

They can fix this in their code by using WordPress' get_site_url() function:
 
https://developer.wordpress.org/reference/functions/get_site_url/)

### Steps to Reproduce

1. Go to "External connection" => "Add new".
2. Add the external site URL and select "authorise connection".

### Environment information

N/A

### WordPress information

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by weronikasiuda** [comment]
Hi! Thank you so much for looking into it - do you think this is likely to be resolved soon, i.e. in the next week or so? We rely on this in one of our projects, so if this proves to be more complicated, we will need to reconsider our tools!

**Comment by peterwilsoncc** [comment]
A fix for this is included in the upcoming 2.0.0 release, it was fixed in https://github.com/10up/distributor/pull/934

This issue was originally reported in #730, so I'll close this issue off as a duplicate.
