### ISSUE TITLE
How to solve: Limited connection established. Authentication failed due to invalid credentials. Push distribution unavailable. Pull distribution limited to basic content, i.e. title and content body.

### ISSUE THREAD

**Issue by Audertist** [10up/distributor#1058]
### Describe your question

Hello, 

I am running into this error: 

Limited connection established.
Authentication failed due to invalid credentials.
Push distribution unavailable.
Pull distribution limited to basic content, i.e. title and content body.

and 

Limited connection established.
Push distribution unavailable.
Pull distribution limited to basic content, i.e. title and content body.

After much attempts, I have been unable to push content from one site to another and I cannot pull all post types despite making them open to rest api. For some information, I use metabox for my custom post types and custom fields. Additionally, I was wondering if when pushing or pulling will it also transfer the hierarchal order of my posts?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@Audertist are you attempting to connect different WordPress instances or within the same multisite network?

**Comment by Audertist** [comment]
> @Audertist are you attempting to connect different WordPress instances or within the same multisite network?

Hello I am trying to connect two different wordpress installs on a non-multisite network. One is from the main domain and the other is a subdomain. I have already tried uninstalling and reinstalling the plugin and I reset the passwords and usernames multiple times.

**Comment by Audertist** [comment]
![Screenshot 2023-05-26 185125](https://github.com/10up/distributor/assets/134737853/725feb5c-8a08-484b-ad85-0a9d8b44f301)
![Screenshot 2023-05-26 185002](https://github.com/10up/distributor/assets/134737853/ed29683f-0a7c-4f93-8944-07b51595e2df)
![Screenshot 2023-05-26 184933](https://github.com/10up/distributor/assets/134737853/453173a2-5dbc-48f5-8f1c-1dce05cb6d60)

**Comment by Audertist** [comment]
After some more debugging I found out I had a previous code snippet that opened up one of my custom post types to rest api but disabled gutenberg editor. I believe that is likely the reason why its not allowing me to pull a specific post type. However I still cannot push and pull from my subdomain to the main domain.

**Comment by Audertist** [comment]
*Edit, I did some more debugging on my end and I solved it, turns out I forgot to allow pull authentication on the other subdomain to allow the pull. I did it the first time I installed on both ends and I just forgot to do it again.

**Comment by Audertist** [comment]
*Note, actually still cannot pull but I did find a workaround
