### ISSUE TITLE
Not pulling images

### ISSUE THREAD

**Issue by The-Co-Foundry** [10up/distributor#1078]
### Describe the bug

We have Distributor install on these sites:
[https://kitstart.com/](https://kitstart.com/) distributing to [https://ayoba.kitstart.com/](https://ayoba.kitstart.com/)

This page is an example: [https://ayoba.kitstart.com/force-for-good-2/](https://ayoba.kitstart.com/force-for-good-2/) we can see that it is connected see screengrab: kitstart1.png and when we go to view original it takes us to the correct page on the main site: [https://kitstart.com/force-for-good/](https://kitstart.com/force-for-good/) however when we update images on that page they disappear on the distributed page. To see this scroll down to the section named "Proud to be a B Corp" (see screenrgab kitstart2.png) and you will see a yellow B corp image. However on the distributed page [https://ayoba.kitstart.com/force-for-good-2/](https://ayoba.kitstart.com/force-for-good-2/) the recently updated image in that section has disappeared, see screengrab3.png

Can you tell me why the image is not updating despite the fact that the two pages are connected?

### Steps to Reproduce

1. Go to [https://ayoba.kitstart.com/force-for-good-2/](https://ayoba.kitstart.com/force-for-good-2/) 
2. Scroll down to the section named: Proud to be a B corp – you will see there is no image there
3. Click on [https://kitstart.com/force-for-good/](https://kitstart.com/force-for-good/)
4. Scroll down to the section named: Proud to be a B corp – you will see there is a recently updated yellow image there

### Screenshots, screen recording, code snippet

<img width="559" alt="kitstart1" src="https://github.com/10up/distributor/assets/101260274/23157ccb-518a-4c0f-b0e6-c8294fd2cd95">
<img width="1084" alt="kitstart2" src="https://github.com/10up/distributor/assets/101260274/6822fac9-a579-4e81-9fc2-8cf40db3eda5">
<img width="1095" alt="kitstart3" src="https://github.com/10up/distributor/assets/101260274/c373b8e3-493d-4e64-b41f-26c57f656fcd">

### Environment information

Any device or browser

### WordPress information

`
### wp-core ###

version: 6.2.2
site_language: en_GB
user_language: en_GB
timezone: Europe/London
permalink: /blog/%year%/%monthnum%/%day%/%postname%/
https_status: true
multisite: true
user_registration: false
blog_public: 1
default_comment_status: open
environment_type: production
site_count: 3
network_count: 1
user_count: 8
dotorg_communication: true

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: KitStart (basekit)
version: 3
author: Anonymous
author_website: (undefined)
parent_theme: none
theme_features: core-block-patterns, post-thumbnails, menus, widgets-block-editor, post-formats, automatic-feed-links, widgets, editor-style
theme_path: /nas/content/live/kitstart/wp-content/themes/basekit
auto_update: Disabled

### wp-themes-inactive (5) ###

Genesis Block Theme: version: 1.0.0, author: StudioPress, Auto-updates disabled
Page Builder Framework: version: 2.6.8, author: David Vongries (latest version: 2.10.3), Auto-updates disabled
Twenty Twenty-One: version: 1.4, author: the WordPress team (latest version: 1.8), Auto-updates disabled
Twenty Twenty-Three: version: 1.0, author: the WordPress team (latest version: 1.1), Auto-updates disabled
Twenty Twenty-Two: version: 1.1, author: the WordPress team (latest version: 1.4), Auto-updates disabled

### wp-mu-plugins (5) ###

Force Strong Passwords - WPE Edition: version: 1.8.0, author: Jason Cosper
WP Engine Cache Plugin: version: 1.1.3, author: WP Engine
WP Engine Seamless Login Plugin: version: 1.6.0, author: WP Engine
WP Engine Security Auditor: version: 1.0.10, author: wpengine
WP Engine System: version: 5.0.1, author: WP Engine

### wp-plugins-active (33) ###

ACF Content Analysis for Yoast SEO: version: 3.0.1, author: Thomas Kräftner, ViktorFroberg, marol87, pekz0r, angrycreative, Team Yoast (latest version: 3.1), Auto-updates disabled
Admin Menu Editor: version: 1.10.4, author: Janis Elsts (latest version: 1.11), Auto-updates disabled
Advanced Custom Fields: Font Awesome: version: 4.0.4, author: Matt Keys (latest version: 4.0.5), Auto-updates disabled
Advanced Custom Fields PRO: version: 5.12.2, author: Delicious Brains (latest version: 6.1.6), Auto-updates disabled
Bellows Accordion Menu: version: 1.4.1, author: SevenSpark (latest version: 1.4.2), Auto-updates disabled
Better Search Replace: version: 1.4.2, author: WP Engine, Auto-updates disabled
Category Order and Taxonomy Terms Order: version: 1.7.4, author: Nsp-Code (latest version: 1.7.7), Auto-updates disabled
Custom Editor Styles: version: 1.1, author: Planet IA, Auto-updates disabled
Custom Post Type UI: version: 1.13.1, author: WebDevStudios (latest version: 1.13.6), Auto-updates disabled
Disable REST API: version: 1.7, author: Dave McHale, Auto-updates disabled
Distributor: version: 1.9.1, author: 10up Inc., Auto-updates disabled
EU Cookies Bar: version: 1.0.12, author: VillaTheme, Auto-updates disabled
FacetWP: version: 3.5.9, author: FacetWP, LLC (latest version: 4.2.1), Auto-updates disabled
Google Analytics for WordPress by MonsterInsights: version: 8.10.1, author: MonsterInsights (latest version: 8.16), Auto-updates disabled
Imagify: version: 2.1.1, author: Imagify – Optimize Images & Convert WebP, Auto-updates disabled
Instagram Feed Pro Developer: version: 5.12.3, author: Smash Balloon, Auto-updates disabled
Kitstart Custom ACF Distribution Plugin: author: (undefined), version: 1.0.0, Auto-updates disabled
NS Cloner - Site Copier: version: 4.2.2, author: Never Settle (latest version: 4.2.2.2), Auto-updates disabled
Post Types Order: version: 2.0.5, author: Nsp Code (latest version: 2.0.9), Auto-updates disabled
Post Type Switcher: version: 3.2.1, author: Triple J Software, Inc., Auto-updates disabled
Read Meter - Reading Time & Progress Bar for WordPress.: version: 1.0.6, author: Brainstorm Force, Auto-updates disabled
Really Simple SSL: version: 6.0.10, author: Really Simple Plugins (latest version: 7.0.5), Auto-updates disabled
Redirection: version: 5.3.5, author: John Godley (latest version: 5.3.10), Auto-updates disabled
Simple Page Ordering: version: 2.4.3, author: Jake Goldman, 10up (latest version: 2.5.1), Auto-updates disabled
Sticky Posts - Switch: version: 2.1.3, author: Markus Wiesenhofer, Auto-updates disabled
SVG Support: version: 2.5.4, author: Benbodhi (latest version: 2.5.5), Auto-updates disabled
UpdraftPlus - Backup/Restore: version: 1.23.3, author: UpdraftPlus.Com, DavidAnderson (latest version: 1.23.4), Auto-updates disabled
WordPress Importer: version: 0.8, author: wordpressdotorg (latest version: 0.8.1), Auto-updates disabled
WPCode - Insert Headers, Footers, and Code Snippets: version: 2.0.3, author: WPCode (latest version: 2.0.12), Auto-updates disabled
WP Rocket: version: 3.12.0.5, author: WP Media (latest version: 3.13.4), Auto-updates disabled
Yoast Duplicate Post: version: 4.5, author: Enrico Battocchi & Team Yoast, Auto-updates disabled
Yoast SEO: version: 19.10, author: Team Yoast (latest version: 20.9), Auto-updates disabled
Yoast SEO Premium: version: 19.5, author: Team Yoast, Auto-updates disabled

### wp-plugins-inactive (14) ###

ActiveCampaign: version: 8.1.10, author: ActiveCampaign (latest version: 8.1.12), Auto-updates disabled
Akismet Anti-Spam: version: 5.0.1, author: Automattic (latest version: 5.1), Auto-updates disabled
All-in-One WP Migration: version: 7.73, author: ServMask (latest version: 7.75), Auto-updates disabled
Distribute ACF Images: version: 1.0.0, author: Con Vista Al Mar, Auto-updates disabled
Genesis Blocks: version: 1.5.4, author: StudioPress (latest version: 2.0.0), Auto-updates disabled
Image CDN: version: 1.1.9, author: imageengine, Auto-updates disabled
Media Cleaner: version: 6.5.7, author: Jordy Meow (latest version: 6.6.4), Auto-updates disabled
Media Cleaner (Pro): version: 6.5.8, author: Jordy Meow, Auto-updates disabled
Media Sync: version: 1.2.9, author: Erol Živina (latest version: 1.3.1), Auto-updates disabled
Simple Multisite Crossposting: version: 2.7, author: Misha Rudrastyh, Auto-updates disabled
Simple Multisite Crossposting – ACF with Gutenberg support: version: 1.0, author: Misha Rudrastyh, Auto-updates disabled
Simple Multisite Crossposting – Attachments in Custom Fields: version: 2.0, author: Misha Rudrastyh, Auto-updates disabled
Smush: version: 3.12.4, author: WPMU DEV (latest version: 3.13.1), Auto-updates disabled
WP Migrate Lite: version: 2.6.4, author: WP Engine (latest version: 2.6.7), Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1691
imagemagick_version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: File uploads is turned off
post_max_size: 100M
upload_max_filesize: 50M
max_effective_size: 50 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 137 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 6144
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 9.22337203685E+18
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, AVI, AVIF, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HEIC, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIDEO, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 5.4.0-1098-gcp x86_64
httpd_software: Apache
php_version: 8.0.28 64bit
php_sapi: apache2handler
max_input_variables: 10000
time_limit: 3600
memory_limit: 512M
max_input_time: 3600
upload_max_filesize: 50M
php_post_max_size: 100M
curl_version: 7.74.0 OpenSSL/1.1.1n
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.42-46-log
client_version: mysqlnd 8.0.28
max_allowed_packet: 16777216
max_connections: 500

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /nas/content/live/kitstart/wp-content
WP_PLUGIN_DIR: /nas/content/live/kitstart/wp-content/plugins
WP_MEMORY_LIMIT: 64M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: true
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### distributor ###

0: 1.9.1
1: 
	Override Author Byline: Yes
	Media Handling: Featured image and attached images
2: 
	MASTER Clone: 
- Blog ID: 11
- URL: https://master.kitstart.com
- Registered: 2023-03-16 10:26:20
- Last updated: 2023-04-27 08:32:51
	Ayoba: 
- Blog ID: 12
- URL: https://ayoba.kitstart.com
- Registered: 2023-04-26 14:07:04
- Last updated: 2023-06-19 13:12:02
3: N/A

`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by The-Co-Foundry** [comment]
Please could you give me an idea as to when someone will be able to look at this? I really appreciate your help.

**Comment by sokratesagogo** [comment]
I may be missing something, but both of the sites you have linked to above are not WordPress sites...

**Comment by The-Co-Foundry** [comment]
Thank you so much for responding. They are very definitely WordPress sites, you can see from the logs shared above too. We are very keen to get a solution to this, please let me know if you need anything from me.

**Comment by sokratesagogo** [comment]
> Thank you so much for responding. They are very definitely WordPress sites, you can see from the logs shared above too. We are very keen to get a solution to this, please let me know if you need anything from me.

My mistake, apologies I should have checked beyond looking at the "Powered by Basekit" badge in the footer of the sites.

**Comment by dhanendran** [comment]
I have tested this issue and I couldn't reproduce it with multiple attempts. I have tested the issue with the 1.9.1 version of the plugin and latest WP version with no other plugin/theme installed.

**Comment by airplanenoise** [comment]
i have the same issue with two test sites i built to try this out. we are using flexible blocks, i wonder if that's the issue.

**Comment by dhanendran** [comment]
@airplanenoise I have tested this again with default theme in 2 sites and only the distributor plugin sync works just fine. So it might be the flexible blocks plugin causing the issue. Can you check this after disabling the flexible blocks plugin?

**Comment by airplanenoise** [comment]
flexible blocks cause a lot of issues, even for acf-json sync. i will test
and let you know.

**Comment by sokratesagogo** [comment]
We have a problem with images being distributed when the WP Performance Lab plugin was activated with WebP option activated. Problem persisted even after the plugin was deactivated.
