### ISSUE TITLE
Test how content is distributed with Gutenberg

### ISSUE THREAD

**Issue by jasonbahl** [10up/distributor#109]
It would be good to look at how content is distributed: 

- From a Gutenberg enabled site to a non-Gutenberg site
- From a non-Gutenberg site to a Gutenberg site
- From a Gutenberg site with no custom blocks to a Gutenberg Site with a lot of custom blocks
- From a Gutenberg site with lots of custom blocks to a Gutenberg site with no custom blocks

---- 

I would test with variations of whitelisting blocks as well. . .for example, on OSHPD one of our post types has _just_ one allowed block, and it's a custom block. Curious how Gutenberg would handle distributed content if it distributes the rendered content. . .the _only_ allowed block is a custom one, and the block meta (HTML comments) wouldn't be present for Gutenberg to render the data in the proper allowed block. . . 🤔

**Comment by helen** [comment]
There was a fair amount of Gutenberg testing done by @dkotter a while back, I'm sure we will be able to find more issues but I'm closing this out in favor of more targeted issues as needed.
