### ISSUE TITLE
Feature Request: Add filters to `set_meta`, `pepare_meta`, and `prepare_taxonomy_terms` and change sequence of events in NetworkSiteConnection

### ISSUE THREAD

**Issue by sethrubenstein** [10up/distributor#1094]
### Is your enhancement related to a problem? Please describe.

I would like to use Distributor to both automatically distribute posts using hooks and to create a migration pathway using custom WP CLI commands but would need some additional entry points to modify data as it moves through Distributor. 

My recommendation/ask is for these filters in `Utils`

### `set_meta`
- Add a `dt_before_set_meta` filter before any data is processed. This would allow data to be transformed before it is actually updated. You could use dt_after_set_meta to modify data but we'd still be updating post meta with potentially incorrect data and this would allow us to save on a subsequent db write. 

### `prepare_meta`
- Add a `dt_prepared_meta` filter to the end of the function, before data is returned. An alternative to the set_meta filter, depends on when you need to change data. 

### `prepare_taxonomy_terms`
- Add a `dt_prepared_taxonomy_terms` filter to the end of the function, before data is returned. This would allow us for example to change the term slugs from a network site to match the term slugs on our index site, matching the end result for our migration on our distributed site. 

Lastly, a request to change the sequence of events in the network_site_connection push and pull functions.
Currently the order of operations after inserting the post into the target site is:
1. set meta
2. set terms
3. set media

If we change it to
1. set media
2. set terms
3. set meta

Then it's possible using the filters listed above to for example in our use case do a lookup of attachments for the post if media is set early and then in our meta change our attachment id's accordingly. Same for term ids, if they get set before meta then if you have any references to term ids in your post meta you can look those up and update them then. 

I have a pull request ready with these changes if that works for you all, listing that in the comments below.

### Designs

I would like to use Distributor to both automatically distribute posts using hooks and to create a migration pathway using custom WP CLI commands but would need some additional entry points to modify data as it moves through distributor. 

My recommendation/ask is for these filters in `Utils`

### `set_meta`
- Add a `dt_before_set_meta` filter before any data is processed. This would allow data to be transformed before it is actually updated. You could use dt_after_set_meta to modify data but we'd still be updating post meta with potentially incorrect data and this would allow us to save on a subsequent db write. 

### `prepare_meta`
- Add a `dt_prepared_meta` filter to the end of the function, before data is returned. An alternative to the set_meta filter, depends on when you need to change data. 

### `prepare_taxonomy_terms`
- Add a `dt_prepared_taxonomy_terms` filter to the end of the function, before data is returned. This would allow us for example to change the term slugs from a network site to match the term slugs on our index site, matching the end result for our migration on our distributed site. 

Lastly, a request to change the sequence of events in the network_site_connection push and pull functions.
Currently the order of operations after inserting the post into the target site is:
1. set meta
2. set terms
3. set media

If we change it to
1. set media
2. set terms
3. set meta

Then it's possible using the filters listed above to for example in our use case do a lookup of attachments for the post if media is set early and then in our meta change our attachment id's accordingly. Same for term ids, if they get set before meta then if you have any references to term ids in your post meta you can look those up and update them then. 

I have a pull request ready with these changes if that works for you all, listing that in the comments below.

### Describe alternatives you've considered

I have attempted follow up CLI commands and using existing hooks but they all have tradeoffs and feel this implementation would offer maximum developer extensibility.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@sethrubenstein thanks for the well detailed issue!  We're working through some final mechanisms on 2.0.0.-beta1 and will come back to this quickly once that gets settled as well as your associated PR in #1095.
