### ISSUE TITLE
Update admin menu icon to have the same width & height

### ISSUE THREAD

**Issue by zach-adams** [10up/distributor#1119]
### Is your enhancement related to a problem? Please describe.

The icon shown in the main WP sidebar for the plugin seems to be very slightly squished width-wise. I found the source SVG at "assets/img/icon.svg" and it seems like it's being set to 36px by 39px in the SVG:
https://github.com/10up/distributor/blob/develop/assets/img/icon.svg

I doubt that squish is intended, if it's not then I propose updating the icon so it has the same width/height. I've created a fixed version of the icon on my own for consideration which you can see in the designs section

It looks like there's also the data URI versions that will need to be updated accordingly in these files:
https://github.com/10up/distributor/blob/develop/includes/external-connection-cpt.php#L665
https://github.com/10up/distributor/blob/develop/includes/settings.php#L309
I'm also not sure if this javascript version will need to be updated as well:
https://github.com/10up/distributor/blob/develop/assets/js/components/plugin-icon.js
Those are all the references to the current icon I could find at a quick glance, but you'll want to check for others

### Designs

Existing Icon:
![current-icon](https://github.com/10up/distributor/assets/6644396/02e3cc03-5d24-44cb-a2c6-3fb2512ea649)
Updated Icon:
![icon](https://github.com/10up/distributor/assets/6644396/9452a297-4d07-4ccb-8af8-977172c662b5)
Example of current icon in the menu:
<img width="161" alt="2023-08-04_14-55-c7759pQK" src="https://github.com/10up/distributor/assets/6644396/f11a2328-63b4-485a-8247-5d2570f34022">
Example of updated icon in the menu:
<img width="160" alt="2023-08-04_14-51-AwLFn4b4" src="https://github.com/10up/distributor/assets/6644396/23a9f138-8140-4e18-8dab-ac92777baf1e">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@peterwilsoncc I don't think there's a reason for an uneven ratio here, is there?

**Comment by peterwilsoncc** [comment]
@jeffpaul Not that I can see, I suspect a tpyo.
