### ISSUE TITLE
List formerly-linked posts in pull UI with option to reassociate

### ISSUE THREAD

**Issue by deltafactory** [10up/distributor#1120]
### Is your enhancement related to a problem? Please describe.

In our use-case we need to leave ourselves the option to make a change on one of the targets, putting it temporarily out of sync with the origin. The current workflow includes unlinking that post, making the change, and at some point re-linking the post so that it is subscribed to future updates.

We also expect that we'll want to pull the changes into the related post on the origin. On the origin side of the experience, this seems like it could fit within the Pull UI. Currently the only entries listed to be pulled for a given External connection/content type are ones that have never been associated.

I am using v2.0.0-rc1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@deltafactory are the items you're changing in post content or meta?

**Comment by deltafactory** [comment]
I suppose it could be either but post content would be the most important to pull back to the origin. In our scenario we have some custom post types with specific meta values that we exclude through the appropriate filter so that they never leave their environment.

**Comment by jeffpaul** [comment]
@deltafactory seems that perhaps the way in which you're editing the remote post meta isn't the best approach as you should be able to leverage hooks to edit that without making the post content itself unlinked

**Comment by deltafactory** [comment]
I'm not sure what you're referencing as far as post meta. My primary concern is post content but a solution should probably address meta as well.

Back to the original issue: I would prefer not to unlink the post in the first place, but we need the option to temporarily and immediately alter the live/target content so that it's different from the source. Ideally, we would be able to pull those changes back to the origin by finding the article from the external connections list.

**Comment by jeffpaul** [comment]
@deltafactory the only way to support that flow currently would be to unlink the remote post to make those changes to post content.  Getting that updated on the origin, currently, would be a function of replicating those changes on the origin post.  Then updating the remote post so its linked again should get things all back in sync.
