### ISSUE TITLE
Cannot pull posts after update

### ISSUE THREAD

**Issue by ArchimedesIT** [10up/distributor#1130]
### Describe the bug

We did the update of the plugin this morning. After running the update on both sites, we cannot pull posts anymore. On the site that is pulling the post, the connection seems to be fine. (green light)

### Steps to Reproduce

None..

### Environment information

WordPress 6.3.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@ArchimedesIT I'm assuming you're connecting two separate WordPress instances and not using a multisite setup, correct?  If so, can you provide the Site Health Info export for us to try and replicate your setup and better triage what might be going wrong?

**Comment by ArchimedesIT** [comment]
Yes, we use  two WordPress instances.  We rolled back the old version for now and its working fine again. Where can i find the data: Site Health Info export?

**Comment by peterwilsoncc** [comment]
@ArchimedesIT You can find the site health information by logging in to the WordPress Admin and then going to Tools > Site Health. Once that screen loads, click the info tab at the top of the screen. Once the "Results are still loading… " message disappears, click copy site info to clipboard and paste it in to this issue.

**Comment by jeffpaul** [comment]
Moving to the 2.1.0 milestone as we've not yet been able to reproduce this
