### ISSUE TITLE
Show View link in Push menu for external connections

### ISSUE THREAD

**Issue by PaddyWhacks** [10up/distributor#115]
Would be super useful just to click a "View Post" link right from the distributor interface. See my super rough mockup attached.

![untitled-2](https://user-images.githubusercontent.com/9625104/39533709-1033630a-4e30-11e8-8d5e-bba80c10bd15.png)

**Comment by jeffpaul** [comment]
@PaddyWhacks note that this exists for posts distributed to internal connections (e.g., within a multisite setup), but as @adamsilverstein noted in https://github.com/10up/distributor/issues/437#issuecomment-531795775 this currently does not show for posts distributed to external connections.  I'm going to update this issue to be specific to the external connection view link with related discussion on how best to solve that here as well.

**Comment by jeffpaul** [comment]
Here's an example of the View link next to a successfully distributed post for an internal connection that we'd want to mimic for successfully distributed content to external connections.  
<img width="1073" alt="Screen Shot 2019-09-19 at 9 03 14 PM" src="https://user-images.githubusercontent.com/2818133/65293679-a4fda200-db21-11e9-9573-92ddccaab349.png">
