### ISSUE TITLE
auto sync of linked posts Not Working

### ISSUE THREAD

**Issue by skinnyrepacks** [10up/distributor#1165]
### Describe the bug

Dear sir, i have setup the plugin, but when i update the main site post it doest not update it on the site2,,,,, it remains the same 

i have also disabled all plugin to check if they are causing the issue but not working , also the post is linked 

i tried to unlink and then linked it back 

### Steps to Reproduce

Click on Pull post and then
update the post on main site
it will not be updated on the Exnernal site 

### WordPress information

**### Site2 Details**
`
### wp-core ###

version: 6.4.1
site_language: en_US
user_language: en_US
timezone: America/Los_Angeles
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/nginx/domains/steamreloaded.com/public
wordpress_size: 49.46 MB (51861442 bytes)
uploads_path: /home/nginx/domains/steamreloaded.com/public/wp-content/uploads
uploads_size: 13.73 MB (14395506 bytes)
themes_path: /home/nginx/domains/steamreloaded.com/public/wp-content/themes
themes_size: 34.83 MB (36516959 bytes)
plugins_path: /home/nginx/domains/steamreloaded.com/public/wp-content/plugins
plugins_size: 62.16 MB (65177869 bytes)
database_size: 17.09 MB (17924096 bytes)
total_size: 177.27 MB (185875872 bytes)

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: Video WP Child (video-wp-child)
version: 1.1
author: An-Themes
author_website: http://www.anthemes.net/
parent_theme: Video WP (video-wp)
theme_features: core-block-patterns, widgets-block-editor, menus, automatic-feed-links, title-tag, post-thumbnails, editor-style, widgets
theme_path: /home/nginx/domains/steamreloaded.com/public/wp-content/themes/video-wp-child
auto_update: Disabled

### wp-parent-theme ###

name: Video WP (video-wp)
version: 4.0
author: anthemes.com
author_website: https://anthemes.com
theme_path: /home/nginx/domains/steamreloaded.com/public/wp-content/themes/video-wp
auto_update: Disabled

### wp-themes-inactive (1) ###

Twenty Twenty-Four: version: 1.0, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (17) ###

Advanced Custom Fields PRO: version: 5.8.12, author: Elliot Condon (latest version: 6.2.4), Auto-updates disabled
Advanced Editor Tools: version: 5.9.2, author: Automattic, Auto-updates enabled
Advance Search Form: version: 1.4.9.9, author: Cactusthemes, Auto-updates disabled
Better Font Awesome: version: 2.0.4, author: Mickey Kay, Auto-updates disabled
Classic Editor: version: 1.6.3, author: WordPress Contributors, Auto-updates enabled
Code Snippets: version: 3.6.2, author: Code Snippets Pro, Auto-updates disabled
Contact Form 7: version: 5.8.4, author: Takayuki Miyoshi, Auto-updates enabled
Dave's WordPress Live Search: version: 4.8.1, author: Dave Ross, Auto-updates disabled
Disable XML-RPC: version: 1.0.1, author: Philip Erb, Auto-updates enabled
Disqus for WordPress: version: 3.0.23, author: Disqus, Auto-updates enabled
Distributor: version: 2.0.2, author: 10up Inc., Auto-updates enabled
Meta Box: version: 5.9.0, author: MetaBox.io, Auto-updates disabled
Rank Math SEO: version: 1.0.207, author: Rank Math, Auto-updates disabled
Restore Classic Widgets: version: 3.5, author: Bill Minozzi, Auto-updates enabled
Shortcodes Plugin: version: 1.2, author: An-Themes, Auto-updates disabled
WordPress REST API Authentication: version: 3.0.0, author: miniOrange, Auto-updates disabled
WP-PageNavi: version: 2.94.1, author: Lester 'GaMerZ' Chan, Auto-updates disabled

### wp-plugins-inactive (1) ###

Advanced Content Templates: version: 2.2.2, author: Clifton Griffin, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1692
imagemagick_version: ImageMagick 6.9.12-72 Q16 x86_64 17615 https://legacy.imagemagick.org
imagick_version: 3.7.0
file_uploads: 1
post_max_size: 1280M
upload_max_filesize: 1280M
max_effective_size: 1 GB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 125 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 196608
	imagick::RESOURCETYPE_MAP: 125 GB
	imagick::RESOURCETYPE_MEMORY: 63 GB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 9.2233720368548E+18
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIDEO, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.25

### wp-server ###

server_architecture: Linux 3.10.0-1160.81.1.el7.x86_64 x86_64
httpd_software: nginx/1.21.6
php_version: 7.4.3 64bit
php_sapi: fpm-fcgi
max_input_variables: 10000
time_limit: 2000
memory_limit: 2000M
max_input_time: 60
upload_max_filesize: 1280M
php_post_max_size: 1280M
curl_version: 7.29.0 NSS/3.53.1
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false
current: 2023-12-04T09:38:37+00:00
utc-time: Monday, 04-Dec-23 09:38:37 UTC
server-time: 2023-12-04T01:38:35-08:00

### wp-database ###

extension: mysqli
server_version: 10.3.37-MariaDB
client_version: mysqlnd 7.4.3
max_allowed_packet: 83886080
max_connections: 800

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/nginx/domains/steamreloaded.com/public/wp-content
WP_PLUGIN_DIR: /home/nginx/domains/steamreloaded.com/public/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 2000M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: false
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### distributor ###

0: 2.0.2
1: Yes
2: m
3: 
	Override Author Byline: No
	Media Handling: Featured image and attached images
4: N/A
5: 
	Main site: 
- URL: https://Main site.com/wp-json/
- Version: 2.0.2
- Status: valid
- Auth method: Username / Password
- Username:
- Roles Allowed to Push: administrator, editor
- Additional data: {"errors":[], "can_post":["post", "page", "attachment", "nav_menu_item", "wp_block", "wp_template", "wp_template_part", "wp_navigation"], "can_get":["post", "page", "attachment", "nav_menu_item", "wp_block", "wp_template", "wp_template_part", "wp_navigation"], "endpoint_suggestion":false, "is_authenticated":"yes"}

`
**### Main Site Details**
`
### wp-core ###

version: 6.4.1
site_language: en_US
user_language: en_US
timezone: America/Los_Angeles
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/nginx/domains/steamreloaded.com/public
wordpress_size: 49.46 MB (51861442 bytes)
uploads_path: /home/nginx/domains/steamreloaded.com/public/wp-content/uploads
uploads_size: 13.73 MB (14395506 bytes)
themes_path: /home/nginx/domains/steamreloaded.com/public/wp-content/themes
themes_size: 34.83 MB (36516959 bytes)
plugins_path: /home/nginx/domains/steamreloaded.com/public/wp-content/plugins
plugins_size: 62.16 MB (65177869 bytes)
database_size: 17.09 MB (17924096 bytes)
total_size: 177.27 MB (185875872 bytes)

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: Video WP Child (video-wp-child)
version: 1.1
author: An-Themes
author_website: http://www.anthemes.net/
parent_theme: Video WP (video-wp)
theme_features: core-block-patterns, widgets-block-editor, menus, automatic-feed-links, title-tag, post-thumbnails, editor-style, widgets
theme_path: /home/nginx/domains/steamreloaded.com/public/wp-content/themes/video-wp-child
auto_update: Disabled

### wp-parent-theme ###

name: Video WP (video-wp)
version: 4.0
author: anthemes.com
author_website: https://anthemes.com
theme_path: /home/nginx/domains/steamreloaded.com/public/wp-content/themes/video-wp
auto_update: Disabled

### wp-themes-inactive (1) ###

Twenty Twenty-Four: version: 1.0, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (17) ###

Advanced Custom Fields PRO: version: 5.8.12, author: Elliot Condon (latest version: 6.2.4), Auto-updates disabled
Advanced Editor Tools: version: 5.9.2, author: Automattic, Auto-updates enabled
Advance Search Form: version: 1.4.9.9, author: Cactusthemes, Auto-updates disabled
Better Font Awesome: version: 2.0.4, author: Mickey Kay, Auto-updates disabled
Classic Editor: version: 1.6.3, author: WordPress Contributors, Auto-updates enabled
Code Snippets: version: 3.6.2, author: Code Snippets Pro, Auto-updates disabled
Contact Form 7: version: 5.8.4, author: Takayuki Miyoshi, Auto-updates enabled
Dave's WordPress Live Search: version: 4.8.1, author: Dave Ross, Auto-updates disabled
Disable XML-RPC: version: 1.0.1, author: Philip Erb, Auto-updates enabled
Disqus for WordPress: version: 3.0.23, author: Disqus, Auto-updates enabled
Distributor: version: 2.0.2, author: 10up Inc., Auto-updates enabled
Meta Box: version: 5.9.0, author: MetaBox.io, Auto-updates disabled
Rank Math SEO: version: 1.0.207, author: Rank Math, Auto-updates disabled
Restore Classic Widgets: version: 3.5, author: Bill Minozzi, Auto-updates enabled
Shortcodes Plugin: version: 1.2, author: An-Themes, Auto-updates disabled
WordPress REST API Authentication: version: 3.0.0, author: miniOrange, Auto-updates disabled
WP-PageNavi: version: 2.94.1, author: Lester 'GaMerZ' Chan, Auto-updates disabled

### wp-plugins-inactive (1) ###

Advanced Content Templates: version: 2.2.2, author: Clifton Griffin, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1692
imagemagick_version: ImageMagick 6.9.12-72 Q16 x86_64 17615 https://legacy.imagemagick.org
imagick_version: 3.7.0
file_uploads: 1
post_max_size: 1280M
upload_max_filesize: 1280M
max_effective_size: 1 GB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 125 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 196608
	imagick::RESOURCETYPE_MAP: 125 GB
	imagick::RESOURCETYPE_MEMORY: 63 GB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 9.2233720368548E+18
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIDEO, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.25

### wp-server ###

server_architecture: Linux 3.10.0-1160.81.1.el7.x86_64 x86_64
httpd_software: nginx/1.21.6
php_version: 7.4.3 64bit
php_sapi: fpm-fcgi
max_input_variables: 10000
time_limit: 2000
memory_limit: 2000M
max_input_time: 60
upload_max_filesize: 1280M
php_post_max_size: 1280M
curl_version: 7.29.0 NSS/3.53.1
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false
current: 2023-12-04T09:38:37+00:00
utc-time: Monday, 04-Dec-23 09:38:37 UTC
server-time: 2023-12-04T01:38:35-08:00

### wp-database ###

extension: mysqli
server_version: 10.3.37-MariaDB
client_version: mysqlnd 7.4.3
max_allowed_packet: 83886080
max_connections: 800

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/nginx/domains/steamreloaded.com/public/wp-content
WP_PLUGIN_DIR: /home/nginx/domains/steamreloaded.com/public/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 2000M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: false
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### distributor ###

0: 2.0.2
1: Yes
2: 
3: 
	Override Author Byline: No
	Media Handling: Featured image and attached images
4: N/A
5: 
	Main site: 
- URL: https://Main site.com/wp-json/
- Version: 2.0.2
- Status: valid
- Auth method: Username / Password
- Username:
- Roles Allowed to Push: administrator, editor
- Additional data: {"errors":[], "can_post":["post", "page", "attachment", "nav_menu_item", "wp_block", "wp_template", "wp_template_part", "wp_navigation"], "can_get":["post", "page", "attachment", "nav_menu_item", "wp_block", "wp_template", "wp_template_part", "wp_navigation"], "endpoint_suggestion":false, "is_authenticated":"yes"}

`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@skinnyrepacks its likely due to the [WordPress REST API Authentication](https://wordpress.org/plugins/wp-rest-api-authentication/) plugin blocking the REST API access between those sites.  You'll need to ensure that Distributor has proper access via that plugin ...OR... disable that plugin.
