### ISSUE TITLE
Add filter to get_available_authorized_sites()

### ISSUE THREAD

**Issue by barryceelen** [10up/distributor#117]
Adding a filter to the `NetworkSiteConnection::get_authorized_sites()` method would be useful to be able to exclude sites from being available for distributing to and from.

(The function performs a `wp_remote_post()` request to each site to see if the user can edit posts on that particular site. It might be useful to (also) add a filter before that happens.)

**Comment by sillybean** [comment]
I had this same issue. I'll do the PR.
