### ISSUE TITLE
error 503 sever down

### ISSUE THREAD

**Issue by impressionforce** [10up/distributor#1170]
### Describe your question

Every time i start to pull content the server stoped working, generate 503 error. i ran the tests on two different servers, bluehost generate 503 error . I have another site hosted on AWS lightsail generate same error and to have the site active i have to reboot the instance. I'm new with the plugin and i don't know what is the issue and how to diagnostic or fix this issues. I have around 2500 articles to to sync between groups of sites. 

<img width="1248" alt="Screenshot 2024-01-01 at 9 24 43 PM" src="https://github.com/10up/distributor/assets/155405800/29ad3df2-d2c5-4182-84e7-e387946bdc6b">
<img width="1440" alt="Screenshot 2024-01-01 at 9 40 49 PM" src="https://github.com/10up/distributor/assets/155405800/b7ed3905-ecf2-4db9-8483-f374c0a333d6">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@impressionforce that sounds like its an issue with your servers being available, see the following from [mdn web docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503):

> The HyperText Transfer Protocol (HTTP) 503 Service Unavailable server error response code indicates that the server is not ready to handle the request.

> Common causes are a server that is down for maintenance or that is overloaded. This response should be used for temporary conditions and the [Retry-After](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) HTTP header should, if possible, contain the estimated time for the recovery of the service.

I'd recommend checking with your host(s) to ensure your sites are publicly available and that there haven't been status issues with either host/platform.
