### ISSUE TITLE
Change post category

### ISSUE THREAD

**Issue by IonTulbure** [10up/distributor#1171]
### Describe your question

Hi. Is it possible to bulk change the post terms ? I would like all posts with cat X from source site on import to be assigned to cat Y on target site (category mapping). An option to change post terms before Content Pull would be useful. 

Another scenario would be to auto import all posts to Featured category for example. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@JohnnyBravoTheBest you'll likely want to leverage the [existing hooks](https://10up.github.io/distributor/index.html) and possibly see examples of how to extend with our [sample code snippets](https://10up.github.io/distributor/tutorial-snippets.html).

**Comment by JohnnyBravoTheBest** [comment]
@jeffpaul Hi. Thanks for reaching out. 

What is the appropriate hook to use ? Also where it is best to implement this on source or target site ?
