### ISSUE TITLE
Issue on adding a External Connection

### ISSUE THREAD

**Issue by michaelasg** [10up/distributor#1173]
Remote site is on Hostinger Webhosting

When I try to add New External Connection on the origin Site I get this:

Distributor not installed on remote site.
cURL error 56: Recv failure: Connection reset by peer (http_request_failed)

Needless to say the plug is installed and there is no obvious way why this request is somehow blocked. rest API is up, WP JSON is up

Any ideas?

**Comment by jeffpaul** [comment]
@michaelasg is there a security plugin active on the remote site?  Does Hostinger have some sort of firewall or other access restriction that's blocking access to the REST API?  If you try yourdomain.com/wp-json/ on the remote site while not logged in there, do you see anything?  Can you provide a Site Health Info export from both of the sites to better help triage?

**Comment by michaelasg** [comment]
I kinda figured it out, it wasn't Hostinger. It's something blocking on the origin WP site. Rest API is open on Origin, I don't see anything regarding problematic plugins. In the hosting panel (iBrave hosting for the origin) there is nothing that catches my eye What could it be? I should probably talk to their support. What ports should be open?

I tried between two WPs on Hostinger and it worked well, no issues. Now I need to figure out the iBrave site.... something is blocking it to reach the outside WPs
