### ISSUE TITLE
Custom taxonomy not being distributed

### ISSUE THREAD

**Issue by Becca-loftmynd** [10up/distributor#1186]
### Describe the bug

Using the plugin for a while now in a wordpress multisite
network with 5 sites and sharing posts with it. Was working fine for over a year until know since it isn't sharing the values of a custom taxonomy anymore. Interesting thing is, that if you disconnect the post from the origin post and reconnect it again it shows up. But it doesn't update, so if I change that custom taxonomy in the original post it's not changing in the shared post (only if you disconnect and reconnect again). Any help with this issue would be greatly appreciated!   

### Steps to Reproduce

1. create a custom taxonomy with 'Custom Post Type' for posts in a wordpress multisite network
2. create a post and choose custom taxonomy options
3. distribute that post to another site in the network
4. realize, that all of the content has been shared except the options of the custom taxonomy

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by csloisel** [comment]
I unfortunately haven't been able to reproduce this on a clean environment with only Distributor, and a CPT with a custom taxonomy.

**Comment by phpbits** [comment]
I also tested this out in a clean environment using ACF to generate Post type and taxonomy. The taxonomy is being pulled and pushed as expected.

cc @vikrampm1
