### ISSUE TITLE
authentication failed on ALL admin users and ALL app passwords

### ISSUE THREAD

**Issue by alancontino** [10up/distributor#1189]
### Describe your question

I'm adding a new External Connection (2 already work great - adding a 3rd) - the new connection fails to verify no matter what username, password or app password I use.   I've created different Administrative users on both sites as well as different application passwords on both sites and nothing seems to allow them to authenticate.    The Green dot appears briefly as if it is connected but then switches to Red dot and says "Authentication failed due to insufficient or invalid credentials."   

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@alancontino does that newly connected 3rd site have any sort of security plugin or firewall in place that might be blocking the REST API access?
