### ISSUE TITLE
Allow admins of subsites to push to main site of multisite installation?

### ISSUE THREAD

**Issue by simonwimell** [10up/distributor#1192]
### Describe your question

Hi,
and thanks for a great looking plugin! 👏

We have a multisite setup with a custom post type of "people". All subsites use the same theme and plugins, and has this custom post type. We want to aggregate people from subsites to the main site, but not all people should be synced/aggregated to the main site, so this plugin looks like a good solution where one could select which people to push. 

But we want the administrators of the subsite to be the ones selecting which people to sync/push to the main website, without giving them administrator access to the main site. 

Is this possible somehow? Is my issue/question clear enough? 🙂

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@simonwimell yes, what you've described should be feasible.
