### ISSUE TITLE
Product disconnect

### ISSUE THREAD

**Issue by cdesp** [10up/distributor#1195]
### Is your enhancement related to a problem? Please describe.

If you copy a product on the master site in order to make a new one then if the original product is connected to a site, this connection is copied to the new product. If you copy a product several times you end up with several products connected to a single one on the other site, and every time you change one it gets replaced on the other side.
It would be nice to have a way to disconnect the product by clicking a button on the product page of the master site.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@cdesp that's currently something that would be addressed via technical handling, see the developer docs for this: https://10up.github.io/distributor/tutorial-post-meta.html
