### ISSUE TITLE
Featured Image Not Pulling

### ISSUE THREAD

**Issue by matthew-upslope** [10up/distributor#1198]
### Describe the bug

Distributor is no longer pulling the feature photo for any of our three connected sites. This is a feature that has been working automatically (most of the time). But it not appears to have stopped working.

### Steps to Reproduce

1. click on pull story 
2. click on edit, 
-- it opens up the backend like normal except the story is grayed out because it's still connected to the original. It's supposed to automatically pull in that featured image, and it's not doing that. 

### Environment information

Samsung Chromebook Galaxy 2, Chrome, Version 121.0.6167.188 (Official Build) (64-bit)

### WordPress information

`
### wp-core ###

version: 6.4.3
site_language: en_US
user_language: en_US
timezone: America/Denver
permalink: /%category%/%year%/%monthnum%/%day%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: undefined
environment_type: production
user_count: 214
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /wordpress/core/6.4.3
wordpress_size: 66.41 MB (69631398 bytes)
uploads_path: /srv/htdocs/wp-content/uploads
uploads_size: 103.73 GB (111377709852 bytes)
themes_path: /srv/htdocs/wp-content/themes
themes_size: 17.48 MB (18331499 bytes)
plugins_path: /srv/htdocs/wp-content/plugins
plugins_size: 572.79 MB (600611365 bytes)
database_size: 5.35 GB (5739413504 bytes)
total_size: 109.72 GB (117805697618 bytes)

### wp-dropins (2) ###

advanced-cache.php: true
object-cache.php: true

### wp-active-theme ###

name: Newspack Scott (newspack-scott)
version: 1.85.1
author: Automattic
author_website: https://newspack.com
parent_theme: Newspack (newspack-theme)
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, automatic-feed-links, title-tag, menus, html5, custom-logo, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-font-sizes, editor-color-palette, editor-gradient-presets, custom-spacing, responsive-embeds, amp, post-subtitle, infinite-scroll, jetpack-responsive-videos, jetpack-geo-location, jetpack-content-options, woocommerce, web-stories, editor-style, widgets
theme_path: /srv/htdocs/wp-content/themes/newspack-scott
auto_update: Updates managed by host

### wp-parent-theme ###

name: Newspack (newspack-theme)
version: 1.85.1
author: Automattic
author_website: https://newspack.com
theme_path: /srv/htdocs/wp-content/themes/newspack-theme
auto_update: Updates managed by host

### wp-themes-inactive (5) ###

Newspack Joseph: version: 1.85.1, author: Automattic, Updates managed by host
Newspack Katharine: version: 1.85.1, author: Automattic, Updates managed by host
Newspack Nelson: version: 1.85.1, author: Automattic, Updates managed by host
Newspack Sacha: version: 1.85.1, author: Automattic, Updates managed by host
Twenty Twenty-One: version: 2.1, author: the WordPress team, Updates managed by host

### wp-mu-plugins (1) ###

Health Check Troubleshooting Mode: author: (undefined), version: 1.9.1

### wp-plugins-active (44) ###

Ads.txt Manager: version: 1.4.3, author: 10up, Auto-updates enabled
Akismet Anti-spam: Spam Protection: version: 5.3.1, author: Automattic - Anti-spam Team, Updates managed by host
Broadstreet: version: 1.46.3, author: Broadstreet, Auto-updates enabled
Co-Authors Plus: version: 3.5.15, author: Mohammad Jangda, Daniel Bachhuber, Automattic, Auto-updates enabled
Code Snippets: version: 3.6.2, author: Code Snippets Pro, Auto-updates enabled
Distributor: version: 2.0.3, author: 10up Inc., Updates managed by host
Gravity Forms: version: 2.7.17, author: Gravity Forms (latest version: 2.8.4), Auto-updates disabled
Gravity Forms Advanced Post Creation Add-On: version: 1.4.0, author: Gravity Forms, Auto-updates enabled
Gravity Forms Coupons Add-On: version: 3.3.0, author: Gravity Forms, Auto-updates enabled
Gravity Forms Mailchimp Add-On: version: 5.2.0, author: Gravity Forms, Auto-updates enabled
Gravity Forms Slack Add-On: version: 2.1.0, author: Gravity Forms, Auto-updates enabled
Gravity Forms Stripe Add-On: version: 5.5.0, author: Gravity Forms, Auto-updates enabled
GS Logo Slider Lite: version: 3.6.5, author: GS Plugins, Auto-updates enabled
GS Logo Slider PRO: version: 3.5.3, author: GS Plugins, Auto-updates enabled
Health Check & Troubleshooting: version: 1.7.0, author: The WordPress.org community, Auto-updates enabled
Jetpack: version: 13.2-a.7, author: Automattic, Updates managed by host
MC4WP: Mailchimp for WordPress: version: 4.9.11, author: ibericode, Auto-updates enabled
Newspack: version: 3.1.1, author: Automattic, Updates managed by host
Newspack - Dynamic Data Shortcode: version: 1.0.0, author: Daniel Brown, Auto-updates enabled
Newspack Ads: version: 1.47.0, author: Automattic, Updates managed by host
Newspack Blocks: version: 3.0.1, author: Automattic, Updates managed by host
Newspack Campaigns: version: 2.30.1, author: Automattic, Updates managed by host
Newspack Content Converter: version: 0.0.13-alpha, author: Automattic, Auto-updates enabled
Newspack Listings: version: 2.14.1, author: Automattic, Updates managed by host
Newspack Manager: version: 1.51.1, author: Automattic, Updates managed by host
Newspack Newsletters: version: 2.10.3, author: Automattic, Updates managed by host
Newspack Sponsors: version: 1.11.1, author: Automattic, Updates managed by host
OneSignal Push Notifications: version: 2.4.3, author: OneSignal, Auto-updates enabled
Parse.ly: version: 3.13.3, author: Parse.ly, Updates managed by host
Perfmatters: version: 2.2.0, author: forgemedia (latest version: 2.2.4), Auto-updates enabled
Public Post Preview: version: 2.10.0, author: Dominik Schilling, Auto-updates enabled
PWA: version: 0.8.0, author: PWA Plugin Contributors, Auto-updates enabled
Redirection: version: 5.4.2, author: John Godley, Auto-updates enabled
Simple Local Avatars: version: 2.7.7, author: 10up, Auto-updates enabled
Site Kit by Google: version: 1.121.0, author: Google, Auto-updates enabled
Super Cool Ad Inserter Plugin: version: 0.6.3, author: Automattic, Auto-updates enabled
WooCommerce: version: 8.6.1, author: Automattic, Updates managed by host
WooCommerce Name Your Price: version: 3.5.2, author: Kathy Darling, Auto-updates enabled
WooCommerce Stripe Gateway: version: 7.9.3, author: WooCommerce, Updates managed by host
Woo Subscriptions: version: 6.0.0, author: WooCommerce, Updates managed by host
WP Job Manager: version: 2.2.2, author: Automattic, Auto-updates enabled
Yoast SEO: version: 22.1, author: Team Yoast, Auto-updates enabled
Yoast SEO Premium: version: 21.8, author: Team Yoast, Auto-updates enabled
Zapier for WordPress: version: 1.0.4, author: Zapier, Auto-updates enabled

### wp-plugins-inactive (1) ###

WP Carousel: version: 2.6.2, author: ShapedPlugin LLC, Auto-updates enabled

### code-snippets (1) ###

snippet-1: name: Required Job Field, scope: global, modified: 2023-01-21 12:44:09

### wp-media ###

image_editor: Photon_Subsizes_BFI_Image_Editor_GD_1_3
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: 1
post_max_size: 2047M
upload_max_filesize: 2047M
max_effective_size: 2 GB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, AVIF
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 5.10.0-19-amd64 x86_64
httpd_software: nginx
php_version: 8.1.27 64bit
php_sapi: fpm-fcgi
max_input_variables: 6144
time_limit: 1200
memory_limit: 512M
max_input_time: 1200
upload_max_filesize: 2047M
php_post_max_size: 2047M
curl_version: 8.4.0 OpenSSL/1.1.1w
suhosin: false
imagick_availability: false
pretty_permalinks: true
current: 2024-02-27T17:36:43+00:00
utc-time: Tuesday, 27-Feb-24 17:36:43 UTC
server-time: 2024-02-27T10:36:42-07:00

### wp-database ###

extension: mysqli
server_version: 10.4.26-MariaDB-log
client_version: mysqlnd 8.1.27
max_allowed_packet: 104857600
max_connections: 500

### wp-constants ###

WP_HOME: https://oilcity.news
WP_SITEURL: https://oilcity.news
WP_CONTENT_DIR: /srv/htdocs/wp-content
WP_PLUGIN_DIR: /srv/htdocs/wp-content/plugins
WP_MEMORY_LIMIT: 512M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8
DB_COLLATE: utf8_general_ci

### wp-filesystem ###

wordpress: not writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### jetpack ###

site_id: 222199582
ssl_cert: No
time_diff: undefined
version_option: 13.2-a.7:1709043722
old_version: 13.2-a.7:1708377376
public: Public
master_user: #193 adminnewspack
is_offline_mode: off
is_offline_mode_constant: off
current_user: #185 matthew
tokens_set: Blog 
blog_token: $!Ji0qRIaOui(hck9gW8!%WgLrEn0SGK
user_token: Not set.
version: 13.2-a.7
jp_plugin_dir: /wordpress/plugins/jetpack/13.2-a.7/
plan: complete
protect_header: {"trusted_header":"REMOTE_ADDR","segments":1,"reverse":false}
full_sync: {"started":"Thu, 24 Aug 2023 13:45:28 +0000","finished":"Thu, 24 Aug 2023 13:45:49 +0000","progress":{"options":{"finished":true},"functions":{"finished":true},"constants":{"finished":true},"users":{"total":"1","sent":1,"finished":true,"last_sent":"193"},"network_options":{"finished":true}},"config":{"options":true,"functions":true,"constants":true,"users":[193],"network_options":true}}
sync_size: undefined
sync_lag: 0 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"https:\/\/oilcity.news","siteurl":"https:\/\/oilcity.news","WP_HOME":"https:\/\/oilcity.news","WP_SITEURL":"https:\/\/oilcity.news"}
idc_error_option: false
idc_optin: true
cxn_tests: All Pass.

### google-site-kit ###

version: 1.121.0
php_version: 8.1.27
wp_version: 6.4.3
reference_url: https://oilcity.news
amp_mode: no
site_status: connected-site
user_status: authenticated
verification_status: verified-non-site-kit
connected_user_count: 2
active_modules: site-verification, search-console, analytics, analytics-4, pagespeed-insights, tagmanager
recoverable_modules: none
required_scopes: 
	openid: ✅
	https://www.googleapis.com/auth/userinfo.profile: ✅
	https://www.googleapis.com/auth/userinfo.email: ✅
	https://www.googleapis.com/auth/siteverification: ✅
	https://www.googleapis.com/auth/webmasters: ✅
	https://www.googleapis.com/auth/analytics.readonly: ✅
	https://www.googleapis.com/auth/tagmanager.readonly: ✅
capabilities: 
	googlesitekit_authenticate: ✅
	googlesitekit_setup: ✅
	googlesitekit_view_posts_insights: ✅
	googlesitekit_view_dashboard: ✅
	googlesitekit_manage_options: ✅
	googlesitekit_update_plugins: ✅
	googlesitekit_view_splash: ✅
	googlesitekit_view_authenticated_dashboard: ✅
	googlesitekit_view_wp_dashboard_widget: ✅
	googlesitekit_view_admin_bar_menu: ✅
	googlesitekit_view_shared_dashboard: ⭕
	googlesitekit_read_shared_module_data::["search-console"]: ⭕
	googlesitekit_read_shared_module_data::["analytics-4"]: ⭕
	googlesitekit_read_shared_module_data::["pagespeed-insights"]: ⭕
	googlesitekit_manage_module_sharing_options::["search-console"]: ✅
	googlesitekit_manage_module_sharing_options::["analytics-4"]: ⭕
	googlesitekit_manage_module_sharing_options::["pagespeed-insights"]: ✅
	googlesitekit_delegate_module_sharing_management::["search-console"]: ✅
	googlesitekit_delegate_module_sharing_management::["analytics-4"]: ⭕
	googlesitekit_delegate_module_sharing_management::["pagespeed-insights"]: ⭕
enabled_features: 
	adsModule: ⭕
	audienceSegmentation: ⭕
	consentMode: ⭕
	ga4AdSenseIntegration: ⭕
	gm3Components: ⭕
search-console_shared_roles: none
search-console_management: owner
analytics-4_shared_roles: none
analytics-4_management: owner
pagespeed-insights_shared_roles: none
pagespeed-insights_management: all_admins
search_console_property: sc-domain:oilcity.news
analytics_account_id: 9130••••
analytics_property_id: none
analytics_profile_id: none
analytics_use_snippet: yes
analytics_4_account_id: 9130••••
analytics_4_ads_conversion_id: none
analytics_4_property_id: 2808039••
analytics_4_web_data_stream_id: 5986••••••
analytics_4_measurement_id: G-EZ••••••••
analytics_4_use_snippet: yes
analytics_4_available_custom_dimensions: none
tagmanager_account_id: 2441••••••
tagmanager_container_id: GTM-PNP••••
tagmanager_amp_container_id: none
tagmanager_use_snippet: yes

###  ###

0: undefined
1: Yes
2: publisher@oilcity.news
3: 
	Override Author Byline: Yes
	Media Handling: Featured image and attached images
4: N/A
5: 
	County17: 
- URL: https://county17.com/wp-json/
- Version: 2.0.3
- Status: valid
- Auth method: Username / Password
- Username: shawn
- Roles Allowed to Push: administrator, editor, author, contributor
- Additional data: {"errors":[], "can_post":["post", "page", "attachment", "nav_menu_item", "wp_block", "wp_template", "wp_template_part", "wp_navigation", "job_listing", "give_forms", "product"], "can_get":["post", "page", "attachment", "nav_menu_item", "wp_block", "wp_template", "wp_template_part", "wp_navigation", "job_listing", "give_forms", "product"], "endpoint_suggestion":false, "is_authenticated":"yes"}
	Cap City: 
- URL: https://capcity.news/wp-json/
- Version: 2.0.3
- Status: valid
- Auth method: Username / Password
- Username: shawn
- Roles Allowed to Push: administrator, editor, author
- Additional data: {"errors":[], "can_post":["post", "page", "attachment", "nav_menu_item", "wp_block", "wp_template", "wp_template_part", "wp_navigation", "job_listing", "give_forms", "product"], "can_get":["post", "page", "attachment", "nav_menu_item", "wp_block", "wp_template", "wp_template_part", "wp_navigation", "job_listing", "give_forms", "product"], "endpoint_suggestion":false, "is_authenticated":"yes"}

### parsely (17) ###

apikey: oilcity.news
content_id_prefix: undefined
use_top_level_cats: false
custom_taxonomy_section: category
cats_as_tags: false
track_authenticated_users: false
lowercase_tags: true
force_https_canonicals: false
track_post_types: 
	0: post
track_page_types: 
	0: page
disable_javascript: false
disable_amp: false
meta_type: json_ld
logo: https://oilcity.news/wp-content/uploads/2023/01/logo.png
disable_autotrack: false
plugin_version: 3.13.3
parsely_wipe_metadata_cache: false

`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rogeeherrera** [comment]
is there update on this? I am getting the same bug, featured image is pulled but not assigned to post

**Comment by csloisel** [comment]
I have tried various methods but haven't been able to replicate this issue at this time.

**Comment by Crag-Monkey** [comment]
I'm having the same issue- featured images are not being set on the distributed posts. I can manually set _thumbnail_id in the post_meta table and the featured image will appear, but as soon as the original post is updated _thumbnail_id gets wiped out again.

The theme I'm using is Divi and I've also tested using twentytwentyfour on the receiving site.

Disabling ALL plugins on BOTH sites except for Distributor (version 2.0.4) does not change this behavior.

**Comment by kirtangajjar** [comment]
@dkotter  I tried many things to reproduce this issue, but I was unable to. The featured image was always set in all cases for me :/
