### ISSUE TITLE
Fatal error when pushing item

### ISSUE THREAD

**Issue by daveywf** [10up/distributor#1221]
### Describe the bug

Getting a fatal error through AJAX when trying to push a post to another website:
PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /home/xxxxx/public_html/wp-content/plugins/distributor/includes/push-ui.php:270

### Steps to Reproduce

- Edit a post
- Push it to another website

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@davey013 could you share a site health export from your site so we can try and replicate to try and resolve this?

**Comment by daveywf** [comment]
`
### wp-core ###

version: 6.5.2
site_language: nl_NL
user_language: nl_NL
timezone: Europe/Amsterdam
permalink: /%postname%/
https_status: true
multisite: true
user_registration: false
blog_public: 1
default_comment_status: undefined
environment_type: production
site_id: 1
site_count: 2
network_count: 1
user_count: 19
dotorg_communication: true

### wp-dropins (2) ###

advanced-cache.php: true
maintenance.php: true

### wp-active-theme ###

name: Enfold Child (enfold-child)
version: 1.0
author: Kriesi
author_website: http://www.kriesi.at
parent_theme: Enfold (enfold)
theme_features: core-block-patterns, avia_exclude_bbPress, deactivate_tribe_events_calendar, avia_exclude_menu_exchange, avia_exclude_pojo_accessibility, avia_exclude_wp_accessibility, avia_exclude_wpml, avia_exclude_leaflet_map, avia_mega_menu, avia_improved_backend_style, avia_option_pages_toggles, avia_sidebar_manager, automatic-feed-links, nav_menus, menus, widgets, woocommerce, post-formats, avia_post_meta_compat, force-post-thumbnails-in-widget, post-thumbnails, widgets-block-editor, block-templates, title-tag, editor-styles, editor-style, customize-selective-refresh-widgets, responsive-embeds, editor-color-palette, editor-font-sizes, avia_no_session_support
theme_path: /home/ekwcdev/public_html/wp-content/themes/enfold-child
auto_update: Uitgeschakeld

### wp-parent-theme ###

name: Enfold (enfold)
version: 5.7
author: Kriesi
author_website: https://kriesi.at
theme_path: /home/ekwcdev/public_html/wp-content/themes/enfold
auto_update: Uitgeschakeld

### wp-plugins-active (34) ###

Advanced Custom Fields PRO: version: 6.2.9, author: WP Engine, Auto-updates uitgeschakeld
Akismet Anti-spam: Spam Protection: version: 5.3.2, author: Automattic - Anti-spam Team, Auto-updates uitgeschakeld
Converter for Media: version: 5.12.5, author: matt plugins, Auto-updates uitgeschakeld
Distributor: version: 2.0.4, author: 10up Inc., Auto-updates uitgeschakeld
Event Espresso: version: 5.0.19.p, author: Event Espresso, Auto-updates uitgeschakeld
Event Espresso - Mollie Gateway (EE 4.6.15+): version: 1.1.6.p, author: Event Espresso, Auto-updates uitgeschakeld
Event Espresso - Ticketing (EE 4+): version: 1.0.11.p, author: Event Espresso, Auto-updates uitgeschakeld
Event Tickets: version: 5.9.1.1, author: The Events Calendar, Auto-updates uitgeschakeld
Event Tickets Plus: version: 5.6.1, author: The Events Calendar (latest version: 5.10.1), Auto-updates uitgeschakeld
FacetWP: version: 4.0.3, author: FacetWP, LLC, Auto-updates uitgeschakeld
FacetWP - Alpha: version: 1.3.5, author: FacetWP, LLC, Auto-updates uitgeschakeld
FacetWP - Relevanssi integration: version: 0.7.2, author: FacetWP, LLC, Auto-updates uitgeschakeld
GravityExport Lite: version: 2.2.0, author: GravityKit, Auto-updates uitgeschakeld
Gravity Forms: version: 2.8.8, author: Gravity Forms (latest version: 2.8.9), Auto-updates ingeschakeld
Gravity Forms Mollie Add-On: version: 1.5.0, author: Gravity Forms, Auto-updates uitgeschakeld
Kwaaijongens: version: 3.4.7, author: Kwaaijongens, Auto-updates uitgeschakeld
Mollie Payments for WooCommerce: version: 7.5.2, author: Mollie, Auto-updates uitgeschakeld
Relevanssi: version: 4.22.2, author: Mikko Saari, Auto-updates uitgeschakeld
Smash Balloon Instagram Feed: version: 6.3.1, author: Smash Balloon, Auto-updates uitgeschakeld
The Events Calendar PRO: version: 6.0.1, author: The Events Calendar, Auto-updates uitgeschakeld
User Role Editor: version: 4.64.2, author: Vladimir Garagulya, Auto-updates uitgeschakeld
WooCommerce: version: 8.8.2, author: Automattic (latest version: 8.8.3), Auto-updates uitgeschakeld
WordPress Backup & Security Plugin - BlogVault: version: 5.53, author: Kwaaijongens, Auto-updates uitgeschakeld
WordPress Importer: version: 0.8.2, author: wordpressdotorg, Auto-updates uitgeschakeld
WP-SCSS: version: 4.0.2, author: Connect Think, Auto-updates uitgeschakeld
WP All Export - ACF Export Add-On Pro: version: 1.0.5, author: Soflyy, Auto-updates uitgeschakeld
WP All Export - User Export Add-On Pro: version: 1.0.7, author: Soflyy, Auto-updates uitgeschakeld
WP All Export Pro: version: 1.8.8, author: Soflyy, Auto-updates uitgeschakeld
WP All Import - ACF Add-On: version: 3.3.8, author: Soflyy, Auto-updates uitgeschakeld
WP All Import - WooCommerce Import Add-On Pro: version: 4.0.0, author: Soflyy, Auto-updates uitgeschakeld
WP All Import Pro: version: 4.8.7, author: Soflyy, Auto-updates uitgeschakeld
WP Crontrol: version: 1.16.3, author: John Blackbourn, Auto-updates uitgeschakeld
Yoast Duplicate Post: version: 4.5, author: Enrico Battocchi & Team Yoast, Auto-updates uitgeschakeld
Yoast SEO: version: 22.5, author: Team Yoast (latest version: 22.6), Auto-updates uitgeschakeld

### wp-plugins-inactive (3) ###

Query Monitor: version: 3.16.2, author: John Blackbourn, Auto-updates uitgeschakeld
The Events Calendar: version: 6.3.7, author: The Events Calendar (latest version: 6.4.0), Auto-updates uitgeschakeld
WP Mail Logging: version: 1.12.0, author: WP Mail Logging Team, Auto-updates uitgeschakeld

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Niet beschikbaar
imagemagick_version: Niet beschikbaar
imagick_version: Niet beschikbaar
file_uploads: 1
post_max_size: 150M
upload_max_filesize: 150M
max_effective_size: 150 MB
max_file_uploads: 20
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, AVIF, XPM
ghostscript_version: 9.27

### tec-tickets ###


### wp-server ###

server_architecture: Linux 4.18.0-147.8.1.el8.lve.1.x86_64 x86_64
httpd_software: Apache
php_version: 8.2.18 64bit
php_sapi: litespeed
max_input_variables: 10000
time_limit: 30
memory_limit: 2048M
max_input_time: 60
upload_max_filesize: 150M
php_post_max_size: 150M
curl_version: 7.87.0 OpenSSL/1.1.1w
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true
current: 2024-05-01T06:39:46+00:00
utc-time: Wednesday, 01-May-24 06:39:46 UTC
server-time: 2024-05-01T08:39:42+02:00

### wp-database ###

extension: mysqli
server_version: 8.0.36-cll-lve
client_version: mysqlnd 8.2.18
max_allowed_packet: 268435456
max_connections: 250

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/ekwcdev/public_html/wp-content
WP_PLUGIN_DIR: /home/ekwcdev/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 64M
WP_MAX_MEMORY_LIMIT: 2048M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Ongedefinieerd
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### distributor ###

0: 2.0.4
1: 
	Override Author Byline: Yes
	Media Handling: Featured image only
2: 
	EKWC [EN]: 
- Blog ID: 2
- URL: https://ekwc.nl/en
- Registered: 2021-09-03 06:29:43
- Last updated: 2024-04-29 15:16:40
3: N/A

`
