### ISSUE TITLE
mapping to different categories possible?

### ISSUE THREAD

**Issue by willemb2** [10up/distributor#1222]
### Describe your question

Newby here. Thank you for making this plugin available. Our foundation runs 3 news websites for slightly overlapping audiences. Some posts we publish on 2 or 3 sites. Multisite appeared to be no solution for us because you can't share a media library and some plugins don't work on multisite. So this is a great time saver for us.

Our 3 sites have **different sets of categories** and my editors prefer to keep it that way. But I noticed that when a category on mainsite.com is not present on remotesite.com, Distributor creates it. This results in too many categories on remotesite.com. Is there a way to set a mapping to a destination category in the pull- or push-process? I could not find anything in the documentation about this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@willemb2 there's no built-in way to do category mapping between sites, but you could customize that by extending Distributor via [existing hooks](https://10up.github.io/distributor/) to do that.  If you're not able to extend that on your own, then feel free to reach out (jeff.paul@10up.com) if you'd like to discuss how 10up could help you with that via a consulting engagement.

**Comment by willemb2** [comment]
Thanks @jeffpaul , at least good to learn that I didn't miss something. I'm not a developer, unable to use the hooks. I'll tell my editors that if they want to use this attractive toy, they'll either have to reorganize their categories or attract more sponsors to finance paid customization.

BTW I did manage to add 2 of your snippets to our child theme's functions.php: 'Push original publication date' and 'Automatically unlink posts'. Works flawless!
