### ISSUE TITLE
How to remove distributed connections?

### ISSUE THREAD

**Issue by pinksharpii** [10up/distributor#1223]
### Describe your question

Sorry if this is a dumb question but it's not obvious how to remove a post from being distributed. I can see where a post is distributed to but there's no way to remove the connection. We need the admins to be able to revoke content at any point. What am I missing?
<img width="1044" alt="Screenshot 2024-05-14 at 3 01 27 PM" src="https://github.com/10up/distributor/assets/3431241/454bc27f-ba32-4c10-8e73-ee9851951f74">
<img width="305" alt="Screenshot 2024-05-14 at 3 05 26 PM" src="https://github.com/10up/distributor/assets/3431241/3534e6fe-6a09-45e8-b29f-6af6116fbb09">

Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@pinksharpii in terms of within the UI, you can remove the connection between posts on the remote post site (open the post and click the "unlink" link) and you could then proceed further by deleting the remote post if you don't want it there as published/draft/etc at all.

**Comment by pinksharpii** [comment]
So there's really not a way from the "main" post to revoke it from all/any sites it's been distributed to? You have to go to each site individually?

**Comment by pinksharpii** [comment]
If I delete the post on a distributed site, it still shows on the "source" site that it's distributed to that site. Is this a bug?

**Comment by jeffpaul** [comment]
@pinksharpii did that distributed post get fully deleted or just moved to Trash?  It probably needs to be fully deleted for it to no longer register on the origin post/site.

**Comment by pinksharpii** [comment]
Hi we ended up not going with this plugin in the end, so I can't confirm how it was deleted.

**Comment by tatof** [comment]
I got the same problem, removing (and deleting from trash) doesn't trash the remote post.

@pinksharpii what solution did you use?

edit: i also went for an other solution
