### ISSUE TITLE
Authentication failed due to insufficient or invalid credentials.

### ISSUE THREAD

**Issue by abarrabes88** [10up/distributor#1224]
### Describe your question

Hello,

I am setting up an external connection but I am getting all time this error: 

**"Authentication failed due to insufficient or invalid credentials."**

I tried to setting up using "Application Password" and also "User / Password"... but I am getting same error with both methods.

I also have installed distributor in the remote site.

![image](https://github.com/10up/distributor/assets/85565417/157cbf98-0bc1-46fe-a3cd-bf525ad918b4)

![image](https://github.com/10up/distributor/assets/85565417/b8269970-c4b8-42bc-803b-95125971c368)

![image](https://github.com/10up/distributor/assets/85565417/23149f10-db26-4c60-88cb-81b5f66ad486)

I think I have everything configured correctly and I don't know where to look... can you help me? thank you so much!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@abarrabes88 the most reliable flow, when connecting different WordPress instances (noting that you don't need to do this for sites within a network), is to use the [connection wizard flow](https://github.com/10up/distributor/?tab=readme-ov-file#set-up-external-connections).  That will effectively create an application password for the connected user.  Using the Application Passwords plugin is no longer necessary or recommended and creating a general user password is also not recommended.  In the examples you provided screenshots for, were any of those using the connection wizard flow?

**Comment by abarrabes88** [comment]
Thanks for your help Jeff ,

Yes, in one of the examples (named SyncKarsWithUser) I do it like this.

I have done it again to show it the process I follow:

1. Authentication Method: Username / Password and I fill External Site Url field:
![image](https://github.com/10up/distributor/assets/85565417/50e11348-9ce6-41b3-958d-d5b0d0bff268)

2. Click on "Authorize Connection". It redirects me to remote site and I click in "Yes, I approve this connection"
![image](https://github.com/10up/distributor/assets/85565417/6d961657-4ed7-40ac-9af2-970204734a5a)

3. It redirects me another time to the Main Site and I see the error I described above :(
![image](https://github.com/10up/distributor/assets/85565417/5cb32b7b-92d1-436e-a35b-c02492b7e7d8)

Thanks you very much!

**Comment by abarrabes88** [comment]
Hello! Any idea what could happen????

**Comment by abarrabes88** [comment]
Now is also giving this error:
![image](https://github.com/10up/distributor/assets/85565417/eed8dc76-6fec-4a8f-a3a8-9a17f15303cb)

Obviously I have distributor in the remote site.

thanks

**Comment by jeffpaul** [comment]
@abarrabes88 perhaps there's some sort of firewall or authentication in front of that ignasic27.sg-host.com or more to the point of that error Distributor isn't installed on that site at all?
