### ISSUE TITLE
Unified Extensibility APIs in WordPress 6.6

### ISSUE THREAD

**Issue by vikrampm1** [10up/distributor#1239]
WordPress 6.6 unified the different slots and extensibility APIs between the post and site editors.

Please check the extension and validate the following along with the version bump issue #1238 

- [ ] Check if the plugin is integrating twice, once with wp.editPost and once using wp.editSite
- [ ] If yes, then update those to use wp.editor global variable (@wordpress/editor package or wp-editor script handle) as noted here https://make.wordpress.org/core/2024/06/18/editor-unified-extensibility-apis-in-6-6/

**Comment by kirtangajjar** [comment]
I checked the plugin and it's only using `@wordpress/edit-post`, so no need to make any changes here.
