### ISSUE TITLE
Custom post type is not being pulled or pushed

### ISSUE THREAD

**Issue by WeiterGmbH** [10up/distributor#1240]
### Describe the bug

Custom post type is not being pulled or pushed.

I have enabled rest api access already.

### Steps to Reproduce

I have used cpt ui to create custom post type. re established the plugin in both websites. i also tried to update connections.  it still showing that i cant pull or push that cpt items to remote website. check following screenshots

### Screenshots, screen recording, code snippet

These are screenshot urls

https://bit.ly/4boHIjP
https://bit.ly/45NZjQY

### WordPress information

`
### wp-core ###

version: 6.5.5
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/u522723048/domains/each.weiterdev.ch/public_html
wordpress_size: 54.71 MB (57371313 bytes)
uploads_path: /home/u522723048/domains/each.weiterdev.ch/public_html/wp-content/uploads
uploads_size: 25.75 KB (26368 bytes)
themes_path: /home/u522723048/domains/each.weiterdev.ch/public_html/wp-content/themes
themes_size: 12.47 MB (13073701 bytes)
plugins_path: /home/u522723048/domains/each.weiterdev.ch/public_html/wp-content/plugins
plugins_size: 102.72 MB (107712239 bytes)
database_size: 4.00 MB (4194304 bytes)
total_size: 173.93 MB (182377925 bytes)

### wp-dropins (1) ###

object-cache.php: true

### wp-active-theme ###

name: Hello Elementor (hello-elementor)
version: 3.1.0
author: Elementor Team
author_website: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, menus, automatic-feed-links, title-tag, html5, custom-logo, editor-style, align-wide, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider
theme_path: /home/u522723048/domains/each.weiterdev.ch/public_html/wp-content/themes/hello-elementor

### wp-themes-inactive (3) ###

Twenty Twenty-Four: version: 1.1, author: the WordPress team
Twenty Twenty-Three: version: 1.4, author: the WordPress team
Twenty Twenty-Two: version: 1.7, author: the WordPress team

### wp-mu-plugins (2) ###

Disable Auto Updates: author: (undefined), version: (undefined)
WP STAGING Optimizer: version: 1.5.5, author: WP STAGING

### wp-plugins-active (9) ###

Custom Post Type UI: version: 1.17.1, author: WebDevStudios
Distributor: version: 2.0.4, author: 10up Inc.
Elementor: version: 3.22.3, author: Elementor.com
Hostinger AI: version: 2.0.6, author: Hostinger
Hostinger Easy Onboarding: version: 2.0.11, author: Hostinger
Hostinger Tools: version: 3.0.2, author: Hostinger
LiteSpeed Cache: version: 6.2.0.1, author: LiteSpeed Technologies
WP STAGING PRO - Backup Duplicator & Migration: version: 5.4.0, author: WP-STAGING
WP STAGING WordPress Backup Plugin - Backup Duplicator & Migration: version: 3.8.0, author: WP-STAGING, WPStagingBackup

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1809
imagemagick_version: ImageMagick 7.1.1-19 Q16-HDRI x86_64 21601 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: 1
post_max_size: 3072M
upload_max_filesize: 3072M
max_effective_size: 3 GB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 2 TB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 196608
	imagick::RESOURCETYPE_MAP: 1,006 GB
	imagick::RESOURCETYPE_MEMORY: 503 GB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 9.2233720368548E+18
imagemagick_file_formats: 3FR, 3G2, 3GP, A, AAI, AI, APNG, ART, ARW, ASHLAR, AVI, AVIF, AVS, B, BAYER, BAYERA, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, C, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUBE, CUR, CUT, DATA, DCM, DCR, DCRAW, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FARBFELD, FAX, FF, FILE, FITS, FL32, FLV, FRACTAL, FTP, FTS, FTXT, G, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, HALD, HDR, HEIC, HEIF, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K, K25, KDC, LABEL, M, M2V, M4V, MAC, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MPO, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, O, ORA, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PHM, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PS, PS2, PS3, PSB, PSD, PTIF, PWP, QOI, R, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGB565, RGBA, RGBO, RGF, RLA, RLE, RMF, RSVG, RW2, SCR, SCREENSHOT, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, STRIMG, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TM2, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, Y, YAML, YCbCr, YCbCrA, YUV
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, AVIF, XPM
ghostscript_version: 9.27

### wp-server ###

server_architecture: Linux 4.18.0-513.11.1.lve.el8.x86_64 x86_64
httpd_software: LiteSpeed
php_version: 8.1.27 64bit
php_sapi: litespeed
max_input_variables: 5000
time_limit: 480
memory_limit: 3072M
max_input_time: 480
upload_max_filesize: 3072M
php_post_max_size: 3072M
curl_version: 7.87.0 OpenSSL/1.1.1w
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true
current: 2024-07-03T06:12:14+00:00
utc-time: Wednesday, 03-Jul-24 06:12:14 UTC
server-time: 2024-07-03T06:12:13+00:00

### wp-database ###

extension: mysqli
server_version: 10.11.7-MariaDB-cll-lve
client_version: mysqlnd 8.1.27
max_allowed_packet: 1073741824
max_connections: 2000

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/u522723048/domains/each.weiterdev.ch/public_html/wp-content
WP_PLUGIN_DIR: /home/u522723048/domains/each.weiterdev.ch/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 3072M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### distributor ###

0: 2.0.4
1: Yes
2: raja@weiter.ch
3: 
	Override Author Byline: Yes
	Media Handling: Featured image and attached images
4: N/A
5: 
	each sub website 1: 
- URL: https://eachsub1.weiterdev.ch/wp-json/
- Version: 2.0.4
- Status: valid
- Auth method: Username / Password
- Username: raja@weiter.ch
- Roles Allowed to Push: administrator, editor
- Additional data: {"errors":[], "can_post":["post", "page", "attachment", "nav_menu_item", "wp_block", "wp_template", "wp_template_part", "wp_navigation", "wp_font_family", "wp_font_face"], "can_get":["post", "page", "attachment", "nav_menu_item", "wp_block", "wp_template", "wp_template_part", "wp_navigation", "wp_font_family", "wp_font_face"], "endpoint_suggestion":false, "is_authenticated":"yes"}

`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WeiterGmbH** [comment]
By the way I also tried to add custom post type manually with following code.. which is also not working.

`function create_custom_post_type() {
$args = array(
'labels' => array(
'name' => __('Custom Posts', 'textdomain'),
'singular_name' => __('Custom Post', 'textdomain')
),
'public' => true,
'has_archive' => true,
'rewrite' => array('slug' => 'custom-posts'),
'show_in_rest' => true, // This enables the REST API support
'supports' => array('title', 'editor', 'thumbnail', 'excerpt')
);

register_post_type('custom_post', $args);
}

add_action('init', 'create_custom_post_type');`

**Comment by phpbits** [comment]
@vikrampm1 I have tried various methods but haven't been able to replicate this issue at this time. Thanks!

**Comment by kirtangajjar** [comment]
@vikrampm1 I have tried to replicate the issue on my end as well. I registered post type with rest api access on both sites and I was able to pull CPT post without any issues. This issue is good to close
