### ISSUE TITLE
[WP 6.6] Impossible to publish post if distributed as draft

### ISSUE THREAD

**Issue by claudiulodro** [10up/distributor#1249]
### Describe the bug

Under WP 6.6, if a post is distributed as a draft, it is impossible to publish the post without unlinking it because the Publish button is disabled. 

### Steps to Reproduce

1. Using WP 6.5, distribute a post with the "As draft" checkbox checked and keep the posts linked. On the site you distributed it to, the Publish button should be clickable and should publish the post.
<img width="1719" alt="Screenshot 2024-07-18 at 1 21 20 PM" src="https://github.com/user-attachments/assets/cb206fb8-cbbb-4e3c-b7fb-3b6a7856ce11">
2. Update the site you distributed the post to WP 6.6 and/or distribute a post with the "As draft" checkbox checked to a site that is running WP 6.6. Observe that the Publish button is disabled and the draft cannot be published.
<img width="1719" alt="Screenshot 2024-07-18 at 1 22 16 PM" src="https://github.com/user-attachments/assets/d36c1e6f-fc8e-4363-8c48-7b54b5933370">

### Screenshots, screen recording, code snippet

See above

### Environment information

n/a

### WordPress information

I tested with WP 6.5.5 and WP 6.6.0 on a site running the `develop` branch as well as the latest releases of Distributor, and with no other plugins

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by phpbits** [comment]
@vikrampm1 The fix here is ready for code review here: https://github.com/10up/distributor/pull/1252. Thanks!
