### ISSUE TITLE
Add WordPress Playground integration

### ISSUE THREAD

**Issue by jeffpaul** [10up/distributor#1266]
### Is your enhancement related to a problem? Please describe.

- [ ] add blueprint to github folder
- [ ] add repo badge to playground

Note that we'll want to set up the playground as a multisite, not fully certain that's yet possible so if not let's open an issue upstream in the playground repo and then mark this as blocked by that.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dottxado** [comment]
Hello 👋 I am studying Playground and I stumbled upon this issue 😄 

If you need a blueprint to run a multisite WordPress instance with your plugin installed and activated, here it is:

```
{
  "$schema": "https://playground.wordpress.net/blueprint-schema.json",
  "landingPage": "wp-admin/network/plugins.php",
  "phpExtensionBundles": [
    "kitchen-sink"
  ],
  "features": {
    "networking": true
  },
  "steps": [
    {
      "step": "enableMultisite"
    },
    {
      "step": "installPlugin",
      "pluginZipFile": {
        "resource": "url",
        "url": "https://github-proxy.com/proxy/?repo=10up/distributor&branch=stable"
      }
    },
    {
      "step": "wp-cli",
      "command": "wp plugin activate distributor-stable --network"
    }
  ]
}
```

You can test it with [this link](https://playground.wordpress.net/#ewogICIkc2NoZW1hIjogImh0dHBzOi8vcGxheWdyb3VuZC53b3JkcHJlc3MubmV0L2JsdWVwcmludC1zY2hlbWEuanNvbiIsCiAgImxhbmRpbmdQYWdlIjogIndwLWFkbWluL25ldHdvcmsvcGx1Z2lucy5waHAiLAogICJwaHBFeHRlbnNpb25CdW5kbGVzIjogWwogICAgImtpdGNoZW4tc2luayIKICBdLAogICJmZWF0dXJlcyI6IHsKICAgICJuZXR3b3JraW5nIjogdHJ1ZQogIH0sCiAgInN0ZXBzIjogWwogICAgewogICAgICAic3RlcCI6ICJlbmFibGVNdWx0aXNpdGUiCiAgICB9LAogICAgewogICAgICAic3RlcCI6ICJpbnN0YWxsUGx1Z2luIiwKICAgICAgInBsdWdpblppcEZpbGUiOiB7CiAgICAgICAgInJlc291cmNlIjogInVybCIsCiAgICAgICAgInVybCI6ICJodHRwczovL2dpdGh1Yi1wcm94eS5jb20vcHJveHkvP3JlcG89MTB1cC9kaXN0cmlidXRvciZicmFuY2g9c3RhYmxlIgogICAgICB9CiAgICB9LAogICAgewogICAgICAic3RlcCI6ICJ3cC1jbGkiLAogICAgICAiY29tbWFuZCI6ICJ3cCBwbHVnaW4gYWN0aXZhdGUgZGlzdHJpYnV0b3Itc3RhYmxlIC0tbmV0d29yayIKICAgIH0KICBdCn0K)


I have enabled the multisite, installed Distributor from GitHub using the stable branch and activated it in the network using WP-CLI. Sadly, seems that there is no other choice to activate a network-wide plugin than installing the whole WP-CLI 🤔 

I would be happy to work on a PR to add the blueprint to your repo, please let me know 💪

**Comment by dkotter** [comment]
> I would be happy to work on a PR to add the blueprint to your repo, please let me know

@dottxado That would be great if you have time to get a PR open for that. Thanks!
