### ISSUE TITLE
Question about modifications

### ISSUE THREAD

**Issue by sjmwa** [10up/distributor#1272]
### Describe your question

General question, where do these snippets and hooks get added to make modifications? Is it in the main functions.php file, or specific files for the plugin?

Also do these need to be added on just the source blog or both the source and destination blogs.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
> General question, where do these snippets and hooks get added to make modifications? Is it in the main functions.php file, or specific files for the plugin

It will depend on how you have things set up but generally these modifications will go in your own `functions.php` file or something similar. These aren't modifications you'll need to make to the Distributor plugin itself.

> Also do these need to be added on just the source blog or both the source and destination blogs.

This will also depend based on what you're trying to do and what your workflow looks like but in general, these changes usually need to exist on both sides.

As an example, if you're wanting to modify something before it get's pushed and you always push from one site to another (never the other way around), you'd only need to make the modification on the source site. But if you're wanting to make the same change and you push content out from multiple sites, the change will need to be made on all sites.
