### ISSUE TITLE
How to convert to original subsite post link

### ISSUE THREAD

**Issue by hanmaier** [10up/distributor#1275]
### Describe your question

![1726904277555](https://github.com/user-attachments/assets/1a41f815-5479-4408-acdc-43ac68fbe76b)

i want to change link to subsite link 
what should i do 
anybody can help me ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@hanmaier I don't quite understand your question.  Thanks for the screenshot, but could you give a bit more context of the steps you took, your expected result, and the actual result so I can help triage better for you?

**Comment by hanmaier** [comment]
Pull the posts of the sub-site to the main site, but the link displayed in the "View" button of the post on the main site is the link of the main site instead of the link of the sub-site @jeffpaul
