### ISSUE TITLE
How to pull Woocommerce product?

### ISSUE THREAD

**Issue by alexlii1971** [10up/distributor#1276]
### Describe your question

Hello,

I am new here, and I just setup a wordpress on local Mac.

I can note there are posts under Pull Content from, and I can pull posts from the remove site on Digitalocean.

But, there is not any Woocomerce products or pages show up in Pull Content From.

So, how should I pull Products from remote site to local site please?

Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@alexlii1971 do you have Distributor and Woo set up on both ends?
