### ISSUE TITLE
Documenting available filters and actions

### ISSUE THREAD

**Issue by robbiet480** [10up/distributor#128]
What are everyones thoughts on documenting filters and actions? I quickly threw the following lists together with grep as a starting point. Happy to write some docs, whether in Markdown files in the repo or the wiki. Or, proper WordPress documentation so we can hopefully generate HTML off the code eventually?

## Filters
`apply_filters( 'distributable_post_types', array_diff( $post_types, [ 'dt_ext_connection', 'dt_subscription' ] ) );`
`apply_filters( 'distributor_get_original_site_link', __( sprintf( 'By <a href="%s">%s</a>', esc_url( $site_url ), esc_html( $site_name ) ), 'distributor' ) );`
`apply_filters( 'dt_ajax_requires_with_credentials', false )`
`apply_filters( 'dt_auth_format_get_args', $args, $context, $this );`
`apply_filters( 'dt_auth_format_post_args', $args, $context, $this );`
`apply_filters( 'dt_auth_prepare_credentials', $auth, $args, self::$slug );`
`apply_filters( 'dt_blacklisted_meta', [ 'dt_unlinked', 'dt_connection_map', 'dt_subscription_update', 'dt_subscriptions', 'dt_subscription_signature', 'dt_original_post_id', 'dt_original_post_url', 'dt_original_blog_id', 'dt_syndicate_time', '_wp_attached_file', '_edit_lock', '_edit_last' ] );`
`apply_filters( 'dt_capabilities', 'manage_options' )`
`apply_filters( 'dt_create_missing_terms', true );`
`apply_filters( 'dt_drafts_can_be_distributed', false ) ) {`
`apply_filters( 'dt_external_capabilities', 'manage_options' ), 'distributor' );`
`apply_filters( 'dt_get_media_details', $media_details, $media_post->ID );`
`apply_filters( 'dt_item_mapping', new \WP_Post( $obj ), $post, $this );`
`apply_filters( 'dt_media_item_args', $media_item, $media_post->ID );`
`apply_filters( 'dt_network_site_connection_enabled', true )`
`apply_filters( 'dt_pull_capabilities', 'manage_options' )`
`apply_filters( 'dt_pull_post_args', $post_array, $item_array['remote_post_id'], $post, $this ) );`
`apply_filters( 'dt_push_capabilities', 'manage_options' )`
`apply_filters( 'dt_push_post_args', $post_body, $post, $this )`
`apply_filters( 'dt_push_post_timeout', 5, $post )`
`apply_filters( 'dt_remote_get', $formatted_post, $args, $this );`
`apply_filters( 'dt_remote_get_query_args', $query_args, $args, $this );`
`apply_filters( 'dt_remote_get_url', $posts_url, $args, $this )`
`apply_filters( 'dt_sync_media_delete_and_replace', true, $post_id ) ) {`
`apply_filters( 'dt_sync_meta', $meta_key, $meta_value, $post_id ) ) {`
`apply_filters( 'dt_syncable_taxonomies', $taxonomies, $post );`
`apply_filters( 'dt_update_term_hierarchy', true );`

## Actions

`do_action( 'dt_link_post' );`
`do_action( 'dt_log_sync', $item_id_mappings, $sync_log, $this );`
`do_action( 'dt_process_distributor_attributes', $post, $request, $update );`
`do_action( 'dt_pull_filters' );`
`do_action( 'dt_pull_post', $new_post, $this, $post_array );`
`do_action( 'dt_push_post', $new_post, $post_id, $args, $this );`
`do_action( 'dt_push_post', $response, $post_body, $type_url, $post_id, $args, $this );`
`do_action( 'dt_unlink_post' );`

**Comment by helen** [comment]
Going to close this out since we have the hook documentation now, and we can open a separate issue to discuss how to surface that on a non-code level (parsing, wiki, general docs, etc.).
