### ISSUE TITLE
After pulling an internal post from one site, it should still be available to pull from other sites

### ISSUE THREAD

**Issue by rmarscher** [10up/distributor#165]
It looks like the `dt_sync_log_*` site meta/option has a mapping of original post IDs to the post ID it has been distributed to. But it doesn't track which site it was distributed to.

Let's say Site A is the source for the post. We go to Site B and pull in that post. If we go to Site C, the post shows as already pulled and shows Post Deleted if the same post ID doesn't exist in Site C.

It seems that the structure of the sync log needs to be changed to include which site the destination post ID exists on.

There is a block in PullListTable::prepare_items():

```
		foreach ( $this->sync_log as $old_post_id => $new_post_id ) {
			if ( false === $new_post_id ) {
				$skipped[] = (int) $old_post_id;
			} else {
				$syndicated[] = (int) $old_post_id;
			}
		}
```

I _could_ create a pull request for this, but it seems to be a pretty significant change that would require carefully updating all of the places that use the sync log. Ideally the structure change would be backwards compatible. For example, the value in the sync log could become `[$new_post_site_id, $new_post_id]` and then if it's not an array, you can assume the value is just the `$new_post_id` without the site ID included.

**Comment by rmarscher** [comment]
I should add that the current workaround to this is to instead push each post to all of the other sites you want it on rather than pulling.

**Comment by tlovett1** [comment]
@rmarscher thanks for the report. I created a PR in #170. Let me know what you think.

**Comment by rmarscher** [comment]
@tlovett1 Thanks. That PR looks like a perfect approach to me. :shipit:
