### ISSUE TITLE
Internal Connections not showing

### ISSUE THREAD

**Issue by seorichard** [10up/distributor#176]
Hi there,

I have this setup in a multisite environment (1 main, 2 subdomains) and I don't see the internal connections. It could be because I'm on WPEngine and the sites are currently password protected but thought I'd check here if that is indeed the issue (before I remove the protection).

Thanks!

**Comment by dkotter** [comment]
Hey @seorichard, thanks for reaching out. I've not tried setting up internal connections on sites that are password protected, but that may impact the sites that show as available for a connection.

Currently we grab all sites on the network, loop through those and make a remote request to the site to verify the current user has permissions to access that site. If they don't, that site won't be shown as an internal connection.

Not sure how the password protection is set up on WP Engine (HTTP basic auth? a plugin? something else?) but it wouldn't surprise me if that makes those requests return unsuccessful, which would mean they won't show up as a connection.

**Comment by seorichard** [comment]
Makes total sense. I believe WP Engine is using HTTP basic auth for this particular staging environment which is removed once I go live.

Thanks!
