### ISSUE TITLE
Media Sideloading Stores WP_Errors

### ISSUE THREAD

**Issue by ChaosExAnima** [10up/distributor#177]
Hey there,

I discovered I believe what's a bug in the system. In the `set_media` function in `utils.php`, it runs `process_media` before storing the result in the `_thumbnail_id` post meta.

Unfortunately, `process_media` internally uses [`wp_handle_sideload`](https://developer.wordpress.org/reference/functions/wp_handle_sideload/), which can return a `WP_Error` object. That outcome is not checked by the code before it stores the media, so the error object is stored in the post meta and causes fatal errors when featured image functions are used in the site.

Recommended fix: Instead of directly setting the post meta, use [`set_post_thumbnail`](https://developer.wordpress.org/reference/functions/set_post_thumbnail/) instead to safely set the post's featured image.

**Comment by ChaosExAnima** [comment]
@tlovett1 please let me know if you need additional information.

**Comment by tlovett1** [comment]
Nice find! Seems like we just need to add a check for `WP_Error` here - https://github.com/10up/distributor/blob/master/includes/utils.php#L421

**Comment by ChaosExAnima** [comment]
@tlovett1 - That'd also work, but I'd recommend `set_post_thumbnail` as it also verifies if the attachment ID exists and is an attachment before saving. I think we should absolutely check for errors for all media items either way, though.

Do you want a PR?

**Comment by ChaosExAnima** [comment]
Nevermind, making a PR anyway. :)
