### ISSUE TITLE
cURL error with self signed SSL for local dev

### ISSUE THREAD

**Issue by danmaby** [10up/distributor#179]
I'm receiving a `cURL error 60` when I install the plugin on a multisite locally with a self signed SSL: 

![screenshot 2018-08-13 00 16 32](https://user-images.githubusercontent.com/13104185/44024584-9b8bb974-9ee5-11e8-943e-f40ce1e4f1cc.jpg)

The plugin functions as expected when using http:// 

PHP 7.2
WP 4.9.8 (multisite subdirectory)
Distributor 1.2.2
Local By Flywheel 2.2.4

**Comment by jeckman** [comment]
Are you able to run cURL for other external network connections inside Local by Flywheel?

See http://local.getflywheel.com/community/t/potential-curl-or-ssl-error/7210

**Comment by bobbingwide** [comment]
Hi Dan, on a local install trying to use an external connection to another local site I also got the cURL error 60. My workaround was to implement a filter hook to set `sslverify` to false.

```
add_filter( "dt_auth_format_get_args", "thugin_dt_auth_format_get_args", 10, 3 );
add_filter( "dt_auth_format_post_args", "thugin_dt_auth_format_get_args", 10, 3 )
function thugin_dt_auth_format_get_args( $args, $context, $thisobj ) {
	$args['sslverify'] = false;
	return $args;
}
```
Initially I got the following messages.
```
Limited connection established. Authentication failed.
Push distribution unavailable.
Pull distribution limited to basic content, i.e. title and content body.
 ```
but adding the same filter function to two hooks seems to have resolved the problem.

Note: I am using the application-password plugin.

**Comment by dkotter** [comment]
@danmaby Just wondering if you saw the update above ^? And if so, has that helped? I know I've had to do something similar when working locally on an https site, so hopefully that helps fix the issue.

**Comment by jeffpaul** [comment]
@danmaby are you still seeing the cURL error or can we close this issue as resolved?

**Comment by bobbingwide** [comment]
> @danmaby are you still seeing the cURL error or can we close this issue as resolved?
Why do you think this has been resolved? Is there a fix?

**Comment by grappler** [comment]
Have the same problem on a local vagrant environment.

**Comment by jeffpaul** [comment]
@bobbingwide I was curious if @danmaby had been able to resolve it with your instructions, that way I knew more specifically what could resolve his issue within the Distributor codebase.

**Comment by jeffpaul** [comment]
@grappler do the edits that @bobbingwide noted solve this for you?

**Comment by jeffpaul** [comment]
@danmaby @grappler were either of you able to try the edits suggested by @bobbingwide on this and confirm this is no longer an issue for you locally?

**Comment by grappler** [comment]
Setting `sslverify` to false allows the request to work locally. Just need to figure out next how to have the work only locally.

**Comment by bobbingwide** [comment]
@grappler  

> Just need to figure out next how to have the work only locally.

Do you mean you need to test whether or not the request is being run locally? 
I wrote myself an `are_you_local` method. https://github.com/bobbingwide/oik/blob/7cbf51b9b2e8360aa89ab56bb7a3193470c9cd57/libs/class-oik-remote.php#L779

**Comment by grappler** [comment]
> Do you mean you need to test whether or not the request is being run locally?

I have tested the code locally but I want the connections to ssl verified in production. I think I will be able to work somethings out with the environment constants.

Thanks for sharing your `are_you_local` method.

**Comment by jeffpaul** [comment]
@grappler were you able to get this to work for you locally?  If so, it would be great if you could confirm those details so we can add them to our documentation for others to utilize... thanks!

**Comment by jeffpaul** [comment]
@grappler were you able to get this to work for you locally?

**Comment by jeffpaul** [comment]
@grappler were you able to get this to work for you locally?

**Comment by jeffpaul** [comment]
@grappler were you able to get this to work for you locally?

**Comment by peterwilsoncc** [comment]
I'm going to close this off due to lack of response.

For local development, using this as an mu-plugin ought to resolve any issues with self-signed SSL certificates and/or application passwords preventing the use of an HTTP scheme.

**Please do not use this in production, it's really not a good idea**

```php
<?php

namespace Run\This\In\Local\Development\Only\It\Is\Unsafe;

function application_passwords_available () {
	return true;
}

function no_scheme_errors( $error ) {
	$error->remove( 'invalid_redirect_scheme' );
}

function no_ssl_verify_locally( $args, $url ) {
	$self_signed_hosts = array(
		'//xu-distributor.local/',
		'//ms-distributor.local/',
		'//localhost/',
	);

	foreach( $self_signed_hosts as $host ) {
		if ( strpos( $url, $host ) !== false ) {
			$args['sslverify'] = false;
		}
	}

	return $args;
}

add_filter( 'wp_is_application_passwords_available', 'Run\\This\\In\\Local\\Development\\Only\\It\\Is\\Unsafe\\application_passwords_available' );

add_action( 'wp_authorize_application_password_request_errors', 'Run\\This\\In\\Local\\Development\\Only\\It\\Is\\Unsafe\\no_scheme_errors' );

add_filter( 'http_request_args', 'Run\\This\\In\\Local\\Development\\Only\\It\\Is\\Unsafe\\no_ssl_verify_locally', 10, 2 );
```

**Comment by jeffpaul** [comment]
@peterwilsoncc might it be worth adding that to the `Snippets` part of the Distributor dev docs site (including the strong DO NOT USE IN PRODUCTION note)?
