### ISSUE TITLE
Meta value not pushed correctly if the value is an array

### ISSUE THREAD

**Issue by ravichandrach1** [10up/distributor#191]
For Internal connections within the same multisite, If meta value is an array, only the last value is being saved for a pushed post.

Steps to reproduce:

1. Create a new post on the source site and create a custom meta with value `a:3:{i:0;i:1;i:1;i:2;i:2;i:3;}`.
2. Publish the post and Distribute it to any site on the network.
3. Check the meta value for the distributed post on the target site, the meta value will be `3`

The issue seems to be at https://github.com/10up/distributor/blob/master/includes/utils.php#LC116. As we are looping through all the values in the meta array, we are updating the meta with the current value in the array, so only the last value in the meta array will be persisted. Not sure on why we are looping through the values if the meta value is an array.

```
$meta_array = (array) $meta_value;
			foreach ( $meta_array as $meta_item_value ) {
				if ( ! in_array( $meta_key, $blacklisted_meta, true ) ) {
					$meta_item_value = maybe_unserialize( $meta_item_value );
					update_post_meta( $post_id, $meta_key, $meta_item_value );
				}
			}
```

**Comment by jeremyfelt** [comment]
I ran into this as well and started poking at a solution (#193). With that branch, I'm able to distribute featured media and meta array values as expected.

**Comment by dkotter** [comment]
@ravichandrach1 Can you test this again with PR #193? I've just tested following your instructions and I do see the meta values being distributed correctly now if they are arrays. But would love if you could test as well and confirm this fixes the issues you're seeing. Thanks!

**Comment by ravichandrach1** [comment]
@dkotter Tested PR#193 on multiple sites and networks, it fixes the meta value array issue. This is good to merge. Thanks!
