### ISSUE TITLE
Revamp branch structure and release method

### ISSUE THREAD

**Issue by helen** [10up/distributor#195]
Right now the branch naming and defaults defy convention and our own git-flow-based best practices, in that `master` is what we would typically call `develop` and `stable` is really `master`. This is confusing for a lot of dev users who expect to be able to use master in production, whether that is a reasonable expectation or not. We should not rename things just to rename them though, which would also cause problems for clones. There's also the matter of how the plugin gets packaged up and downloaded - right now all downloads get all the files in the repo, whether as a ZIP or a git clone. To that end, I propose we do the following at the point of next release (well, directly after release):

- [x] "Freeze" `master` as a representation of stable **development** code until the next release when we merge `develop` into `master` as usual. `stable` is now the representation of stable **release** code.
- [x] Create a `develop` branch off of `master` to serve as the "bleeding edge" moving forward.
- [x] Set the default branch on GH to be `develop` so that PRs go to the right place.
- [x] Change the parent branch of outstanding PRs to `develop`. For some PRs this may require some merging so that it can be done cleanly in the UI. Better to do this as much as possible rather than close and create new PRs.
- [x] Delete all built files from `master` and stop committing built files. IMPORTANT: This will break installs where people update by pulling from Git. This is on purpose. We will need to add some kind of admin notice letting them know they need to either run `npm build` or switch to `stable`. We could potentially manage this the same kind of way WordPress core does - by appending `-src` to the version number and letting the build process remove that for the actual released package and then detecting that in the version string plus checking for a built file before showing a notice. A PR for that notice can be started now.
- [x] Delete all source files from `stable`, as well as any other files that are unnecessary for the plugin to run (e.g. tests). All releases should continue to be packaged up from `stable`. This will "orphan" the `stable` branch, as it will diverge and will no longer be able to receive merge commits.
- [x] Figure out the best way to commit to `stable` moving forward. Automation is preferable - seems likely the best method will be having CI handle build + commit based on tools made for `gh-pages` which is a similar situation (e.g. https://github.com/X1011/git-directory-deploy). That said, because this is also where releases come from, it will need to be tested extremely thoroughly.
- [x] Tags moving forward should be tagged both on `stable` and `master`, using `X.Y.Z` and `X.Y.Z-src` or similar, respectively.
- [x] Document the branch structure and download instructions very clearly in multiple places, especially where people might be entering from places other than the repo home on GitHub (i.e. don't assume people read the entire readme). We should probably be generally pushing people to download the actual ZIP package rather than cloning the repo, but if they want to clone the repo in production, they will want to stay on the `stable` branch. If they want to run `master`, they will need to be handling builds themselves.
- [x] Document the release procedure very thoroughly.
- [x] Test everything. At least twice.

**Comment by tlovett1** [comment]
This makes sense to me.
