### ISSUE TITLE
Product Attributes  [ Bug ]

### ISSUE THREAD

**Issue by madmax3365** [10up/distributor#197]
Because of this peace of code in utils.php set_meta function <br>
<pre><code> 
foreach ( $meta_array as $meta_item_value ) {
				if ( ! in_array( $meta_key, $blacklisted_meta, true ) ) {
					$meta_item_value = maybe_unserialize( $meta_item_value );
					update_post_meta( $post_id, $meta_key, $meta_item_value );
				}
</code></pre>
_product_attributes meta saving in wp_postmeta as serialized flat array.
How data should be <pre><code>a:1:{s:8:"pa_gfads";a:6:{s:4:"name";s:8:"pa_gfads";s:5:"value";s:0:"";s:8:"position";i:0;s:10:"is_visible";i:1;s:12:"is_variation";i:0;s:11:"is_taxonomy";i:1;}}</code></pre>
How data saved now <pre><code>a:6:{s:4:"name";s:6:"pa_asd";s:5:"value";s:0:"";s:8:"position";s:1:"0";s:10:"is_visible";s:1:"1";s:12:"is_variation";s:1:"0";s:11:"is_taxonomy";s:1:"1";}</code></pre>

**Comment by helen** [comment]
Hi @madmax3365 - thanks for the report. Could you confirm if this is the same issue as reported in #191 and, if possible, if #193 fixes the issue for you?

**Comment by madmax3365** [comment]
> Hi @madmax3365 - thanks for the report. Could you confirm if this is the same issue as reported in #191 and, if possible, if #193 fixes the issue for you?

An update does not fix the issue. We must receive _product_attrubutes like this array
<code><pre>
Array
(
    [pa_asd] => Array
        (
            [name] => pa_asd
            [value] => 
            [position] => 0
            [is_visible] => 1
            [is_variation] => 0
            [is_taxonomy] => 1
        )

    [fga] => Array
        (
            [name] => Fga
            [value] => abc
            [position] => 1
            [is_visible] => 1
            [is_variation] => 0
            [is_taxonomy] => 0
        )

)
</pre></code>
But received something like 
<code><pre>

 
Array
(
    [0] => Array
        (
            [name] => pa_asd
            [value] => 
            [position] => 0
            [is_visible] => 1
            [is_variation] => 0
            [is_taxonomy] => 1
        )

    [1] => Array
        (
            [name] => pa_test
            [value] => 
            [position] => 1
            [is_visible] => 1
            [is_variation] => 0
            [is_taxonomy] => 1
        )

)
</pre></code>

**Comment by dkotter** [comment]
@madmax3365 thanks for the additional feedback and testing. I just pushed a fix (in #224) that will use the keys from the meta array we are processing, when saving that meta to the distributed post. In my test, using the meta value you reference above, this appears to fix the issue. If you have time, would love if you could test out that PR and verify it fixes your issue. Thanks!

**Comment by dkotter** [comment]
@madmax3365 Ah, my bad. Just noticed you had already opened a PR (#215) that does the exact same thing as the PR I just opened. Closing mine out in favor of yours, thanks so much for the fix here!
