### ISSUE TITLE
Post Updating Failed (500 error)

### ISSUE THREAD

**Issue by Kpudlo** [10up/distributor#203]
Hello!

I've really enjoyed using Distributor for a multisite I've setup. However, I'm having an issue with one site being able to update a published post.

![image](https://user-images.githubusercontent.com/4432822/45883055-f8f27100-bd7d-11e8-87ad-243c78861cad.png)

I'm not having any problems with saving drafts. I have disabled all plugins, and changed themes back to the the standard twenty-seventeen, but it still happens. When I disable Gutenberg, I get an HTTP 500 error page. 

I had an issue with a timeout when I originally pulled information to the main site from this sub site at one point, I don't know if that has anything to do with this either.  That was due to me still setting up the server and not having the innodb/apache settings optimized at the time, but I've worked through those issues.

Thank you again for the plugin!
-Kevin

**Comment by dkotter** [comment]
Hey @Kpudlo, thanks for the report! Do you happen to know if Gutenberg is giving any error messages in the browser console? Having those errors would be helpful in trying to debug this. Trying to narrow down whether this is just a Gutenberg issue or something wrong on the Distributor side (though the report of getting a 500 error when Gutenberg is disabled seems like it would make Distributor the culprit). Thanks!

**Comment by jeffpaul** [comment]
@Kpudlo is this still an issue and if so could you clarify the question from @dkotter above?

**Comment by Kpudlo** [comment]
@jeffpaul, @dkotter, my apologies for not replying back in September! This is no longer an issue for me. Thank you for your assistance!

**Comment by jeffpaul** [comment]
Closing as resolved, thanks!
