### ISSUE TITLE
Ensure plugin passes WordPress VIP standards

### ISSUE THREAD

**Issue by adamsilverstein** [10up/distributor#206]
This feedback is from a code review by @tomjn:

- The Update checker uses htmlentities in places were esc_html should be used
- The Update checkers uses @ operators to swallow a warning parse_url generates, but that warning was eliminated in PHP 5.3.3. If it can be bumped to PHP v5.3 minimum rather than 5.2 then these can be eliminated

**Comment by peterwilsoncc** [comment]
This was largely achieved in https://github.com/10up/distributor/pull/901

There are still issues in the plugin updater that need to be resolved as it doesn't meet the VIP Coding standards. The only real solution I see for that is to either source another GitHub to WP updater script or write a custom one for use with 10up plugins distributed in this manner.

I'm not really keen on the latter.

**Comment by jeffpaul** [comment]
Marking this as closed by #901 in `1.7.0`.
