### ISSUE TITLE
Can't Pull Content - External Connection URL Error

### ISSUE THREAD

**Issue by catlawson09** [10up/distributor#209]
Hello,

I have attempted to set up an External Connection but when I set up the External Connection URL it shows:

"Limited connection established. Authentication failed.
Push distribution unavailable.
Pull distribution limited to basic content, i.e. title and content body."

My error logs show a "client denied by server configuration'. 

I have added the `RewriteRule .* - [E=REMOTE_USER:%{HTTP:Authorization}]` to the .htaccess file, assuming it was an HTTP Authorization issue. I had found a ticket that related to this and it seemed to have been a bug?

Additionally - Even when I have done the reverse with the sites to see if the other site will pull content, the External Connection seems to be green but all it says when I try to pull content is "Could not pull content from connection due to error".  But there is none of the above errors.

Essentially, I'm not sure if there is something I"m missing in the set up process or where any of the errors are coming from.  I haven't been been able to get the plugin to work thus far so any guidance on how to get this plugin to work and work properly would be great!

Thanks!

**Comment by dkotter** [comment]
@catlawson09 Thanks for the report! I know there's another issue opened (#164), where a connection was showing as being available even when it wasn't really. That sounds like part of what you might be running into here as well.

For the first part, Distributor does require Basic Authentication be setup for external connections to work correctly. We recommend using the [Application Passwords](https://wordpress.org/plugins/application-passwords/) plugin for that. Have you set up any sort of authentication for this connection?

**Comment by catlawson09** [comment]
@dkotter Thank you for your assistance and your suggestion. Installing the Applications Passwords plugin and using that seemed to have pulled the content. 

Thank you again!

**Comment by dcgraphics1** [comment]
Hello, I've encountered a similar error with No external connection, After adding the url, it specifies the page ID (ex: https://www.xxxx.org/?p=21) then it says Did you mean: https://xxxx.org/wp-json?
So, I've downloaded the the Application Passwords, then I was prompted to change the htaccess files for connecting the sites. And then the plugin wants to base64 encode it using a terminal window as well as your username to use it with the REST API. A bit too much to make this plugin work. Let me know if there is a better solution.

**Comment by jeffpaul** [comment]
@dcgraphics1 I'm working on updating our documentation to provide more detailed setup instructions for External Connections.  If you're still having problems, then please give this a try: https://github.com/10up/distributor/tree/fix/readme-instructions#setup-external-connections-using-application-passwords

**Comment by jeffpaul** [comment]
@dcgraphics1 any updates on trying those instructions for setting up External Connections?
