### ISSUE TITLE
Search in Pull UI incorrectly sanitizes

### ISSUE THREAD

**Issue by ChaosExAnima** [10up/distributor#230]
In the Distributor Pull UI, searching is returning incorrect results for queries with spaces or other formatting.

Reviewing the code, and it seems that `sanitize_key` was used to sanitize search text, which strips out all text and formatting. Suggest replacing that with `rawurlencode` or `sanitize_text_field`.

**Comment by robbiet480** [comment]
Funny, I was just planning to report this as well, good timing @ChaosExAnima :)

@helen This one seems somewhat bad so I'm tagging you, hope that's OK!

**Comment by ChaosExAnima** [comment]
I try! PR is now up whenever you're ready, @helen. Thanks!

**Comment by helen** [comment]
For history, this was introduced in https://github.com/10up/distributor/commit/5600b2aafb639d9e13b8c84f8ff7760bdf54ede4
