### ISSUE TITLE
Cannot pull content

### ISSUE THREAD

**Issue by Cynthia20189** [10up/distributor#235]
Hi there,
I'm trying to add an external connection to a second site that I manage. I'll add the URL (I have tried the URL for the blog and the URL for a single post), and it will give me other suggestions (such as the other site's URL with a post number attached, such as site2.org/?p=12345 which doesn't work, either). 
When I go to the External Connections tab in the WP dashboard menu, the Connection I added comes up, but there's a yellow circle with "verify" beside it. When I click on that, it will take me "edit connection" and then will say "no connection found" when I'm in the edit connection screen. 
I've checked that UN and PW are correct for the site I want to pull from, the URLs are either the blog or the post themselves, and I'm an admin on both sites. 
I'm not quite sure what else to try. Thanks!

**Comment by dkotter** [comment]
Hi @Cynthia20189,

Couple things you can test here. The URL you enter for the external connection should point to the JSON endpoint, which should be `site2.org/wp-json/` (or at least that's what I always use). Also, and you may already have this set up, but external connections require HTTP Basic Authentication be set up. We typically recommend the [Application Passwords](https://wordpress.org/plugins/application-passwords/) plugin for this.

Let me know if either of those suggestions helps out here.

**Comment by helen** [comment]
Closing out for now, however please do continue the conversation as needed and we can always reopen the issue or create new ones if we find bugs. I've opened #260 to talk about making the onboarding/setup process better.
