### ISSUE TITLE
Timeout on ajax_verify_external_connection

### ISSUE THREAD

**Issue by madmax3365** [10up/distributor#244]
When trying to create an external connection with the site, which has over 10 post types  ajax_verify_external_connection can't establish a connection because of a timeout. 
The core problem in WordPressExternalConnection's check_connections method. It gets all post types available in REST and does for each of them remote_get and remote_post to check user's permissions.
<code><pre>
foreach ( $types as $type_key => $type ) {
...
$type_response = wp_remote_get( $link, $this->auth_handler->format_get_args( array( 'timeout' => self::$timeout ) ) );
					 }
					 if ( ! is_wp_error( $type_response ) ) {
					 $code = (int) wp_remote_retrieve_response_code( $type_response );
					 if ( 401 !== $code ) {
					 $can_get[] = $type_key;
					}
...
		if ( in_array( 'POST', $routes[ $route ]['methods'], true ) ) {
					$type_response = wp_remote_post(
					$link,
					$this->auth_handler->format_post_args(
					array(
					'timeout' => self::$timeout,
					'body'    => array( 'test' => 1 ),
					)
					)
					);
					if ( ! is_wp_error( $type_response ) ) {
					$code = (int) wp_remote_retrieve_response_code( $type_response );
					if ( 401 !== $code ) {
					$can_post[] = $type_key;
					}
					}
					 }
...
}
</pre></code>

**Comment by arsendovlatyan** [comment]
Hey @helen ,
In our case we have ~15 post types and it's a problem to get external connection verified, usually, therefore, we had to change external connection verification process.
It will be very nice if we can include this change in next releases, for sure happy to make any improvement/fix that you will point out.

**Comment by helen** [comment]
Thanks for the diagnosis and PR - we will take a look at your approach and consider it as we figure out our ideal scenario for how this should work.
