### ISSUE TITLE
Comments activated by default when sharing post between 2 sites with comments globally disabled

### ISSUE THREAD

**Issue by jonpasquier** [10up/distributor#249]
Hi, 

I have 2 instances of WordPress with comment globally disabled (Settings > Discussion > Allow people to post comments on new articles is unchecked on both sites) but when the post appears on the destination sites both Allow comments and Allow trackbacks checkboxes of the post discussion metabox are checked by default.

The expected behaviour in this case would be to not have any of these checkboxes checked.

I'm using the latest distributor release, which is installed on both sites.

Thank you!

**Comment by helen** [comment]
Thanks for the report - we will take a look!

**Comment by helen** [comment]
Confirmed that comments/pingbacks are always on after a pull, whether it was globally set that way or explicitly turned off for that post. It seems to inherit the receiving site's settings on push.

**Comment by helen** [comment]
@jonpasquier If you're in a position to test patches, I've opened #251 which fixes this issue for me.

**Comment by jonpasquier** [comment]
Hi Helen,

Sorry for the delay.

I have been able to test your patch and I confirm that it is working, now discussion settings are preserved when a post is pulled from another website.

Thanks!
