### ISSUE TITLE
Issue with Notices in Gutenberg

### ISSUE THREAD

**Issue by JasonHoffmann** [10up/distributor#252]
I looked around and didn't see an issue for this, but it seems that recent updates to Gutenberg broke the notices being used in the plugin. The notices currently don't show at all with the latest version of Gutenberg. The issue appears to arise from this PR: https://github.com/WordPress/gutenberg/pull/9617.

The first issue is that the notice method from `gutenberg-syndicated-post.js` is no longer part of the `core/editor` data package, but `core/notices`. That's a fairly simple fix though.

The larger issue seems to be that the `createWarningNotice` method no longer accepts an element as it's first argument, but instead accepts a string, followed by a series of actions, the best example of which I found here: https://github.com/WordPress/gutenberg/blob/8cbfb3cca07ff7e517cd908315cfb75ab92a4eb7/packages/editor/src/components/provider/index.js#L34-L47

That means the `gutenberg-syndicated-post.js` file would need to be changed to reflect this, and some of the language would likely need to change as well. I may be wrong, and there may be a way to pass a WP Element to the `createWarningNotice` function, but I haven't found one yet. The only thing I've gotten working is refactoring the notices to use plain text strings and a series of actions after, for instance:

![screen shot 2018-11-15 at 12 19 05 pm](https://user-images.githubusercontent.com/1718298/48569802-b4440b80-e8d0-11e8-9cdb-eb09d4845ace.png)

From a UX perspective, however, you may want to change the messaging, or try and figure out a way to add plain HTML or WP Elements to the `createWarningNotice` method. I have a branch in progress I'd be happy to submit so you can see how I've got it working, but I'm betting you would want to make changes to the way the messages are structured. Let me know and I can post some more screenshots of the other messages, or submit the PR so y'all can take a look.

Thanks!

**Comment by adamsilverstein** [comment]
Thanks for the bug report @JasonHoffmann - would be happy to review a branch in progress! can you please open a PR and prefix the title with `WIP:` (which explicitly prevents it from being merged)?
