### ISSUE TITLE
Empty posts created when pushing

### ISSUE THREAD

**Issue by stevehadley** [10up/distributor#255]
When post/s are pushed from site A to site B many empty posts are created, as well as the intended post/s, empty posts are listed as:

(no title) — Draft

WordPress version : 4.9.8
Plugins installed : 'Distributor' and 'Application Passwords'

**Comment by stevehadley** [comment]
Two months an no reply?

**Comment by helen** [comment]
I apologize, must have missed this during triage. Is this still happening to you, and is it consistent with every push or just some of them?

**Comment by evolveonline** [comment]
Hi Helen. I am having the same issue. I am testing the plugin at the moment and I've setup a network of test sites. I am syndicating blog posts to each site, but empty draft pages are being created, as described above.

**Comment by stevehadley** [comment]
It's a reallllly good plugin, very keen to implement but can't with this issue.

**Comment by jeffpaul** [comment]
@stevehadley @evolveonline are you still seeing these empty posts getting created or can this be closed as resolved now?

**Comment by stevehadley** [comment]
@jeffpaul no still seeing the empty posts. What commit was supposed to resolve this?

**Comment by evolveonline** [comment]
@jeffpaul unfortunately the empty posts became too much of a problem for us so we ended up switching to Broadcast

**Comment by jeffpaul** [comment]
@stevehadley no specific commit is known to resolve this, but I've been unable to replicate this locally.  Please confirm which plugins/theme are active, if Distributor is setup on a multisite / different WP instances / or both, and anything else that may be unique about your setup so we can best help triage... thanks!

**Comment by jeffpaul** [comment]
@evolveonline apologies that we weren't able to resolve this for you.  I'd be curious if there are other features of Broadcast that made you consider that over Distributor, as we'd like to ensure Distributor best meets the needs of the community... thanks!

**Comment by jeffpaul** [comment]
@stevehadley note that we just released version 1.5.0 with some major improvements to the push menu and pull screen, mind checking to see if you're still getting empty posts or confirming that all appears to be functioning properly now (as I'm still unable to replicate your issue)?

**Comment by rickyangeles** [comment]
@jeffpaul I've also noticed this when pushing content to sites in a local environment.

**Comment by jeffpaul** [comment]
@rickyangeles are you seeing that in the latest version (1.5.0)?  If so, can you confirm what other plugins/themes are installed on your sites so I can try to replicate and triage further?

**Comment by rickyangeles** [comment]
@jeffpaul Below is a list of plugins and the version being used.

Advanced Custom Fields PRO (5.8.2)
Application Passwords (0.1.0)
Auto Upload Images (3.2.2)
Custom Post Type UI (1.6.2)
Debug Bar (1.0)	
Distributor (1.5.0)
Go Live Update URLS (5.2.9)
Gravity Forms (2.4.11)
WordPress Importer (0.6.4)
WP Migrate DB Pro (1.9.8)	
WP Migrate DB Pro Media Files (1.4.14)
WP Migrate DB Pro Theme & Plugin Files (1.0.5)
Yoast SEO (11.7)

**Comment by rickyangeles** [comment]
Theme is UnderStrap (https://understrap.com/)

**Comment by jeffpaul** [comment]
@rickyangeles is your local environment multisite or different instances?

**Comment by jeffpaul** [comment]
Thanks to some triage from @rellison959, I've been able to replicate empty `Pages` (though not `Posts`).  There are two scenarios where this occurs:
1) On wp-admin/admin.php?page=distributor, clicking the `(Verify)` link for an External Connection will generate a single `(no title) — Draft` Page on that external site.
2) On wp-admin/post.php?post=###&action=edit (where ### is a number for a valid External Connection), clicking the `Update Connection` button will generate two `(no title) — Draft` Pages on that external site.

**Comment by jeffpaul** [comment]
@stevehadley @rickyangeles can you confirm whether you're seeing empty Posts or Pages?  We've replicated an issue with empty Posts (see my previous comment), but have yet to replicate for Posts.

**Comment by rickyangeles** [comment]
@jeffpaul The sites are different instances. I was able to replicate the issue using the two scenarios you listed above, each scenario producing a single draft Page. Did not notice any new empty Posts.

**Comment by jeffpaul** [comment]
@rickyangeles thanks for the confirmation, I'll keep you posted once a fix for this makes it into a Distributor release.

**Comment by johnwatkins0** [comment]
Note with regard to this scenario:

> On wp-admin/admin.php?page=distributor, clicking the (Verify) link for an External Connection will generate a single (no title) — Draft Page on that external site.

It's not actually the "(Verify)" link in particular that causes the empty post to send. Clicking the title of the external link post also does it, as does refreshing wp-admin/post.php?post=###&action=edit where ### is a number for a valid External Connection.

**Comment by johnwatkins0** [comment]
Also noting that empty posts of the `wp_block` post type are also being generated at the same time:

<img width="718" alt="Screen Shot 2020-02-05 at 10 22 40 PM" src="https://user-images.githubusercontent.com/9020968/73905783-1edebf80-4866-11ea-939b-7db1e044c204.png">

Doesn't seem to be affecting any other post types. 🤔

**Comment by jeffpaul** [comment]
Closed via #245
