### ISSUE TITLE
Onboarding: External connection setup is confusing

### ISSUE THREAD

**Issue by helen** [10up/distributor#260]
Setting up a fully-capable external connection is a bit confusing and requires the installation/setup of authentication methods that are not currently built into WP. There are a few things here that I think could use improving:

- [x] Change `External Connection Type` to make it more clear that it's about the authentication method (currently Basic Authentication or oAuth 2 via WordPress.com - NOT a WordPress.com site)

- [x] Add links to plugins/resources on setting up a given auth method - the oAuth one does some of this already

- [x] Clarify some of the language (e.g. `Please be warned all these users will inherit the permissions of the user on the remote site` could be helped with an example)

**Comment by helen** [comment]
Looks like Application Passwords also works fine, which is perhaps a better suggestion to give than the actual Basic Auth plugin?

**Comment by adamsilverstein** [comment]
Yes, **Application Passwords** is what I use and would actually like to see us consider bundling it (via composer) with Distributor. I opened an issue to support its recent addition of a setup flow that makes using it much easier, see https://github.com/10up/distributor/issues/286
