### ISSUE TITLE
Do internationalization properly

### ISSUE THREAD

**Issue by helen** [10up/distributor#267]
Coming out of #266, let's do internationalization properly! These are probably worth breaking out into sub-issues:

- [x]  Fix up the way strings are internationalized generally (I see a bunch of English-centric assumptions that don't actually work such as appending an `s` to pluralize)
- [x] Do everything correctly to get things registered in PHP and JS
- [ ] Add JS PO file generation to the build process
- [ ] Lay out a plan for how we source and include translations

**Comment by jeffpaul** [comment]
Noting that we may want to consider including https://github.com/varunsridharan/action-wp-pot-generator as part of our release process.

**Comment by peterwilsoncc** [comment]
> Add JS PO file generation to the build process

See #947 

> Do everything correctly to get things registered in PHP and JS

Covered by #916 (use wp-scripts) and #935 (fixing untranslable strings)

> Lay out a plan for how we source and include translations

Some discussion of using [wearerequired/traduttore](https://github.com/wearerequired/traduttore) in #660 but under discussion.

**Comment by jeffpaul** [comment]
Noting that I would be fine holding off on `Lay out a plan for how we source and include translations` as long as the POT file generated is as accurate and complete as we can make it (as then Distributor users can generate their own translation files for locales of particular need and include those themselves).  Current research seems to point to sourcing and including translations may be more work than eventual benefit (for a plugin not able to make use of the translate.wordpress.org infrastructure).
