### ISSUE TITLE
A large network with hundreds sites leads to inaccessible Pull Content screen

### ISSUE THREAD

**Issue by JinZhenlin** [10up/distributor#270]
This is the first time we try the plugin on our network with about 292 sites . We network-activated the Distributor plugin, went to a site's dashboard and selected Distributor > Pull content. But the page was never able to load after more than 5 minutes. Eventually the connection timed out. We need to know if there are any known issues for this plugin to work with a large number of sites. Thanks!

**Comment by jeffpaul** [comment]
Thanks for this @JinZhenlin , definitely looks like an opportunity for some performance tweaks.  We'll look into this to see what we can improve.  If you have interest and availability to work on a PR, we'd greatly appreciate it... thanks!

**Comment by dkotter** [comment]
@JinZhenlin Thanks for this report. I just pushed some fixes in #355 that significantly sped things up for me. Would love to hear your thoughts on that and if you have time to test, to see if this helps in your use case. Thanks!

**Comment by jeffpaul** [comment]
@JinZhenlin any updates on being able to test PR #355 to see how it improves/impacts your loading issue?
