### ISSUE TITLE
Gutenberg: Can't publish post distributed as draft

### ISSUE THREAD

**Issue by helen** [10up/distributor#272]
The second publish button (when you have the pre-flight checklist enabled) is disabled, making it impossible to publish a distributed post without resorting to a bulk edit on the posts list.

**Comment by helen** [comment]
Testing this against 5.0-RC3, it seems that the publish button is disabled even on initial load.

**Comment by devjclose** [comment]
This issue resurfaces if using Classic Editor plugin. Publish button (and all publish related options) are disabled.

Tested with WP 5.0.3, Classic Editor 1.3 and Distributor 1.3.7
