### ISSUE TITLE
Attachments cannot be loaded from local environments

### ISSUE THREAD

**Issue by helen** [10up/distributor#280]
Due to the `http_request_host_is_external` filter in core, remote get requests to domains that resolve to IP addresses that appear to be internal (e.g. start with `127` or `192`, among others) fail out and somewhat non-descriptively. I am not sure if this can actually impact production environments since network connections are processed differently from external connections, but I think we should probably proactively set that to `true` for Distributor requests.

We also need to consider handling and reporting the failure to distribute media items but that is broader and needs its own issue.

**Comment by Ritesh-patel** [comment]
Opened https://github.com/10up/distributor/pull/323 which fixes this. We yet to add unit tests for process_media function, and when we do, we can add test for this filter.
