### ISSUE TITLE
Feature: Easier setup flow for Application Passwords & External connections

### ISSUE THREAD

**Issue by adamsilverstein** [10up/distributor#286]
Since https://github.com/georgestephanis/application-passwords/pull/39#issuecomment-283677076 Application Password supports a much easier flow when setting up an application password. Distributor can link to the remote site with a special URL that lets the user create the new key on the fly, during the setup flow. 

Implementing this flow would make external connection setup much smoother.

From the PR:
> The idea is to give a page in wp-admin where you can send a user, they can authenticate via wp-login.php if needed, then manually approve (or reject) it and it will send the user back to the app with an application password in tow that the app can store and use.

> It saves the user from having to find their profile page and create and retype or copy/paste an application password. Should be more understandable.

**Comment by helen** [comment]
That's really cool! Is that released in the App Passwords plugin on .org?

**Comment by jeffpaul** [comment]
Note that we're planning to ship plugin detection only in 1.4, and can investigate this magic link in 2.0

**Comment by kasparsd** [comment]
@helen https://github.com/georgestephanis/application-passwords/pull/39 is now part of Application Passwords version 0.1.0 on WP.org.

**Comment by adamsilverstein** [comment]
Yea! ❤️ ❤️ ❤️
