### ISSUE TITLE
push-ui Fatal error

### ISSUE THREAD

**Issue by mikemorales** [10up/distributor#288]
anyone have this error when you try activate the plugin?

Fatal error: Can't use function return value in write context in /home/moralesy/public_html/cliente/ALLABOUTCABO/wp-content/plugins/distributor-stable/includes/push-ui.php on line 328

**Comment by Ritesh-patel** [comment]
Hi @mikemorales 

I think this is related to php running on your server, which php version you are using? Distributor requires php 5.6+.

Thank you.

**Comment by helen** [comment]
Closing this pending further feedback from @mikemorales. Agree that it sounds like a PHP version issue.
