### ISSUE TITLE
Several Media Types Processing

### ISSUE THREAD

**Issue by madmax3365** [10up/distributor#300]
Currently, distributor creates attachments in destination only for images with extensions `jpeg|jpg|gif|png`.  We need to distribute attached pdf files with the post, but because of process_media function in `utils.php` line 591, we can't. We think it's a good idea to provide a filter in the mentioned function, so users could decide which media type they want to process.

**Comment by helen** [comment]
Being able to filter this makes sense to me. Currently in #301 this ends up becoming a per-filename thing, does it perhaps make more sense to filter the regex for matches? Or perhaps to have both so you can also decide not to process a specific item?

**Comment by madmax3365** [comment]
@helen I've added a filter for regex. Please review it, and let us know which of the filters you want to keep, so we could continue our development.
