### ISSUE TITLE
get_available_authorized_sites() scaling issue with lots of sites

### ISSUE THREAD

**Issue by michaelradojevic** [10up/distributor#309]
The time it takes to run the wp_remote_post() calls in get_available_authorized_sites() really adds up when you have more than a few sites in a multisite network (we have 49). Logged in users are getting 10-20 second page load times on supported post types. Here's a screenshot from Query Monitor:

![image](https://user-images.githubusercontent.com/46765002/51355797-0d652280-1a6d-11e9-896f-00fd2c611484.png)

I'm not familiar enough with the WordPress API to know if there's a better way to do this, but having Distributor figure out the authorized sites in the background would at least allow the post to load immediately.

It looks like #270 might be a similar issue.

**Comment by jeffpaul** [comment]
Thanks for this @michaelradojevic , definitely looks like an opportunity for some performance tweaks.  We'll look into this along with #270 to see what we can improve.  If you have interest and availability to work on a PR, we'd greatly appreciated it... thanks!

**Comment by dkotter** [comment]
@michaelradojevic Thanks for this report. I just pushed some fixes in #355 that significantly sped things up for me. Would love to hear your thoughts on that and if you have time to test, to see if this helps in your use case. Thanks!

**Comment by jeffpaul** [comment]
@michaelradojevic any updates on being able to test PR #355 to see how it improves/impacts your loading issue?

**Comment by michaelradojevic** [comment]
@jeffpaul @dkotter Sorry about the lack of updates - I've been busy with lots of non-web stuff lately (do-all IT). I'll try to get some testing in by the end of this week and update with my results.

**Comment by michaelradojevic** [comment]
@dkotter @jeffpaul That took care of it! With these commits I'm now seeing only ~70 ms added to page loads with Distributor enabled vs. the 10-20 seconds I'm seeing with the current release.

**Comment by jeffpaul** [comment]
@michaelradojevic thanks for the feedback, stay tuned for the 1.5.0 release as that'll most likely be where these improvements get included!
