### ISSUE TITLE
The distributor REST API field are not getting populated correctly 

### ISSUE THREAD

**Issue by ivanlopez** [10up/distributor#324]
Once a piece of content is distributed if you look at that content via the WordPress REST API the `distributor_original_site_name` and the `distributor_original_site_url` are not populated correctly. Instead of having the original site name and URL they are pointing at the current site name and home url.

**Comment by jeffpaul** [comment]
@ivanlopez nice catch; if you've got time we'd welcome a PR to populate those correctly!
