### ISSUE TITLE
Taxonomy slugs generated with special characters

### ISSUE THREAD

**Issue by gaelgerard** [10up/distributor#325]
Hello,

In my main website I have CPT taxonomies named with the inches character (Ecran 4.3″...).

While wp will remove those character to generate the slug (ecran-4-3), Distributor is keeping them to generate new slugs when pulling CPs in the child website (ecran-4-3″).

This creates bugs in pulling those posts wich aren't associated to the new taxonomy.

May I suggest to import the existing slugs (generated by wp or created manually in the main site) instead of generating new ones.

It would certainly be easier than escaping special characters in Distributor code and it should take less ressources in the pull process??

Thank you for your help and GREAT plugin 👍

**Comment by jeffpaul** [comment]
@gaelgerard thanks for the feedback, it's greatly appreciated!  We'll take a look at reproducing this locally and if so we'll work to see where it might fit on our release roadmap.  If you have availability and interest to submit a PR to resolve this, then we'd happily review that with you.  Cheers!

**Comment by arsendovlatyan** [comment]
@jeffpaul you may consider https://github.com/10up/distributor/pull/262 , which will solve this issues and few other issues.
