### ISSUE TITLE
PHP Warning in set_meta function

### ISSUE THREAD

**Issue by madmax3365** [10up/distributor#330]
Distribution and post update generates PHP warning in the destination. <br> `Warning: Invalid argument supplied for foreach() in distributor/includes/utils.php on line 125` <br> Warning occurs because in `utils.php` `function format_media_post` line `592` plugin assigns <br> `$media_item['meta'] = \Distributor\Utils\prepare_meta( $media_post->ID );` <br> And inside  `prepare_meta` it filters meta_keys excluding all keys that are `in blacklisted_meta`. And because there's case that media_item has only metas with blacklisted keys, so in `utils.php` line `540` it passes empty array to function <br> `set_meta( $image_id, $media_item['meta'] )`. <br> We can simply check if  `isset($media_item['meta'])` before calling `set_meta` function

**Comment by jeffpaul** [comment]
@madmax3365 thanks for this issue and related PR!  We're working towards a 1.4.0 release in the near future and will look at pulling this into that or a quickly following release.
