### ISSUE TITLE
Can't publish post distributed as Draft

### ISSUE THREAD

**Issue by nate-allen** [10up/distributor#333]
Somewhat related to #272 but not Gutenberg. Updated the plugin to 1.3.8 and now when a post is distributed as Draft, it can't be published because the button is disabled.

![screenshot](https://user-images.githubusercontent.com/8797898/53046697-a4533f00-345e-11e9-9c68-05521451d94c.png)

**Comment by jeffpaul** [comment]
@nate-allen is that the original post or a distributed post?

**Comment by nate-allen** [comment]
@jeffpaul That's a distributed post

**Comment by jeffpaul** [comment]
@nate-allen: @adamsilverstein will help me triage this and once we get to a resolution we'll let you know of any quickly occurring releases for this issue.

**Comment by adamsilverstein** [comment]
testing locally in 4.9, the publish button is available for distributed draft posts:

![](https://cl.ly/a4616a24ae12/68747470733a2f2f636c2e6c792f3461353038336536303666622f456469745f506f73745f5f4d795f47726561745f426c6f675f5f576f726450726573735f3_2019-02-19_22-37-33.jpg
)

I'll test in 9to5preprod next.

**Comment by jeffpaul** [comment]
@nate-allen confirming here that this should now be resolved with the 1.3.9 release: https://github.com/10up/distributor/releases/tag/1.3.9
