### ISSUE TITLE
No connections available for distribution. Multisite

### ISSUE THREAD

**Issue by edemir206** [10up/distributor#338]
Hi,

I just can't make this plugin work in a single multisite installation, always shows this message: No connections available for distribution for every user in the network.

I have users in a custom role, do you need users to be in a special role or something ?

**Comment by arsendovlatyan** [comment]
Hey @edemir206 

- have you created connections ?
- if so and they are active, are you trying to distribute custom post type?

**Comment by jeffpaul** [comment]
@edemir206 thanks for the feedback on Distributor, it's much appreciated.  If you're using Distributor in a multisite setup, then you do not need to worry about setting up External Connections.  Any user logged into the network can distribute any content in the network to any other sites in the network where that user has permission to publish posts (assuming the site supports the same post type).  Can you confirm if you're still having issues and if so provide a little more detail so I can help troubleshoot with you?  Thanks again!

@arsendovlatyan thanks again for helping jump on issues here in GitHub, your help is very much appreciated as well!

**Comment by kg-lvargas** [comment]
I have the same issue. On a Multi site network the no initial connection are set for internal connection. I tried to use  Authentication method Wordpress.com Application and Mange to pull the post but the "Limited connection established. Authentication failed.
Push distribution unavailable.
Pull distribution limited to basic content, i.e. title and content body." message appeared. I don't have set the Application Passowrds plugin set up is this need it ?

**Comment by jeffpaul** [comment]
@kg-lvargas we're working to add more detail to our documentation here in GitHub, but for now you can follow these instructions to setup External Connections on WordPress multisite using the Application Passwords plugin: https://github.com/10up/distributor/tree/fix/readme-instructions#setup-external-connections-using-application-passwords

**Comment by mrazzari** [comment]
Maybe related: we inherited a framework that was doing a `session_start()` by default:

```php
function start_session() {
    if (!session_id()) {
        @session_start();
    }
}
add_action('init', 'start_session', 1);
```
This will cause the "No connections available for distribution" on multisite (no external connections).

A broken plugin / theme outputting text before the <!DOCTYPE> will cause the same issue, eg:
```php
function bad_plugin() {
    echo "-";
}
add_action('init', 'bad_plugin', 1);
```

**Comment by mrazzari** [comment]
Here's another one.

In `\Distributor\InternalConnections\NetworkSiteConnection::get_available_authorized_sites` it's doing an `admin-ajax` ping against every site in the network, to verify permissions.

I'm sure I'm missing something, but... Shouldn't this just `switch_to_blog()` to do these checks?

I've hit upon this issue in a staging install, where `https` was getting a bad cert error (lack of wildcard for subdomains). It's hard to debug unless you look at the plugin's code, because you don't really expect http requests to be fired for internal connections.

**Comment by jeffpaul** [comment]
Thanks for the debugging and feedback @mrazzari; if you've got time we'd welcome a PR to handle those issues!

**Comment by mrazzari** [comment]
Looks like the issues I reported above were fixed by @dkotter in b8dd5c4a (before we discussed them!).
Haven't tested it as I'm on the 1.4 stable, but the commit seems to be doing what it needs to do.

**Comment by jeffpaul** [comment]
@mrazzari great to hear!  Note that we're working on a release in the near term that'll include the commit you referenced, so the next stable build will likely resolve those for you.  Please do test that when it's available and let us know, thanks!

**Comment by jeffpaul** [comment]
@mrazzari note that this should be resolved for you with the v1.5 release.  Please check and let us know, thanks!

**Comment by jeffpaul** [comment]
@mrazzari will you please confirm that the latest release (v1.5) has resolved this for you?

**Comment by mrazzari** [comment]
@jeffpaul apologies for the silence, haven't had a chance to test this. Will do ASAP.

**Comment by jeffpaul** [comment]
@mrazzari any updates on your testing?

**Comment by jeffpaul** [comment]
@mrazzari any updates on your testing?

**Comment by jeffpaul** [comment]
I'm closing this due to lack of response and assuming connections are working correctly, but please re-open with additional details if things are not functioning as expected... thanks!
