### ISSUE TITLE
Warning: WordPressExternalConnection.php

### ISSUE THREAD

**Issue by Webagent05** [10up/distributor#347]
Hi there,

receiving the following error:

Warning: Invalid argument supplied for foreach() in /home/user/public_html/wp-content/plugins/distributor-stable/includes/classes/ExternalConnections/WordPressExternalConnection.php on line 331

shows me an empty page, ... but there should be 30 posts visible.
![distributor-issue](https://user-images.githubusercontent.com/48355318/54152546-c7f61d80-443d-11e9-8814-48ce8c23a7d6.jpg)

Any suggestions? I noticed it also on one of our other installations where distributor is active.

Kind regards,

Webagent05

**Comment by jeffpaul** [comment]
@Webagent05 can you please confirm the WordPress and Distributor versions you're using as well as any other plugins/themes?  Also, can you confirm if this is an internal (aka multisite) or external site that's trying to pull in content?  If it's an external site, can you confirm that the external connection is setup?

**Comment by Webagent05** [comment]
@jeffpaul 

I was pulling content, and suddenly page 1 is empty, page 2 shows posts. So pulled further from page 2.
When 1 page was left the page was empty.

I've changed the screen options 'amount posts'.
Made it 5 posts, again page 1 empty other pages showing posts.

I've repeated this to 1 post per page.
Results in 1 page empty, 1 post not pulled.

![distributor-issue-1](https://user-images.githubusercontent.com/48355318/54154149-85cedb00-4441-11e9-8a2f-9394ceb6a83b.jpg)

Active Plugins
1. Akismet Anti-SpamActivate - active
2. Application Passwords - active
3. Caldera Forms - active
4. Distributor - active
5. Easy Facebook Likebox - active
6. tagDiv Composer - active
7. tagDiv Social Counter - active
8. Two Factor Authentication - inactive
9. UpdraftPlus - Backup/Restore - active
10. WP-Optimize - active
11. Yoast SEO Premium - active
12. YouTube Pro - active

Inactive Plugins:
1. WP Rocket - inactive
2. Login No Captcha reCAPTCHA - inactive
3. MainWP Child - inactive
4. Regenerate Thumbnails - inactive
5. reSmush.it Image Optimizer - inactive
6. Featured Images in RSS for Mailchimp & Other Email - inactive
7. Image optimization service by Optimole - inactive
8. Gutenberg Autosave - inactive
9. Auto Upload Images - inactive

Theme:
Newspaper theme, no child-theme active

Connection:
External website: connection O.K.
![distributor-issue-2](https://user-images.githubusercontent.com/48355318/54154226-b0209880-4441-11e9-8173-3470a1ca173b.jpg)

If you need more information, please let me know.

Kind regards,

Webagent05

**Comment by Webagent05** [comment]
Forgotten plugin

RSSaggregator on master website

**Comment by Webagent05** [comment]
@jeffpaul any idea of the issue?

**Comment by jeffpaul** [comment]
@Webagent05 are you able to push content from `News from Bitcoinmag.eu` to whatever site these screenshots are from?

**Comment by Webagent05** [comment]
Yes, but at a certain moment in the pull ist there was 1 item left. But it wasn't shown.

I removed the connection and I'm trying it again.

ps. would be nice to have an option to keep the original post date ... & filter/sorting is not working in the pulled content overview.

**Comment by Webagent05** [comment]
@jeffpaul ... I'm thinking ...

Changed theme to standard didn't matter, but ... just try to put the post options 'amount of pulled posts' to 30 items and pull than the posts. Maybe it will re-produce...

**Comment by Webagent05** [comment]
@jeffpaul 

After removing the connection and adding the connection again. It seems solving this issue.

**Comment by jeffpaul** [comment]
@Webagent05 thanks for the update, may have just been network latency then?  Are you still seeing the warning on the Pull Content screen or has that disappeared as well as seeing the posts appear in the list table now?

**Comment by jeffpaul** [comment]
@Webagent05 Are you still seeing the warning on the Pull Content screen or has that disappeared as well as seeing the posts appear in the list table now?

**Comment by jeffpaul** [comment]
@Webagent05 are you still seeing this warning or can we close this issue as resolved?

**Comment by jeffpaul** [comment]
@Webagent05 I'm closing this issue as resolved, but please let me know if you're still having problems so we can try to help... thanks!
