### ISSUE TITLE
ACF Field date does not migrate when pulling to a subsite from a subsite.

### ISSUE THREAD

**Issue by tedgeving** [10up/distributor#350]
Request to add/improve support for pulling ACF fields attached to a CPT in a multisite environment.  

I did test run our staging environment, body and featured image fields migrated correctly.  The ACF image fields did not have the correct images attached.  However the unattached images were migrated to the media manager.  We are using ACF and the ACF Repeater field to build layouts on these pages.  Perhaps the Repeater Field type is the culprit?

![pulled-from](https://user-images.githubusercontent.com/24211/54318436-f72a9d00-45ab-11e9-8690-ff735e975679.jpg)

![result](https://user-images.githubusercontent.com/24211/54318441-fb56ba80-45ab-11e9-9ab9-15e82f77298d.jpg)

**Comment by jeffpaul** [comment]
@tedgeving thanks for the feedback, it's greatly appreciated!  In the [`Known Caveats/Issues` section](https://github.com/10up/distributor#known-caveatsissues) we call out some known issues with `Post Meta Associations` and `External Connection Post Type Support` as well as available hooks and how a CPT needs to be registered to ensure full distribution support.  Let me know if your uses are different than what we've noted and we can continue to triage to see what else might be needed for you... thanks!

**Comment by tedgeving** [comment]
@jeffpaul  Thanks for responding.  My bad for not reading the docs more carefully.   Is there any documentation on how to use the use the hooks mentioned above that I can take look at?

**Comment by jeffpaul** [comment]
@tedgeving none that I'm immediately aware of.  If you have specific examples you're trying to solve for, let us know and I'll check to see if anyone has related code that could be helpful.

**Comment by arsendovlatyan** [comment]
@tedgeving I can provide ACF integration code, but it's part of our fork (we have ingratiation with ACF, WooCommerce and other extensions) and was not tested with original Distributior plugin. However, I think if you will load this file from a child theme or make it as a separate plugin - it must work!
Hope this helps!

[acf.zip](https://github.com/10up/distributor/files/2987162/acf.zip)

**Comment by jeffpaul** [comment]
Possibly related to #180 and #103

**Comment by kg-lvargas** [comment]
@arsendovlatyan Will that acf,zip will help for files too? I really need to be able to import a AFC file attribute when I use distributor.

**Comment by arsendovlatyan** [comment]
@kg-lvargas Yes, we are successfully distributing ACF's  file-type custom fields.

**Comment by jeffpaul** [comment]
Closing in favor of #81.
