### ISSUE TITLE
Multisite No connection found

### ISSUE THREAD

**Issue by gerfoley** [10up/distributor#354]
Any one have issues getting the connection to work on one site of a multisite set up?

As in trying to add external connection to a single site on the multisite and the connection won't work.

I have added the Applications Password plugin to the other site and have tested it by adding to another install (that isn't multisite) and it works.

Just can't get it to work on the multisite.. Any ideas of how to troubleshoot?

**Comment by jeffpaul** [comment]
@gerfoley if you're still not seeing a green circle in the `Status` column on http://yourdomain.com/wp-admin/admin.php?page=distributor, then the External Connection setup is not yet complete.  On the `Edit External Connection` screen you'll want http://externaldomain.com/wp-json as the general format set in the `External Connection URL` field.

You'll also want to ensure that the `Password` set on that screen comes from the externaldomain.com site and using the `Application Passwords` created on the user profile page (e.g. http://externaldomain.com/wp-admin/profile.php) and not the users WordPress password from the `Account Management` section.

If you've completed all those steps and still not able to push content to your external site, then let me know and we'll continue to triage your setup.

**Comment by gerfoley** [comment]
I have tried all of that and still can’t get it to connect.

Have the same connection working on a single site install.

It’s just on multisite that I can’t get it to work

**Comment by jeffpaul** [comment]
@gerfoley are all the sites you're looking to distribute to/from within the same multisite instance?  If so, then you don't need to utilize External Connections.  Apologies for not asking this question first.

**Comment by gerfoley** [comment]
Hi @jeffpaul no the connection that I am unable to get working is between the multisite and an external single site. I am able to get the single site to pull content from the multisite, the connection works that way. 

But cannot get the connection to work to allow push between the multisite and the single site which seems odd.

**Comment by jeffpaul** [comment]
@gerfoley on your multisite setup, do you see a green circle in the `Status` column of the Distributor External Connections page (e.g., http://yourmultisite.com/wp-admin/admin.php?page=distributor)?

If not, then something may not be configured correctly so please confirm what you have set for `Authentication Method`, `External Connection URL`, and `Roles Allowed to Push` so I can try to help troubleshoot... thanks!

**Comment by gerfoley** [comment]
@jeffpaul no thats the issue that I was wondering if someone had any idea how I could troubleshoot :)

I can only get the red circle (No Connection) on the multisite.

Authentication Method: Username / Password
External Connection Url: siteurl/wpjson
Roles Allowed to push: Administrator

I'm able to connect the same site to a single install successfully.

Its just within the multisite that it isn't working.. Was just hoping someone would have seen a similar issue and be able to point me in the right direction to troubleshoot.

**Comment by jeffpaul** [comment]
@gerfoley:
1) Is the username in the `Authentication Method` an active user on your external single site and the password from the `Application Passwords` section of that users profile?
2) Is the `External Connection URL` in the format of "http://externaldomain.com/wp-json"?
3) Is the user you're logged into the multisite and trying to push to the external single site an Administrator (since that's the only role you have selected as allowed to push)?

**Comment by gerfoley** [comment]
@jeffpaul Hi Jeff, yes to all 3 of those questions :(

**Comment by jeffpaul** [comment]
@gerfoley seems like it might be best for us to coordinate for a screenshare so I can try and help troubleshoot with you in real time.  Mind sending me an email (jeff.paul@10up.com) so we can find time to meet and try and get this resolved for you?

**Comment by kg-lvargas** [comment]
@jeffpaul I have the same issue on a distributed multisite setup. I used the external connection with wordpres.com Application authentication method but I get a "Limited connection established. Authentication failed.
Push distribution unavailable.
Pull distribution limited to basic content, i.e. title and content body."  So of the other posts talk about having a  Application Passwords plugin set up... is this necesary when using wordpres.com Application authentication

**Comment by jeffpaul** [comment]
Closing in favor of #338.
