### ISSUE TITLE
Option to defalut pulled in content to draft

### ISSUE THREAD

**Issue by mikelking** [10up/distributor#358]
*Summary*
Currently when pulling an article from another brand in distributor on WordPress, the article is automatically published on the new brand that is pulling it in. We would like to have these default to unpublished i.e. draft to allow the editor the opportunity to update category, tags and images etc before publishing. This would match how we push articles using distributor, where the default is unpublished.

*Benefits*
Allow editor to implement brand-specific taxonomy adjustment, ensure article shows up in correct location on site at correct time etc while maintaining the original canonical association.

**Comment by jeffpaul** [comment]
@mikelking thanks for the feedback and welcome to Distributor-land, glad to have you here!  Your idea is similar to  #317, so dropping in that reference here.  In terms of your usage, do you ever distribute as published to some sites but draft to others or would you always distribute as draft?  I'm trying to determine how we could best support your request this while giving flexibility to broad use cases.

**Comment by mikelking** [comment]
@jeffpaul ,

My apologies on the delay. Yes we do on occasion distribute to published state but that would be the outlier.

**Comment by jeffpaul** [comment]
@mikelking I wanted to note that the Pull menu now defaults pulled content to draft as of v1.6.0.  If that solves your request here, then please confirm so we can close this issue... thanks!

**Comment by jeffpaul** [comment]
Closing this as Distributor now defaults pulled content to draft as of the 1.6.0 release.

**Comment by mikelking** [comment]
Hey sorry I just discovered that the email notices were all being sucked into JUNK... Yes defaulting to draft on push/pull of content is great. This is GTG.
