### ISSUE TITLE
Enable whitelisting/blacklisting taxonomies/terms

### ISSUE THREAD

**Issue by jeffpaul** [10up/distributor#379]
**Is your enhancement related to a problem? Please describe.**
A request came in to enable whitelisting/blacklisting taxonomies/terms in Distributor that don’t want new terms created.  An example would be if you want certain posts to be pulled in via Distributor but only allow certain terms to be set or created in a specific taxonomy.

**Describe the solution you'd like**
PR already submitted: #378

**Designs**
n/a

**Describe alternatives you've considered**
You can currently solve for this by returning false in the `dt_create_missing_terms` filter, but its helpful to expand upon that filter and include the taxonomy and term as arguments.

**Additional context**
Relates to #378.

**Comment by helen** [comment]
Fixed in #378 - added `$taxonomy`, `$term_array`, and `$term`.
