### ISSUE TITLE
ACF image field does not migrate.

### ISSUE THREAD

**Issue by FilNunes** [10up/distributor#381]
I am using the distribuitor to use and copy customs post from site A to Site B.
These custom posts have ACF custom fields , All fields (Featured, image, body text, input ACF fields)  are copying well the info, except for the ACF image Field. This field is empty on the Site B.

Do you have any idea how to fix this?

Kind Regards,
Filipe Nunes

**Comment by jeffpaul** [comment]
@FilNunes there are some related image issues reported that we will take a look at after we finish up our [1.5.0 release](https://github.com/10up/distributor/milestone/16), which is mainly focused on major performance improvements on the Push and Pull screens within Distributor as well as an enhanced connection setup process.  From there we'll be reviewing open issues and PRs to determine what to target in our next release, so for now I'm milestoning this for `Future Release` and will keep you posted as we get further into triaging and resolving this issue.  If you're able to do some [debugging](https://wordpress.org/support/article/debugging-in-wordpress/) and send along additional details, then that'll help when we get into triaging this.

Note, this may possibly be related to #380.

**Comment by FilNunes** [comment]
@jeffpaul 
I have found out that wrong image ID is referenced. The problem is related with media ID that is not updated within the data that was distributed and old image remains but it is nonexistent (or the wrong image will be displayed) on new site. 
Example: 	
meta_key:  eventocapa   (ACF field name)
meta_value: 540  Value from old Website A:, Instead of the new media ID on Site B

If i changed directy the  the Media ID on database on Site B, works well.

The problem is the distribuitor is not updating the final media ID.

Kind Regards,
Filipe Nunes

**Comment by mrazzari** [comment]
@FilNunes we're using this in prod to solve this issue https://github.com/ulkish/distribute-acf-images

**Comment by FilNunes** [comment]
@mrazzari 

Thanks for sharing, your code only works for multi network sites.  You can improve your code checking if is_multisite().

Kind Regards,
Filipe Nunes

**Comment by mrazzari** [comment]
@FilNunes you're right! It's not my code, I'll file an issue though! Thanks!

**Comment by jeffpaul** [comment]
Closing in favor of #81
