### ISSUE TITLE
Generate hook docs

### ISSUE THREAD

**Issue by jeffpaul** [10up/distributor#387]
With many people already extending and others looking to further extend Distributor, we should look to generate hook docs for folks to leverage (possibly in docs/hooks.md to start and we can iterate from there unless folks have a better starting point?).

**Comment by jeffpaul** [comment]
Received the following from someone via the distributorplugin.com webform:
> The only thing that stands out to me is that I don't see any documentation on how to hook into it to carry over featured images or acf fields. I've worked around it by using urls for the necessary images for now.

Seems like adding any sort of documentation on hooks/filters available would be helpful.

**Comment by helen** [comment]
I have a dream of generating hook docs using GitHub Actions... :)

**Comment by jeffpaul** [comment]
Closed via #448 and #482.
