### ISSUE TITLE
Update Pull Content screen

### ISSUE THREAD

**Issue by jeffpaul** [10up/distributor#392]
**Is your enhancement related to a problem? Please describe.**
Making batch manipulation easier to understand and establish patterns for scale for setups with lots of connected sites.  Having `Skipped` items treated like new allows to pull things late which were accidentally skipped for some reason.

**Describe the solution you'd like**
From the designs below, ignore the changing header as we'll keep the existing header as-is.
- [x] `Pull` and `Skip` batch controls
- [x] include "All" option in post type dropdown to view all available content to pull across all available post types
- [x] ability to "un-skip" an item // include view of all `Skipped` posts and ability to `Unskip` a post to have it return to a state of being able to `Pull` or `Skip` again as well as direct option to `Pull` from the `Skipped` view.  This should be a row action as well as bulk action.

**Designs**
General screen flow:
1. https://cldup.com/s6qnqaojZg.png
1. https://cldup.com/-rGHbjj8L1.png
1. https://cldup.com/tCPn2kZ3Wm.png

**Describe alternatives you've considered**

**Additional context**
Relates to #40.

Props GH:@oszkarnagy / WP:[@oszkarnagy](https://profiles.wordpress.org/oszkarnagy/) for the UX analysis and recommendation.

**Comment by mrhasbean** [comment]
Any update on this functionality? Very challenging at present with staff profiles missing on sites because they were accidentally skipped and no way of overriding that at present.

**Comment by jeffpaul** [comment]
@mrhasbean this work isn't planned for a couple releases in the future.  Have you tried going to the source site and pushing them to the site(s) that are missing that content?

**Comment by mrhasbean** [comment]
Hi Jeffrey,

Thanks for the reply. The source site is the main (parent) site of the multisite installation and I don’t get a “Push” option there, otherwise I would use that. Was wondering why I don’t see that option?

Cheers,
Steve

**Comment by jeffpaul** [comment]
@mrhasbean the push menu is available in the admin bar for any published content ([screenshot](https://camo.githubusercontent.com/0b29e5649392ddffaee975ff58dad393e95d080e/68747470733a2f2f6469737472696275746f72706c7567696e2e636f6d2f77702d636f6e74656e742f7468656d65732f6469737472696275746f722d7468656d652f6173736574732f696d672f707573682d73637265656e73686f742e6a7067)).

**Comment by emisrw** [comment]
@jeffpaul Somebody from stuff removed distributed posts and now these posts are in skipped tab. I tried push from parent site but not showing (tried as draft and normally). Is any another option ? e.g. remove manually from database ?

**Comment by jeffpaul** [comment]
Closed now that #728 has been merged.
