### ISSUE TITLE
Update pulled content management

### ISSUE THREAD

**Issue by jeffpaul** [10up/distributor#397]
**Is your enhancement related to a problem? Please describe.**
Include various states for better communicating the current status of distributed content.

**Describe the solution you'd like**
- [ ] in Posts table view, include better details in Distributor icon column, add Pushed/Pulled/Linked/Unlinked in hover details for each item (see: https://cldup.com/kVpFJIy8bM.png)
- [ ] links to linked content should open original in a new tab (see: https://cldup.com/kVpFJIy8bM.png)
- [ ] add `Pulled content` sidebar (see: https://cldup.com/c9gR5SBTPB.png)
- [ ] on clicking `Unlink from Original` show confirmation to ensure user understands the implications of the action (see: https://cldup.com/c9gR5SBTPB.png)
- [ ] add `Unlinked content` sidebar (see: https://cldup.com/JKwubnt5x1.png)
- [ ] on clicking `Restore link to Original` show confirmation to remove ambiguity around data overwrite implications, then go back to `Pulled content` state (see: https://cldup.com/JKwubnt5x1.png)

**Designs**
1. https://cldup.com/kVpFJIy8bM.png
1. https://cldup.com/c9gR5SBTPB.png
1. https://cldup.com/JKwubnt5x1.png

**Describe alternatives you've considered**
none

**Additional context**
Props GH:@oszkarnagy / WP:[@oszkarnagy](https://profiles.wordpress.org/oszkarnagy/) for the UX analysis and recommendation.

**Comment by ravinderk** [comment]
> in the Posts table view, include better details in the Distributor icon column, and add Pushed/Pulled/Linked/Unlinked in hover details for each item (see: https://cldup.com/kVpFJIy8bM.png)

@jeffpaul I was reviewing the pull request, but the icons displayed in the images could be more straightforward. The difference between the pulled and pushed posts needs to be cleaner. I can find differences when I visit the post-edit page.

I am expecting two icons for the following categories:
- Pushed (Need to decide)
- Pulled (We can use icons mentioned in the image)

Let me know what you think.
