### ISSUE TITLE
duplicated content when distributed

### ISSUE THREAD

**Issue by espechtcfe** [10up/distributor#398]
Our site that 10Up developed uses Distributor.  We recently noticed that one of the custom post types - Webcast - was showing items that should have been automatically unpublished after a certain date.  We then found that even when we manually unpublished the item, it was not being removed from our archive page.  We were attempting to unpublish them from the main site, not one of the sites to which the content was being distributed.  Looking further, we found that when we looked on the site it was distributed to, there were duplicates.  And when we edited each copy, they both said that they were linked from the main site.  We found that if we manually unpublished each one, we were finally able to remove the content item from the site.

It appears that the version of Distributor that we're using - 1.3.4 - is out-of-date.  Our wordpress version is 5.1.1.  We're now testing the upgraded version of Distributor in our staging environment.  Does it seem like the problems we've experienced are simply due to the version needing to upgraded?  If not, I wanted to bring this to the attention of the community to prevent others from experiencing this issue.

**Comment by jeffpaul** [comment]
@espechtcfe thanks for the feedback, it's greatly appreciated!  I've seen an issue about empty posts from Pushing (see #255), but not duplicates.  I'll be curious to hear how your testing in Staging goes with Distributor 1.4.1 to see if your issue is resolved.  If not then please confirm any other active plugins/theme, if Distributor is setup on a multisite / different WP instances / or both, and anything else that may be unique about your setup so we can best help triage... thanks!

**Comment by espechtcfe** [comment]
Thank you for the reply, jeffpaul.  We're having trouble reproducing the issue.  Any new items we've created on the main site seem to be getting to the distributed site once.  Is there anything I should look for in the database on the items that were duplicated that would help better understand what happened?

**Comment by espechtcfe** [comment]
Something interesting I am seeing is when I edit the item that exists in the main site (there's only one of them), the Distributor section at the top of the page doesn't display.  When I open a different item in the main site, I do see the Distributor section.

**Comment by espechtcfe** [comment]
Here are the plugins that are network activated for the sites:
10up Experience, Attachment Taxonomies, Classic Editor, Distributor, ElasticPress, Safe Redirect Manager, Unpublish, WP REST Filter, Yoast SEO
It is a multisite configuration.

**Comment by jeffpaul** [comment]
@espechtcfe some followup questions from your comments...
1) do the duplicated posts show that they're linked to the original/source post (you'll see the Distributor icon and hovertext of `Linked` on your All Posts page at yourdomain.com/wp-admin/edit.php)?
2) Whether you're using the Classic Editor or Gutenberg, you should see the `Distributor` menu in the admin bar.  However, if you're editing a draft post then the `Distributor` menu will not appear, it must be a published post.  Can you confirm if the item you're editing that does NOT have the `Distributor` menu appear in the admin bag is a published post?

**Comment by espechtcfe** [comment]
1 - both of the duplicated posts show that they're linked to the original
2 - that makes sense.  when the editors saw the post on the site, they put the item on the main site in draft status in an attempt to take it down.  they later went directly to the distributed site and put both items in draft as well.

**Comment by espechtcfe** [comment]
Do you know how I can tell if the two distributed items are linked to the same item on the main site?

**Comment by jeffpaul** [comment]
@espechtcfe on the All Posts page at yourdomain.com/wp-admin/edit.php, the Distributor column on the right will show the Distributor icon and link to the original/source post.  So check the links for those duplicates to see if they're referencing the same original/source post.

**Comment by espechtcfe** [comment]
Thanks.  The originals look identical, but they have different URL formats:
/webcasts/01-18-18-webcast/
/?post_type=webcast&p=359997

**Comment by jeffpaul** [comment]
@espechtcfe ok so does that mean that there do NOT appear to be duplicates then?  If so, it sounds like things are working correctly for you, correct?  If so, are we good to close this issue?

**Comment by espechtcfe** [comment]
I think there are duplicates.  When I search for the title in the main site, I only get one result.
You can close this if you want though since I don't know what the editors were doing - if they were only working on the main site or what.  I could create a new one if I see it happen again.

**Comment by jeffpaul** [comment]
Thanks @espechtcfe, please do let me know if you see this happen again (or have other feedback for us)!
