### ISSUE TITLE
Delay `send_notifications` until after all meta has saved (Yoast SEO problem).

### ISSUE THREAD

**Issue by timstl** [10up/distributor#399]
**Is your enhancement related to a problem? Please describe.**
When updating an existing post, the Yoast SEO meta information sent to a linked post is not up-to-date. It appears Yoast does not save its metadata until after _send_notifications_ has already run, so Distributor's _distributor_meta_ array is incorrect.

**Describe the solution you'd like**
If possible, have send_notifications run after all new meta has finished saving. I've tried simply adding a higher priority in the plugin code to the _save_post_ action, but wasn't able to get that working.

**Describe alternatives you've considered**
For now, I've created [a plugin](https://github.com/timstl/distributor-yoast-sync) that filters _dt_subscription_post_args_. This plugin goes through the _$_POST_ data and updates _$post_body['post_data']['distributor_meta']_ with the correct Yoast meta values. While this method works, it's specific to Yoast SEO and can easily break with changes to Yoast SEO.

**Additional context**
I have only produced this problem with external connections; I have not tried on network sites.

I marked this as an enhancement because it's related to another plugin. Other custom fields seem to pass correctly during an update, including the (non-media) ACF fields I have tested. I suspect there are other plugins where this is a problem, though.

The above plugin also fixes an issue with Yoast social images pointing to the incorrect media IDs and URLs, but that is partially a separate issue related to media IDs and custom fields that I believe is already known.

Thanks!

Tim

**Comment by jeffpaul** [comment]
@timstl welcome to Distributor, thanks for the feedback and the plugin reference to resolve this issue.  We're looking at some other SEO-related items in our 2.0.0 release so I've milestoned this alongside those issues.  If there's anything else you've built to extend Distributor, then we'd love to learn about that and the underlying problem that you solved in hopes that it might benefit the broader community of Distributor users.  Thanks again!

**Comment by jeffpaul** [comment]
@dinhtungdu let's also take a look at the plugin from @timstl in the description above alongside the other SEO research you're looking into for Distributor... thanks!

**Comment by dinhtungdu** [comment]
@timstl You're right, distributor hooks into `save_post` action while Yoast SEO uses `wp_insert_post` which is fired later than `save_post`, see [link](https://github.com/Yoast/wordpress-seo/blob/ec8ae1080970aa229e7f7ca97373649383db9488/admin/metabox/class-metabox.php#L50-L55).

@jeffpaul I think we can use `wp_insert_post` instead, it's the latest action fired when adding/updating a post so we can ensure that we distribute posts lately when all metas are saved.

**Comment by peterwilsoncc** [comment]
Now that Distributor requires WordPress 5.7 or later, it may be possible to use the [`wp_after_insert_post` function and hook](https://make.wordpress.org/core/2020/11/20/new-action-wp_after_insert_post-in-wordpress-5-6/) added in 5.7.0.

This action is intended to run after all the post data has been saved to the database, including meta data and terms.
