### ISSUE TITLE
PHP Notice: Undefined variable: local_post_types

### ISSUE THREAD

**Issue by grappler** [10up/distributor#400]
**Describe the bug**
`Notice: Undefined variable: local_post_types in /plugins/distributor/includes/utils.php on line 261`

**Steps to Reproduce**

1. Go to Pull Content page wp-admin/admin.php?page=pull
2. See PHP Notice

**Expected behavior**
No PHP Notice

**Comment by jeffpaul** [comment]
@grappler welcome to Distributor, thanks for the feedback and even more so for the PR, it's greatly appreciated!
