### ISSUE TITLE
Pull posts from a specific taxonomy

### ISSUE THREAD

**Issue by joestrat** [10up/distributor#424]
**Describe your question**

We have a network site which we are using to post jobs (a custom post type). We have a single site that receives all the jobs. We want to be able to distribute the jobs from this single site out to a couple of other sites on the same network depending on a single taxonomy.

The distribution side works but I cannot see a way to filter results by a taxonomy.

What I would like is to be able to specify if job has X taxonomy, push to this site 1, else if has Y taxonomy push to this site 2.

Is this currently possible? If so a nudge in the direction would be great.

Thanks

**Comment by adamsilverstein** [comment]
> We want to be able to distribute the jobs from this single site out to a couple of other sites on the same network depending on a single taxonomy.

@joestrat Hi, thanks for opening this issue.

Question: is your plan to distribute these job (posts) automatically with a cron job? If so, you should be able to write some code that iterates thru new posts since the last run and sends them to the appropriate site based on the taxonomy. eg if the category is orange push to site a, if the category is apple push to site b.

or are you wanting to push these items manually and suggesting that the list of sites in the push menu should reflect the taxonomy selection, eg if the category is orange only show site 1 in the menu?

**Comment by joestrat** [comment]
We would be setting up a cron to run every hour on the primary site that would then push the relevant jobs up to the sub sites. No jobs would actually be shown on the parent site.

Can set up a cron job easily enough and seperate jobs into their respective taxonomies. The pushing itself I might need a little more info on. 

The function 'push' in NetworkSiteConnection.php looks like what I need  -

```
public function push( $post_id, $args = array() ) {
		$post              = get_post( $post_id );
		$original_blog_id  = get_current_blog_id();
		$original_post_url = get_permalink( $post_id );
		$using_gutenberg   = \Distributor\Utils\is_using_gutenberg( $post );

		$new_post_args = array(
			'post_title'   => get_the_title( $post_id ),
			'post_name'    => $post->post_name,
			'post_content' => Utils\get_processed_content( $post->post_content ),
			'post_excerpt' => $post->post_excerpt,
			'post_type'    => $post->post_type,
			'post_author'  => get_current_user_id(),
			'post_status'  => 'publish',
		);

		$media = \Distributor\Utils\prepare_media( $post_id );
		$terms = \Distributor\Utils\prepare_taxonomy_terms( $post_id );
		$meta  = \Distributor\Utils\prepare_meta( $post_id );

		switch_to_blog( $this->site->blog_id );

		// Distribute raw HTML when going from Gutenberg enabled to Gutenberg enabled.
		$remote_using_gutenberg = \Distributor\Utils\is_using_gutenberg( $post );
		if ( $using_gutenberg && $remote_using_gutenberg ) {
			$new_post_args['post_content'] = $post->post_content;
		}

		// Handle existing posts.
		if ( ! empty( $args['remote_post_id'] ) && get_post( $args['remote_post_id'] ) ) {

			// Setting the ID makes `wp_insert_post` perform an update.
			$new_post_args['ID'] = $args['remote_post_id'];
		}

		if ( empty( $args['post_status'] ) ) {
			if ( isset( $new_post_args['ID'] ) ) {

				// Avoid updating the status of previously distributed posts.
				$existing_status = get_post_status( (int) $new_post_args['ID'] );
				if ( $existing_status ) {
					$new_post_args['post_status'] = $existing_status;
				}
			}
		} else {
			$new_post_args['post_status'] = $args['post_status'];
		}

		add_filter( 'wp_insert_post_data', array( '\Distributor\InternalConnections\NetworkSiteConnection', 'maybe_set_modified_date' ), 10, 2 );

		$new_post_id = wp_insert_post( apply_filters( 'dt_push_post_args', $new_post_args, $post, $args, $this ) );

		remove_filter( 'wp_insert_post_data', array( '\Distributor\InternalConnections\NetworkSiteConnection', 'maybe_set_modified_date' ), 10, 2 );

		if ( ! is_wp_error( $new_post_id ) ) {
			update_post_meta( $new_post_id, 'dt_original_post_id', (int) $post_id );
			update_post_meta( $new_post_id, 'dt_original_blog_id', (int) $original_blog_id );
			update_post_meta( $new_post_id, 'dt_syndicate_time', time() );
			update_post_meta( $new_post_id, 'dt_original_post_url', esc_url_raw( $original_post_url ) );

			if ( ! empty( $post->post_parent ) ) {
				update_post_meta( $new_post, 'dt_original_post_parent', (int) $post->post_parent );
			}

			\Distributor\Utils\set_meta( $new_post_id, $meta );
			\Distributor\Utils\set_taxonomy_terms( $new_post_id, $terms );

			/**
			 * Allow bypassing of all media processing.
			 *
			 * @param bool                  true           If Distributor should set the post media.
			 * @param int                   $new_post_id   The newly created post ID.
			 * @param array                 $media         List of media items attached to the post, formatted by {@see \Distributor\Utils\prepare_media()}.
			 * @param int                   $post_id       The original post ID.
			 * @param array                 $args          The arguments passed into wp_insert_post.
			 * @param NetworkSiteConnection $this          The distributor connection being pushed to.
			 */
			if ( apply_filters( 'dt_push_post_media', true, $new_post_id, $media, $post_id, $args, $this ) ) {
				\Distributor\Utils\set_media( $new_post_id, $media );
			};
		}

		/**
		 * Action triggered when a post is pushed via distributor.
		 *
		 * @param int                $new_post_id   The newly created post ID.
		 * @param int                $post_id       The original post ID.
		 * @param array              $args          The arguments passed into wp_insert_post.
		 * @param ExternalConnection $this          The distributor connection being pushed to.
		 */
		do_action( 'dt_push_post', $new_post_id, $post_id, $args, $this );

		restore_current_blog();

		return $new_post_id;
	}
```

Specifically switch_to_blog( $this->site->blog_id );

Would wrapping that in an if statement e.g.


```
if ( has_term( 'legal', 'job_listing_website', $post ) ) {

switch_to_blog( '2' );

} else if ( has_term( 'finance', 'job_listing_website', $post ) ) {

switch_to_blog( ''3 );

}
```


Or am I way off?

**Comment by adamsilverstein** [comment]
That is close! push will handle the switch to blog for you...

You probably want to group your query by term, or probably make one WP_Query for each term in a loop, then....

for each term set up a connection to the correct remote site

```$connection = new \Distributor\InternalConnections\NetworkSiteConnection( get_site( $remote_blog_id ) );```

then... for each new or updated post:
```$connection->push( $original_post_id, $args );``` (where $args would override arguments, it this is an update, specify the remote post id  `remote_post_id` available in meta).

**Comment by Uprootednut** [comment]
Hi Adam,

Appreciate you help. Sorry for not getting back to you sooner but got side tracked by other projects.

I've got something that appears to be working. 


```
register_activation_hook(__FILE__, 'ips_pushjobs');

function ips_pushjobs() {
    if (! wp_next_scheduled ( 'ips_hourly_event' )) {
	wp_schedule_event(time(), 'hourly', 'ips_hourly_event');
    }
}

add_action('ips_hourly_event', 'push_jobs_between_ips');

function push_jobs_between_ips() {
    
	// do something every hour
    push_jobs_between_sites();
    
}

function push_jobs_between_sites(){
    
     $new_jobs = new WP_Query( array (
        'post_type' => 'job_listing',
        'posts_per_page' => -1,
        'meta_query' => array(
            array(
                'key' => '_distributed',
                'value' => 'yes',  // or whatever it is you're using here
                'compare' => '!=',
            )
        ),
        'tax_query' => array(
            array(
                'taxonomy'  => 'job_listing_website',
                'field'     => 'slug',
                'terms'     => 'site-seven',
                'operator'  => 'NOT IN'
            )

        ),
        )
    );
    
   while ( $new_jobs->have_posts() ) : $new_jobs->the_post();
        
        if ( has_term( 'site-one', 'job_listing_website' ) ) {
            $remote_blog_id = 2;
        } else if ( has_term( 'site-two', 'job_listing_website' ) ) {
            $remote_blog_id = 3;
        } else if ( has_term( 'site-three', 'job_listing_website' ) ) {
            $remote_blog_id = 4;
        } else if ( has_term( 'site-four', 'job_listing_website' ) ) {
            $remote_blog_id = 5;
        }  else if ( has_term( 'site-five', 'job_listing_website' ) ) {
            $remote_blog_id = 6;
        } else {}
    
        $original_post_id = get_the_ID();

        $connection = new \Distributor\InternalConnections\NetworkSiteConnection( get_site( $remote_blog_id ) ); 
        
        $connection->push( $original_post_id, $args );
    
        update_post_meta( $original_post_id, '_distributed', 'yes');

    endwhile;
  
}

```

I was having issues with post being duplicated do I added a meta _distributed and set it to 'yes' once moved so it gets filtered out of the query.

Is this approach sustainable? Or do you for see issues in the future with this method?

Thanks

**Comment by Uprootednut** [comment]
This at least appears to be working for me. However I'm using a second plugin to filter these posts. The plugin caches all the posts to be able to search the data quicker, however these imported posts aren't being added into the cache automatically. I can add posts on an ID basis to the cache manually.

Is there an action I can hook into for when a job is successfully pushed so I can run a function to add that specific ID to the cache.  This  would need a trigger on the receiving end. Currently everything is happening on the side that is pushing.  Hope that makes sense.
 
(I just relaised I have logged into another account. I am the original creator of this thread.)

**Comment by adamsilverstein** [comment]
> Is there an action I can hook into for when a job is successfully pushed so I can run a function to add that specific ID to the cache. 

@Uprootednut -

Try `dt_push_post` https://github.com/10up/distributor/blob/09e924ff91d834d2f512eee676b036c4d6b332d6/includes/classes/InternalConnections/NetworkSiteConnection.php#L147-L155

**Comment by jeffpaul** [comment]
@Uprootednut does Adam's previous response resolve your questions here?

**Comment by jeffpaul** [comment]
@Uprootednut does Adam's previous response resolve your questions here?

**Comment by jeffpaul** [comment]
@Uprootednut I'm closing this issue for lack of response, but if you're able to respond with an update then we can re-open and continue to help answer your question. Thanks!
