### ISSUE TITLE
Update language / wording to be more consistent

### ISSUE THREAD

**Issue by jakemgold** [10up/distributor#43]
We use phrases like "Distribute" and "Syndicate" interchangeably through the UI; let's take a pass at making this consistent, leaning toward things like "Distribute" instead of "Syndicate" in the menu interface.

**Comment by jeffpaul** [comment]
It looks like we've cleaned up a good bit of these references.  All I'm finding at this point (besides actual code and comments) are:
- Description in [README.md](https://github.com/10up/distributor/blob/5bdff720aa72bb4dd6ac7a02d52143b0fa2259b9/README.md)
- Description in [lang/distributor.pot](https://github.com/10up/distributor/blob/d9fe123c06f16937f100c3d9cf14f384c2db5450/lang/distributor.pot#L872)
- Description in [package.json](https://github.com/10up/distributor/blob/329349c77d37812c4dec5aa3a52c9dc3c22e45a0/package.json#L3)
- Description in [distributor.php](https://github.com/10up/distributor/blob/d9fe123c06f16937f100c3d9cf14f384c2db5450/distributor.php#L4)
- Description on [microsite](https://distributorplugin.com/)

So this boils down to "do we want to tweak the description" of Distributor to fully remove "syndicate"?
