### ISSUE TITLE
Test ordering with WP Acceptance

### ISSUE THREAD

**Issue by jeffpaul** [10up/distributor#436]
**Is your enhancement related to a problem? Please describe.**
In #434 we set the ordering in remote_get(), but left the WP Acceptance tests for after the 1.5 release.

**Describe the solution you'd like**
- [ ] Add WP Acceptance tests to properly test the ordering on this page.

**Designs**
n/a

**Describe alternatives you've considered**
none.

**Additional context**
none.

**Comment by adrianduffell** [comment]
I can work on a PR for this.

**Comment by jeffpaul** [comment]
@adrianduffell are you still planning on working on a PR for this?  If so, is there anything you need to get that submitted?

**Comment by adrianduffell** [comment]
Hey @jeffpaul sorry I am no longer with 10up so it would be best to re-assign this.

**Comment by dhanendran** [comment]
@jeffpaul I can work on this

**Comment by jeffpaul** [comment]
@dhanendran all yours, thanks!

**Comment by jeffpaul** [comment]
Closing as `wontfix` as we've migrated from WP Acceptance to Cypress for our e2e tests.
