### ISSUE TITLE
Distributed post shows as distributable (for external connections)

### ISSUE THREAD

**Issue by adamsilverstein** [10up/distributor#437]
**Describe the bug**
After distributing a post, the post is greyed out in the distributor admin-bar menu and a 'view' link links to the distributed post. This works correctly for network install/connections, however for external connections the remote site is first greyed out after distributing, then on a refresh shows as if the post can be distributed (despite having already been distributed to the remote site):

In this screenshot 'New Test' is an external connection site I have already distributed the post to, note that it shows as if I can distribute to it still. One of the multisite asites shows the correct behavior with a 'view' link. I included the post meta data in the screenshot where you can see the post has been distributed to the external connection.

![image](https://user-images.githubusercontent.com/2676022/61909402-4801b900-aeef-11e9-8af3-2215f89f6650.png)

Possibly broke in the lazy load menu refactor.

**Steps to Reproduce**

1. Publish a post and distribute it to an *external connection*.
2. Refresh the editor
3. Open the Distributor admin-bar menu, note that the external connection is available for distributing.

**Expected behavior**
After distributing a post to an external site, the external site should be greyed out and ideally a 'View' link should point to the distributed post.

**Screenshots**
I noticed that as soon as you interact with one of the other connections, the connection becomes disabled:

![image](https://cl.ly/80f9445e147d/Screen%252520Recording%2525202019-07-25%252520at%25252003.22%252520PM.gif)

**Environment information**
 - Device: Macbook
 - OS: MacOs latest
 - Browser and version: Chrome Beta 
 - Distributor version: develop
 - Theme and version: ?
 - Other installed plugin(s) and version(s): ?

**Comment by jeffpaul** [comment]
@adamsilverstein as @avag-novembit noted in #443, these two issues may be related.  If so, does #444 appear to similarly resolve this issue?

**Comment by adamsilverstein** [comment]
> @adamsilverstein as @avag-novembit noted in #443, these two issues may be related. If so, does #444 appear to similarly resolve this issue?

Quite possibly - I'll give this a test.

**Comment by adamsilverstein** [comment]
Verified that #444 does resolve the issue reported here. I do wonder after testing this why we don't show the "View" link for external connections.
