### ISSUE TITLE
Run WP Acceptance tests in parallel

### ISSUE THREAD

**Issue by jeffpaul** [10up/distributor#438]
**Is your enhancement related to a problem? Please describe.**
Currently the runtime for the complete set of WP Acceptance tests is... lengthy.

**Describe the solution you'd like**
Look into running the WP Acceptance tests in parallel to reduce the overall length of time needed to run the tests.

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
n/a

**Comment by adamsilverstein** [comment]
Tests running in parallel:
![image](https://cl.ly/d6d30b73b841/Screen%252520Recording%2525202019-08-01%252520at%25252010.00%252520AM.gif)

**Comment by adamsilverstein** [comment]
Tests passed in about 15 min, a 20 min improvement over before.

![image](https://user-images.githubusercontent.com/2676022/62314920-6ae11f80-b451-11e9-8b6b-f411e5c1bfd0.png)

**Comment by jeffpaul** [comment]
NICE!!!

**Comment by adamsilverstein** [comment]
Fixed by https://github.com/10up/distributor/pull/439
