### ISSUE TITLE
Add WP Acceptance tests for PHP 5.6 and WordPress 4.7

### ISSUE THREAD

**Issue by jeffpaul** [10up/distributor#440]
**Is your enhancement related to a problem? Please describe.**
Our [requirements state](https://github.com/10up/distributor#requirements) that you need at least PHP 5.6 and WordPress 4.7 to run Distributor.  So let's make sure we've got a WPA test that covers those.

**Describe the solution you'd like**
- [ ] add WPA test to cover PHP 5.6 and WP 4.7

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by adrianduffell** [comment]
I can work on a PR for this.

**Comment by jeffpaul** [comment]
Note that @ryanwelcher has a draft PR started on this here: #537
