### ISSUE TITLE
Already distributed connection is selectable for external connection

### ISSUE THREAD

**Issue by avag-novembit** [10up/distributor#443]
**Describe the bug**

After distributing a post to specific connection the same connection is active again and can be selected to distribute to it again. This, I think, comes from:

    if ( ! is_wp_error( $connection ) ) {
			$dom_connections[ 'external' . $connection->id ] = [
				'type'       => 'external',
				'id'         => $connection->id,
				'url'        => $connection->base_url,
				'name'       => $connection->name,
				'syndicated' => ( ! empty( $connection_map['external'][ (int) 
    $external_connection->ID ] ) ) ? true : false,
			];
		} 

in the `get_connections()` function in 'includes/push-ui.php'. And the check it with 

    _.isEmpty( connections[ key ]['syndicated'] )

will return true regardless the `connections[ key ]['syndicated']` is `true` or `false` as it takes [`object` type](https://underscorejs.org/#isEmpty) parameter.

**Steps to Reproduce**

1. Open the 'edit post' page for a post which isn't distributed yet;
2. Distribute it;
3. Refresh the page;
4. After the loading connections, the connection where the post is just distributed can be selected again.

**Expected behavior**

The connection where the post is just distributed should be inactive so won't be possible to distribute post on that connection again.

**Screenshots**

[here is the screenshot](https://prnt.sc/orjoo0) where we have `"syndicated":true` for the second connection but it can be selected and distributed to that connection again.

**Environment information**
 - Distributor version: 1.5.0 (latest version)

**Additional context**

n/a

**Comment by avag-novembit** [comment]
Will go ahead and send a PR with fix.

**Comment by jeffpaul** [comment]
@avag-novembit thanks for the detailed report and to you and @madmax3365 for the related PR!  I've milestoned this for review in our upcoming release and will get back to you then with any questions from code review.

**Comment by avag-novembit** [comment]
Related #437
