### ISSUE TITLE
After distributing a post "No connections selected" label in distributor menu

### ISSUE THREAD

**Issue by avag-novembit** [10up/distributor#451]
**Describe the bug**

After distributing a post in the distributor menu shows "No connections selected" label though post has been successfully distributed. The same after page reload. Should it behave this way or it's a bug?

**Steps to Reproduce**

1. Distribute a post
2. After distributing the post it shows "No connections selected" label in distributor menu
3. The same "No connections selected" message after page reload

**Expected behavior**

Shouldn't it show already distributed connections in distributor menu instead of "No connections selected"?

**Screenshots**

![distributor_bug](https://user-images.githubusercontent.com/15778302/63924291-11244300-ca59-11e9-8497-9f75f51f7c12.png)

**Environment information**
 - Device: PC
 - OS: Windows 10
 - Browser and version: Chrome (latest)
 - Distributor version: 1.5.0 (latest)

**Additional context**

In case I'm missing something could you clarify how should it work?

Thank you
Avag

**Comment by jeffpaul** [comment]
@avag-novembit the Push menu also shows "Post successfully distributed." which is the result of your push action.  Based on your screenshot, it appears that you could still distribute to "healthshop" but you'd need to click on that in order to make the "Distribute" button active and thus the current message of "No connections selected".  I think everything appears correct here, but please clarify your question if I'm not fully understanding you... thanks!

**Comment by avag-novembit** [comment]
Hi @jeffpaul, thanks for the response. 

That part is clear, my question is after successfully pushing shouldn't that connection remain selected?
And the same question after page refresh, when we successfully distributed the post, should previously distributed connections remain selected?

Thanks

**Comment by jeffpaul** [comment]
@avag-novembit after successfully pushing that connection should appear greyed out with a "View" link on the right that would take you to that distributed post / site, but previously distributed connections do not remain selected as you already distributed to that site and cannot do so again.  That view should be the same after refreshing the origin post as well.

**Comment by avag-novembit** [comment]
@jeffpaul thanks for the clarification. Just an another question, that 'view' link should exist for 'external connection' as well? Because it seems doesn't show up.

**Comment by jeffpaul** [comment]
@avag-novembit that "View" link does not appear to display when content has been pushed to an external connection (i.e. to a different WordPress instance), only to internal connections (i.e. within a single WordPress multisite network).

**Comment by avag-novembit** [comment]
@jeffpaul thanks again for the clarification. I think we can close this.
