### ISSUE TITLE
Featured Imaged not pulled

### ISSUE THREAD

**Issue by rsd** [10up/distributor#452]
Everything working fine with the content.
Only the Featured Image is not pulled.  Any internal image is pulled together, just fine.
So, to correct, I must unlink the post and add the image (available thru Multisite Global Media).

**Comment by rsd** [comment]
observing a little better, it tries to pull.
a blank space is shown where the image should be, and if I open the post, there is a spinner in the featured image option on the side bar indicating it is busy.  Latter on, it seems to give up.
Note that even a gallery with many images is pulled correctly.

**Comment by jeffpaul** [comment]
@rsd does #380 appear to match your issue?  If so, then that is currently milestoned for our v2.1 release.  If 380 is different, please note here what's different so we can ensure we cover both cases in a PR to better handle featured images... thanks!

**Comment by rsd** [comment]
It seems to be so.
In 2.1 we will find out.
thanks

**Comment by iaingooey** [comment]
Hi There, Is there any chance of 2.1 coming out? just regarding the Featured images not pulling through to duplicate sites?

Cheers

**Comment by jeffpaul** [comment]
@iaingooey we're currently working on v2, so there's no timeline yet on 2.1 nor any specific handling on featured images.
