### ISSUE TITLE
Cannot pull deleted posts

### ISSUE THREAD

**Issue by rsd** [10up/distributor#453]
If you trash and delete a post, it will show as skip and not be able to repull it.

**Comment by jeffpaul** [comment]
@rsd welcome to Distributor and thanks for the feedback!

I'm able to replicate this and cannot seem to think of a use case where this should be the intended behavior.  I do see that you can go an Push that post back to the site that it was trashed/deleted on, so there's currently a workaround.

I'm going to milestone this for our `3.0.0` release though we may be able to pull this into an earlier release, I'll update you if that's the case.  If you're able to work on a PR to fix this, then I'd gladly look to get this into a nearer term release... thanks!
