### ISSUE TITLE
Internal mulitsite with subdomains: Only Pull content avaiable - No Push

### ISSUE THREAD

**Issue by Siedlerchr** [10up/distributor#454]
Hi,
first of all thanks for the cool plugin!

I am trying around with the Distributor plugin and from what I read it should be possible to push content in my internal multisite without setting up an external connection. However, I am only able to Pull content.
I'm using Wordpress  5.2.3, with a mulitsite setup which uses subdomains and Distributor Plugin 1.5.0. 
Am I misunderstanding something here?

**Comment by jeffpaul** [comment]
@Siedlerchr welcome to Distributor!  You should see a `Distributor` menu item in the admin bar after publishing your content that allows you to push to your internal multisite connections ([see screenshot here](https://camo.githubusercontent.com/0b29e5649392ddffaee975ff58dad393e95d080e/68747470733a2f2f6469737472696275746f72706c7567696e2e636f6d2f77702d636f6e74656e742f7468656d65732f6469737472696275746f722d7468656d652f6173736574732f696d672f707573682d73637265656e73686f742e6a7067)).  If you're not seeing that, then please provide details on any additional plugins and theme that are active so I can continue to help troubleshoot... thanks!

**Comment by Siedlerchr** [comment]
Thanks for the screenshot. I totally overlooked that in the top bar 🤦‍♂. (Hidden in plain sight) I   was always looking at the admin sidebar menu as well, because there is only  "Pull content" and External connections.

**Comment by jeffpaul** [comment]
@Siedlerchr glad to hear all is working for you!  If you run into any other issues or have ideas on how Distributor could be improved to better meet your needs, please let us know... thanks!
