### ISSUE TITLE
Showing "Limited connection established. Authentication failed" for authenticated connections

### ISSUE THREAD

**Issue by avag-novembit** [10up/distributor#457]
**Describe the bug**

Showing "Limited connection established. Authentication failed" message for authenticated connections on the "Edit External Connection" page.

**Steps to Reproduce**

1. Go to 'wp-admin > Distribution > External Connections'
2. Click on 'Verify' of the previously created external connection.
3. After opening "Edit External Connection" page scroll down to the "External Connection URL", where after "Checking endpoint" shows message "Limited connection established. Authentication failed" though the authentication was successful.

**Expected behavior**

In the mentioned section should show up "Connection established" message in case authentication was successful.

**Screenshots**

![connection-error](https://user-images.githubusercontent.com/15778302/65245287-5fc77900-dafd-11e9-8d45-62c64a1f945f.png)

Here we can see that authentication was successful by judging by "dt_verify_external_connection" AJAX response, though we see "Limited connection established. Authentication failed" message.

**Environment information**
 - OS: Windows 10 Pro
 - Browser and version: Chrome, 76.0.3809.132 (latest)
 - Distributor version: 1.5.0 (latest)

**Additional context**

This behavior comes from `distributor/assets/js/admin-external-connection.js` line 86, where we have:

    if ( response.data.errors.no_distributor || ! response.data.can_post.length ) {

though `response.data.can_post` is an object, and we should use instead:

    if ( response.data.errors.no_distributor || ! Object.keys( response.data.can_post ).length ) {

I'm going to create a PR which fixes the issue.

**Comment by jeffpaul** [comment]
@avag-novembit thanks for the feedback and related PR, we'll get this through review and get back to you with any questions.  Note that I've milestoned this for our next release, v2.0.  I'm curious about the `Connection Groups` part of your screenshot, that seems to be something custom you've built downstream, mind sharing more about what that functionality is?

**Comment by avag-novembit** [comment]
Yes, `Connection Groups` functionality is added on top of the original distributor, which, as the name suggests, allows to create connection groups and distribute to the grouped connections by a single action. The issue doesn't come from the original distributor plug-in, there were modifications in the our fork which I missed, sorry about that. I think we can close the issue.
