### ISSUE TITLE
Bad links pointing to filter/hooks in README.md

### ISSUE THREAD

**Issue by dmchale** [10up/distributor#461]
PR will follow this post, but per the contributing guidelines wanted to create an Issue first and make sure there was something to reference. 

Three links send the reader to "here" without referencing what the name of the filter or hook is, which is confusing since the links have become stale and do not point to the correct line numbers in their files anymore.

I propose fixing the current links to the current line numbers, and adding the names of filters/hooks when linking to them. That way when code changes again in the future, the reader still has enough info to help themselves and find the appropriate line of code.

**Comment by jeffpaul** [comment]
Resolved via #462
