### ISSUE TITLE
Row action for pulling single post

### ISSUE THREAD

**Issue by lakrisgubben** [10up/distributor#465]
**Is your enhancement related to a problem? Please describe.**

It would be nice to have a way to pull a single post without using bulk actions on the pull posts list table.

**Describe the solution you'd like**

This could be fixed by adding another link "Pull" to the [current row actions "View" and "Skip",](https://github.com/10up/distributor/blob/b1dd60f9fdb6e22efd84a85807a6b7aec91e615e/includes/classes/PullListTable.php#L324) see image:
<img width="401" alt="Screenshot 2019-10-03 at 14 04 50" src="https://user-images.githubusercontent.com/1754954/66125263-cc0aa800-e5e6-11e9-9f9d-32a97e98e497.png">

It seems in the code that this is already half done, since the [function `process_actions` contains a switch statement for the 'syndicate' as well as the 'bulk-syndicate' action.](https://github.com/10up/distributor/blob/b1dd60f9fdb6e22efd84a85807a6b7aec91e615e/includes/pull-ui.php#L187) I tested this by just adding the following code to [line 325 in the PullListTable class](https://github.com/10up/distributor/blob/develop/includes/classes/PullListTable.php#L325), and that seems to work though I haven't tested it thoroughly yet. Happy to make a PR if y'all think it's a good idea.

`'pull' => sprintf( '<a href="%s">%s</a>', esc_url( wp_nonce_url( admin_url( 'admin.php?page=pull&action=syndicate&_wp_http_referer=' . rawurlencode( $_SERVER['REQUEST_URI'] ) . '&post=' . $item->ID . '&connection_type=' . $connection_type . '&connection_id=' . $connection_id . '&pull_post_type=' . $item->post_type ), 'bulk-distributor_page_pull' ) ), esc_html__( 'Pull', 'distributor' ) ),`

**Comment by jeffpaul** [comment]
@lakrisgubben interesting idea, thanks for the feedback!  I'm marking this as `help wanted` and for a future release, so if someone's able to work up a PR on this I'd gladly pull it into review for any upcoming planned releases.

**Comment by lakrisgubben** [comment]
thanks @jeffpaul. I've added a PR for this. #508
