### ISSUE TITLE
Can Still Assign Term to Linked Post

### ISSUE THREAD

**Issue by turtlepod** [10up/distributor#468]
**Describe the bug**

Still able to add term in linked post (using Gutenberg)

**Steps to Reproduce**

1. Distribute a post to another site in network, e.g from Site A (original) to Site B 
2. Edit the post in Site B.
3. Should not be able to edit the post/add term in edit screen (need to unlink first)
4. However, we can do that by clicking the label of the term.

**Expected behavior**

Should not be able to do this.

**Screenshots**

**Environment information**
 - Device: ThinkPad13
 - OS: Win10pro
 - Browser and version: Chrome
 - Distributor version: 1.5.0
 - Theme and version: Custom
 - Other installed plugin(s) and version(s):

**Additional context**

**Comment by jeffpaul** [comment]
@turtlepod can you confirm the version of WordPress that this is appearing in?

**Comment by turtlepod** [comment]
WP 5.2.2, no gutenberg

**Comment by peterwilsoncc** [comment]
I noticed this applies to tags too in the most recent version of WordPress, the tags can be added in the distributed copy of the post but not removed.

If the origin post is updated, the custom terms are subsequently removed. 

![terms](https://github.com/10up/distributor/assets/519727/6a8faec7-7882-477f-9556-3d102c780e7b)

**Comment by kmgalanakis-sage** [comment]
@jeffpaul I noticed that @peterwilsoncc tried to deal with this issue in https://github.com/10up/distributor/pull/1069. Even though his approach has side-effects. I'm pretty sure this cannot be done with just CSS. Are we interested in investing more time on @peterwilsoncc 's fix to implement a JS solution or are we good with that?
