### ISSUE TITLE
Is there a select all option?

### ISSUE THREAD

**Issue by biggiebangle** [10up/distributor#469]
**Is your enhancement related to a problem? Please describe.**
We have more than 10 sites to push to at once, and after clicking on all of the sites, the distribute button is unreachable. 

**Describe the solution you'd like**
Could you add a select all option and move the 'distribute' button above the selected list?

**Comment by jeffpaul** [comment]
@biggiebangle currently there is no select all option, though we're tracking that (and some other potential updates for the Push distribution modal) via #393.  Please subscribe to that issue to get updates on when it'll be available in Distributor, thanks!

**Comment by jeffpaul** [comment]
Closing in favor of #393.
