### ISSUE TITLE
Add a 'syndicatable' capability filter to the push UI

### ISSUE THREAD

**Issue by pragmatic-tf** [10up/distributor#472]
**Is your enhancement related to a problem? Please describe.**
The Distributor plugin provides a way to push/syndicate content out to any number of sites from either the edit post screen or when logged in and viewing a post on the front-end.

However, there are some use cases where it might not be desirable for the user who wants to push to another site (or sites) to also have the capability to edit the original post.

**Describe the solution you'd like**
Access to the push UI is currently based on the `edit_posts` capability but as there isn't a filter on this capability check I'd suggest simply adding one to the check found in the `syndicatable()` function. 

This will allow plugins to override the capability required to either a different core capability or to add their own custom capability.

**Designs**
N/A

**Describe alternatives you've considered**
There are capability filters which would allow users without post edit permissions to **pull** content, but the pull and push functionality may have different applications or use cases as their UI and user flow is slightly different. Adding a new filter to the push capability check gives more options for extending this plugin and is relatively low impact.

**Comment by jeffpaul** [comment]
@pragmatic-tf welcome to Distributor and thanks for the feedback!  I'll review this with the team and get back to you with any questions, noting that we're aiming for a v2.0 release later this year so if you have time to submit a related PR for more detailed review then that'd be warmly welcomed as well.  Thanks!

**Comment by pragmatic-tf** [comment]
Thanks for the welcome @jeffpaul! 

I've added the above related PR for further review. I wasn't too sure if the included comment docblock counted as documentation for the PR tasks section so I've left that blank for now. More than happy to update any documentation as required, or check it off if that's already covered.

**Comment by jeffpaul** [comment]
Closed via #473.
