### ISSUE TITLE
The "Distributor" menu item isn't showing in "front end" for pages

### ISSUE THREAD

**Issue by avag-novembit** [10up/distributor#483]
**Describe your question**

The "Distributor" menu item isn't showing in "front end" for pages for logged in as administrator users:
![dist-page-front](https://user-images.githubusercontent.com/15778302/68477270-74df9f00-0246-11ea-91f8-a2e1634fa3a6.png)
![dist-page-admin](https://user-images.githubusercontent.com/15778302/68477278-7a3ce980-0246-11ea-9835-2638e74697c2.png)
However, we can see it in post single page:
![dist-post-front](https://user-images.githubusercontent.com/15778302/68477330-a0fb2000-0246-11ea-9621-589ceee3e2d6.png)
Should it work in that way?
Thanks.

**Comment by jeffpaul** [comment]
@avag-novembit the Distributor push menu should show for any published content.  Can you confirm that the "Sample Page" item in the first screenshot was published at the time of the screenshot being taken?

**Comment by avag-novembit** [comment]
Yes, it was published.

**Comment by jeffpaul** [comment]
@avag-novembit can you confirm your WordPress and Distributor version so I can try to replicate this?  Also, are you seeing any console errors that may help me troubleshoot this?

Oh, and to answer your question earlier... no it should not work that way.  Posts and Pages should be able to be pushed from the site front end view.

**Comment by avag-novembit** [comment]
@jeffpaul thanks for the comment.

Both are the latest version:
 - WordPress version: 5.2.4
 - Distributor version: 1.5.0

And there aren't any console errors.
