### ISSUE TITLE
Not bringing in images

### ISSUE THREAD

**Issue by CoolWebDesignNZ** [10up/distributor#486]
**Describe the bug**
When I pulled in a listing from one of my multisites it brought everything in successfully except the images. It brought in the feature image no problem but not the gallery. All the images were shaded out. I could click on them and see them when editing the gallery but they would not show on the live site.
I have the settings set to thumbnail resizing allowed. And "Process the featured image and any attached images" selected.

**Steps to Reproduce**

1. Go to Distributor > Pull Content > Pulled the page
2. Click on 'view'
3. Image Gallery is not there

**Expected behavior**

Should see the image gallery in the header. This is the listing I pulled https://www.millersflat.online/listing-item/clutha-gold-cycle-and-walking-trail/ I had to unlink it to get the images to work on here https://roxburgh.guide/listing/clutha-gold-cycle-and-walking-trail/

**Screenshots**

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - Theme and version: 
 - Other installed plugin(s) and version(s):
Analytify
Anti-Spam by CleanTalk
Contact Form 7
Duplicate Page
Envato Market
Envira Gallery Lite
MultiSite Clone Duplicator
Simple 301 Redirects
Slider Revolution
SSL Insecure Content Fixer
The Events Calendar
UrbanGo Checkout
UrbanGo Membership
WooCommerce
WooCommerce Stripe Gateway
WPBakery Page Builder
Yoast SEO

**Comment by jeffpaul** [comment]
@CoolWebDesignNZ can you confirm the version of Distributor and WordPress you're using?

**Comment by CoolWebDesignNZ** [comment]
Hi Jeffrey



Thanks for getting back to me. 



WordPress version 5.2.4

Distributor version 1.5.0



Thanks

Sandra

http://www.coolweb.designhttp://www.coolweb.designhttp://www.coolweb.designhttp://www.coolweb.designhttp://www.coolweb.design









---- On Tue, 12 Nov 2019 04:58:45 +1300 Jeffrey Paul <notifications@github.com> wrote ----



https://github.com/CoolWebDesignNZ can you confirm the version of Distributor and WordPress you're using?

**Comment by jeffpaul** [comment]
Potentially similar issue as #445, related to WPBakery Page Builder?

**Comment by lanceadam** [comment]
I'm also experiencing this issue with any images attached to ACF fields. Has there been any solution?

**Comment by jeffpaul** [comment]
@lanceadam we haven't investigated this any further as we're focused on wrapping up the `1.6.0` release while this issue is currently milestoned for our `2.1.0` future release.  If you're able to help troubleshoot, identify a potential solution, and submit a PR I'd be happy to pull this into a nearer term release.

**Comment by jeffpaul** [comment]
Closing in favor of #445, please subscribe to that issue for future updates on our progress.
