### ISSUE TITLE
Remove Canonical Tag

### ISSUE THREAD

**Issue by brandon-cybermark** [10up/distributor#496]
We are trying to add code to our functions.php theme file to remove the Distributor canonical tag being outputting. Our efforts had continually failed. We tried. 

add_action( 'init', 'my_remove_filter' );
function my_remove_filter() {
    remove_filter( 'get_canonical_url', array( '\Distributor\InternalConnections\NetworkSiteConnection', 'canonical_url' ), 10, 2 );
    remove_filter( 'wpseo_canonical', array( '\Distributor\InternalConnections\NetworkSiteConnection', 'wpseo_canonical_url' ) );
}

**Comment by jeffpaul** [comment]
@brandon-cybermark to help clarify here, you're looking for an enhancement to Distributor to allow for the removal of the canonical tag on distributed posts ...OR... asking a question about how to do so with the existing `get_canonical_url` and `wpseo_canonical` filters?

**Comment by brandon-cybermark** [comment]
How to do so with the current filters.

On Dec 5, 2019, at 6:37 PM, Jeffrey Paul <notifications@github.com> wrote:

﻿

@brandon-cybermark<https://github.com/brandon-cybermark> to help clarify here, you're looking for an enhancement to Distributor to allow for the removal of the canonical tag on distributed posts ...OR... asking a question about how to do so with the existing get_canonical_url and wpseo_canonical filters?

**Comment by dinhtungdu** [comment]
We need to do the removal after the filters have been added. In our case, the filters are added in `template_redirect`, so we need to hook after that:

```
add_action( 'template_redirect', function () {
	remove_filter( 'get_canonical_url', array( '\Distributor\InternalConnections\NetworkSiteConnection', 'canonical_url' ), 10, 2 );
	remove_filter( 'wpseo_canonical', array( '\Distributor\InternalConnections\NetworkSiteConnection', 'wpseo_canonical_url' ) );
}, 20 );
```
