### ISSUE TITLE
Shortcodes within plugins are not rendered when pulling content within multisite

### ISSUE THREAD

**Issue by petenelson** [10up/distributor#497]
When on a network/multisite install and you pull content from one site to another, shortcodes within plugins from the selected site are not being rendered before inserting the post into the current site. The raw shortcode gets added to the post content.  Pushing content from one site to another is not affected as the push functionality runs `the_content` filter before pushing the post.

This is due to some limitations around WP core. For a network pull, the code switches to the selected site via `switch_to_blog()` to get the post. Because switching blogs does not activate any plugins, and if the shortcode is within a plugin, running `the_content` filter would still not have any effect.

A possible solution would be to make an HTTP call to the selected site's REST API endpoint right after copying the post. This exposes the rendered content of the post, and we could update the current site's post with the rendered content.

Because I need to get this working for a client's site, I'll likely take that code and refactor it for a patch for Distributor.

**Comment by jeffpaul** [comment]
Thanks again for the heads up on this @petenelson even more so in offering to craft a PR to resolve this! 🙏

**Comment by jeffpaul** [comment]
Closed via #498.
