### ISSUE TITLE
VIP Go setup

### ISSUE THREAD

**Issue by jonny-bull** [10up/distributor#500]
**Describe your question**

I've got a WP multisite set up locally with Distributor that works as expected.

When deploying to a VIP Go environment, the sites in my network aren't detected.

Is there any extra setup required to get networked sites to appear as options for pulling and pushing on VIP Go?

**Comment by jeffpaul** [comment]
@jonny-bull welcome to Distributor and great question!  Unfortunately I don't have an immediate answer for you, though you might try the [WPCOM OAuth2 connections](https://github.com/10up/distributor#requirements) to see if that works while I dig a bit to get you a better answer.

Note that 10up is closed for the holidays starting tomorrow through Wednesday, January 1st so it'll likely be early January at best before I'm able to get back to you with an answer.  Apologies for the delay, but hopefully you'll have a safe and happy holiday in the meantime... cheers!

**Comment by jeffpaul** [comment]
@jonny-bull were you able to try using the WPCOM OAuth2 connections to see if that resolved things for you?

**Comment by jeffpaul** [comment]
@jonny-bull were you able to try using the WPCOM OAuth2 connections to see if that resolved things for you?

**Comment by WPprodigy** [comment]
Hey @jeffpaul,

I believe this is what might have been tripping them up: https://github.com/10up/distributor/blob/2e8e0779a4dd83739c78317d7faa5f331f7c36d7/distributor.php#L110-L112 `Distributor\Utils\is_vip_com()` is still true for VIP Go sites, but seems only necessary for WPcom VIP Sites.

Could perhaps also check if the `VIP_GO_ENV` constant is set and is not false: https://github.com/Automattic/vip-go-mu-plugins/blob/abcc27185d0b163f66153575cdd4cd41148deb26/000-vip-init.php#L66.

Alternatively, I think we've got everybody migrated to VIP Go that is using this plugin, so I could double check on that and this logic could potentially just be removed entirely?

**Comment by jeffpaul** [comment]
@WPprodigy thanks for the notes, much appreciated!  I'd rather play it cautious and avoid any mistake in a VIP site getting caught here, so the VIP_GO_ENV check you noted make be the best route.

**Comment by jeffpaul** [comment]
@WPprodigy any chance you've been able to check to see if everybody using Distributor has been migrated to VIP Go?

**Comment by WPprodigy** [comment]
Confirmed! All on VIP Go.

**Comment by jeffpaul** [comment]
In discussing the best approach here, the decision was to remove the logic noted in the https://github.com/10up/distributor/issues/500#issuecomment-580494918.
