### ISSUE TITLE
Remove "Registration" notice when registered

### ISSUE THREAD

**Issue by hearvox** [10up/distributor#501]
Remove "Registration" input-field descritiion after successful registration (green checkmark). Screenshot attached (vers 1.5).
![dist-reg-gey-setting](https://user-images.githubusercontent.com/275759/71918805-51e74380-3140-11ea-94c3-2c2f4fa55f51.png)

**Comment by jeffpaul** [comment]
Welcome to Distributor @hearvox and thanks for the feedback.  I concur this makes sense and have labeled this as a `good first issue` and `help wanted` in case someone's able to work on a PR; in which case I'd pull this from our `Future Release` milestone into the next release.

**Comment by dhanendran** [comment]
@jeffpaul I have raised a PR for this https://github.com/10up/distributor/pull/702

**Comment by jeffpaul** [comment]
Awesome, many thanks for the help @dhanendran!
