### ISSUE TITLE
Remove default Add New Ext. Conn. field value upon added URL.

### ISSUE THREAD

**Issue by hearvox** [10up/distributor#502]
And added external URL write on top of the default input-element value of the Add New External Connection text field, so both are visible (screenshot attached, vers 1.5).
![dist-new-external](https://user-images.githubusercontent.com/275759/71919021-e05bc500-3140-11ea-8cb0-2f0401bd92ec.png)

**Comment by jeffpaul** [comment]
@hearvox what OS and browser are you using in seeing this issue?

**Comment by hearvox** [comment]
Mac 10.14.6, Chrome 79.0.3945.117 (Official Build) (64-bit).
Connected two sites, issue happened on both.

Happened only during setup. Did not persist. The next time I viewed those connections settings screen the field was as-expected: just the domain name, no default text.

**Comment by jeffpaul** [comment]
I'm milestoning this for `Future Release` as its feasible the changes coming in #368 may make this issue irrelevant as the process/fields/UI will all be updated.

**Comment by theskinnyghost** [comment]
@jeffpaul I tried to replicate this on Mac 12.6.8 and Chrome 117.0.5938.132 (Official Build) (x86_64) but also Firefox, Brave and Safari and I wasn't able to. Given that an "external connection" is a CPT and we use the WP Core field for setting the title, I think we can close this out.
