### ISSUE TITLE
Suggest "/wp-json" for External Connection URL field.

### ISSUE THREAD

**Issue by hearvox** [10up/distributor#503]
The settings screen's External Connection URL field seems to require a "wp-json" endpoint. If true, perhaps suggest that in the description for that input field, rather than after the user enters an URL w/o that endpoint  ("Did you mean..."). Screenshot attached, vers 1.5.
![dist-external-url](https://user-images.githubusercontent.com/275759/71919222-5eb86700-3141-11ea-95f1-82a2c8eb5594.png)

**Comment by jeffpaul** [comment]
@hearvox this should get resolved with #368, so I'm linking these two to ensure we double-check this issue as 368 gets through review and testing.

**Comment by helen** [comment]
This seems to work well with #368 (still in progress) - I honestly don't know the history here behind why we don't just automatically try appending that but we do suggest it. @tlovett1 any recollection?

**Comment by jeffpaul** [comment]
Closing via #368.
