### ISSUE TITLE
Confirm pull for users in Pull Content screen (redirect to Pulled list?)

### ISSUE THREAD

**Issue by hearvox** [10up/distributor#504]
After a post is pulled using the Dashboard> Distributor> Pull Content screen, user may not see the "Posts have been pulled" admin notice (I missed it), so not now the pull succeeded.

One solution is, after a pull, to redirect the Pulled content list (?page=pull&status=pulled).

**Comment by jeffpaul** [comment]
@hearvox thanks for the feedback, we'll look at this in an upcoming release but would gladly pull this into an earlier release if someone's able to work on a PR for this.

**Comment by jeffpaul** [comment]
Closed via #575.
