### ISSUE TITLE
Pull Content list of "View | Edit" links not WP standard order

### ISSUE THREAD

**Issue by hearvox** [10up/distributor#505]
In WP admin post lists, the mousover-displayed links are ordered with Edit first, "Edit | ... | View".

Distributor reverses that order, "View | Edit". Might the WP standard be more user-expected?

**Comment by jeffpaul** [comment]
@hearvox thanks (again!) for the feedback, I've similarly marked this for an upcoming release, and would gladly look to pull this into an earlier release if someone's able to work on a PR for this.

**Comment by jeffpaul** [comment]
Closed by #532
