### ISSUE TITLE
ACF Flexible content does not distribute - Featured image does.

### ISSUE THREAD

**Issue by mlangone** [10up/distributor#506]
ACF Flexible content fields do not distribute, these include images, repeating fields and standard fields. The main flex content field however does come over, we have had the issue before with a plugin we made where we had to continue to traverse children of children of children to the level of fields that where created. Something like at least ~5 levels deep to get the fields to be recognized.

The featured page image however did come through.

Expected result
<img width="1369" alt="Screen Shot 2020-01-09 at 7 46 20 AM" src="https://user-images.githubusercontent.com/4027703/72077318-487ee800-32b4-11ea-8487-fa58d1d6343b.png">

Actual result
<img width="1380" alt="Screen Shot 2020-01-09 at 7 46 30 AM" src="https://user-images.githubusercontent.com/4027703/72077328-4cab0580-32b4-11ea-859e-f86291eee0b2.png">

**Comment by jeffpaul** [comment]
@mlangone thanks for the feedback, this looks similar to #81, #350, and #381.  I've milestoned this issue alongside those other three and will look to handle these together in our planned v2.1 release.

**Comment by manolobevia** [comment]
We are experiencing something similar. We are using ACF plugin for creating custom files, on top of that we are using another plugin call Advanced Custom Fields: Image Aspect Ratio Crop Field. This plugin creates a new advance custom file type, where we are able to upload and crop images. When we pull post from one site to another, images are not pulled.

**Comment by dinhtungdu** [comment]
@manolobevia Maybe this comment can give you some inspiration for handling custom fields distribution: https://github.com/10up/distributor/issues/609#issuecomment-656022292

**Comment by jeffpaul** [comment]
Closing in favor of #81.
