### ISSUE TITLE
Who to and save post_date of original post while pushing it across MU network

### ISSUE THREAD

**Issue by Copylefter** [10up/distributor#520]
**Describe your question**

I need to have the original post_date in pushed posts. I want to make a function by analogy with that https://github.com/10up/distributor/issues/233. But I couldn't get post_date of the original post. How I could get it?

**Comment by jeffpaul** [comment]
@Copylefter as noted in the [**Known Caveats/Issues** section](https://github.com/10up/distributor#known-caveatsissues):
> **Distributing Post Date** - By default, the "post date" on distributed stories is the date its published on the remote site, not the date published on the origin site. This can be overridden by extending Distributor with custom code to make it preserve the post date.

You'll find the listing of available actions and filters to accomplish this in our [hook documentation](https://10up.github.io/distributor/).

**Comment by Copylefter** [comment]
@jeffpaul Thank you a lot.
