### ISSUE TITLE
Limited connection established. Authentication failed.

### ISSUE THREAD

**Issue by mark-macrae** [10up/distributor#521]
I found this plugin and it seems to be exactly what we need in this case.  Multiple sites operated by the same company that want to be able to easily replicate blog posts between them.

Unfortunately, after following your install instructions I get the following warning/error:
Limited connection established. Authentication failed.
Push distribution unavailable.
Pull distribution limited to basic content, i.e. title and content body.

I had had to edit my .htaccess for the two sites in question as your instructions mentioned as a solution to the PHP Authentication problem.

I would really love to be able to use this plugin... help!

**Comment by jeffpaul** [comment]
@mark-macrae I'm assuming you're setting Distributor up across different WordPress instances, otherwise if you're running multisite then you do not need to set up External Connections as Distributor works on mulitisite without needing to connect the various multisites.  If you are working across different WordPress instances, are you still having a problem after editing the .htaccess file or are things working now?

**Comment by jeffpaul** [comment]
@mark-macrae can you provide an update on how things are or are not working for you so I can try to help troubleshoot for you?

**Comment by mark-macrae** [comment]
Hi Jeffrey,
To be honest, i wasn't able to get it working so I put it on the back
burner.

Our second site got indefinitely delayed for covid-19 reasons and now maybe
will be launched in fall.

But the basic idea is two different WordPress installations publishing the
same blog content. It seemed that's what this plugin could do. But I had
that authentication issue stop me.
mark

**Comment by jeffpaul** [comment]
@mark-macrae we have an update pending for Distributor that helps streamline the process of setting up external connections, I'll make a note to remind you when that's released so you can try setting up connections again then.

**Comment by jeffpaul** [comment]
@mark-macrae note that we just released Distributor 1.6.0, so please give that a shot if you're still having issues setting up External Connections.

**Comment by mark-macrae** [comment]
Thanks so much for following up.  I'll be able to give it a try next week.
Fingers crossed.



                                           Mark MacRae
Actor, Singer, Sailor, Storyteller
www.markmacrae.ca

**Comment by jeffpaul** [comment]
@mark-macrae any updates on testing Distributor 1.6.0 to see if it resolves your issue?

**Comment by jeffpaul** [comment]
@mark-macrae any updates on testing Distributor 1.6.4 to see if it resolves your issue?
