### ISSUE TITLE
Searching for posts during a multisite pull does not work correctly

### ISSUE THREAD

**Issue by petenelson** [10up/distributor#522]
**Describe the bug**
When searching for posts to pull from a multisite install using multiple words, posts from the source site cannot be found.

**Steps to Reproduce**

1. On the source site (where you're pulling from), publish a post titled "A post about Global Entry"
2. On the target site, go to Distributor > Pull, search for "global entry"
3. The post from the source site is not found.

**Expected behavior**
When searching, the post from the source site is found.

**Screenshots**
![image](https://user-images.githubusercontent.com/1757075/74453120-96ed4c80-4e47-11ea-9587-247ac5440f6e.png)

**Environment information**
- WordPress multisite, version: 5.3.2
 - Distributor version: 1.5.0

**Additional context**
This appears to be a [bug here](https://github.com/10up/distributor/blob/develop/includes/classes/InternalConnections/NetworkSiteConnection.php#L404) when searching multiple words and query string encoding. Adding `urldecode()` to this line fixes the problem, but I'll do additional debugging to determine the correct fix overall.

**Comment by petenelson** [comment]
I'll be working on a pull request to address this.

**Comment by jeffpaul** [comment]
Closed via #533.
