### ISSUE TITLE
Add filter for request timeout

### ISSUE THREAD

**Issue by aahovhannisyan** [10up/distributor#523]
In case the posts have large meta, updating the post meta may take more than 5 seconds. We have **\Distributor\Subscriptions\send_notifications** function working in background, and sending big amount of posts to be distributed (4000 in our case) when others aren't yet completed, causes to have multiple processes working in parallel with the endpoint. Some of the processing scripts get timeout, and we have incomplete post metas distributed as result. We need to wait for the endpoint response, and only after that send the next post to be distributed.

Suggestion is to add a filter for the timeout, so we can hook in and modify it as desired.
https://github.com/10up/distributor/blob/develop/includes/subscriptions.php#L283

I can see a similar filter in **\Distributor\ExternalConnections\push()**
https://github.com/10up/distributor/blob/develop/includes/classes/ExternalConnections/WordPressExternalConnection.php#L616

**Comment by jeffpaul** [comment]
@armdev17 welcome to Distributor and thanks for the feedback.  I would love your help on this Issue, would be happy to review a PR for it, and will attempt to provide any assistance you might need; any chance you'd be able to work on a PR for this?

**Comment by aahovhannisyan** [comment]
@jeffpaul thanks. Sure, I'll submit a pull request for this.
