### ISSUE TITLE
Remove Post connection records

### ISSUE THREAD

**Issue by PaddyWhacks** [10up/distributor#530]
I have had a few times when distributing a post from a site that for whatever reason it fails. Despite the post not going through, distributor still thinks that there is a connected post (although the receiving site does not show the post) and the site / external connection is greyed out when trying to distribute. In this particular instance it was cause the site receiving the post accepted it, but then I think was rolled back to the day before.

I would love to manage my active connections for each post - i.e. if for whatever reason a distributed post fails, I can remove the connection for the receiving site, and then it will make the site from grey to white again and I can try again to distribute the post.

**Comment by jeffpaul** [comment]
@PaddyWhacks that sounds a bit like the disconnect post feature on remote sites that allows you to effectively edit the distributed post (but the sever ability for future updates from the origin post)... just having the ability to do this from the origin site (whether the remote post actually exists or not).  Do you have any mockups in mind for how this might look/work to display the full list of sites the origin post thinks its distributed to and how you'd remove a connected post?
