### ISSUE TITLE
Automatically Pulled by cron

### ISSUE THREAD

**Issue by sebastienserre** [10up/distributor#536]
Hello,
I don't know if I do not find the solution or if it isn't possible yet but I'd like to automatically pull new content on a wp-cron task for example.

Is it possible?

Many thanks

**Comment by jeffpaul** [comment]
@sebastienserre can you provide some more details into the problem you're trying to solve with this approach?  Depending on those details, there may be an option for you within Distributor or a separate way to solve it altogether.

**Comment by sebastienserre** [comment]
Hello,
I've a customer with a multisite.
Posts are published on main-site.example.com and must be pulled by sub-site.example.com

I see 2 ways:

- Main-site.example.com will automatically push on "save_post"
- sub-site.example.com will periodically pull posts from main-site.example.com

maybe another way exists. I'm opened to all solutions

**Comment by jeffpaul** [comment]
@sebastienserre is it just that they want the distribution of posts to happen immediately without having to utilize the Distributor push menu from main-site.example.com?

**Comment by sebastienserre** [comment]
yes it is

**Comment by jeffpaul** [comment]
@sebastienserre this will be covered by #456 later this year.  Will the approach in 456 cover your needs?

**Comment by sebastienserre** [comment]
Yes it will cover, many thanks
