### ISSUE TITLE
Connection Established, But in Posts No Connection Available

### ISSUE THREAD

**Issue by dmvieira74** [10up/distributor#546]
**Describe your question**

Hello, I have Distributor set up on main site and Distributor/Application Passwords set up on the remote site. I get the green light on my connection status. The roles have been assigned. But when I go into a post and hover over Distributor in the admin bar, it states "No connections available for distribution".

Any ideas on how to troubleshoot this?

Thanks in advance,
Dennis

**Comment by jeffpaul** [comment]
@dmvieira74 to confirm some of your details:
1) You're trying to connect two different WordPress installs and not to sites within the same multisite instance, correct?
2) You're utilizing the password provided by the Application Passwords plugin when adding the External Connection on your main site, correct?
3) The post you're trying to distribute is from your main site, correct?

**Comment by dmvieira74** [comment]
@jeffpaul 

1. Yes. I have two separate WP installs, but they are on the same server.
2. Yes. I have Application Passwords set up on the remote site. On the main site, for the authentication method, I am using Username/Password. Those credentials come from the Application Passwords plugin on the remote site. On the main site, the external connection gets a green light.
3. Yes. I am trying to push a post from the main site to the remote site.

Thanks!

**Comment by jeffpaul** [comment]
@dmvieira74 ok, then that's definitely odd.  Are you seeing any console errors?

We're working to add Distributor information into the Site Health Info section of WordPress, see #517, so we'll be able to capture a little better technical info to troubleshoot once v2.0 is released in a couple of weeks.

**Comment by dmvieira74** [comment]
Hi @jeffpaul 

There are no console errors, but some warnings about non unique nonce ids. Those warnings are for the custom fields' hidden ajax nonces.

I will keep an eye out for the new version, thank you!

**Comment by jeffpaul** [comment]
@dmvieira74 have you been able to test this with Distributor 1.6.0 and determine if your issue still exists?

**Comment by dmvieira74** [comment]
Hi @jeffpaul I have not been able to test any new version of the plugin. I have since deactivated it. At some point I will revisit it and update here, but I do not know when that will be. Thanks for the check up!
