### ISSUE TITLE
External Connections admin page markup enhancements

### ISSUE THREAD

**Issue by samikeijonen** [10up/distributor#550]
Refers to admin page `admin.php?page=distributor`.

**Is your enhancement related to a problem? Please describe.**
- Title “External connections” and link “Add new” is wrapped inside the same H1.
- I’d keep the same markup as in all the other similar views like `edit.php?post_type=page` for consistency. 
- `<h2 class="screen-reader-text">Filter connections list</h2>` missing before filters list.
- aria-current=”page” missing from the current filter.

**Describe the solution you'd like**
Replicate what `edit.php?post_type=dt_ext_connection` would give by default when clicking All (count).

**Comment by joshuaabenazer** [comment]
@jeffpaul I'm picking this up
