### ISSUE TITLE
Distributed post content get converted to classic (from block) after updating the original

### ISSUE THREAD

**Issue by dinhtungdu** [10up/distributor#561]
**Describe the bug**

After updating original post (blocks based content), the content of distributed posts is converted to single classic editor. In `is_using_gutenberg` function, we use `use_block_editor_for_post` which is return `false` in my tests; it even isn't loaded sometimes.
**Steps to Reproduce**

1. Setup distributor and external connection.
2. Publish a blocks based post.
3. Push that post to an external connection.
4. See the distributed post is block based.
5. Update the original post.
6. See the distributed post content gets converted to a single classic block.

**Expected behavior**

The content should be block based after updating the original post.

**Comment by dkotter** [comment]
@dinhtungdu I was able to reproduce this as well, both with internal and external connections.

After some debugging, the issue for me had to do with Gutenberg making two requests to save a post (see https://github.com/WordPress/gutenberg/issues/12903). The first request correctly identifies we are using Gutenberg and updates the syndicated item with the raw content and then the second request has the failing `is_using_gutenberg` check and then updates the syndicated item with the rendered content, not the raw content.

We had partially solved for this for internal connections (see #518) but didn't bring those changes over to external connections. So I think that should be brought over and then we need to determine the best way to ensure updates only happen once and that they happen with the correct content (I have a few ideas but need to think them through a bit more)

**Comment by dinhtungdu** [comment]
@dkotter Thanks for testing, I used `xDebug` and discovered that for the first request, the `use_block_editor_for_post` hasn't been loaded yet, so `is_using_gutenberg` return `true` because we check for the content of the post. For the second request, `use_block_editor_for_post` is loaded and it returns `false` because of the following block of code.

```
	if ( isset( $_GET['meta-box-loader'] ) ) {
		check_admin_referer( 'meta-box-loader', 'meta-box-loader-nonce' );
		return false;
	}
```

In my test, the content at the time it's passed to `is_using_gutenberg` is always block-based content. But due to `use_block_editor_for_post` returning `false`, the rendered content is used to update syndicated posts.

Also note that once the syndicated post content is converted to classic, it will be always classic even the raw content (blocks) is synced correctly because we check for Gutenberg status on both sides before populating content.

**Comment by jeffpaul** [comment]
@dkotter is this issue fully resolved by #579?

**Comment by dinhtungdu** [comment]
FYI, in my latest test on the current `develop` branch, I don't have this issue anymore.

**Comment by jeffpaul** [comment]
Thanks @dinhtungdu, I'll close this by #579 then.
