### ISSUE TITLE
Select All button placement and style

### ISSUE THREAD

**Issue by dkotter** [10up/distributor#577]
In #495, a Select All button and a None button were added to the Distributor drop-down menu. This makes it easy to select all connections to distribute to at once, rather then having to select these individually.

Right now these buttons show above the connection list but seems like maybe we would want to move these buttons below that list, maybe even right align instead of left align?

Also, we use the same style for both the Select All and None buttons. Thinking maybe the None button should take the secondary button style that WordPress has, or maybe even just a text link?

Here are some screenshots on how it currently looks:

Default with no connections currently selected:
<img width="726" alt="Screen Shot 2020-04-13 at 8 48 53 AM" src="https://user-images.githubusercontent.com/916738/79471090-6482db80-7fbf-11ea-809d-047878489b77.png">

All connections selected:
<img width="810" alt="Screen Shot 2020-04-13 at 8 49 00 AM" src="https://user-images.githubusercontent.com/916738/79471131-719fca80-7fbf-11ea-8780-79899643d54a.png">

Some connections selected but not all:
<img width="813" alt="Screen Shot 2020-04-13 at 8 49 11 AM" src="https://user-images.githubusercontent.com/916738/79471169-7d8b8c80-7fbf-11ea-8d81-43b71cf04d80.png">

**Comment by dkotter** [comment]
Just noting these button styles were slightly changed in #569, that was recently merged in. Changed the None button to the secondary button style.

<img width="749" alt="Screen Shot 2020-05-19 at 8 51 44 AM" src="https://user-images.githubusercontent.com/916738/82341839-2b6acc00-99ae-11ea-9624-f21ec4a66b14.png">

<img width="812" alt="Screen Shot 2020-05-19 at 8 51 53 AM" src="https://user-images.githubusercontent.com/916738/82341786-1aba5600-99ae-11ea-943a-35248f770bff.png">

<img width="816" alt="Screen Shot 2020-05-19 at 8 52 01 AM" src="https://user-images.githubusercontent.com/916738/82341895-3aea1500-99ae-11ea-8ea0-3f6be5a60ea7.png">

**Comment by helen** [comment]
I'm digging in here, just commenting to document my thought process and see if there's anything I'm overlooking or approaching in a funny way:

* I think "Select All" should indeed go underneath the list.
* "Select None" should actually probably be "Clear" and a text button next to the "Selected connection" header on the right.
* The disabled states (already distributed and selected) in the list of available connections are not really visually discernible, need to do something with that.

**Comment by helen** [comment]
Opened a PR for this in #589, there are a few things outstanding in there that are nice-to-haves but not blockers.
