### ISSUE TITLE
Accidental Skipped Posts

### ISSUE THREAD

**Issue by zacnboat** [10up/distributor#580]
I've had a number of accidental skips by editors managing our site, and there doesn't appear to be a way to UN-skip a post that has been skipped. Am I missing something? This seems like kind of a basic functionality that SHOULD be there.

**Comment by jeffpaul** [comment]
@zacnboat we have some designs on potentially updating the Pull Content screen in #392, including being able to access skipped posts.  If those designs/process appears to match what you're looking for, then let's close this issue and track things within the larger focus of 392.

**Comment by jeffpaul** [comment]
@zacnboat have you had a chance to check the designs in 392 to see if they'd meet your needs here?

**Comment by jeffpaul** [comment]
@zacnboat I'm closing this issue in favor of #392, but if you have further needs than what 392 will cover please either add them to 392 or re-open this issue and provide those details.  Thanks!

**Comment by jeffpaul** [comment]
@zacnboat note that this will be feasible with the pending 1.6.3 release.
