### ISSUE TITLE
UI bug: switching set up process doesn't clear fields

### ISSUE THREAD

**Issue by jeffpaul** [10up/distributor#583]
**Describe the bug**
From @helen's [comment](https://github.com/10up/distributor/pull/368#issuecomment-612242826) on #368:
UI bug - if I click "Manually Setup Connection" but then decide to switch to WordPress.com Application, the fields do not disappear. [See screenshot](https://share.getcloudapp.com/bLueYZNR) for what I mean. I think this should probably reset entirely, so hide the fields when you switch, but if you switch _back_ to `Username/Password` it should give you the wizard thing again.

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - Distributor version: 
 - Theme and version: 
 - Other installed plugin(s) and version(s):

**Additional context**

**Comment by jeffpaul** [comment]
Punting to 1.6.1 as something to resolve in a minor release, happy to get a PR reviewed and merged if someone's able to work on this in the meantime.

**Comment by dhanendran** [comment]
@jeffpaul I can work on this issue.

**Comment by dhanendran** [comment]
PR: https://github.com/10up/distributor/pull/727
