### ISSUE TITLE
Push Posts to all subsites in Multisite install

### ISSUE THREAD

**Issue by wisnetmaster** [10up/distributor#591]
**Describe your question**
First off, great plugin! I was able to go into a subsite and "Pull" a custom post type "Listings" from the main site just fine. We have quite a few subsites and would like to the ability to "Push" the Listings from the main site to all subsites. I only see the option to pull from individual subsites. Sorry if am overlooking something obvious!

**Comment by helen** [comment]
Hi there! I would not say it's particularly obvious - when you're viewing or editing a post on the main site, up in the admin bar you'll see a Distributor menu which will allow you to push to subsites. An upcoming update will allow you to select all sites at once - see #495 and #589 for what that will look like.

**Comment by wisnetmaster** [comment]
@helen awesome. thanks for the update! Being able to select all posts and push to selected/all subsites would be awesome!

**Comment by jeffpaul** [comment]
@wisnetmaster since the Push functionality exists ([see this screenshot](https://distributorplugin.com/wp-content/themes/distributor-theme/assets/img/push-screenshot.jpg)), I'm going to close out this issue.  If you run into any issues or have other needs for Distributor, then please come back and let us know... thanks!

**Comment by wisnetmaster** [comment]
@jeffpaul can you bulk push posts, or just individual ones?

**Comment by jeffpaul** [comment]
@wisnetmaster there is no integration for Distributor in the `Bulk Actions` functionality of the All Posts/Pages list tables, so the only option to distribute out to multiple connections is from within a single post/page/CPT via the admin bar.

**Comment by wisnetmaster** [comment]
@jeffpaul would be a nice feature! Anyways, cool plugin.

**Comment by jeffpaul** [comment]
@wisnetmaster bulk push would essentially mean pushing more than one post to the same connections.  If that's something you have a legitimate use case for, then please open a separate issue noting use case and any UX or user flows that you'd have in mind.
