### ISSUE TITLE
Show count of selected connections in Push menu

### ISSUE THREAD

**Issue by jeffpaul** [10up/distributor#592]
**Is your enhancement related to a problem? Please describe.**

As an offshoot from #589, there's an additional UI improvement we can make to the Push menu in the form of noting how many connections are selected for distribution.

**Describe the solution you'd like**

- [ ] Show the number of selected connections - this needs i18n consideration in whatever string, easier to just put the count in parens rather than trying to pluralize

**Designs**

n/a

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by roshniahuja** [comment]
I have Generated [PR](https://github.com/10up/distributor/pull/1020) for this task.
Please have a look and let me know if is there anything.
