### ISSUE TITLE
Distributor admin bar menu unavailable in Gutenberg fullscreen mode (current WP default)

### ISSUE THREAD

**Issue by jeffpaul** [10up/distributor#597]
**Describe the bug**
In testing something unrelated, I noticed that WP 5.4 and the new default of fullscreen mode for Gutenberg that post-publish you don’t get the admin bar anymore so the Distributor menu is no longer visible in Gutenberg when it used to be.

**Steps to Reproduce**

1. Go to Gutenberg editor of a Post
2. Publish a post
3. See that admin bar is no longer present
4. :sad-panda:

**Expected behavior**
I know we want to avoid cluttering up the sidebar with more cognitive load and maintaining 2 UIs, so some options to consider are:
- integrating Distributor push actions into the Gutenberg slotfills versus relying on the admin bar
- something in the Gutenberg view to trigger showing the existing UI
- ...something else I haven't considered?

**Screenshots**

**Environment information**
 - Device:  Mac mini (2018)
 - OS:  MacOS 10.15.5
 - Browser and version:  Firefox 77.0.1
 - WordPress version: 5.4.2
 - Distributor version:  1.5.0
 - Theme and version:  Twenty Twenty 1.4
 - Other installed plugin(s) and version(s):

**Additional context**

Back in August 2019 a [Gutenberg issue was opened](https://github.com/WordPress/gutenberg/issues/16988) looking to add a SlotFill to the Toolbar in the Gutenberg header.  Later that month our very own @ryanwelcher [pushed up a PR](https://github.com/WordPress/gutenberg/pull/17198) to try and solve that issue, but it appears the Gutenberg team either doesn't appreciate the issue at hand or don't agree with the approach of the PR as there's no clear direction from that team on how to resolve the linked issue (either by iterating on the PR or via a completely separate approach).

Then in April of this year, a [similar issue was opened](https://github.com/WordPress/gutenberg/issues/21739) which then referenced back to the earlier issue and PR from August 2019.  Then again in May of this year, a [related issue was opened](https://github.com/WordPress/gutenberg/issues/22178) focused more on missing the New/View Page options from the adminbar.

In reviewing Gutenberg PRs to see what other options may currently be explored to adjust the fullscreen mode all that seems to exist is a [merged (and then reverted) PR](https://github.com/WordPress/gutenberg/pull/21121) from March of this year that attempted to make the WP logo toggle the WP Admin sidebar view on/off from fullscreen mode.  A [second PR attempt](https://github.com/WordPress/gutenberg/pull/22191) on this WP logo toggle from May of this year is still open and appears on hold and unlikely to be merged in time to make it into WP 5.5.

**Comment by jeffpaul** [comment]
While we work to determine how best to resolve this issue, I'm going to push up a PR to add a caveat to our readme and alert Distributor users to disable fullscreen editing to ensure they have access to the admin bar.

**Comment by Siedlerchr** [comment]
This was annoying me as well. Totally ridiculous that they didn't add a switch to disable it in the settings.
As a workaround I installed this plugin which is actually a single file 
https://wordpress.org/plugins/disable-block-editor-fullscreen-mode/
See the code: I'm not a PHP Dev, but this might help you:
https://plugins.trac.wordpress.org/browser/disable-block-editor-fullscreen-mode/trunk/disable-block-editor-fullscreen-mode.php

**Comment by jeffpaul** [comment]
@Siedlerchr thanks for sharing, though right now I don't want to force block fullscreen mode in Distributor so much as alert the Distributor community that it needs to be disabled to view the Distributor push menu in the admin bar.  Glad to see you've found a workaround that best fits your usage!

**Comment by jeffpaul** [comment]
Some additional input on folks running into this issue lately, possible option to consider:
> Might be worth making a big bigger/obvious or be a warning in the WP Admin, I don’t think an admin warning would be inappropriate

We'll want to see if the Gutenberg setting for fullscreen mode is targetable to then display a warning in the admin, as otherwise we'd be showing the warning to everyone who may not need to worry about this issue (e.g., they use classic editor, they work with fullscreen mode disabled).
