### ISSUE TITLE
Push original publication date

### ISSUE THREAD

**Issue by Borkent** [10up/distributor#604]
Hi,

I am trying to find a working solution to keep the publication date on the new pushed post.
So basically both sites have the same publication date. I am not using multisite.

I found one thread but it seems to break the distribution process and returns failed distribution.
https://github.com/10up/distributor/issues/233

Anybody here have a working function?

regards,
Thomas

**Comment by jeffpaul** [comment]
@Borkent as noted in our [Known Caveats/Issues](https://github.com/10up/distributor#known-caveatsissues):
> **Distributing Post Date** - By default, the "post date" on distributed stories is the date its published on the remote site, not the date published on the origin site. This can be overridden by extending Distributor with custom code to make it preserve the post date.

So unless I'm misunderstanding your question, it sounds like Distributor support the date defaults that you're asking for.  If I'm not correctly understanding your question, then please restate so I can try to better answer... thanks!

**Comment by Borkent** [comment]
You are correct, I dont know how to extend it to make it preserve the post date! Is there a tutorial somewhere?

**Comment by jeffpaul** [comment]
@Borkent, you'll find the listing of available actions and filters to accomplish this in our [hook documentation](https://10up.github.io/distributor/).  I suspect you're looking for [`dt_push_post_args`](https://10up.github.io/distributor/dt_push_post_args.html).

**Comment by Borkent** [comment]
Hi Jeff,

Thanks. Any chance you can write me a function to add to functions.php? My php skills are close to none. I can pay for it through paypal.

Regards,
Thomas

**Comment by TangramWerbeagentur** [comment]
Hi Jeff, 

I have the same problem and just as Borkent no clue how to solve it on my own. Is there any chance for this to become a feature in the future?

**Comment by Borkent** [comment]
> Hi Jeff,
> 
> I have the same problem and just as Borkent no clue how to solve it on my own. Is there any chance for this to become a feature in the future?

That would be awesome, at the moment I am left clueless on what to do. I use hooks for fishing 🤣

**Comment by dinhtungdu** [comment]
Hi @Borkent @TangramWerbeagentur 
You can pass the post date along with other push args to keep your date synced between origin and remote sites, for example:

```
add_filter( 'dt_push_post_args', function( $post_body, $post ) {
    $post_body['date'] = $post->post_date;

    return $post_body;
}, 10, 2 );
```

**Comment by TangramWerbeagentur** [comment]
Hey, cool! Thanks a lot, this solution is working perfectly.

**Comment by jmslbam** [comment]
The code example that @dinhtungdu provided here, https://github.com/10up/distributor/issues/604#issuecomment-699775009, worked for me with 1 adjustment. Because there is no `date` index for the body. Ref: https://developer.wordpress.org/reference/functions/wp_insert_post/#parameters

I needed to change the index `date` to `post_date` so it becomes:

```
add_filter( 'dt_push_post_args', function( $post_body, $post ) {
    $post_body['post_date'] = $post->post_date;

    return $post_body;
}, 10, 2 );
```

Thank you for the provided solution!
