### ISSUE TITLE
Standardize copy and links for editor notification on linked remote posts

### ISSUE THREAD

**Issue by jeffpaul** [10up/distributor#611]
**Is your enhancement related to a problem? Please describe.**
Depending on whether you push or pull a post and whether you view the remote post in Gutenberg or the Classic Editor, you will get four different possible editor notifications that the remote post is linked to the origin post.  Let's try and standardize the copy and format of what's displayed.

Pulled post in Gutenberg:
![Screen Shot 2020-07-08 at 8 04 29 PM](https://user-images.githubusercontent.com/2818133/86985192-4eb42b00-c156-11ea-9feb-8b9ceeb41921.png)

Pulled post in Classic Editor:
![Screen Shot 2020-07-08 at 8 05 30 PM](https://user-images.githubusercontent.com/2818133/86985227-68ee0900-c156-11ea-9f97-0d9540e6a2fe.png)

Pushed post in Gutenberg:
![Screen Shot 2020-07-08 at 8 06 16 PM](https://user-images.githubusercontent.com/2818133/86985278-858a4100-c156-11ea-808f-c6218398603a.png)

Pushed post in Classic Editor:
![Screen Shot 2020-07-08 at 8 07 10 PM](https://user-images.githubusercontent.com/2818133/86985332-a3f03c80-c156-11ea-873e-a149fddf979f.png)

**Describe the solution you'd like**

- [ ] standardize copy to "Distributed from `origin site name`.  The original will update this version unless you unlink from the original."
- [ ] link the text for `origin site name` to the origin post
- [ ] link "unlink from the original" to the Distributor unlink action

**Designs**

n/a

**Describe alternatives you've considered**

None, we should be standardizing this copy, links, and action across all possible permutations of the editor notification.

**Additional context**

n/a

**Comment by cdwieber** [comment]
After toying with this a bit, I can see why the Gutenberg version is set up as it is: the notification accepts simply a "message" and then an array of "actions", so the "message" must necessarily be separated from the "actions" (i.e. unlink, view original).* It seems that the i18n functions escape HTML making kludging in an inline link difficult without upending the notification system. There may be a way to do it I'm not seeing, but from now I'll submit a PR that takes care of the verbiage discrepancy and go from there.

*Reference: assets/js/gutenberg-syndicated-post.js:14

**Comment by jeffpaul** [comment]
@cdwieber do you think there's more we can technically do to standardize that copy or do you think what we've got merged in your PR is the best we can do and should otherwise close this issue?
