### ISSUE TITLE
After adding new CPT to show_in_rest => true, External Connections need to be refreshed

### ISSUE THREAD

**Issue by willopez** [10up/distributor#612]
**Describe your question**

Hello, 
I use a site builder named [Oxygen](https://oxygenbuilder.com) and have two installations of a site, one is a development and the other on is the live version. Both, dev and live are part of a multi-site WordPress installation. I have successfully established connections from live to dev and I am able to pull content to the live site from the dev site. However, Oxygen templates don't appear in the dropdown under the "Pull" screen. Are pulling Oxygen templates not supported for external connections? I do see the option for "Templates" when attempting to pull from another site within the network. 

Thanks!

**Comment by jeffpaul** [comment]
@willopez if you're using a single multisite install of WordPress, then you do not need to set up External Connections as Distributor works for Posts and Pages across all sites within a multisite without additional configuration.  Adding External Connections will require any [Custom Post Types](https://github.com/10up/distributor#known-caveatsissues) to be registered with the argument `show_in_rest => true` which sounds like may not be happening on your External Connection sites.  So if you're working off a single multisite, then remove the External Connections and Distributor should ideally work for all post types.

**Comment by willopez** [comment]
Thanks @jeffpau, in my case I need to add the `show_in_rest => true` argument to the custom post type.

**Comment by willopez** [comment]
I spoke too soon, my custom post type does not show up in the dropdown after adding the `show_in_rest => true` argument. Note, my sites are using an external connection and NOT on a multi-site installation. Seems like this is an actual issue.

**Comment by arsendovlatyan** [comment]
@willopez  We had similar issue too, in our case, after adding the `show_in_rest => true` argument  on both sides, we also had to update connection, so, connection settings will be updated and include the custom post type as distribute available.

**Comment by jeffpaul** [comment]
I've updated the title and labels for this issue noting that we should update our docs to note that External Connections need to be refreshed in this scenario.

**Comment by jeffpaul** [comment]
@willopez @arsendovlatyan note that this was added to our README.md in 8554605 and 0a5d6ca as part of the [1.6 release](https://github.com/10up/distributor/releases/tag/1.6.0).
