### ISSUE TITLE
Limited Connection established... .htaccess changes implemented, Application Password installed.

### ISSUE THREAD

**Issue by john-lynch-cp** [10up/distributor#615]
I have two Wordpress instances, both on the same hosting provider. Distributor installed on each, trying to connect using "External" connection. I'm using "Application Password" on both instances to generate authentication keys. 

The connection is working one way i.e. Site A -> Site B

I have amended the .htaccess on both sides to enable this, adding the line:

`RewriteRule .* - [E=REMOTE_USER:%{HTTP:Authorization}]`

Unfortunately, when I try to connect Site B -> Site A I receive the error: 

> Limited connection established. Authentication failed.
>     Push distribution unavailable.
>     Pull distribution limited to basic content, i.e. title and content body.

Is there something else I should be checking? 

The only difference I can see is the location of the instances relative to the domain root of the server. One is located in /webspace/httpdocs/subdomainname/ while the other is in /webspace/siteapps/ 

Appreciate any insight that can be shared!

**Comment by jeffpaul** [comment]
@john-lynch-cp note that you'll only need External Connections for separate WordPress instances.  If these are two sites within the same multisite, then you do not need External Connections and Distributor will function upon install and activation.  If these are separate sites, please update to Distributor 1.6.0 as that enhances and simplifies the External Connection process.

**Comment by john-lynch-cp** [comment]
Thanks. Multi site is not an option. This is a test environment for what will eventually be a network of sites, one primary, many secondary and on different infrastructure.

Already running 1.6.0 and connecting in one direction worked just fine. Cannot figure out why there is a problem in the opposite way.

**Comment by jeffpaul** [comment]
@john-lynch-cp can you please provide Site Health Info exports from the two sites to help us better triage?

**Comment by john-lynch-cp** [comment]
Thanks @jeffpaul - that alone was enough to point me in the right direction. The instance which was refusing connections was running PHP 7.2.31, which was different from that one the server which successfully accepted connections (7.3.19). Once upgraded, I have successfully established connections in both directions.

**Comment by jeffpaul** [comment]
@john-lynch-cp oh great, glad to hear things are working now!  I'm going to close out this issue, but if anything else comes up or you see ways that Distributor could be enhanced to better meet your needs then please do not hesitate to come back here and let us know... cheers!
