### ISSUE TITLE
Visual Composer Issues 

### ISSUE THREAD

**Issue by ghost** [10up/distributor#617]
hi guys Have an issue while pulling linked content on multisite using Wp Backery. The issue is when the content is pulled for the first time everything is ok, once you update the post and it is automatically pulled on  the microsite the layout is broaken and all the content is inserted into text blocks rather than in WPBackery widgets

**Comment by jeffpaul** [comment]
@SamMAdmaN welcome to Distributor and thanks for the feedback!  We're tracking known issues with WPBakery in #445 and have tentatively slotted development of a fix for that in our v2.1 release.  Note that we're currently at v1.6 and have a couple other releases planned ahead of v2.1 so there's no concrete timeline on a fix specific to WPBakery.  If you have a more urgent or important need to resolve this issue, then please reach out to me (jeff.paul@10up.com) and we can discuss alternate options... thanks!

**Comment by jeffpaul** [comment]
Closing in favor of #445, please subscribe to that issue for future updates on our progress.
