### ISSUE TITLE
Auth Setup Wizard's Application Title field width

### ISSUE THREAD

**Issue by jeffpaul** [10up/distributor#619]
**Is your enhancement related to a problem? Please describe.**
The `Application Title` field in the Auth Setup Wizard has a set width and any text over that length scrolls within that display.
Example:
https://cloudup.com/cSVfw2mBSHa && https://cloudup.com/cDuZQVi1hCZ

**Describe the solution you'd like**
Ideally the text in the `Application Title` field displays in full and doesn't require scrolling within that display.

**Designs**
n/a

**Describe alternatives you've considered**
n/a

**Additional context**

This may be an upstream issue with [Application Passwords](https://github.com/WordPress/application-passwords), so not certain if we'll need to submit a PR there and then adjust in Distributor once that's released.

**Comment by dhanendran** [comment]
@jeffpaul I can work on this issue.

**Comment by jeffpaul** [comment]
In testing this with @dhanendran looks like this has been resolved in the latest Distributor, WP core, and App Pwds releases:
![Screen Shot 2021-02-17 at 10 31 21 AM](https://user-images.githubusercontent.com/2818133/108235515-80896900-710b-11eb-8722-2154cf8611f9.png)
