### ISSUE TITLE
Editor pull capabilities

### ISSUE THREAD

**Issue by josephmasongsong** [10up/distributor#626]
Hello, awesome plugin thanks my org finds it very useful. Can anyone point me in the way of documentation on how to give Editors pull capabilities? Thank you in advance!

**Comment by dinhtungdu** [comment]
Hi @josephmasongsong, to allow Editors to pull, you need these following filters:

```
add_filter( 'dt_pull_capabilities', function() {
	return 'edit_others_posts';
} );
add_filter( 'dt_capabilities', function() {
	return 'edit_others_posts';
} );
```

**Comment by josephmasongsong** [comment]
That did the trick! Thank you so much @dinhtungdu !
