### ISSUE TITLE
Remote delete distributed posts

### ISSUE THREAD

**Issue by TangramWerbeagentur** [10up/distributor#627]
**Is your enhancement related to a problem? Please describe.**

When deleting a post on the "host" site it's not deleted on the "client" site. 

EDIT: I just realized that if you delete posts on the "client" site that still exist on the "host" they are still marked as distributed and can't be distributed to the "client" again.

**Describe the solution you'd like**

Optional deletion of distributed post when deleting "master" post.

**Designs**

An extra dialog when deleting a linked "master" post if you want to delete all distributed instances, too.

**Additional context**

Our client wants to manage three websites from one backend, and we don't want to use a multisite. So we have four backends, and one serves as "master". Deleted posts not being deleted from the sites distributed to means we have to open the other backends manually.

**Comment by jeffpaul** [comment]
@TangramWerbeagentur thanks for the feedback, its greatly appreciated!

We've started discussions on how to handle post status changes on the origin site (host site in your terms) in #112, so I'd recommend subscribing to that issue to watch progress on that topic.  If that issue feels like it covers your needs, then let's please close your issue so we can ensure conversations are all tracked within a single issue to keep discussions in one place... thanks!

**Comment by jeffpaul** [comment]
Closing this in favor of #112.
