### ISSUE TITLE
Content pushes fine initially, but updates not applied afterwards

### ISSUE THREAD

**Issue by pbaddock** [10up/distributor#628]
I am not reporting this as a bug, as Wordpress 5.5 update is throwing a bit of a wildcard into the mix so I'm a bit sus on it.  Source site has 5.5 running. 1 remote site as 5.5, one does not.   

I have my primary (pushing) site able to push a new post inc images etc to the (2) remote sites fine, but then subsequent updates on at the source are not updated on either of the remote sites after the initial push.  All the messages on the remote sites show the article is still linked to the source and the source saying it's linked to the remote sites but updates at the source do not update the remote end.

Would love suggestions on how to troubleshoot.  Tried disabling wordfence everywhere but didn't change the situation.

**Comment by pbaddock** [comment]
Perhaps unrelated but my source site is http and remote sites https.
I've backed wordpress 5.5 out now and trying again to troubleshoot.

**Comment by pbaddock** [comment]
no luck. stuck (tried removing all variables - wordfence, wordpress versions, nothing in debug logs with debugging enabled, nothing in error logs)..

**Comment by pbaddock** [comment]
Something interesting that I had never noticed before is that there seems to be a new custom post type "Distributor subscription" in the source site which adds a new subscription for each new distribution / post - perhaps that's expected functionality but I had never spotted that previously so mention it in case its not supposed to happen.

**Comment by jeffpaul** [comment]
@pbaddock thanks for the feedback and testing notes, though I just tried to replicate on a couple local sites and content updates as expected for me.  Details of my two testing sites are noted here: https://github.com/10up/distributor/issues/618#issuecomment-676608895.  If you're still seeing this occur for you, please provide Site Health Info from your sites as well as any console errors you may be seeing so we can better help triage... thanks!

**Comment by jeffpaul** [comment]
@pbaddock are you still seeing this issue and, if so, can you please provide your Site Health Info and any console errors so we can help triage for you?

**Comment by pbaddock** [comment]
Hi Jeff,
Tks for reaching out - I wasn't able to get past it, and have shifted to WP
Site Synch.  Tks for making contact anyway.

Cheers,

Pip Baddock
*Online Marketing Consultant*
Ph (id)/WhatsApp: +62 819 3462 8222
Ph (au) +61 3 9018 5170
