### ISSUE TITLE
Pulling postsdisables styling of the post display

### ISSUE THREAD

**Issue by itsik259** [10up/distributor#629]
**Describe your question**

Hello. I'm using the plugin in two websites using the AVADA wordpress theme.
After installing everything and making sure everything is correct, I pulled a blog post from one website to the other.
I then tried to edit the post to change some styling to suit the pulling site, but all options to do so are disabled as long as the post is linked to the original.
Is there a way to set the format of the pulled post and or create a template to be populated with the data from the pulled post to adjust the way all posts are displayed?
Thanks
Itsik

**Comment by itsik259** [comment]
Any one???

**Comment by jeffpaul** [comment]
@itsik259 what sorts of styling changes are you trying to make?

**Comment by itsik259** [comment]
Hi Jeff.
CSS related changes, title sizes etc.

**Comment by jeffpaul** [comment]
@itsik259 what sorts of changes are you trying to make?  Are these things that could be handled in your pulling site's theme or advanced CSS settings?  In general, you are not able to sever the Distributor connection between sites and maintain the flow of updates from the origin post to the remote post (your pulling site in this instance).

**Comment by jeffpaul** [comment]
(sorry, I replied to this from an old tab and didn't see the prior comments, I'll update my comment based on your prior update)

**Comment by jeffpaul** [comment]
@itsik259 I would expect that CSS and heading treatment changes should all be things you could edit with the advanced CSS or possibly via AVADA settings.

**Comment by itsik259** [comment]
Thank you for your reply
I'm talking about simple CSS changes that do not require advanced CSS. The problem is that on a regular post when you click on the heading element in the AVADA builder, you're able to change the settings while on a post that have been pulled the heading element is not clickble...

**Comment by jeffpaul** [comment]
@itsik259 that's because content pushed to or pulled into a remote site is not editable so that it can stay in sync with the content from the origin site.  If you need to make edits to content on a remote site, then you need to sever the Distributor link though that means any changes to the content on the origin site will no longer update the remote site content.
