### ISSUE TITLE
Tags Race Condition with another plugin?

### ISSUE THREAD

**Issue by silverman63** [10up/distributor#634]
Hi all, I'm not sure this is quite a bug report as its related to compatibility with another plugin.

Whenever a post is created or updated, our plugin sends an update with the latest WordPress tags to our service. We use the following hook:

```php
add_action( 'save_post', array( $this, '<callback>' ), 11, 3 );
````

The tags and categories are grabbed with `wp_get_post_terms` and `get_the_category()`

It seems a good percentage of the time that our plugin is unable to retrieve the correct tags for the **syndicated** version of a post. For example:

1. Post created in Site A with tags "foo", "bar" ==> our service sends "foo, bar" as tags
2. Post pushed to Site B
3. Post syndicated to Site B ==> our service gets no tags, though they're clearly visible in Site B Admin. Updating tags on Site B sends "foo, bar" appropriately.

It seems like this is some kind of race condition? Any recommendations on how to solve for this?

**Comment by dinhtungdu** [comment]
Hi @silverman63,

Distributor sets terms after the post has been inserted, so using `save_post` won't help you to grab the terms of syndicated posts. I recommend using `set_object_terms` to make sure you get terms after they're updated.

**Comment by jeffpaul** [comment]
@silverman63 are you all set here with the hook information provided such that we can close out this issue?

**Comment by jeffpaul** [comment]
@silverman63 I'm closing this due to no response, but if you still have an issue here please comment/re-open and we'll help... thanks!
