### ISSUE TITLE
How to set a taxonomy upon distribution completion

### ISSUE THREAD

**Issue by mikelking** [10up/distributor#637]
I have a multisite that we distribute content across, usually as a push action and I need to be able to set a specific taxonomic value upon receipt in the destination site.

To clarify when we push content from the canonical source to any other recipient site I need to set a custom taxonomy to a specific value.

Additionally if we pull content from one site into another the, we want to ensure that the receiving site sets the appropriate custom taxonomy upon receipt.

Site stats: 
PHP 7.3
WordPress: 5.4.2
Distributor: 1.5.0

**Comment by dinhtungdu** [comment]
> To clarify when we push content from the canonical source to any other recipient site I need to set a custom taxonomy to a specific value.
@mikelking So you want to set different taxonomy value for each remote site? Eg: one post distributes to three remote sites, and you want to set different value for a taxonomy for those three sites.

Distributor distributes all taxonomies that registered to that post type, is that not you're looking for?

**Comment by mikelking** [comment]
Sorry @dinhtungdu I did not see the email notice about this. The distribution of all of the taxonomies associated is not the issue and it works perfectly. We have an additional administrative taxonomy on ALL recipient sites that we would like to set automatically upon receipt of the distributed content (regardless of being pushed or pulled).

**Comment by dinhtungdu** [comment]
@mikelking I see. For your problem, you can use [`dt_push_post`](https://10up.github.io/distributor/dt_push_post.html) and [`dt_pull_post`](https://10up.github.io/distributor/dt_pull_post.html) to set taxonomy upon receipt. For example:
```
add_action( 'dt_push_post', 'set_taxonomy' );
add_action( 'dt_pull_post', 'set_taxonomy' );

function set_taxonomy( $new_post_id ) {
    // Your logic here.
}
```

**Comment by mikelking** [comment]
@dinhtungdu 

Thank you!
