### ISSUE TITLE
Allow for Pulling items previously Skipped

### ISSUE THREAD

**Issue by elgeorge2k** [10up/distributor#638]
**Describe your question**
How do I unskip posts? I removed it so that it could pull again with the right category and now its in "Skipped" and there is no way to remove, do I need to remove with phpmyadmin?

**Comment by dinhtungdu** [comment]
@elgeorge2k We planned to update the pull content screen to include the ability to pull skipped items at #392. If those designs/process appears to match what you're looking for, then let's close this issue and track things within the larger focus of 392.

**Comment by jeffpaul** [comment]
@elgeorge2k are you good with what's described in #392 such that we can close this issue and track all pull-related updates in 392?

**Comment by jeffpaul** [comment]
Closing in favor of the combination of #397 and #392.

**Comment by jeffpaul** [comment]
@elgeorge2k note that this will be feasible with the pending 1.6.3 release.

**Comment by elgeorge2k** [comment]
Thanks
