### ISSUE TITLE
Add support for core auto-updates for registered sites

### ISSUE THREAD

**Issue by jeffpaul** [10up/distributor#656]
**Is your enhancement related to a problem? Please describe.**
Now that WP core supports enabling auto-updates for plugins, we should look to support that functionality for registered Distributor sites.

**Describe the solution you'd like**

**Designs**
Here's a screenshot from a sample install showing enable/disable states for plugins on WP.org on an unregistered Distributor site.  We'll want to ensure the yellow notice box extends fully to the right column.
![Screen Shot 2020-10-20 at 12 40 56 PM](https://user-images.githubusercontent.com/2818133/96624168-ff8fa180-12d1-11eb-9bc2-1a0cdc437237.png)

Otherwise for registered sites we'll want to allow for the enable/disable states in that far right column.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by dhanendran** [comment]
@jeffpaul I can work on this issue.

**Comment by dhanendran** [comment]
@jeffpaul I gave a try to enable the auto-update functionality https://github.com/10up/distributor/pull/726
