### ISSUE TITLE
develop branch missing vendor dependencies - 'Failed opening required ...'

### ISSUE THREAD

**Issue by splaquet** [10up/distributor#657]
First time user here...

I installed the latest zip, using wp-cli.  After installing, I received a fatal error on the front end and these 2 error lines repeating in debug.log:
PHP Warning:  require_once(/public_html/wp-content/plugins/distributor/vendor/georgestephanis/application-passwords/application-passwords.php): failed to open stream: No such file or directory in /public_html/wp-content/plugins/distributor/distributor.php on line 116
PHP Fatal error:  require_once(): Failed opening required '/public_html/wp-content/plugins/distributor/vendor/georgestephanis/application-passwords/application-passwords.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /public_html/wp-content/plugins/distributor/distributor.php on line 116

`wp plugin install https://github.com/10up/distributor/archive/develop.zip --activate-network`

I double checked on the files in the develop repo, and noticed that the files are in fact missing from the repo source.  

...I then merged the previous files into the developer.  Everything worked at that point.

BUT... upon registering for a key, I realized that the download was linked to a stable branch.  (the default branch was develop) My apologies for not paying attention!  But, as I'd already drafted up this post, I thought I'd send as an FYI.

###
After using the same method to install the stable branch, everything worked 100% as expected.

**Comment by dinhtungdu** [comment]
@splaquet If you want to install `develop` branch, you'll want to use `git`, not WP CLI. Because `develop` is for development, you will need to install dependencies and build the assets before activating it. In detail, after cloning/downloading `develop`, you will need to run `npm start` in the root directory of the plugin.

If the WP CLI is the prefer option to install plugin, then `stable` is the branch to use.

**Comment by helen** [comment]
For more information here, we do show a notice that you will need to build certain files when you're running a dev version, but yes, it does fatal without `composer install`. I think this will become better in WP 5.6+ as Application Passwords will be built into core and we can stop making that a hard requirement.

**Comment by helen** [comment]
Nothing actionable here :)
