### ISSUE TITLE
Support for AMP - amp-dev-mode 

### ISSUE THREAD

**Issue by rickalee** [10up/distributor#658]
We recently launched a fully AMP site. AMP Standard mode for logged-in users strips out any non-compliant styles or scripts so our jQuery and Underscores based JS is getting stripped from admin bar making it less convenient for users to Distribute a post. 

https://github.com/ampproject/amp-wp/issues/5533

Weston pointed toward this blog post. 
https://weston.ruter.net/2019/09/24/integrating-with-amp-dev-mode-in-wordpress/
 
Appears we need to add admin-bar as dependency to any enqueues and 
data-ampdevmode to any inline script tags.

**Comment by jeffpaul** [comment]
Noting here that folks should still be able to use the site backend for push distribution, noting that you will need to disable `fullscreen mode` in the Block editor for the admin bar to be visible with the Distributor menu.
