### ISSUE TITLE
Update from 1.5 to 1.6 broke updates for custom post types

### ISSUE THREAD

**Issue by andrewortolano** [10up/distributor#659]
Working in a Wordpress multisite environment; running most recent version of WP core.

When using version 1.5, I could:

- Create a custom post type
- Create a post in that type
- Distribute it to another site in the Wordpress multisite network
- Make changes to the original
- **See those changes reflected in the distributed version**

Since updating to version 1.6, changes are no longer reflected in the distributed custom post type.

But if I remove the 1.6 version and replace it with the 1.5 version, this functionality works as expected.

**Comment by jeffpaul** [comment]
@andrewortolano if you distribute a custom post type in 1.6 will additional updates to the origin post be sync'd to the distributed posts?

**Comment by andrewortolano** [comment]
No, they will not. For custom post types:

- First publish and distribute always works as expected
- After publish, you can get changes to sync from original to distributed by unlinking from the original and then relinking it
- But changes made to the original do not propagate out to distributed 

And in my testing, not even changes to the Title were synced out to the distributed post, so I don't think it's a custom field bug.

**Comment by mikenosko** [comment]
This doesn't seem to work even for default post types. 

I created a post on my second multisite blog and it pulled to my first one. Then updated the post on the second one but nothing got updated on the first one.

**Comment by mikenosko** [comment]
I think i figured it out! 

I didn't have the plugin running on my second blog! I was using the Pull method on the first blog and obvs the post_save event hook didn't run on updated as it wasn't enabled. 

Enabling the plugin on my second blog seems to have fixed my issue even for custom post types. 
@andrewortolano can you confirm that you have the plugin enabled on all the blogs?

**Comment by xyralothep** [comment]
I'm getting the same problem currently - using Multisite with a CPT.  The post distributes fine, however when I make changes on the original site they aren't propagated through to the duplicated post.  If I delete the post on the original site too, the duplicated post remains.

I have the plugin running on the main site and the subsites.

**Comment by dkotter** [comment]
@andrewortolano @xyralothep Thanks both for the reports.

Looking through what changed from 1.5.0 to 1.6.0, in particular with the logic that updates distributed items in multisites, the only thing I'm seeing is a check we added when a post is using Gutenberg (see https://github.com/10up/distributor/pull/518).

I'm wondering if either of you (or both of you) can provide details on how you have these CPT's registered (in particular, the params you're passing to `register_post_type`). Also, are the sites you're testing on using Gutenberg or the Classic Editor (both the original site and the site you're distributing to)?

I just tested with a pretty basic CPT in my local environment, running Distributor 1.6.2 and updates distributed successfully, both when using Gutenberg on both sites and when using the Classic Editor on both sites. I'm guessing there's a scenario I'm just not testing, so if either of you could provide more information, that would be super helpful. Thanks!

**Comment by xyralothep** [comment]
Hi,

Thanks for looking into this for me.  Here's how I'm registering the CPT:

`		$args = array(
			'labels' => array(
				'name' => 'Offers',
				'singular_name' => 'Offer'
			),
			'public' => true,
			'supports' => array(
				'title', 'author', 'revisions'
			),
			'has_archive' => true,
			'rewrite' => array(
				'slug' => 'offers',
				'with_front' => false
			),
			'show_in_rest' => true
		);
		register_post_type('offers', $args);`

The CPT doesn't use Gutenberg because it just has a few simple ACF fields.

Cheers!

**Comment by dkotter** [comment]
@xyralothep Thanks for the additional information. Just to clarify further, if I setup a test post type using the same arguments as you shared, I get a post screen that does not have any way to set the actual `post_content`, is that correct? Assuming all data is just stored in meta fields (sounds like ACF in this case).

If that's correct, this is definitely a scenario we need to account for in our `is_using_gutenberg` utility function, as most of the checks it runs assumes there is some `post_content`. But just wanted to make sure that is what's going on before I work on getting a fix in place.

**Comment by xyralothep** [comment]
Yep, that's right, there is no post_content - just some ACF fields.  Thanks!

**Comment by dkotter** [comment]
Thanks @xyralothep for that confirmation. I think I have a fix in place that handles this situation. Feel free to test out #710 if you want and if so, let me know if that fixes the update issue.

@andrewortolano I'd still be curious to see if your situation is the same, using a post type that doesn't actually use `post_content`, or if there's another bug here we need to track down. Thanks!

**Comment by xyralothep** [comment]
That's sorted it, thank you!

**Comment by dkotter** [comment]
@xyralothep Awesome, thanks for the confirmation. We'll work to get this queued up for our next release.
