### ISSUE TITLE
i18n po/mo not loaded

### ISSUE THREAD

**Issue by sebastienserre** [10up/distributor#660]
**Describe the bug**
I translated Distributor in french but only strings in the plugin page but the translations are not loaded in the plugin setings it self:
![distrubor-fr](https://user-images.githubusercontent.com/3902621/97082185-228ac000-1608-11eb-8229-4558d2f0a359.png)
![distrubor-fr-settings](https://user-images.githubusercontent.com/3902621/97082206-49e18d00-1608-11eb-94da-60ba3ea65c1a.png)

[distributor-fr_FR.zip](https://github.com/10up/distributor/files/5432900/distributor-fr_FR.zip)

**Environment information**
 - WordPress version: 5.5.1

**Comment by jeffpaul** [comment]
Likely relates to  #267.

**Comment by dinhtungdu** [comment]
@sebastienserre Where did you put your translation file? Your translation is working for me. I put your mo and po files in `wp-content/languages/plugins/` directory:
![image](https://user-images.githubusercontent.com/5423135/97423318-9fd46e80-1941-11eb-9d18-72372dec1e13.png)

**Comment by sebastienserre** [comment]
Thank you @dinhtungdu 
I tested in 'lang' folder inside Distributor plugin folder.
If you ship my translations, they won't be loaded.

**Comment by dinhtungdu** [comment]
@sebastienserre Thank you so much! I can confirm this issue. I created #662 to fix this one. If you have time, please give it a review.

**Comment by sebastienserre** [comment]
OK I note to test it asap.
I'm quiet new and do not see any "lang/" folder to make a PR with french po/mo ?
How to proceed ?

**Comment by jeffpaul** [comment]
I've got Dutch translation files from Geert van der Heide <info@geertvanderheide.nl>, so it would be good to finally settle how we handle shipping translations for Distribution.  @helen any thoughts/preference on how this is managed outside of WordPress.org's TranslatePress functionality?

**Comment by dinhtungdu** [comment]
@jeffpaul @helen We can still ship the translations through new releases (I know it's not an optimal way) if we don't have any better solution.

**Comment by jeffpaul** [comment]
@peterwilsoncc curious if you're seen any good examples for how to handle translations for plugins that are not released on WP.org (and thus aren't able to take advantage of the translate.wordpress.org language packs)?

**Comment by peterwilsoncc** [comment]
@jeffpaul I know of [wearerequired/traduttore](https://github.com/wearerequired/traduttore) which sets up a translation interface similar to translate.wordpress.org but I've not used it. It seems fairly actively developed.

**Comment by peterwilsoncc** [comment]
> We can still ship the translations through new releases (I know it's not an optimal way) if we don't have any better solution.

My inclination is to go down this path for now to avoid perfect being the enemy of the good.

**Comment by jeffpaul** [comment]
@peterwilsoncc I think my only concern there is if a new release adjusts where the strings are located wouldn't the translation files be inaccurate and not actually render the translated text as expected?

**Comment by peterwilsoncc** [comment]
@jeffpaul Sorry, I am a little unclear what you mean. Are you referring to the strings being relocated within the plugin, the location of the translation files changing or something else?

**Comment by jeffpaul** [comment]
@peterwilsoncc talking about the strings being relocated within the plugin

**Comment by peterwilsoncc** [comment]
@jeffpaul I don't think that will be a problem, I think the line number references are translatior comments rather used by the files. I tested relocating `Howdy, %s` on an EN_AU install and the translation to `G'day, %s` continued working.

**Comment by peterwilsoncc** [comment]
I tested [wearerequired/traduttore](https://github.com/wearerequired/traduttore) locally and I think it could provide a suitable interface. 

As the french translation provided in this original issue are out of date, there's about 40 strings missing, I will move this ticket off the 1.7.0 release as there are no up-to-date translations to include.

I think it would be a poorer experience for 15% of the strings to be untranlated.
