### ISSUE TITLE
Update Application Passwords handling for WordPress 5.6

### ISSUE THREAD

**Issue by jeffpaul** [10up/distributor#661]
**Is your enhancement related to a problem? Please describe.**
When [WordPress 5.6](https://make.wordpress.org/core/5-6/) is released, currently scheduled for 8 December 2020, we will want to handle for the scenario where [Application Passwords](https://github.com/WordPress/application-passwords) is now [available in WordPress core](https://make.wordpress.org/core/2020/09/23/proposal-rest-api-authentication-application-passwords/) as it was [merged](https://github.com/WordPress/wordpress-develop/commit/1856d0fe2ad01b53daaf8338a4250088367ac948) as part of the [5.6 Beta 1 release](https://wordpress.org/news/2020/10/wordpress-5-6-beta-1/).

**Describe the solution you'd like**
This issue will help us track discussion on how best to handle for this scenario

**Designs**

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by jeffpaul** [comment]
Related: https://make.wordpress.org/core/2020/11/05/application-passwords-integration-guide/

**Comment by geertvdheide1** [comment]
I'm just a new user of this plugin, but isn't this issue urgent by now? WP 5.6 is scheduled to be released in a few days. Will everything continue to work on Wordpress 5.6? Won't the plugin at least need a check to see if the Application Password class already exists (from native WP) and use that if it does?

Also, the settings screen of the plugin still recommends installing Application Passwords as a separate plugin, while it's actually provided with Distributor. Trying to activate the separate plugin of course throws a fatal error because the class is already defined. This is out of date and should no longer be recommended. This point could be fixed together with any changes surrounding Application Passwords needed for WP 5.6.

**Comment by jeffpaul** [comment]
Just tested on a new WP 5.6 RC4 install, installed and activated Distributor 1.6.1, and the `User Profile` now presents two `Application Passwords` sections:
<img width="1255" alt="Screen Shot 2020-12-06 at 9 33 31 PM" src="https://user-images.githubusercontent.com/2818133/101306525-c15f2a80-380a-11eb-83ec-e53ceb9d8ccd.png">

On a network install, with a preexisting External Connection, it similarly duplicates the `Application Passwords` section in the `User Profile` and also duplicates the reference to the external connection:
![Screen Shot 2020-12-06 at 22 00 24-fullpage](https://user-images.githubusercontent.com/2818133/101308148-cb832800-380e-11eb-90bb-b146afb39f1e.png)

The network site was able to still distribute to internal and external connections, the remote site was able to distribute back to the origin site in the network as well.  So all Distributor functionality appears to work as expected, though there's definitely a case where some confusion will arise from the duplicate `Application Passwords` sections in the `User Profile`.

**Comment by jeffpaul** [comment]
As @geertvdheide1 notes, we'll likely want to update our docs at https://github.com/10up/distributor#setup-external-connections-using-application-passwords to reference this will only be necessary on WP versions before 5.6 as from 5.6 onwards Application Passwords will come bundled with WP core.

**Comment by jeffpaul** [comment]
Noting that when trying to use the `Application Passwords` section `Revoke` button, that only the first section works to actually revoke while the second instance of the section does nothing upon clicking the `Revoke` button.

**Comment by jeffpaul** [comment]
Noting that I still need to test Pulling content and creating a new External Connection.

**Comment by dinhtungdu** [comment]
Auth Wizard is not working with Application Password in core. A fix is in progress.
