### ISSUE TITLE
The directory structure of the update is incorrect. All files should be inside a directory named distributor, not at the root of the ZIP archive.

### ISSUE THREAD

**Issue by sebastienserre** [10up/distributor#670]
Hello,

On WP 5.5.3 it's impossible to update to Distributor 1.6.1
![distributor](https://user-images.githubusercontent.com/3902621/99849027-1a785e80-2b7b-11eb-82ba-3cb33823e2ed.png)

**Comment by helen** [comment]
@sebastienserre Hmm sorry about that, I used `git archive` but I wonder if I should have been doing it from a directory up. I've regenerated a ZIP, can you try again and let me know if that works?

**Comment by sebastienserre** [comment]
Thank you, @helen, It has been updated automatically now.
