### ISSUE TITLE
Possible timeout

### ISSUE THREAD

**Issue by vlastaw** [10up/distributor#671]
Hi, I have 70+ websites (our organisations branches) to distribute to. Problem is their websites have less visitors and often get flushed from webserver cache, therefore it takes a lot of time for them to first-load. Even though I named them in groups like Group1-Group5 by 12 websites, I still suspect Distributor to time out while distributing. On each distribute it only sends the content to a few websites in the group. I have to manually find those not served and try again. I am pretty sure that this is not happening because of PHP max_execution_time, which I have 300. It probably times out while waiting for an individual server or has an internal time limit for the whole batch. Would it please be possible to describe how Distributor works while batch-distributing (unfortunately I can't read that from source code) and maybe tweak its behavior to wait longer? Maybe some progress monitor in WP Admin would be nice (list of servers successfuly distributed and number of servers succesfuly distributed in a batch)? Thank you a lot. In the meantime we will try to set up an uptime monitor for our branches to keep their websites from being flushed and therefore to shorten the response time.

**Comment by jeffpaul** [comment]
@vlastaw have you updated to Distributor 1.6.1?  It includes error reporting that may help further identify what the root cause is of your issue.

**Comment by vlastaw** [comment]
Hi, yes, 1.6.1. How do I enable and find the error reporting? Tried WP's debug.log, but nothing is written in there by Distributor. Tried to increase dt_push_post_timeout directly in WordPressExternalConnection.php to 450, but no change. I guess editing it in WordPressExternalConnection should have worked, right? In case not, could you please write for me the exact line to put to functions.php? Unfortunately WordPress is a little deviation from .NET apps I usually use. Distributing to two sites works OK (and ends with There were some issues distributing the post.) Distributing to 12 only distributes to some (in order) or even none sites and also ends with the same error. Thank you for any solution.

**Comment by vlastaw** [comment]
OK, I did some dirty work and changed all integers for $timeout to 60. Namely line 303 in subscriptions.php and lines 57 and 616 in WordPressExternalConnection.php. Suspect the first one actually was the one that caused my distribution to work OK.

**Comment by dkotter** [comment]
@vlastaw Glad you were able to get things working.

I would guess it was updating the timeout value in `WordPressExternalConnection.php`, as this is what will fire when initially distributing an item. The timeout value in `subscriptions.php` is used when pushing updates to an already existing distributed item (which would more than likely have the same issue, so updating both of those is good).

For reference for anyone that reads this in the future, both of those values can be updated via a filter call, `dt_push_post_timeout` and `dt_subscription_post_timeout` respectively. The former has a default of 45, the latter has a default of 5.
