### ISSUE TITLE
Change from subdomain to domain after distribution

### ISSUE THREAD

**Issue by madriverweb** [10up/distributor#674]
If during development the multisite subsites are set up as subdomains, and once launched we change the site addresses (URLs) of the subsites to their domain names (and redirect the subdomains to the domains on the hosting platform), will this cause any problem with the posts that have already been distributed?

**Comment by dinhtungdu** [comment]
> will this cause any problem with the posts that have already been distributed?

Distributed posts should continue working because for Network connections, Distributor use site ID to distribute post.

**Comment by madriverweb** [comment]
Thank you!
