### ISSUE TITLE
Can Distributor recognize custom posts created by plugins other than ACF?

### ISSUE THREAD

**Issue by madriverweb** [10up/distributor#675]
For an subsite of a multisite, can Distributor recognize custom post types that are set up by other plugins (such as Genesis Testimonial Slider) rather than only by ACF?

**Comment by jeffpaul** [comment]
@madriverweb yes, as noted in the [Known Caveats/Issues](https://github.com/10up/distributor#known-caveatsissues) section of the readme, this is enabled by default for multisite and for separate instances the CPT needs to be registered with the REST API:
> **Custom Post Type Support** - Internal Connections (multisite) support multiple post types. In order for distribution to work with External Connections that have custom post type content, that post type needs to be registered with the argument `show_in_rest => true` on the external site.
