### ISSUE TITLE
Duplicate content ?

### ISSUE THREAD

**Issue by Dirpyth** [10up/distributor#686]
Thank you very much for this plugin.

I just have one question :
I have installed multisite WP (subdirectories). My main site is www.web.com and another site www.web.com/blogs.

I have created a page www.web.com/blogs/page1 -  I have pulled this page into www.web.com/page1.

My question : Is it a **duplicate content** as we have the same content with 2 different URLs? 
2 pages are indexed, or only the main page? Can I restrict direct access to www.web.com/blogs/page1? 

Looking forward to hearing from you. Thanks.

**Comment by dkotter** [comment]
@Dirpyth Thanks for the question. Distributor does make use of canonical URLs (see https://github.com/10up/distributor#known-caveatsissues) so in your scenario, www.web.com/page1 will have a canonical URL that points to www.web.com/blogs/page1. This lets search engines know that even though these pages may have the same content, one page is the source (www.web.com/blogs/page1) and should be treated as such, which removes any concern around duplicate content.

For your second question:

> Can I restrict direct access to www.web.com/blogs/page1?

There's nothing in Distributor that could do this but if you wanted to restrict access to that page through other means, you can do that. Though to my first point, the canonical URL on www.web.com/page1 will point to www.web.com/blogs/page1, so you probably don't want to restrict access to that page or search engines won't be able to index it properly.

If you want to restrict access to the original content, in that case you'd want to ensure the canonical doesn't point to the original but points to the distributed item, in this case www.web.com/page1. To accomplish this, you'll need to write some custom code that removes the canonical filters Distributor adds.
