### ISSUE TITLE
External Connection  Authorization Process Error

### ISSUE THREAD

**Issue by anilpainuly121** [10up/distributor#687]
I am trying to connect external website via authorize connection process but this process halted at " Yes I approve the connection" button.
This button greyed out after pressing it and site not redirected back to main site. it halted there.

and this is happening with many sites.

Please help.
Regards
Anil

**Comment by jeffpaul** [comment]
@anilpainuly121 can you confirm the WordPress and Distributor versions on the sites you're trying to connect together?

**Comment by anilpainuly121** [comment]
Hi. Wordpress is latest updated version 5.6
And distributor is 1.6.1.

I also did troubleshooting with uninstalling other plugins and themes.

But no luck yet

**Comment by dinhtungdu** [comment]
@anilpainuly121 In 5.6, Application Passwords was merged into the WordPress core, and it breaks the Auth Wizard feature of Distributor (which relies on Application Passwords). We acknowledge the bug and are working on the solution. You can track the progress in #682 (which continues #676 and #681).
