### ISSUE TITLE
Remove posts from skipped and pull posts again. 

### ISSUE THREAD

**Issue by emisrw** [10up/distributor#690]
Removed distributed posts are in skipped tab. I tried to push from parent site but the posts didn't show up (tried as draft and normally). Is any another option ? Can I remove manually from database ?

**Comment by andrew-dixon** [comment]
@emisrw Just had this same issue, you can edit the `dt_sync_log` under the `options` table for the site you are attempting to pull to, e.g. `wp_2_options`, etc... I just needed to clear the whole list and start again, so I just set the `option_value` to an empty string. There is also an issue to fix this here: #638

**Comment by jeffpaul** [comment]
Thanks @andrew-dixon, and yes @emisrw we've got this covered in #638 so I'd recommend subscribing to updates on that issue to see when that becomes available in Distributor... thanks!

**Comment by jeffpaul** [comment]
@emisrw @andrew-dixon note that this will be feasible with the pending 1.6.3 release.
