### ISSUE TITLE
Can't verify connection, can pull but can't push

### ISSUE THREAD

**Issue by dfardon** [10up/distributor#691]
**Describe the bug**
With two Wordpress installs on separate domains but on the same server, I have attempted to connect "mainsite" with "remotesite". I have created an Application password for the admin user on "remotesite" and then run the setup wizard on "mainsite" but can not get the connection verified. I have done the same thing using manual setup with the same result. 

"Mainsite" can now pull from "remotesite" but is not able to push content to "remotesite" (which is what I wanted to do). 

The error message I get is:

Limited connection established.

    Authentication failed due to invalid credentials.
    Push distribution unavailable.
    Pull distribution limited to basic content, i.e. title and content body.

**Expected behavior**
Mainsite to be able to push content to remotesite

**Screenshots**

**Environment information**

 - WordPress version: 5.6 on both sites
 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

`
### wp-core ###

version: 5.6
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: undefined
environment_type: production
user_count: 3
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/luxuryvillasdubr/public_html
wordpress_size: 73.02 MB (76561798 bytes)
uploads_path: /home/luxuryvillasdubr/public_html/wp-content/uploads
uploads_size: 208.57 MB (218696775 bytes)
themes_path: /home/luxuryvillasdubr/public_html/wp-content/themes
themes_size: 16.85 MB (17665694 bytes)
plugins_path: /home/luxuryvillasdubr/public_html/wp-content/plugins
plugins_size: 114.96 MB (120547419 bytes)
database_size: 51.29 MB (53776802 bytes)
total_size: 464.68 MB (487248488 bytes)

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: OceanWP (oceanwp)
version: 2.0.2
author: Nick
author_website: https://oceanwp.org/about-me/
parent_theme: none
theme_features: core-block-patterns, align-wide, wp-block-styles, responsive-embeds, editor-styles, editor-style, menus, post-formats, title-tag, automatic-feed-links, post-thumbnails, custom-header, custom-logo, html5, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, customize-selective-refresh-widgets, widgets
theme_path: /home/luxuryvillasdubr/public_html/wp-content/themes/oceanwp
auto_update: Enabled

### wp-themes-inactive (1) ###

Twenty Twenty-One: version: 1.1, author: the WordPress team, Auto-updates disabled

### wp-mu-plugins (1) ###

installatron_hide_status_test.php: author: (undefined), version: (undefined)

### wp-plugins-active (23) ###

a3 Lazy Load: version: 2.4.3, author: a3rev Software, Auto-updates disabled
AddToAny Share Buttons: version: 1.7.42, author: AddToAny, Auto-updates enabled
Advanced Editor Tools (previously TinyMCE Advanced): version: 5.6.0, author: Automattic, Auto-updates enabled
All-in-One WP Migration: version: 7.32, author: ServMask, Auto-updates enabled
All-in-One WP Migration Google Drive Extension: version: 2.62, author: ServMask, Auto-updates enabled
Autoptimize: version: 2.8.1, author: Frank Goossens (futtta), Auto-updates enabled
Better Search Replace: version: 1.3.4, author: Delicious Brains, Auto-updates enabled
Classic Editor: version: 1.6, author: WordPress Contributors, Auto-updates enabled
Cookie Notice: version: 1.3.2, author: dFactory, Auto-updates enabled
Distributor: version: 1.6.1, author: 10up Inc., Auto-updates disabled
Elementor: version: 3.0.16, author: Elementor.com, Auto-updates enabled
Form Maker: version: 1.13.49, author: 10Web Form Builder Team, Auto-updates enabled
Google Analytics for WordPress by MonsterInsights: version: 7.14.0, author: MonsterInsights, Auto-updates enabled
Ocean Extra: version: 1.6.9, author: OceanWP, Auto-updates enabled
Post Duplicator: version: 2.22, author: Metaphor Creations, Auto-updates enabled
Really Simple SSL: version: 4.0.5, author: Really Simple Plugins, Auto-updates enabled
Responsive Lightbox & Gallery: version: 2.3.1, author: dFactory, Auto-updates enabled
ShortPixel Image Optimizer: version: 4.21.1, author: ShortPixel, Auto-updates enabled
Smart Slider 3: version: 3.4.1.14, author: Nextend, Auto-updates enabled
Sticky Side Buttons: version: 1.0.9, author: Maeve Lander, Auto-updates enabled
Wordfence Security: version: 7.4.14, author: Wordfence, Auto-updates enabled
WP Super Cache: version: 1.7.1, author: Automattic, Auto-updates enabled
Yoast SEO: version: 15.5, author: Team Yoast, Auto-updates enabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 1024M
upload_max_filesize: 1024M
max_effective_size: 1 GB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.25

### wp-server ###

server_architecture: Linux 3.10.0-1062.4.3.el7.x86_64 x86_64
httpd_software: nginx/1.15.12
php_version: 7.2.34 64bit
php_sapi: fpm-fcgi
max_input_variables: 100000
time_limit: 300
memory_limit: 256M
max_input_time: 600
upload_max_filesize: 1024M
php_post_max_size: 1024M
curl_version: 7.74.0 OpenSSL/1.1.1i
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.32
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/luxuryvillasdubr/public_html/wp-content
WP_PLUGIN_DIR: /home/luxuryvillasdubr/public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### distributor ###

0: 1.6.1
1: Yes
2: dfardon@yahoo.com
3: 
	Override Author Byline: Yes
	Media Handling: Featured image and attached images
4: N/A
5: 
	Villa Ella: 
- URL: https://www.villaelladubrovnik.com/wp-json
- Version: 1.6.1
- Status: warning
- Auth method: Username / Password
- Username: rmgve
- Roles Allowed to Push: administrator
- Additional data: {"errors":[], "can_post":[], "can_get":["post", "page", "attachment", "wp_block", "portfolio"], "endpoint_suggestion":false, "is_authenticated":"no"}

`
**Additional context**

**Comment by jeffpaul** [comment]
@dfardon are you seeing any browser console errors on your "mainsite" or "remotesite"?  From the error message you shared, it sounds like the Application Password set up did not complete successfully from "mainsite" to "remotesite".  Assuming you utilized the setup wizard, did you run into any errors or have issues in completing that process?

**Comment by dfardon** [comment]
Hi Jeff, No related console errors on either site in normal use.

When I run the setup wizard, all is fine to the point where I click the "Yes I approve of this connection" button, at which point the button becomes greyed out and nothing further happens. At this point I see the following console error:

Uncaught TypeError: a is undefined
    <anonymous> https://www.villaelladubrovnik.com/wp-admin/js/auth-app.min.js?ver=5.6:2
    jQuery 2
        dispatch
        handle

**Comment by dkotter** [comment]
@dfardon Thanks for the bug report. This sounds like the same issue reported on #689. Feel free to read my latest comment there for full details but the short version is there's a conflict between the version of Application Passwords Distributor loads and the new version that WordPress 5.6 now loads by default. We have some fixes we're working on to address this that will hopefully be released soon, but there is a work around to manually set up connections in the mean time that I detailed on that other ticket.

**Comment by dfardon** [comment]
@dkotter Thanks for the help, I tried manual authentication before when the automatic connection failed and had no joy. However, I have deleted any existing connections and tried again and now I have successfully connected mainsite to two remote sites, with the green button for each that shows connection is established.
However, having published a test post and tried to push it to the remote sites, I get the error message "There were some issues distributing the post. ". 
All usernames belong to Administrators so there should be no problem with permissions. 
Is there a debug log I can post up here for you, or a detailed error message?

**Comment by jeffpaul** [comment]
@dfardon we're in the process of finishing up a 1.6.2 release that should resolve this, I'll report back here when that's ready for you to update and test again.  I appreciate your feedback and patience, thanks!

**Comment by dkotter** [comment]
@dfardon If the connection is set up correctly now, there should be no issue with permissions. One of the other big things we often see is issues with remove request timeouts, since all the data is being sent remotely when distributing to external connections (see https://github.com/10up/distributor#known-caveatsissues).

If you open the browser console while distribution is happening, do you see any errors there? You can also inspect the request in the Network tab of the console to see if that provides any information.

**Comment by dfardon** [comment]
@dkotter I don't expect it's a timeout issue, I'm just trying to push a simple post with 200 words of text, and a featured image, nothing more than that. 

I see the following error in the browser console when distribution fails and the error message displays:

Uncaught TypeError: T is null
    C push.js:122
    <anonymous> push.js:179
    setTimeout handler* push.js:381
    jQuery 7
    <anonymous> push.js:375
    jQuery 2
        dispatch
        handle

**Comment by jeffpaul** [comment]
@dfardon we pushed our version 1.6.2 yesterday, please see if that helps resolve your issue... thanks!

**Comment by dfardon** [comment]
@jeffpaul Thanks Jeff, I've updated all sites to 1.6.2 and also discovered that the Wordfence firewall blocks Application Passwords by default - why I was still able to set them up I'm not sure, but I've now enabled them and can now connect the sites automatically. 
However, pushing posts still failed until I tried disabling Wordfence entirely, which fixes the problem. I'll look further into it over the next day or two and let you know what config needs to be applied so that Wordfence can be active but pushing posts is still succesful.

**Comment by jeffpaul** [comment]
@dfardon I've definitely seen multiple plugins have issues with Wordfence aggressively blocking (for good reason on the security side, but you need to find the balance where things are blocked but not for core plugin needs).  I believe Wordfence has the ability to see all its settings somewhere, you might check to see if it's blocking something with the REST API as that's my best guess for now.

**Comment by dfardon** [comment]
@jeffpaul Sorted, by identifying the push attempt in the Live Traffic log in Wordfence on the remote sites, I've been able to add the IP to the Firewall Allowlist and posting now works. Thanks very much for your help. Have a good weekend!

**Comment by jeffpaul** [comment]
That's great to hear @dfardon!  I'm going to close this issue as it sounds like you're all set.  If anything else crops up, please let us know.
