### ISSUE TITLE
Working with Custom Fields Plugin

### ISSUE THREAD

**Issue by jmichiels01** [10up/distributor#692]
I am using the [Advanced Custom Fields plugin](https://www.advancedcustomfields.com/) to add an additional image to my posts. While the image is copied to the destination site, the image is not associated with the post. In order to add the secondary image, I have to unlink it from the original post. is there a way to ensure data in custom fields are passed over and linked appropriately?

**Comment by jeffpaul** [comment]
@jmichiels01 we have a similar report of image issues with ACF (see #381) and have assigned all ACF-related issues to the 2.1.0 milestone to try and resolve together within that release.  Note that 2.1.0 is not in the near future, so if this is of particular urgent or important need for you then please reach out to me directly (jeff.paul@10up.com) and we can look into alternate options for you... thanks!

**Comment by jeffpaul** [comment]
Closing in favor of #81.
