### ISSUE TITLE
Unable to connect to site. The external site is private or not a WordPress site. (rest_api_uri_not_found)

### ISSUE THREAD

**Issue by anilpainuly121** [10up/distributor#698]
Unable to connect to site. The external site is private or not a WordPress site. (rest_api_uri_not_found)

 I am getting this error during connection process.
Wordpress 5.6
Application password
Distributor 1.6.2

**Comment by jeffpaul** [comment]
@anilpainuly121 are you using the Authorize Connection wizard or the Manually Set Up Connection process?  Is the site you're trying to connect blocking access to the REST API perhaps?

**Comment by dkotter** [comment]
@anilpainuly121 That error will happen if Distributor can't determine what the REST API URL should be for the site it is connecting too.

We try to figure that out by making a request to the site and parsing out the `<link>` tags, looking for the tag that has the API URL in it. This should be a tag that looks like this: `<link rel='https://api.w.org/' href='http://example.com/wp-json/' />`

If that tag isn't found, we then return that error message, as we can't connect to the site without knowing that URL.

It is possible for that `<link>` tag to be disabled. Do you happen to know if that is something that was done on the site you're connecting to?

**Comment by anilpainuly121** [comment]
Thanks @dkotter for UPdate, This line of code is visible in view source of Page,..  tried "Rest API Log"  plugins to show logs, which is showing the incoming connection in remote site. 
but not able to figure out what is refusing connection...

**Comment by dkotter** [comment]
@anilpainuly121 Hmm.. that's weird it isn't working if that line of code is there. If possible, can you share with me the URL of the site you're trying to connect to so I can take a look? You can email that to me at darin.kotter@10up.com so you don't have to post that publicly here.

**Comment by anilpainuly121** [comment]
Hi, @dkotter i shared the url vi email.

Thanks & Regards
Anil

**Comment by nishchint** [comment]
Hi There, 

I am facing the same issue. Do we have solution for the same? 

Thank you so much. 

Regards, 
Nishchint

**Comment by jeffpaul** [comment]
@nishchint can you please provide details on your set up?  Are you running a multisite or multiple WordPress instances?  What WordPress and Distributor version are you running?  Are you running any security plugins that may be blocking access to the REST API?
