### ISSUE TITLE
Restoring link to original changes published date

### ISSUE THREAD

**Issue by madriverweb** [10up/distributor#700]
Restoring link to original changes published date in sub-site of a multi-site

**Steps to Reproduce**

Create a post in the main site.
Push it to sub-sites.
Open it in sub-site, unlink from original (date remains).
Relink to original, date changes to current time.

**Expected behavior**
It would seem sensible to reflect the date the original was published, for accuracy. The downside of having it change is the posts are then out of order. This may not be a common occurrence except that I unlinked a bunch while testing and learning the plugin so I had to go back into each and manually update the published date.

**Environment information**
 - Device: Dell desktop
 - OS: W10
 - Browser and version: Firefox 84.0.2 (64-bit)
 - WordPress version: 5.5.3
 
`
### wp-core ###

version: 5.5.3
site_language: en_US
user_language: en_US
timezone: America/New_York
permalink: /%postname%/
https_status: true
multisite: true
user_registration: false
blog_public: 0
default_comment_status: closed
environment_type: production
user_count: 3
site_count: 8
network_count: 1
dotorg_communication: true

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: Reinhardt (reinhardt) NOTE: The theme is a custom version of Hello Pro 3.
version: 3.0.4.0.1
author of mod: MadRiverWeb
original author_website: https://thebrandid.com/
parent_theme: Genesis (genesis)
theme_features: core-block-patterns, menus, post-thumbnails, title-tag, automatic-feed-links, body-open, genesis-inpost-layouts, genesis-archive-layouts, genesis-admin-menu, genesis-seo-settings-menu, genesis-import-export-menu, genesis-readme-menu, genesis-customizer-theme-settings, genesis-customizer-seo-settings, genesis-auto-updates, genesis-breadcrumbs, genesis-menus, genesis-structural-wraps, widgets, custom-logo, html5, genesis-accessibility, genesis-after-entry-widget-area, genesis-footer-widgets, editor-styles, editor-style, align-wide, responsive-embeds, editor-color-palette, editor-font-sizes
theme_path: /nas/content/live/reinhardtcorp/wp-content/themes/reinhardt
auto_update: Auto-updates are not available for this theme.
genesis_recommendations: This theme uses theme supports that are no longer required in Genesis: "404-page" no longer required in "genesis-accessibility" theme support array

### wp-parent-theme ###

name: Genesis (genesis)
version: 3.3.3
author: StudioPress
author_website: https://www.studiopress.com/
theme_path: /nas/content/live/reinhardtcorp/wp-content/themes/genesis
auto_update: Enable update checks at Appearance → Customize → Theme Settings → Updates.

### wp-themes-inactive (6) ###

Essence Pro: version: 1.4.0, author: StudioPress,Auto-updates are not available for this theme.
Genesis Sample: version: 3.4.0, author: StudioPress,Auto-updates are not available for this theme.
Hello! Pro 3: version: 3.0.4, author: brandiD,Auto-updates are not available for this theme.
Infinity Pro: version: 1.3.2, author: StudioPress,Auto-updates are not available for this theme.
Showcase Pro: version: 2.0.2, author: Bloom,Auto-updates are not available for this theme.
Studio Pro: version: 2.3.0, author: SEO Themes,Auto-updates are not available for this theme.

### wp-mu-plugins (4) ###

Force Strong Passwords - WPE Edition: version: 1.6.4, author: Jason Cosper
WP Engine Seamless Login Plugin: version: 1.5.5, author: WP Engine
WP Engine Security Auditor: version: 1.0.9, author: wpengine
WP Engine System: version: 4.1.0, author: WP Engine

### wp-plugins-active (15) ###

Advanced Custom Fields: version: 5.9.3, author: Elliot Condon (latest version: 5.9.4), Auto-updates disabled
Better Font Awesome: version: 1.7.4, author: Mickey Kay, Auto-updates disabled
Classic Editor: version: 1.6, author: WordPress Contributors, Auto-updates disabled
Custom Post Type UI: version: 1.8.1, author: WebDevStudios (latest version: 1.8.2), Auto-updates disabled
Distributor: version: 1.6.1, author: 10up Inc. (latest version: 1.6.2), Auto-updates disabled
Genesis Blocks: version: 1.2.1, author: StudioPress, Auto-updates disabled
Genesis Custom Blocks: version: 1.0.3, author: Genesis Custom Blocks, Auto-updates disabled
Genesis Responsive Slider: version: 1.0.1, author: StudioPress, Auto-updates disabled
Genesis Testimonial Slider: version: 1.5, author: Frank Schrijvers, WPStudio, Auto-updates disabled
Gravity Forms: version: 2.4.22, author: Gravity Forms, Auto-updates enabled
MetaSlider: version: 3.19.1, author: MetaSlider (latest version: 3.20.0), Auto-updates disabled
Multisite Enhancements: version: 1.5.4, author: Frank Bültge (latest version: 1.6.1), Auto-updates disabled
SEO Slider: version: 1.1.0, author: SEO Themes, Auto-updates disabled
Simple History: version: 2.38.0, author: Pär Thernström, Auto-updates disabled
WPFront Scroll Top: version: 2.0.2, author: Syam Mohan, Auto-updates disabled

### wp-plugins-inactive (3) ###

Block Visibility: version: 1.2.0, author: Nick Diego (latest version: 1.4.2), Auto-updates disabled
CoBlocks: version: 2.5.3, author: GoDaddy (latest version: 2.6.0), Auto-updates disabled
Post Carousel: version: 2.1.13, author: ShapedPlugin (latest version: 2.2.4), Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1687
imagemagick_version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
file_uploads: File uploads is turned off
post_max_size: 100M
upload_max_filesize: 50M
max_effective_size: 50 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 38 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 6144
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
gd_version: 2.2.5
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 5.3.0-1018-gcp x86_64
httpd_software: Apache
php_version: 7.4.13 64bit
php_sapi: apache2handler
max_input_variables: 10000
time_limit: 3600
memory_limit: 512M
max_input_time: 3600
upload_max_filesize: 50M
php_post_max_size: 100M
curl_version: 7.58.0 OpenSSL/1.1.1
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.7.31-34-log
client_version: mysqlnd 7.4.13

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /nas/content/live/reinhardtcorp/wp-content
WP_PLUGIN_DIR: /nas/content/live/reinhardtcorp/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: utf8_unicode_ci

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### genesis ###

theme_version: 3.3.3
db_version: 3301
upgrade: 1
blog_cat_num: 5
breadcrumb_posts_page: true
breadcrumb_single: true
breadcrumb_page: true
breadcrumb_archive: true
content_archive: full
content_archive_limit: 300
content_archive_thumbnail: true
entry_meta_after_content: [post_categories] [post_tags]
entry_meta_before_content: [post_date] by [post_author_posts_link] [post_comments] [post_edit]
image_size: thumbnail
image_alignment: alignleft
posts_nav: prev-next
site_layout: content-sidebar
show_featured_image_post: true
avatar_size: 48
footer_text: <img src="http://reinhardtcorp.wpengine.com/wp-content/uploads/warm-cool.png">

### distributor ###

0: 1.6.1
1: 
	Override Author Byline: Yes
	Media Handling: Featured image and attached images
2: 
	Reinhardt Home Heating: 
- Blog ID: 2
- URL: http://rhh.reinhardtcorp.wpengine.com
- Registered: 2020-11-27 15:48:34
- Last updated: 2021-01-21 21:24:19
	Reese Marshall: 
- Blog ID: 3
- URL: http://reese.reinhardtcorp.wpengine.com
- Registered: 2020-11-27 15:49:43
- Last updated: 2021-01-21 21:25:00
	Paul Oil & Propane: 
- Blog ID: 4
- URL: http://paul.reinhardtcorp.wpengine.com
- Registered: 2020-11-27 15:50:02
- Last updated: 2021-01-21 21:32:03
	S&D Petroleum: 
- Blog ID: 5
- URL: http://sd.reinhardtcorp.wpengine.com
- Registered: 2020-11-27 15:50:19
- Last updated: 2021-01-21 21:36:17
	Reinhardt Mini-Mart: 
- Blog ID: 6
- URL: http://rmm.reinhardtcorp.wpengine.com
- Registered: 2020-11-27 15:51:55
- Last updated: 2020-11-27 15:51:55
	The Center Mini-Mart: 
- Blog ID: 7
- URL: http://tc.reinhardtcorp.wpengine.com
- Registered: 2020-11-27 15:52:18
- Last updated: 2020-11-27 15:52:18
	S&D Mini-Mart: 
- Blog ID: 8
- URL: http://sdmm.reinhardtcorp.wpengine.com
- Registered: 2020-11-27 15:52:37
- Last updated: 2020-11-27 15:52:37
3: N/A

`

**Comment by madriverweb** [comment]
Commenting on my own issue: I just tested changing the published date on the original, actually just the time, to see if that would filter through. When updating the original, the timestamp on all the posts pushed to sub-sites changes to current time. Not ideal if someone is just correcting a typo and wants the posts to stay in the original timestamp order of when they were published. The current behavior results in having to edit each of the timestamps on posts pushed to sub-sites to reflect original published date.

**Comment by codiller** [comment]
I'm also having an issue where correcting a typo in a blog is changing the published time on the sub-site to the current time, triggering RSS feed emails twice. :(
