### ISSUE TITLE
Push Anomoly

### ISSUE THREAD

**Issue by SK-AusTX** [10up/distributor#704]
This is a very cool product and core functionality seems to work great.

1) On "Pull Content" page I do not see the selector (mentioned in the documentation) for pulling as "published."

2)  First pull was flawless.  Website to website (not networked).

3) Second push showed error: "...issues distributing post..."  Receiving website, when post was edited, showed page ghosted, "link banner" could not be removed, spinning disk on featured image.  When page was "unlinked" ghosting went away as did spinning disk.  Featured image was missing but could be added from media library (so it did import to website).

THANK YOU for your efforts!

S

![Distributor 2](https://user-images.githubusercontent.com/17478110/105618150-bb68dd00-5da9-11eb-8523-7322dfb32605.JPG)
).  

![Distributor 1](https://user-images.githubusercontent.com/17478110/105618043-c1aa8980-5da8-11eb-9d45-e5684b38cb5a.JPG)

**Environment information**
 - Device: Dell Workstation Win 10 Pro
 - OS: Win 10 Pro
 - Browser Firefox 8402
 - WordPress version: 5.6
`
### wp-core ###

version: 5.6
site_language: en_US
user_language: en_US
timezone: America/Chicago
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /ebs2/vhosts/texasredoubt.com/texasredoubt.com
wordpress_size: loading...
uploads_path: /ebs2/vhosts/texasredoubt.com/texasredoubt.com/wp-content/uploads
uploads_size: loading...
themes_path: /ebs2/vhosts/texasredoubt.com/texasredoubt.com/wp-content/themes
themes_size: loading...
plugins_path: /ebs2/vhosts/texasredoubt.com/texasredoubt.com/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-active-theme ###

name: Layers (layerswp)
version: 2.0.10
author: Obox
author_website: http://www.oboxthemes.com/
parent_theme: none
theme_features: core-block-patterns, post-thumbnails, html5, title-tag, widget-customizer, woocommerce, custom-logo, automatic-feed-links, menus, customize-selective-refresh-widgets, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, widgets
theme_path: /ebs2/vhosts/texasredoubt.com/texasredoubt.com/wp-content/themes/layerswp

### wp-themes-inactive (3) ###

Deli: version: 2.0.15, author: WooCommerce
Storefront: version: 3.3.0, author: Automattic
Twenty Twenty-One: version: 1.1, author: the WordPress team

### wp-plugins-active (31) ###

ActiveCampaign: version: 8.1.4, author: ActiveCampaign
Akismet Anti-Spam: version: 4.1.8, author: Automattic
Broken Link Checker: version: 1.11.15, author: WPMU DEV
Compress JPEG & PNG images: version: 3.2.1, author: TinyPNG
Distributor: version: 1.6.2, author: 10up Inc.
Elementor: version: 3.0.16, author: Elementor.com
ElementsKit Lite: version: 2.1.2, author: Wpmet
ElementsKit Pro: version: 2.1.3, author: Wpmet
Facebook for WooCommerce: version: 2.2.0, author: Facebook
Facebook for WordPress: version: 3.0.0, author: Facebook
Google Tag Manager: version: 1.0.3, author: George Stephanis
Gravity Forms: version: 2.4.21, author: Gravity Forms
Jetpack by WordPress.com: version: 9.3.1, author: Automattic
Layers - Updater: version: 1.4, author: Marc Perel
Layers Pro - Extended Layers customizability: version: 2.0.1, author: Obox
Master Slider Pro: version: 3.4.7, author: averta
Really Simple SSL: version: 4.0.6, author: Really Simple Plugins
reCAPTCHA: version: 1.6, author: Ash Matadeen
Revision Control: version: 2.3.2, author: Dion Hulse
Site Kit by Google: version: 1.24.0, author: Google
Smash Balloon Custom Facebook Feed: version: 2.18.1, author: Smash Balloon
SSL Insecure Content Fixer: version: 2.7.2, author: WebAware
UberMenu 3 - The Ultimate WordPress Mega Menu: version: 3.2.5, author: Chris Mavricos, SevenSpark
UpdraftPlus - Backup/Restore: version: 2.16.46.24, author: UpdraftPlus.Com, DavidAnderson
WooCommerce: version: 4.9.1, author: Automattic
WooCommerce Payments: version: 1.8.0, author: Automattic
WooCommerce PayPal Checkout Gateway: version: 2.1.1, author: WooCommerce
WooCommerce Shipping & Tax: version: 1.25.5, author: Automattic
Wordpress Hide Posts: version: 0.5.3, author: MartinCV
Yoast Duplicate Post: version: 4.0.2, author: Enrico Battocchi & Team Yoast
Yoast SEO Premium: version: 15.6.2, author: Team Yoast

### wp-plugins-inactive (6) ###

Blog Designer Pack: version: 2.2.5, author: InfornWeb
Event Organiser: version: 3.10.4, author: Stephen Harris
PDF Embedder Premium: version: 4.4.1, author: Lever Technology LLC
Redirection: version: 5.0, author: John Godley
Under Construction / Maintenance Mode From Acurax: version: 2.5.9, author: Acurax
W3 Total Cache: version: 2.1.0, author: BoldGrid

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-68 Q16 x86_64 2020-12-15 https://imagemagick.org
file_uploads: File uploads is turned off
post_max_size: 8M
upload_max_filesize: 32M
max_effective_size: 8 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 7 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 6144
	imagick::RESOURCETYPE_MAP: 7 GB
	imagick::RESOURCETYPE_MEMORY: 4 GB
	imagick::RESOURCETYPE_THREAD: 2
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 3.10.0-1062.12.1.el7.x86_64 x86_64
httpd_software: Apache
php_version: 7.4.14 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_filesize: 32M
php_post_max_size: 8M
curl_version: 7.29.0 NSS/3.53.1
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.2.36-MariaDB
client_version: mysqlnd 7.4.14

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /ebs2/vhosts/texasredoubt.com/texasredoubt.com/wp-content
WP_PLUGIN_DIR: /ebs2/vhosts/texasredoubt.com/texasredoubt.com/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### jetpack ###

site_id: 186492876
ssl_cert: No
time_diff: undefined
version_option: 9.3.1:1610673832
old_version: 9.3:1610643664
public: Public
master_user: #1 xxxxxxxxx
current_user: #1 xxxxxxxxxx
tokens_set: Blog User
blog_token: 9x)7xNZk8JqY^fy$U3WR2ZEAGxCSe2L4
user_token: 6FzPXX5a00^$*C$lTeDQIFm(eUk8Eegz
version: 9.3.1
jp_plugin_dir: /ebs2/vhosts/texasredoubt.com/texasredoubt.com/wp-content/plugins/jetpack/
plan: free
protect_header: {"trusted_header":"REMOTE_ADDR","segments":1,"reverse":false}
full_sync: {"started":"Thu, 01 Jan 1970 00:00:00 +0000","finished":"Thu, 01 Jan 1970 00:00:00 +0000","progress":[],"config":[]}
sync_size: 1
sync_lag: 0 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"https:\/\/texasredoubt.com","siteurl":"https:\/\/texasredoubt.com","WP_HOME":"","WP_SITEURL":""}
idc_error_option: false
idc_optin: true
cxn_tests: All Pass.

### google-site-kit ###

version: 1.24.0
php_version: 7.4.14
wp_version: 5.6
reference_url: https://texasredoubt.com
amp_mode: no
site_status: connected-site
user_status: authenticated
connected_user_count: 1
active_modules: site-verification, search-console, analytics, pagespeed-insights, tagmanager
required_scopes: 
	openid: ✅
	https://www.googleapis.com/auth/userinfo.profile: ✅
	https://www.googleapis.com/auth/userinfo.email: ✅
	https://www.googleapis.com/auth/siteverification: ✅
	https://www.googleapis.com/auth/webmasters: ✅
	https://www.googleapis.com/auth/analytics.readonly: ✅
	https://www.googleapis.com/auth/tagmanager.readonly: ✅
capabilities: 
	googlesitekit_authenticate: ✅
	googlesitekit_setup: ✅
	googlesitekit_view_posts_insights: ✅
	googlesitekit_view_dashboard: ✅
	googlesitekit_view_module_details: ✅
	googlesitekit_manage_options: ✅
	googlesitekit_publish_posts: ✅
search_console_property: https://texasredoubt.com/
analytics_account_id: 8495••••
analytics_property_id: UA-8495••••••
analytics_profile_id: 1306•••••
analytics_use_snippet: yes
tagmanager_account_id: 1141••••••
tagmanager_container_id: GTM-54J••••
tagmanager_amp_container_id: none
tagmanager_use_snippet: yes

### distributor ###

0: 1.6.2
1: Yes
2: xxxxxxxxxxxxxxxxxxxxx
3: 
	Override Author Byline: Yes
	Media Handling: Featured image and attached images
4: N/A
5: 
	The Fat Rancher: 
- URL: https://thefatrancher.com/wp-json/
- Version: 1.6.2
- Status: valid
- Auth method: Username / Password
- Username: The_Fat_Rancher
- Roles Allowed to Push: administrator, editor
- Additional data: {"errors":[], "can_post":["post", "page", "attachment", "wp_block"], "can_get":["post", "page", "attachment", "wp_block"], "endpoint_suggestion":false, "is_authenticated":"yes"}

**Comment by dkotter** [comment]
Thanks for the feedback @SK-AusTX 

> On "Pull Content" page I do not see the selector (mentioned in the documentation) for pulling as "published."

Can you point me to the documentation that says this so we can get this updated? There currently is no selector on the Pull screen to set the `post_status`. Unlike Pushing content, when pulling content, it will come in with the same status as the original with no way to change that. So if the original is published, the content you pull will also be published.

We do have a PR opened (#701) that adds a Draft checkbox that will allow you to Pull content in as a draft (same as how Pushing works). But for now, there is no selector to choose a 'published' status (or any status)

> Second push showed error: "...issues distributing post..." Receiving website, when post was edited, showed page ghosted, "link banner" could not be removed, spinning disk on featured image. When page was "unlinked" ghosting went away as did spinning disk. Featured image was missing but could be added from media library (so it did import to website).

This sounds like an error with distributing the featured image, which I'm assuming is why you got an error message. We do have plans in place to improve error messaging and handling across the plugin, making it easier to know what went wrong in the case of an error.

But yes, content that has been distributed can't be edited if it is linked, which is why you're seeing that "ghosting" feature. But as you found out, unlinking the content removes that and allows you to edit, though at that point, the two pieces of content are disconnected and any updates to the original won't propagate to the distributed version

**Comment by jeffpaul** [comment]
@SK-AusTX we're now on Distributor 1.6.4, have you tested to see if this issue is in fact resolved or are you still seeing this occur?

**Comment by SK-AusTX** [comment]
Thank you for following up.

I have installed the update but have not tested.  😉

I will do so and follow up with you.

Do you folks have an address for donations?

Spencer

**Comment by SK-AusTX** [comment]
Thank you so much for a cool product.  Here is what I found today with 1.6.4:

1) Received critical error page (see photo). However, page did pull.

2) Featured image did not pull and does not appear in media folder.  Work-around: Unlink page and manually add featured image.

3) (nit-pick) ASCII code for apostrophe displays instead of apostrophe.  Feature image loading icon spins.

4) Pulled the other direction and featured image pulled but not the embedded images.

Take it easy,
Spencer




![Featured Image but no post images](https://user-images.githubusercontent.com/17478110/118343616-abf3d800-b4ef-11eb-979c-584419c8b1a7.JPG)



![No Featured image in media folder](https://user-images.githubusercontent.com/17478110/118342759-73053480-b4ea-11eb-81c1-1ae9d163db6b.JPG)
 

![Cannot clear distributed from](https://user-images.githubusercontent.com/17478110/118342448-0ccbe200-b4e9-11eb-9286-3d6a5dbd5c6b.JPG)


![No Featured Imaage ](https://user-images.githubusercontent.com/17478110/118342370-aba40e80-b4e8-11eb-82dc-8e6a4746108e.JPG)
![Critical Error on Pull](https://user-images.githubusercontent.com/17478110/118342371-aba40e80-b4e8-11eb-9948-3ce48f5c60f9.JPG)
![No Featured Image Pulled Over](https://user-images.githubusercontent.com/17478110/118342372-ac3ca500-b4e8-11eb-9f96-62ee0f066d97.JPG)
![Push Website Version](https://user-images.githubusercontent.com/17478110/118342374-acd53b80-b4e8-11eb-8bfe-6810f49f1d59.JPG)
![Pull To Website Version](https://user-images.githubusercontent.com/17478110/118342375-acd53b80-b4e8-11eb-96bf-8a013eca1c8d.JPG)

**Comment by jeffpaul** [comment]
@SK-AusTX if those images are within a post created using Elementor, then that is a known issue in general with most page builders (see: #348).  On the apostrophe issue, can you confirm the process that post/page was pushed/pulled and whether Gutenberg is used on the receiving site?

**Comment by jeffpaul** [comment]
@SK-AusTX On the apostrophe issue, can you confirm the process that post/page was pushed/pulled and whether Gutenberg is used on the receiving site?
