### ISSUE TITLE
"Distributor" is not included in the Admin Bar on post

### ISSUE THREAD

**Issue by khiser** [10up/distributor#708]
Although the admin bar is visible, the "Distributor" is not showing as an option on the site that will be pushing content to the other.  (It shows up on the site that is to receive the content.

**Steps to Reproduce**
1. login
2. select a blog post
3. look at admiin bar and no "Distributor" is listed (the bar and other links is there though)

**Expected behavior**
I expected to see the "Distributor" link so I could push the post to another blog site.

**Screenshots**
<img width="1680" alt="Screen Shot 2021-01-25 at 5 48 42 PM" src="https://user-images.githubusercontent.com/77599/105775898-9dc87e80-5f35-11eb-9f86-96320b55b332.png">

**Environment information**
 - Device: Macbook
 - OS: MacOS 10.14.6
 - Browser and version: Chrome Version 87.0.4280.141
 - WordPress version: 5.6
 
`
### wp-core ###

version: 5.6
site_language: en_US
user_language: en_US
timezone: America/New_York
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 2
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /wordpress/core/5.6
wordpress_size: 49.51 MB (51918380 bytes)
uploads_path: /srv/htdocs/wp-content/uploads
uploads_size: 522.68 MB (548067789 bytes)
themes_path: /srv/htdocs/wp-content/themes
themes_size: 1.00 MB (1051977 bytes)
plugins_path: /srv/htdocs/wp-content/plugins
plugins_size: 146.47 MB (153583487 bytes)
database_size: 53.52 MB (56115200 bytes)
wpcomsh-disk-space-used: 647.4 MB
wpcomsh-disk-space-quota: 200.0 GB

### wp-dropins (2) ###

advanced-cache.php: true
object-cache.php: true

### wp-active-theme ###

name: Dynamic News (dynamic-news)
version: 1.1.3
author: ThemeZee
author_website: http://themezee.com
parent_theme: none
theme_features: core-block-patterns, post-thumbnails, automatic-feed-links, editor-style, custom-background, custom-header, menus, infinite-scroll, featured-content, jetpack-responsive-videos, align-wide, responsive-embeds, editor-color-palette, editor-font-sizes, print-style, widgets
theme_path: /wordpress/themes/premium/dynamic-news
auto_update: Updates managed by WordPress.com

### wp-mu-plugins (1) ###

WP.com Site Helper: author: (undefined), version: (undefined)

### wp-plugins-active (16) ###

AdSanity: version: 1.5, author: Pixel Jar (latest version: 1.7.2)
AdSanity - Custom Ad Sizes: version: 1.1, author: Pixel Jar
AdSanity - Image Cache Buster: version: 1.1, author: Pixel Jar
AdSanity - Ordered Ad Group Widget: version: 1.2, author: Pixel Jar
Ads on Content AMP Pages: version: 1.0, author: Alaa AbdelSamie
Advanced Ads: version: 1.23.2, author: Thomas Maier, Advanced Ads GmbH
Akismet Anti-Spam: version: 4.1.8, author: Automattic
AMP: version: 2.0.10, author: AMP Project Contributors
CM Pop-Up banners for WordPress: version: 1.5.0, author: CreativeMindsSolutions
Distributor: version: 1.6.2, author: 10up Inc.
Email Subscribers & Newsletters: version: 4.6.7, author: Icegram
Jetpack by WordPress.com: version: 9.3.2, author: Automattic
MC4WP: Mailchimp for WordPress: version: 4.8.3, author: ibericode
Nextend Social Login: version: 3.0.26, author: Nextendweb
OneSignal Push Notifications: version: 2.1.6, author: OneSignal
Tawk.to Live Chat: version: 0.4.3, author: Tawkto

### wp-plugins-inactive (12) ###

10Web Social Feed: version: 1.1.31, author: 10Web
Classic Editor: version: 1.6, author: WordPress Contributors
CoBlocks: version: 2.6.0, author: GoDaddy
Embed Plus for YouTube - Gallery, Channel, Playlist, Live Stream: version: 13.4.1.2, author: Embed Plus for YouTube Team
Gutenberg: version: 9.7.4, author: Gutenberg Team
Layout Grid: version: 1.3, author: Automattic
Page Builder by SiteOrigin: version: 2.11.8, author: SiteOrigin
Page Optimize: version: 0.5.1, author: Automattic
Popup Maker: version: 1.15.0, author: Popup Maker
Wise Chat: version: 2.9.4, author: Kainex
WordPress.com Editing Toolkit: version: 2.12, author: Automattic
WP Subscribe: version: 1.2.12, author: MyThemeShop

### wp-media ###

image_editor: Photon_Subsizes_WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 2047M
upload_max_filesize: 2047M
max_effective_size: 2 GB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 4.9.0-11-amd64 x86_64
httpd_software: nginx
php_version: 7.3.26 64bit
php_sapi: fpm-fcgi
max_input_variables: 6144
time_limit: 1200
memory_limit: 256M
max_input_time: 1200
upload_max_filesize: 2047M
php_post_max_size: 2047M
curl_version: 7.74.0 OpenSSL/1.1.0l
suhosin: false
imagick_availability: false
pretty_permalinks: true

### wp-database ###

extension: mysqli
server_version: 10.3.21-MariaDB-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: https://championsofdiversity.info
WP_SITEURL: https://championsofdiversity.info
WP_CONTENT_DIR: /srv/htdocs/wp-content
WP_PLUGIN_DIR: /srv/htdocs/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: latin1
DB_COLLATE: latin1_swedish_ci

### wp-filesystem ###

wordpress: not writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### jetpack ###

site_id: 134233576
ssl_cert: No
time_diff: undefined
version_option: 9.3.2:1611066032
old_version: 9.3.1:1610645471
public: Private
master_user: #1 oclynchjr
current_user: #2 khiser
tokens_set: Blog User
blog_token: z5jj#RV5UYXJ(gf$Rm(sC)wP%xea&Iad
user_token: 1RNVZe43Yk6NswXBuraKHjaGbIpdtVIs
version: 9.3.2
jp_plugin_dir: /wordpress/plugins/jetpack/9.3.2/
plan: business
protect_header: ""
full_sync: {"started":"Mon, 25 Jan 2021 17:38:39 +0000","finished":"Mon, 25 Jan 2021 17:38:44 +0000","progress":{"options":{"finished":true},"functions":{"finished":true},"constants":{"finished":true},"users":{"total":"1","sent":1,"finished":true,"last_sent":"2"},"network_options":{"finished":true}},"config":{"options":true,"functions":true,"constants":true,"users":[2],"network_options":true}}
sync_size: undefined
sync_lag: 0 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"https:\/\/championsofdiversity.info","siteurl":"https:\/\/championsofdiversity.info","WP_HOME":"https:\/\/championsofdiversity.info","WP_SITEURL":"https:\/\/championsofdiversity.info"}
idc_error_option: false
idc_optin: true
cxn_tests: All Pass.

### amp_wp ###

amp_mode_enabled: reader
amp_reader_theme: legacy
amp_templates_enabled: post, post, page, attachment, ads, cm-ad-item, es_template
amp_serve_all_templates: This option does not apply to Reader mode.
amp_css_transient_caching_disabled: n/a
amp_css_transient_caching_threshold: 5000 transients per day
amp_css_transient_caching_sampling_range: 14 days
amp_css_transient_caching_transient_count: undefined
amp_css_transient_caching_time_series: 
amp_libxml_version: 2.9.4

### distributor ###

0: 1.6.2
1: Yes
2: {removed}
3: 
	Override Author Byline: Yes
	Media Handling: Featured image and attached images
4: N/A
5: 
	CareerTown: 
- URL: https://careertown.net/wp-json
- Version: 1.6.2
- Status: valid
- Auth method: Username / Password
- Username: kevin
- Roles Allowed to Push: administrator, editor
- Additional data: {"errors":[], "can_post":["post", "page", "attachment", "wp_block"], "can_get":["post", "page", "attachment", "wp_block"], "endpoint_suggestion":false, "is_authenticated":"yes"}

`

**Additional context**

**Comment by dkotter** [comment]
@khiser Thanks for the report. Looking at the screenshot provided, as well as the extra environment details, it appears you're on a WordPress.com site. Distributor won't work properly in that environment, as we have no ability to add custom items to the menu bar (the menu bar WordPress.com uses is different than the one used by just WordPress).

We do support WordPress.com authentication but this was built expressly for use on WordPress.com VIP sites. Some Distributor features may work on normal WordPress.com sites but there will be some things that don't work, like the menu bar.

**Comment by violinman** [comment]
Hello, i am experiencing the same issue that i am unable to view distributor in the admin bar to allow for content to be pushed. My site is not on wordpress.com and i have checked all 3 Wordpress sites and they all behave in the same manner.

Could you offer some suggestions
thanks

**Comment by jeffpaul** [comment]
@violinman if you're viewing your content in WP Admin and utilizing the block editor, then you need to [disable "fullscreen mode"](https://github.com/10up/distributor#known-caveatsissues) in order to see the adminbar that includes the Distributor push menu.  If that's not the case, then please provide more details about your setup and a screenshot/screencast to help demonstrate the issue so we can better assist.

**Comment by violinman** [comment]
Thankyou i have got it working.  Does the distribution tab only appear when viewing the post from the front of the site, which means you can only distribute one at a time ?   Is there any means to distribute multiple posts one one step?

**Comment by jeffpaul** [comment]
@violinman as long as you have "fullscreen mode" disabled in the block editor (or are using the classic editor), then you can distribute content via the Distributor push menu in the adminbar.  There is currently no way to push more than one post at a time, but you can pull multiple posts into a remote site via the Pull Content menu.
