### ISSUE TITLE
ACF Taxonomy field doesn't populate

### ISSUE THREAD

**Issue by robertnabbe** [10up/distributor#709]
(Not sure if this is related to #625 or not) When attempting to push a post that contains an [ACF Taxonomy field](https://www.advancedcustomfields.com/resources/taxonomy/), it will simply remain empty on the recipient site (no data). Granted, the `post_tag` I'm attempting to push down has an ID of 664 on the main site, and 73 on the recipient (that probably doesn't help either).

Right now I'm solving this issue by getting the Term _slug_ on `save_post()`, and writing it to an ACF Input field, which gets pushed down by Distributor just fine.

Running v1.6.

**Comment by jmslbam** [comment]
I think this agency is doing the same "slug" trick in their plugin as you https://github.com/NovemBit/distributor-acf-addon. This plugin is based on external connections.

**Comment by jeffpaul** [comment]
Closing in favor of #81.
