### ISSUE TITLE
Compatibility across themes and pagebuilders?

### ISSUE THREAD

**Issue by dfardon** [10up/distributor#711]
**Describe your question**

Hi, we have managed to push posts from mainsite to two remotesites. 

However when the posts display on the remotesites, the formatting is different to the existing posts on that site. I notice that the first pushed post is created without using the remotesite pagebuilder, whereas the previous posts on those sites were all created directly in the remotesite using the pagebuilder. 

Mainsite uses a commercial theme (Ocean WP) with Elementor as the pagebuilder. Remotesite A uses a different theme (Vierra) but with Elementor. Remotesite B uses a third theme (Enfold) and the Pagebuilder is Avia Layout Builder.

Is there a way to make the posts we push be created on the remotesites via their pagebuilders to keep the destination page styling the same as the previous posts? Or do we have too much variation going on between the three sites?

Thanks!

David

**Comment by dfardon** [comment]
@dkotter Hi, do you have a minute to let me know about this question? Just so we know if we can keep on with Distributor or if it won't work for our scenario. Thanks!

**Comment by dkotter** [comment]
@dfardon Thanks for the question. This is an issue that has been brought to our attention a few times, both with sites using Elementor and sites using other types of page builders (see #348 for some initial thoughts).

It is something that is on our roadmap to look more in depth at and see if there's a better way to handle distributing meta data that would solve the most common page builder use cases but that isn't something that has been started yet. So at the moment, without custom configuration on your end utilizing the existing Distributor hooks to manipulate the data that is sent/received, it seems that Distributor won't work for your particular use case.

That said, I can keep you informed as we work on this issue, as it would be great to have you test things once we have a potential fix in place, to ensure it works for your scenario.

**Comment by dfardon** [comment]
@dkotter Sure, keep me informed, be glad to help. Thanks!

**Comment by jeffpaul** [comment]
Closing in favor of 348.
