### ISSUE TITLE
Duplicate of post is already considered distributed

### ISSUE THREAD

**Issue by ocaisa** [10up/distributor#718]
**Describe the bug**

If a post that was distributed is duplicated, the new post already has the distributor link to the old article (and this link can't be removed).

**Steps to Reproduce**

1. Create a post
2. Distribute it
3. Duplicate the distributed post
4. Try to distribute that (for me it already has a link to the old post)

**Expected behavior**

Post duplication should not include Distributor information

**Screenshots**

**Environment information**
 - Device: Laptop
 - OS: Windows
 - Browser and version: Chrome
 - WordPress version: 5.6.1
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by jeffpaul** [comment]
@ocaisa what plugin are you using to duplicate posts?

**Comment by ocaisa** [comment]
Sorry for being slow to reply on this, I hadn't even realised that we were using a plugin for this. We are using [Duplicate Page](https://wordpress.org/plugins/duplicate-page/).

Not expecting you to be able to fix this for another plugin, so feel free to close. It would be good if it were possible to break the link to the remote site, so that we could fix this easily if we make the same mistake again.

**Comment by jeffpaul** [comment]
@ocaisa I tested the steps you listed using the Duplicate Page plugin and you should be able to click the "unlink" link on the duplicated page to remove the Distributor link and be able to edit that post/page.  See example screenshots below...

Classic Editor
![Screen Shot 2021-02-17 at 9 35 52 AM](https://user-images.githubusercontent.com/2818133/108227749-d528e600-7103-11eb-8deb-d97b982bd425.png)


Block Editor
![Screen Shot 2021-02-17 at 9 36 49 AM](https://user-images.githubusercontent.com/2818133/108227768-d9550380-7103-11eb-88e4-832176169724.png)

**Comment by ocaisa** [comment]
Sorry my steps were not clear enough, what we are doing is creating a duplicate of the original post, which we modify (and then want to distribute as a fresh post). When we do this, the duplicate looks like
![InkedScreenshot 2021-02-17 16 49 03_LI](https://user-images.githubusercontent.com/3840437/108230242-d88e9280-7140-11eb-8c1a-85abc002a963.jpg)
I can't see a way to remove the existing connection there (which links back to the older article on the connected site under "View")

**Comment by jeffpaul** [comment]
@ocaisa ok I see, yes that sounds like the Duplicate Page plugin is copying across all meta values including the Distributor mapping.  You could go in and clear out the `dt_connection_map` value if you're comfortable editing that and it'll clear the connections in place.

**Comment by ocaisa** [comment]
Thanks a lot for the support, for the other admins on this site, that's probably a step too far. I did a bit of digging and I found https://developer.yoast.com/duplicate-post/filters-actions , I'll try to implement that to filter out `dt_connection_map`.

**Comment by ocaisa** [comment]
Wrong plugin :P but it was still pretty easy to add in a filter
```
if (strcmp($meta_key, "dt_connection_map") !== 0) {
    $sql_query_sel[]= "SELECT $new_post_id, '$meta_key', '$meta_value'";
}
```
