### ISSUE TITLE
distributable_post_types filter is not respected in Pull UI screen

### ISSUE THREAD

**Issue by jmslbam** [10up/distributor#720]
**Describe the bug**
while filtering the permited post types via `distributable_post_types`, I noticed that the dropdown in de Pull UI has all the post types in the dropdown. 

**Steps to Reproduce**
Filter the permited post types:

```
add_filter( 'distributable_post_types', function() {
    return [ 'post' => 'post' ];
});
```

Go to the Pull overview page en check the dropdown.

**Expected behavior**
I expected only the Post post type in the dropdown.

**Environment information**
 - WordPress version: 5.6.1

Version | 1.6.2

Override Author Byline: Yes

Media Handling: Featured image and attached images

Internal Connections | 
Maas Wijkontwikkeling:  - Blog ID: 2 - URL: https://waal.local/maasontwikkel - Registered: 2021-02-01 13:52:41 - Last updated: 2021-02-13 17:09:18
Woonslim:  - Blog ID: 3 - URL: https://waal.local/woonslim - Registered: 2021-02-01 13:52:56 - Last updated: 2021-02-03 08:33:12

External Connections | N/A

**Additional context**
Thank you!

**Comment by dkotter** [comment]
@jmslbam There is actually a different filter in place to modify the post types available for pulling: `dt_available_pull_post_types`: https://github.com/10up/distributor/blob/develop/includes/utils.php#L257

I can understand the confusion between that filter and `distributable_post_types`. One is used when pushing content, the other is for pulling content.

**Comment by jeffpaul** [comment]
Labeling this for docs so we can add more clarity to the docblock on `distributable_post_types` and hopefully make the push vs. pull scenario a bit clearer.

**Comment by jmslbam** [comment]
Ah thank your for pointing the other filter out! 

I feel like `distributable_post_types` (or a new `dt_distributable_post_types`) can be the generic overal filter and new `dt_distributable_pull_post_types` and a new `dt_distributable_push_post_types` can be the filter for each scenario.

This makes the filter consistent in their naming convention and logic. Not having the word "push" or "pull" in it, makes it look like a generic filter that goes both ways.

We can deprecate the old filters with `do_action_deprecated` or `apply_filters_deprecated` in WP.

If this new nameing convention feels ok, I can patch up a PR somewhere this month.

**Comment by dkotter** [comment]
@jmslbam I think this all sounds correct and the right approach to me. If you have time to put together a PR, I'd be happy to review it. Thanks!

**Comment by jmslbam** [comment]
I'm stil up for this, but the Distributor project I'm working on has some little hickups :) when it's live I have some spare time!
