### ISSUE TITLE
Compatible With Woocommerce In Multisite?

### ISSUE THREAD

**Issue by jbriggs923** [10up/distributor#722]
**Describe your question**

Hello,

I have a large multi-author blog that I am looking to sell my own products from a separate ecommerce site (they will be setup in multisite). I have three questions:

1. Can Distributor plugin push and pull products created in Woocommerce to other sites running your plugin?
2. Are there any limitations to this?
3. Is it possible for the link generated by Distributor plugin to direct the user to it's source website? (ecommerce site pushes to blogging site. User clicks on the product from the blogging site. The user is then taken to the product on the ecommerce website).

Thank you 10up for all your wonderful plugins and I look forward to hearing from your team! :)

**Comment by jeffpaul** [comment]
@jbriggs923 I just set up a multisite network and a separate WordPress instance with Distributor and WooCommerce activated on both sides.  I then created external connections from the single WordPress instance to two sites on the multisite.

1. I was then able to distributor from the single WordPress instance using the Push method for Distributor in the admin bar and saw it distribute to the network site selected.  I updated the origin product description and saw that update on the remote network site as well.  So it seems the answer to your first question is "yes, Distributor plugin can push and pull products created in Woocommerce to other sites running your plugin".
2. I've not tested the far reaching levels of WooCommerce extensions or all the intricate ways a product can be updated, so I'll defer to you on what critical functions you'd look to ensure work and then see how that works with Distributor.  So back to you on this one, what's most important to ensure Distributor keeps in sync between sites?
3. The standard Distributor handling of this is the author name/link and a quick test on WooCommerce doesn't show this working by default.  If there's not already a [hook to handle this](https://10up.github.io/distributor/), then clarifying your expected workflow will help us understand how Distributor might be enhanced to support this use case.  So again, back to you on this one, can you describe the flow of what you'd expect on this (including screenshots with callouts of which links would ideally direct to alternate/remote/origin sites would be super helpful).

Thanks!
Jeff.

**Comment by jeffpaul** [comment]
@jbriggs923 do you any additional questions from my test results and response above or can we close out this issue?
