### ISSUE TITLE
DOCS: add note that App Pwds is used for REST API auth, not JWT Auth or other plugins

### ISSUE THREAD

**Issue by rosspbauer** [10up/distributor#723]
I am trying to configure an external connection from one WP instance to another both running locally. I have read through the documentation and the caveats section and I am receiving the following `Limited connection established` warning.

<img width="513" alt="Screen Shot 2021-02-19 at 16 30 59" src="https://user-images.githubusercontent.com/49494513/108532681-fe966d00-72cf-11eb-97a1-64e17b6e65b5.png">

Application passwords have been enabled for use over http and have been supplied via the manual configuration settings when creating the connection. 

The mainsite network request to `admin-ajax.php` when checking the connection returns the following response
`{"success":true,"data":{"errors":{"no_types":"no_types"},"can_post":[],"can_get":[],"endpoint_suggestion":false}}`

What might be the cause of this issue? Apologies if there is something I have missed in the documentation or other related issues.

Thanks

**Comment by jeffpaul** [comment]
@rosspbauer in setting up the external connections manually, I assume the password you're using for the connection is generated via the `Application Passwords` section of the user on the external site correct?
![Screen Shot 2021-02-19 at 11 16 17 AM](https://user-images.githubusercontent.com/2818133/108538069-004a3b80-72a4-11eb-89a3-0df36591fe49.png)

You'll also want to ensure you follow these steps to setup manually: https://github.com/10up/distributor/#setup-external-connections-using-application-passwords

**Comment by rosspbauer** [comment]
@jeffpaul, yes I did use the password created by application passwords. Is the username to use the actual user? or the name directly associated to the application password? 

Having said that I have just tried putting a random username and password in for the connection and that results in the same warning and network response. So something doesn't appear to be right. 

I believe I have followed all the steps mentioned for the manual set up.

**Comment by rosspbauer** [comment]
@jeffpaul I have worked out what was causing the issue. We have the `JWT Auth` plugin enabled which after I deactivated allowed everything to work from Distributor's point of view. 

Is there a way of configuring Distributor to work with the `JWT Auth` plugin?

**Comment by jeffpaul** [comment]
@rosspbauer now that Application Passwords is part of WordPress core, that's most likely going to be the primary authenticated way for Distributor to access the REST API for external connections.  If you're locked into using JWT Auth, then we could look into other options for you; if that's of urgent or important need shoot me an email (jeff.paul@10up.com) and we can discuss... thanks!

**Comment by jeffpaul** [comment]
**Updating the title and focus of this issue for us to call out in the readme that Application Passwords is the manner in which Distributor gains authenticated access to the REST API and that other plugins, like JWT Auth, will likely cause issues for external connections.**
