### ISSUE TITLE
Site crashed on the 1.6.3 version

### ISSUE THREAD

**Issue by SieBer15** [10up/distributor#734]
**Describe the bug**

Site crashed on the 1.6.3 version

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: 
 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by jeffpaul** [comment]
@SieBer15 I just tested the 1.6.3 release this morning upgrading from 1.6.2 to 1.6.3 on WordPress 5.7 and everything works as expected.  Can you please provide a little more info on your site setup and the steps taken that caused your site to crash?  Did you see any errors?  Were you updating other plugins at the same time?  Any additional info you can provide so I can try to replicate the issue and help triage for you would be greatly appreciated, thanks!

**Comment by dkotter** [comment]
@SieBer15 I think I found the issue and just pushed a PR in #742. If you had time to test that and see if it fixes your issue, that would be great. Thanks!

**Comment by SieBer15** [comment]
Hello Darin,

Thanks for looking into my error from the Distributor plugin.
I tested your plugin but unfortunately I still get the same error.

With kind regards,
Sietse Berkhout

T +31 (0)6 292 47 398 <tel:+31629247398>
www.sieber.nl <http://www.sieber.nl/> / KvK 62614843 <applewebdata://97928A18-D56C-4BE2-AB9B-AF463002D078#>

**Comment by dkotter** [comment]
@SieBer15 I just updated the PR with one more change, if you have time to test again. I found another issue if a site is using PHP 5.6 so I'm assuming that's the issue you're still experiencing. If you're on a different version of PHP, that would be helpful to know, especially if this PR still doesn't fix the issue for you.

**Comment by SieBer15** [comment]
Hello Darin,

I am using php 7.1 for this website. So with your new adjustment it probably still won't work.

Thanks again!

With kind regards,
Sietse Berkhout

T +31 (0)6 292 47 398 <tel:+31629247398>
www.sieber.nl <http://www.sieber.nl/> / KvK 62614843 <applewebdata://DDD8EA5D-5D2D-413F-AF94-CFEAB76222DB#>

**Comment by jeffpaul** [comment]
@SieBer15 can you please confirm whether the 1.6.4 released version works or still causes this issue for you?

**Comment by SieBer15** [comment]
The problem is solved Jeffrey!

Thanks a lot for your perseverance!

With kind regards,
Sietse Berkhout

T +31 (0)6 292 47 398 <tel:+31629247398>
www.sieber.nl <http://www.sieber.nl/> / KvK 62614843 <applewebdata://637D0B93-6C54-4EC8-893E-1252F535F47C#>
