### ISSUE TITLE
About connection

### ISSUE THREAD

**Issue by FunkkyMonkeyy** [10up/distributor#745]
Hello,
I'm registed for free to try it before i buy it, yah and i have 1 issues for this is:
Limited connection established.
Authentication failed due to invalid credentials.
Push distribution unavailable.
Pull distribution limited to basic content, i.e. title and content body.
I'm sure for you is admin and password for it, is admin role for this remote site.
Help me, and thank you if you reply me.

**Comment by jeffpaul** [comment]
@FunkkyMonkeyy I assume you're trying to connect two different WordPress instances via an External Connection, correct?  If so, did you run into any errors going through the External Connection set up process?  If not, can you share some more info about your setup (WP version, active theme/plugins, Distributor version)?

**Comment by FunkkyMonkeyy** [comment]
Thank you for your reply, jeffpaul. And yah, i try connect two different WordPress, so your plugin just work multisite network, isn't it ?
So WP version is a lasted version now and active plugins is normal, and Distributor version i just down last day so i think this version is a lasted version, right ? And i try connect with your introduction but it's not can be green status, just yellow everytime i remove and make it. And one things i want to ask you about custom post type will have in Distributor plugin ?
Thank you if you reply me.

**Comment by jeffpaul** [comment]
@FunkkyMonkeyy Distributor works within a multisite setup, across different WordPress instances, and any blend of those two as well.  When you went through the External Connection set up process, did you use the automated process or the manual one?  Also, are any of your instances non-SSL or a local environment, either of those may make the functioning of the bundled Application Passwords functionality not work as desired.

**Comment by FunkkyMonkeyy** [comment]
Thank you for your reply, now i see your problem in my web. The plugin you make, it's great and helpful

**Comment by jeffpaul** [comment]
@FunkkyMonkeyy ok so your set up now works with Distributor?  If  so, then let's close this issue.  If you're still having problems, please confirm so we can continue to assist you... thanks!
