### ISSUE TITLE
Attachment's URL not updated when pulling post.

### ISSUE THREAD

**Issue by francisco-domo** [10up/distributor#748]
I ran into this exact same issue which is a couple years old: https://github.com/10up/distributor/pull/184

Im running the latest version and I have an external connection set up, with both sites having "Process featured image and any attached images" checked, but the pulled post attachments (except featured image) still refers to the original URL (although it creates the media to the library of the site from where are pulling). So to sum it up, everything seems to work except that it doesnt' modify the attachment URL.

Thanks for your help.

**Comment by jeffpaul** [comment]
@francisco-domo are those additional images within ACF or a page builder?  If so, there's a general issue with plugin compatibility at play.  Sharing a bit more details about your setup will help identify what may be the root cause here.

**Comment by francisco-domo** [comment]
Hello Jeff, thanks, yes I should have provided that information. I'm using the default block editor.

**Comment by jeffpaul** [comment]
@francisco-domo can you provide an export of your Site Health Info settings so we can try to replicate your setup and help further triage?

**Comment by jeffpaul** [comment]
@francisco-domo can you provide an export of your Site Health Info settings so we can try to replicate your setup and help further triage?
