### ISSUE TITLE
Wordfence Settings

### ISSUE THREAD

**Issue by violinman** [10up/distributor#749]
i get errors whenever Wordfence is turned on the receiving content site. 

I added my IP to all the white list settings i could find however that doesn't seem to have worked.

Does anyone have any ideas ?

**Comment by jeffpaul** [comment]
@violinman its possible that Wordfence is blocking REST API access or some other critical function for  Distributor.  Can you share more details about your setup so we can help further triage?

**Comment by andytylerlewis** [comment]
I'm also seeing this issue on sites we run - if we have WordFence running the Distributor plugin fails. Is it worth speaking to WordFence about this?

**Comment by jeffpaul** [comment]
@andytylerlewis looks like there's a response on this topic from the Wordfence team, see: https://wordpress.org/support/topic/distributor-plugin-being-blocked/#post-14348651

**Comment by violinman** [comment]
Hello,  thanks for your reply.  I've moved onto another platform for this as there were a number of little things that were causing complications with the overall process but the learning mode on wordfence look to be a good solution for this one.
