### ISSUE TITLE
How to access URL from original

### ISSUE THREAD

**Issue by kaputti1o1** [10up/distributor#752]
Hi,

I need to link out to the original post. Is there a variable I can use in the functions.php to get the original URL? I would like to create a shortcode to place the URL in a template.

Thx.

BR
Dirk

**Comment by kaputti1o1** [comment]
@dkotter any idea how I can access the URL of the original post?

**Comment by dkotter** [comment]
@dziemann There are a couple helper functions you should be able to use here:

- `distributor_the_original_post_link`: Pass in the post ID of the Distributed item and this function will directly echo the original URL (if there is one)
- `distributor_get_original_post_link`: Pass in the post ID of the Distributed item and this function will return the original URL or false

**Comment by kaputti1o1** [comment]
Thanks for your help! Unfortunately it always gives back false. Argh! Not sure what goes wrong.

**Comment by dinhtungdu** [comment]
@dziemann Can you share the snippet you're using?

**Comment by kaputti1o1** [comment]
```
add_shortcode( 'orig_post_url', 'orig_post_url' );

function orig_post_url(){
	$orgurl=distributor_get_original_post_link();
	if($orgurl){
		return $orgurl;
	}
		else{
			return 'https://google.com';
		}
}
```

and it always returns google.

**Comment by dinhtungdu** [comment]
@dziemann I'm sorry for the late reply! About your snippet, you need to pass the distributed post ID to `distributor_get_original_post_link` to get the original post link.

Alternatively, you can try this to get the original post URL directly:
```
$original_post_url  = get_post_meta( $post_id, 'dt_original_post_url', true );
```
