### ISSUE TITLE
dt_original_site_name custom field returns empty

### ISSUE THREAD

**Issue by justiny** [10up/distributor#769]
**Describe the bug**

After pulling a post from an external connection, the custom field `dt_original_site_name` returns empty.  Is there a recommended way to pull that original article site name?  

**Steps to Reproduce**

1. Go to pull an article from external connection.
2. Click on the newly pulled article.
3. Scroll down to the custom fields area in the wp post.
4. See empty dt_original_site_name input.

**Expected behavior**

Expected to see original site name which the post is associated.

**Screenshots**
![image](https://user-images.githubusercontent.com/2721886/121209155-d78c8880-c837-11eb-9294-7f4c7f1b12ab.jpg)

**Environment information**
 - Device: MacOS MacBook Pro M1 2020
 - OS: 11.2.2
 - Browser and version: Chrome 91.0
 - WordPress version: 5.7.2

**Additional context**
No other context.

**Comment by jeffpaul** [comment]
@justiny I'm able to replicate this for Pull only, I'm seeing the data appear as expected via Push.  Could you test a Push distribution via the Distributor menu in the WP adminbar and report back if you see the `dt_original_site_name` or not?

**Comment by dkotter** [comment]
@justiny Thanks for this report. I was able to reproduce this myself and I've put together a PR to fix this. If you have a chance, would love for you to test that out and verify it fixes your issue. Thanks!
