### ISSUE TITLE
I need help with establishing connection between sites.

### ISSUE THREAD

**Issue by ccvision** [10up/distributor#772]
**Describe your question**

I cant establish a connection i`ve tried everything...

![noconnection](https://user-images.githubusercontent.com/86671929/123816605-bc251280-d8f7-11eb-9aed-7461a7bdcb0d.png)

**Comment by jeffpaul** [comment]
@ccvision assuming you're following the [setup instructions](https://github.com/10up/distributor#setup-external-connections-using-application-passwords), where in the process are things not working for you?  Similarly providing WordPress, theme, and active plugin versions would be helpful to better help triage.

**Comment by ccvision** [comment]
> @ccvision assuming you're following the [setup instructions](https://github.com/10up/distributor#setup-external-connections-using-application-passwords), where in the process are things not working for you? Similarly providing WordPress, theme, and active plugin versions would be helpful to better help triage.![image](https://user-images.githubusercontent.com/86671929/123914952-45802780-d980-11eb-8f3d-faaa4076b621.png)
This is the mainsite
![image](https://user-images.githubusercontent.com/86671929/123914813-1964a680-d980-11eb-92cb-3186ede66194.png)
![image](https://user-images.githubusercontent.com/86671929/123914871-2bdee000-d980-11eb-9573-44eedb2abaf6.png)

And this is the remote site
![image](https://user-images.githubusercontent.com/86671929/123914925-3c8f5600-d980-11eb-84d5-da70f811a7a3.png)
![image](https://user-images.githubusercontent.com/86671929/123914974-49ac4500-d980-11eb-81bd-1f74b14b0c98.png)

Both sites have been created yesterday. If possible a screen sharing session?

**Comment by jeffpaul** [comment]
@ccvision I'm assuming these are separate WordPress instances (as otherwise you do not need to set up External Connections since Distributor will auto-detect all sites in a multisite setup).  Are you trying to connect these two sites using the wizard flow or the manual setup process?

**Comment by ccvision** [comment]
> @ccvision I'm assuming these are separate WordPress instances (as otherwise you do not need to set up External Connections since Distributor will auto-detect all sites in a multisite setup). Are you trying to connect these two sites using the wizard flow or the manual setup process?

I tried the wizard and manual setup process i just can`t figure it out.

**Comment by ccvision** [comment]
Could you show me screenshot from your setup, i want to setup a multisite setup.

**Comment by ccvision** [comment]
I can give you access if you want?

**Comment by dinhtungdu** [comment]
@ccvision I get an SSL error when I visit your remote site. You have to ensure your remote site is working before creating a connection to it.

![image](https://user-images.githubusercontent.com/5423135/124536295-f0418b80-de41-11eb-9b25-b8ea46ad0ae7.png)

**Comment by ccvision** [comment]
> @ccvision I get an SSL error when I visit your remote site. You have to ensure your remote site is working before creating a connection to it.
> 
> ![image](https://user-images.githubusercontent.com/5423135/124536295-f0418b80-de41-11eb-9b25-b8ea46ad0ae7.png)

its https://d2.complexhosting.eu ;) that should work

**Comment by dinhtungdu** [comment]
@ccvision  I got the same error visiting d2.complexhosting.eu

![image](https://user-images.githubusercontent.com/5423135/125431508-44cf0dce-3692-42bf-b24c-f5c01b03a632.png)

**Comment by ccvision** [comment]
> 
> 
> @ccvision I got the same error visiting d2.complexhosting.eu
> 
> ![image](https://user-images.githubusercontent.com/5423135/125431508-44cf0dce-3692-42bf-b24c-f5c01b03a632.png)

Can i give you access to both of the sites so you can take a look at it?

**Comment by dinhtungdu** [comment]
@ccvision, you should contact your hosting support to fix the SSL issue, Distributor can't establish connections if your sites have an SSL issue.
