### ISSUE TITLE
sync image content issue

### ISSUE THREAD

**Issue by apereirac-apc** [10up/distributor#777]
**Describe your question**

Hello, I need your help, the problem I have is that when synchronizing an entry it synchronizes everything perfectly except the images within the content. How can I do to sync the image within the content?

Thank you very much for all your help.

**Comment by jeffpaul** [comment]
@ale8521 are you using a Page Builder or something like ACF when building your content that includes these images?  Sharing a bit more about your setup will help us better triage for you, thanks!

**Comment by apereirac-apc** [comment]
Hello, thanks for the answer, I use the wordpress block editor to publish the post, but for the visualization I use a divi template, everything loads perfectly, featured image, text, paragraphs, text quotes, buttons, but the only thing that does not load are the images of the content. How can i solve this?

**Comment by jeffpaul** [comment]
@ale8521 page builders like Divi are a know compatibility issue that we're working on handling in our 2.0.0 release.

**Comment by apereirac-apc** [comment]
Thank you very much, I will be looking forward to it. Very good work.

**Comment by ldollard** [comment]
Hi Paul, not to hijack... but is there a roadmap to 2.0.0? Are any other new release for updates?

**Comment by jeffpaul** [comment]
@ldollard you can see what's planned for the 2.0.0 release here: https://github.com/10up/distributor/milestone/20.  We're currently working on [1.6.5](https://github.com/10up/distributor/milestone/26) and have at least a [1.6.6](https://github.com/10up/distributor/milestone/27) and [1.7.0](https://github.com/10up/distributor/milestone/21) release planned before 2.0.0.

**Comment by ldollard** [comment]
Thank @jeffpaul, I knew it was someplace just couldn't locate it so thanks for that, do you know if there is a rough release date for 1.6.5? And anything I can do to help (not a programmer), but open to test anything.

**Comment by jeffpaul** [comment]
@ldollard we're aiming for 1.6.5 by the end of August.  If you want to test Distributor against WordPress 5.8 RC 3 (see #774) and provide feedback on that issue, that would help!

**Comment by jeffpaul** [comment]
As this relates to Divi, I'm going to close this in favor of #348.
