### ISSUE TITLE
How to distribute ACF file attached to post

### ISSUE THREAD

**Issue by abombelli** [10up/distributor#781]
Hello

We have created custom file and image fields with ACF.
For some reason the files the attached files and images are not distributed.

What are we doing wrong?

Thanks
Aldo

**Comment by jeffpaul** [comment]
@abombelli we have an overall tracking issue for ACF, see #81, as a known issue to be resolved tentatively in our 2.1.0 release.  I'm going to close this issue, so please subscribe to 81 for future updates... thanks!
