### ISSUE TITLE
Main site without theme frontend, like headless WordPress

### ISSUE THREAD

**Issue by anilpainuly121** [10up/distributor#783]
Hi, I am using distributor and willing to use main site without theme frontend, like headless WordPress, at present i am using blank page. but user who have urls of posts can access the content, iwant to block that.

Is there any workaround to achieve this...

Thanks and regards
Anil

**Comment by jeffpaul** [comment]
@anilpainuly121 you could use something like [Restricted Site Access](https://wordpress.org/plugins/restricted-site-access/) to block access to your main site.

**Comment by dinhtungdu** [comment]
@anilpainuly121 You can also do the same trick you're using on homepage for the single post/page template.
