### ISSUE TITLE
Distributor won't make a connection between websites

### ISSUE THREAD

**Issue by ccvision** [10up/distributor#793]
**Describe your question**

So, for some reason Distributor won't make a connection between websites.
I'm using the newest version of wordpress with application passwords (the one that comes with WP, not the plugin just to clarify), and the user I'm logging in with is an administrator.
The external URL is "https://xxx.xx/index.php?rest_route=/", and distributor is installed on both wordpress installations.

**Comment by jeffpaul** [comment]
@ccvision are you attempting to connect two separate WordPress instances or two sites within a multisite network?

**Comment by ccvision** [comment]
The two instances are separate

**Comment by dkotter** [comment]
@ccvision Looking at the example URL you posted (`https://xxx.xx/index.php?rest_route=/`), you don't appear to be using pretty permalinks within WordPress. Is that correct?

If so, that is probably the issue. I feel like this has come up before but couldn't find anything while looking through old issues. I'd suggest turning those on if you can and it may be worth us looking into this to see if we can add support for sites that aren't using pretty permalinks.

**Comment by ccvision** [comment]
That solved it, thank you. Not having permalinks indeed stopped it from connecting.
