### ISSUE TITLE
Distributed post not showing on backend

### ISSUE THREAD

**Issue by MaxxxDev** [10up/distributor#794]
Hi !

I just installed the plugin, everything works fine.
I tried distributing a post from site A to site B
Everything went right, BUT, when I go to the backend of site B, I have 1 draft (the distributed one I guess), but when I click on draft, nothing shows up ! I check on the database and the post is there, but it doesn't show on site B backend

Did you ever got this issue before ?

Pardon my english, I'm not a native speaker.

Thanks in advance and have a nice day !

Maxxx

**Comment by jeffpaul** [comment]
@MaxxxDev when you say:
> when I click on draft, nothing shows up 

is that attempting to open the draft post on site B in the editor or via the front end of your site?  Also, please provide WordPress version, Distributor version, other active plugins and theme so we can try to replicate your setup and further assist... thanks!

**Comment by MaxxxDev** [comment]
Hi !

Thanks for your input !

When, after the distribution from SiteA is click on "view", it open the article on SiteB, buuuuut, on SiteB backend (to edit it, like publish it for exemple, the backoffice tells me " Draft(5)3, but when I click to see them, none of them are visible

Wordpress version is 5.8.1 (for both)
Distribution version is Version 1.6.5-dev (for both)
Theme is JOINTSWP (for both)

About the extension that may cause this, could it be polylang (SiteB only)?

**Comment by MaxxxDev** [comment]
I tried doing the reverse :

pull SiteA's post to SiteB, and it works, but distributing from A to B doesn't

**Comment by jeffpaul** [comment]
Closing in favor of #332.
