### ISSUE TITLE
Subsites not showing in Distributor dropdown for some users

### ISSUE THREAD

**Issue by GRMoneta** [10up/distributor#798]
**Describe your question**

I added an existing user to two new subsites.  He can see them and access them from the Sites dropdown, however, those subsites do not appear in his Distributor dropdown list.  We've tried logging in/out, clearing cache, etc.  As the network admin, I have no issues seeing all sites in the Distributor dropdown.  Any suggestions?

**Comment by jeffpaul** [comment]
@GRMoneta that sounds like a bug for sure.  Can you confirm if this is being viewed from the Pull Content screen or via the Distributor Push menu in the adminbar / block editor sidebar?  Also, can you please confirm your WordPress and Distributor versions as well as if you're using subdomains or subdirectories for your multisite install for us to further triage?

**Comment by GRMoneta** [comment]
The user in question can get to and use the pull content screen on the subsites he is added to.  This is only about the push menu in the adminbar.  Classic editor installed, so no blocks.  WP 5.8.1, Dist 1.64-dev    We are using subdirectory multisites.

**Comment by GRMoneta** [comment]
Update:  the new Distributor version 1.6.6 seems to have fixed this issue.  Thanks for being responsive, if that was the case.
