### ISSUE TITLE
Enhancement: Support WP VIP Code Standards

### ISSUE THREAD

**Issue by jamesmorrison** [10up/distributor#799]
**Is your enhancement related to a problem? Please describe.**
During a commit of Distributor to a WP VIP Go repository, the VIP Bot flagged a number of issues with the plugin codebase. _[For privacy reasons, the site in question is not being identified here - contact me directly for further details.]_

**Describe the solution you'd like**
Include the VIP code standards in tests, ensure that where practical code is updated for compatibility; where impractical PHPCS ignore rules are added.

**Designs**
N/A

**Describe alternatives you've considered**
N/A (The only alternative is not to use VIP Go)

**Additional context**
N/A

**Comment by jeffpaul** [comment]
Here’s the ClassifAI PR that added VIPCS and fixed/ignored VIPCS issues: https://github.com/10up/classifai/pull/287.  We would theoretically take a similar approach here.
