### ISSUE TITLE
cURL error 60: SSL certificate problem: certificate has expired (http_request_failed)

### ISSUE THREAD

**Issue by grugel-maintro** [10up/distributor#805]
Have the exact same error:

```
Unable to connect to site.
cURL error 60: SSL certificate problem: certificate has expired (http_request_failed) 
```
 using centos 8 and Wordpress 5.8.1

_Originally posted by @grugel-maintro in https://github.com/10up/distributor/issues/804#issuecomment-932807972_

**Comment by jeffpaul** [comment]
Closing in favor of #804
