### ISSUE TITLE
Lots of limited connection warnings

### ISSUE THREAD

**Issue by alexwolk** [10up/distributor#806]
I'm trying to set this up with a large network I manage where the sites are all on different hosts. It works for about 70% of them, but for the others I get either a Limited connection established. or Distributor is not installed error, even though I'm doing the exact same setup on all the sites

**Comment by jeffpaul** [comment]
@alexwolk you mention "network" but given you have sites on different hosts I assume this is not a WordPress multisite (aka network) set up but rather individual WordPress instances, correct?  If so, are you working with the latest versions of WordPress and Distributor?  Do you have any security plugins running that might be limiting access to the REST API?  Are you following our [External Connection Setup Instructions](https://github.com/10up/distributor#set-up-external-connections-using-application-passwords) and if so where are things failing?
