### ISSUE TITLE
Can push but can't pull

### ISSUE THREAD

**Issue by romeowski** [10up/distributor#822]
Hi, Thanks for your plugin and for your work!

I try to PULL custom post types to SITE A FROM SITE B.
At the moment I can only PUSH this custom post types from SITE B to SITE A.

- Connection established.
- Green Light's on
- Post types permissions: 
Can pull? YES 
Can push? YES

When I click to "Pull Content" from EXTERNAL connection created:
Could not pull content from connection due to error.

WP Version 5.8.2 and Distributor Version 1.6.7 from both sites (not Multisite)
Both https, both run Application password

**Environment information**

 - <details><summary>Site Health Info:</summary>

Version | 1.6.7
-- | --
Valid registration | Yes
Registration email | mymail
Settings | Override Author Byline: NoMedia Handling: Featured image and attached images
Internal Connections | N/A
External Connections | Corporate:  - URL: https://www.mysite.com/wp-json - Version: 1.6.7 - Status: valid - Auth method: Username / Password - Username: mymail - Roles Allowed to Push: administrator - Additional data: {"errors":[], "can_post":["post", "page", "attachment", "wp_block", "wp_template", "press"], "can_get":["post", "page", "attachment", "wp_block", "wp_template", "press"], "endpoint_suggestion":false, "is_authenticated":"yes"}

   </details>

**Comment by jeffpaul** [comment]
@romeowski note that running WP 5.8.2 you do NOT need to install the Application Passwords plugin as that's now part of WP core.  That being said, does your Site A have an external connection to Site B (assuming you're working with different WP instances and not within a multisite setup)?

**Comment by romeowski** [comment]
I also tried uninstalling Application Password and recreating credential in native Application Password but without success: Connection Established, green light, in Pull Content Section "Could not pull content from connection due to error." appears and nothing more.  Nothing appears in Console too.

**Comment by jeffpaul** [comment]
@romeowski are you using any sort of security plugin that may be blocking access to the REST API?

**Comment by romeowski** [comment]
No, it seems that Rest Api works in both sites

**Comment by romeowski** [comment]
Hi, any update on this? Thank you!

**Comment by jeffpaul** [comment]
@romeowski I'm unable to replicate the issue you're seeing.  Is there an old/odd version of PHP, DB/App server, or something else potentially in play based on your knowledge of your hosting setup?

**Comment by jeffpaul** [comment]
Also stating explicitly that just because I cannot replicate your issue does not mean its invalid, just that I've not been able to trigger the issue which makes it near impossible for me to triage to the point of finding a fix to help resolve this for you.  So the more details we can gather to try and replicate, the better.

**Comment by romeowski** [comment]
Hi, sorry for late answer, it was a misconfiguration issue, thank you for support guys!
