### ISSUE TITLE
No connections available for distribution. (Multisite)

### ISSUE THREAD

**Issue by uttam-49** [10up/distributor#825]
I have a multisite setup and distributor (Version 1.6.7) installed in a multisite network. 
Now I am having one issue which is in the toolbar where we have a distributor tab, hovering on it to push data to other sites gives me No connections available for distribution messages. 
![image](https://user-images.githubusercontent.com/88894530/146387116-a79fa15a-eb9c-46d9-88f0-f2dff58b00ff.png)

I have my sites available to pull data in admin.php?page=pull. But I need to use the direct toolbar button to push content. Please help me with this.
I am having this plugin installed in my local environment too where it works completely fine!! So something strange.

**Comment by dkotter** [comment]
@uttam-49 Thanks for the report. From a code perspective, building the list of available connections is the same for both the Push screen and the Pull screen besides one thing:

- For the Push screen, the current post type that you are on must be supported by the connection you want to Push to, or it won't show in the list.

For example, looking at your screenshot it appears you are editing a custom post type (Hotels if I used Google Translate correctly). So the only connections that will show are other sites that also support that same Hotels post type.

If that's already the case, if you could provide some more information on your setup (like plugins and theme being used), I can take a closer look.
