### ISSUE TITLE
Could not pull content from connection due to error

### ISSUE THREAD

**Issue by jmstew3** [10up/distributor#826]
**Describe the bug**
On a site where I have 119 pages available to Pull Content from, I am receiving a "Could not pull content from connection due to error", triggered after I use "Screen Options" to change the Pagination > "Post Per Page" value to more than 100.

**Steps to Reproduce**

1. Go to 'Distributor'
2. Click on 'Pull Content'
3. Make sure you 'Pull Content from' a source that has more than 101 pages
4. Click on 'Screen Options'
5. Under 'Pagination', change the 'Posts per page' value to a number greater than 100 (example: 101)
4. Click 'Apply'
5. See error

**Expected behavior**
I expected to be able to see all of the pages available to 'Pull Content from' on one screen, eliminating the need for pagination (i.e. 1 of 2)

**Screenshots**
- Screenshot of the error when a value greater than 100 is keyed into the 'Posts per page' section of 'Screen Options': <img width="1061" alt="Screen Shot 2021-12-16 at 9 44 45 AM" src="https://user-images.githubusercontent.com/33553552/146392974-78ba5ee9-fec1-4992-b8a0-e691fe56e6c2.png">

- Screenshot of pagination working properly when a value of 100 or less is keyed in: <img width="1061" alt="Screen Shot 2021-12-16 at 9 45 10 AM" src="https://user-images.githubusercontent.com/33553552/146393239-25b63469-3c1a-428b-8429-b22238a5f57c.png">

**Environment information**
 - Device: MacBook Pro w/ M1 Max
 - OS: MacOS 12.0.1
 - Browser and version: Chrome Version 96.0.4664.110 (Official Build) (arm64)

**WordPress information**

<details><summary>Site Health info:</summary>
`
### wp-core ###

version: 5.8.2
site_language: en_US
user_language: en_US
timezone: America/New_York
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: production
user_count: 3
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/turnpoi6/public_html/4seasons
wordpress_size: loading...
uploads_path: /home/turnpoi6/public_html/4seasons/wp-content/uploads
uploads_size: loading...
themes_path: /home/turnpoi6/public_html/4seasons/wp-content/themes
themes_size: loading...
plugins_path: /home/turnpoi6/public_html/4seasons/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-active-theme ###

name: Pro – Child Theme (pro-child)
version: 1.0.0
author: Themeco
author_website: https://theme.co/
parent_theme: Pro (pro)
theme_features: core-block-patterns, cornerstone, cornerstone-theming, cornerstone-legacy-portfolio, cornerstone-legacy-sidebars, widgets-block-editor, post-thumbnails, title-tag, automatic-feed-links, post-formats, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, align-wide, wp-block-styles, widgets, menus
theme_path: /home/turnpoi6/public_html/4seasons/wp-content/themes/pro-child
auto_update: Disabled

### wp-parent-theme ###

name: Pro (pro)
version: 5.1.4
author: Themeco
author_website: https://theme.co
theme_path: /home/turnpoi6/public_html/4seasons/wp-content/themes/pro
auto_update: Disabled

### wp-themes-inactive (3) ###

Twenty Nineteen: version: 2.1, author: the WordPress team, Auto-updates disabled
Twenty Twenty: version: 1.8, author: the WordPress team, Auto-updates disabled
Twenty Twenty-One: version: 1.4, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (29) ###

Accessibility by Audioeye: version: 1.0.4, author: AudioEye, Auto-updates disabled
Admin Menu Editor Pro: version: 2.16.1, author: Janis Elsts, Auto-updates disabled
Advanced Custom Fields PRO: version: 5.11.3, author: Delicious Brains, Auto-updates disabled
AME Branding Add-on: version: 1.3.1, author: Janis Elsts, Auto-updates disabled
Better Search Replace: version: 1.3.4, author: Delicious Brains, Auto-updates disabled
Branda Pro: version: 3.4.6, author: WPMU DEV, Auto-updates disabled
Custom Post Type UI: version: 1.10.1, author: WebDevStudios, Auto-updates disabled
Defender Pro: version: 2.6.5, author: WPMU DEV, Auto-updates disabled
Distributor: version: 1.6.7, author: 10up Inc., Auto-updates disabled
Forminator Pro: version: 1.15.9, author: WPMU DEV, Auto-updates disabled
Hummingbird Pro: version: 3.2.1, author: WPMU DEV, Auto-updates disabled
Insert Headers and Footers: version: 1.6.0, author: WPBeginner, Auto-updates disabled
Quick Featured Images: version: 13.5.7, author: Kybernetik Services, Auto-updates disabled
Redirection: version: 5.1.3, author: John Godley, Auto-updates disabled
Simple Page Ordering: version: 2.3.4, author: Jake Goldman, 10up, Auto-updates disabled
Slider Revolution: version: 6.5.11, author: ThemePunch, Auto-updates disabled
SmartCrawl Pro: version: 2.16.0, author: WPMU DEV, Auto-updates disabled
Smush Pro: version: 3.9.4, author: WPMU DEV, Auto-updates disabled
Snapshot Pro: version: 4.6.0, author: WPMU DEV, Auto-updates disabled
UberMenu 3 - The Ultimate WordPress Mega Menu: version: 3.7.4, author: Chris Mavricos, SevenSpark, Auto-updates disabled
WordPress Importer: version: 0.7, author: wordpressdotorg, Auto-updates disabled
WordPress Toolbar Editor: version: 1.4, author: Janis Elsts, Auto-updates disabled
WP All Export - ACF Export Add-On Pro: version: 1.0.3, author: Soflyy, Auto-updates disabled
WP All Export Pro: version: 1.7.2, author: Soflyy, Auto-updates disabled
WP All Import - ACF Add-On: version: 3.3.5, author: Soflyy, Auto-updates disabled
WP All Import Pro: version: 4.7.1, author: Soflyy, Auto-updates disabled
WPCore Plugin Manager: version: 1.9.1, author: Stuart Starr, Auto-updates disabled
WP Healthcheck: version: 1.3.3, author: Tiago Hillebrandt, Auto-updates disabled
WPMU DEV Dashboard: version: 4.11.6, author: WPMU DEV, Auto-updates enabled

### wp-plugins-inactive (12) ###

Akismet Anti-Spam: version: 4.2.1, author: Automattic, Auto-updates disabled
BackupBuddy: version: 8.7.4.0, author: iThemes, Auto-updates disabled
Beehive Pro: version: 3.3.12, author: WPMU DEV, Auto-updates disabled
CallRail Phone Call Tracking: version: 0.4.9, author: CallRail, Inc., Auto-updates disabled
Carbon Copy Menu Duplicator: version: 1.0, author: Chris Mavricos, SevenSpark, Auto-updates disabled
Hello Dolly: version: 1.7.2, author: Matt Mullenweg, Auto-updates disabled
Menu Management Enhancer: version: 1.2, author: Chris Mavricos, SevenSpark, Auto-updates disabled
Shipper Pro: version: 1.2.11, author: WPMU DEV, Auto-updates disabled
Superfly Menu: version: 5.0.23, author: Looks Awesome, Auto-updates disabled
The Grid: version: 2.7.9.1, author: Themeone, Auto-updates disabled
WP All Export - WooCommerce Export Add-On Pro: version: 1.0.1, author: Soflyy, Auto-updates disabled
Yoast SEO: version: 17.8, author: Team Yoast, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-68 Q16 x86_64 2021-10-14 https://imagemagick.org
imagick_version: 3.5.1
file_uploads: File uploads is turned off
post_max_size: 1024M
upload_max_filesize: 1024M
max_effective_size: 1 GB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 31 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 12288
	imagick::RESOURCETYPE_MAP: 31 GB
	imagick::RESOURCETYPE_MEMORY: 16 GB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.25

### wp-server ###

server_architecture: Linux 3.10.0-1160.49.1.el7.x86_64 x86_64
httpd_software: Apache
php_version: 7.4.26 64bit
php_sapi: cgi-fcgi
max_input_variables: 6000
time_limit: 3000
memory_limit: 1024M
max_input_time: 3000
upload_max_filesize: 1024M
php_post_max_size: 1024M
curl_version: 7.80.0 OpenSSL/1.1.1l
suhosin: false
imagick_availability: true
pretty_permalinks: true

### wp-database ###

extension: mysqli
server_version: 5.7.36
client_version: mysqlnd 7.4.26

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/turnpoi6/public_html/4seasons/wp-content
WP_PLUGIN_DIR: /home/turnpoi6/public_html/4seasons/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 1024M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### distributor ###

0: 1.6.7
1: Yes
2: justin@peakonedigital.com
3: 
	Override Author Byline: Yes
	Media Handling: Featured image and attached images
4: N/A
5: 
	TestFlight: 
- URL: https://testflight.turnpointservices.net/wp-json/
- Version: 1.6.7
- Status: valid
- Auth method: Username / Password
- Username: Justin
- Roles Allowed to Push: administrator
- Additional data: {"errors":[], "can_post":["post", "page", "attachment", "wp_block", "wp_template", "coupons", "team"], "can_get":["post", "page", "attachment", "wp_block", "wp_template", "coupons", "team"], "endpoint_suggestion":false, "is_authenticated":"yes"}

`
</details>

**Additional context**
First time I have experienced this issue. I have been pulling from more than 100 pages for quite some time now (~6 months), and did not notice the issue until today. The only thing I can think is that somehow there is an issue with Chrome and my new MacBook Pro with M1 silicon. Either that, or this is a bug with Distributor's most recent plugin update.

**Comment by jeffpaul** [comment]
@dkotter perhaps this is related to the changes in #811?

**Comment by dkotter** [comment]
@jmstew3 Thanks for the report. This is a direct result of the changes made in #811. We had a maximum limit set on the `per_page` argument to 100. WordPress itself enforces this behind the scenes for any REST endpoint that utilizes the `per_page` argument.

I've created a PR that addresses this by removing that limit and renaming that argument to get around the enforcing coming from WordPress core. This should address the issue you're seeing.

**Comment by jmstew3** [comment]
Awesome work. Thanks!
