### ISSUE TITLE
External connection configuration page loads endlessly after submitting external connection form

### ISSUE THREAD

**Issue by Aldr0n** [10up/distributor#832]
Distributor external connection configuration page loads endlessly after submittung external connection form.

After submitting a new change in an external connection configuration or creating a new one, the site just loads endlessly (or rather really long) and throws a critial wordpress error at the end.

Help :(

**Comment by jeffpaul** [comment]
@Aldr0n can you provide more details about your setup, possibly a Site Health export as well as your browser and version?

**Comment by Aldr0n** [comment]
Hey there, sry for the late reply. I found out that the plugin "Snitch", which acts as a special firewall for api calls, blocks distributor communication. Even if no rules are configured. Hope that helps, and my issue is resolved.

Cheers!
