### ISSUE TITLE
DOCS: Code for hiding canonical link

### ISSUE THREAD

**Issue by ybalkind** [10up/distributor#855]
### Describe your question

Hi

I've checked previous issues and although I've seen reference to the code for hiding canonical links, I'd appreciate if it could please be spelt out for a non-developer exactly what code to insert (I'm using a code snippets plugin to insert code to my site). 

In case its relevant, the reason I need to hide canonical links is that my main site is password protected. I'm using the main site purely as a CMS. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
@ybalkind Thanks for the question. Are you using Internal Connections or External Connections, or both? Also, do you use the Yoast SEO plugin? If you're using all three of those, you'll want this code snippet:

```
add_action( 'template_redirect', function () {
	remove_filter( 'get_canonical_url', array( '\Distributor\InternalConnections\NetworkSiteConnection', 'canonical_url' ), 10, 2 );
	remove_filter( 'wpseo_canonical', array( '\Distributor\InternalConnections\NetworkSiteConnection', 'wpseo_canonical_url' ) );
        remove_filter( 'get_canonical_url', array( '\Distributor\ExternalConnections\WordPressExternalConnection', 'canonical_url' ), 10, 2 );
	remove_filter( 'wpseo_canonical', array( '\Distributor\ExternalConnections\WordPressExternalConnection', 'wpseo_canonical_url' ) );
}, 20 );
```

Feel free to remove any line that mentions Internal or External connections if you aren't using one of those and you can also remove the `wpseo_canonical` lines if you don't use Yoast SEO.

**Comment by ybalkind** [comment]
Perfect thank you

**Comment by jeffpaul** [comment]
Re-opening this for someone to take the code snippet above and add to: https://github.com/10up/distributor/blob/develop/docs/snippets.md so it'll appear on the plugin docs site.
