### ISSUE TITLE
Fix help icon on settings page

### ISSUE THREAD

**Issue by dkotter** [10up/distributor#857]
### Describe the bug

On the Distributor settings page (both on a single site or if network enabled on a multisite), there's an information icon with the text Help next to it. The icon is underlined (since it's a link) and it's underneath the page title. This looks broken to me and I believe we should at least remove the underline from the icon and potentially move this icon up a line next to the title? And maybe hide the Help text and have that as screen reader text?

### Steps to Reproduce

1. Go to the Distributor settings page
2. Notice the information icon and help text underneath the title

### Screenshots, screen recording, code snippet

<img width="324" alt="Screen Shot 2022-03-08 at 3 39 44 PM" src="https://user-images.githubusercontent.com/916738/157338161-535e9de4-8d84-456c-8bf1-90b06041bf6a.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by willhowat** [comment]
Screenshot from PR https://github.com/10up/distributor/pull/871
![Screenshot 2022-04-12 at 16 34 37](https://user-images.githubusercontent.com/1838952/162987018-50568b92-af9c-4c69-972e-fe22698e03fb.png)

**Comment by dkotter** [comment]
@willhowat Thanks! This looks great. Merging this in.
