### ISSUE TITLE
Add ability to set roles allowed to Pull content when creating an External Connection

### ISSUE THREAD

**Issue by dkotter** [10up/distributor#858]
### Is your enhancement related to a problem? Please describe.

When setting up/editing an External Connection currently, you can choose which roles are allowed to Push content. But there is no way to set which roles can Pull content. This can be changed via a [filter](https://github.com/10up/distributor/issues/626#issuecomment-673276684) but seems like we should have the same settings for Pull as we do for Push.

### Designs

<img width="1204" alt="Screen Shot 2022-03-08 at 3 44 53 PM" src="https://user-images.githubusercontent.com/916738/157338631-fb90ca82-da9d-4043-9ae1-cc5002fc04c3.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by peterwilsoncc** [comment]
@faisal-alvi @dkotter Following the discussion in PR #877, was it decided to close this issue out as a wont fix?

**Comment by faisal-alvi** [comment]
@peterwilsoncc posted my opinion in https://github.com/10up/distributor/pull/877#issuecomment-1134285737, waiting on @dkotter's final thought/decision.
