### ISSUE TITLE
Add ability to view all post types when Pulling from an External Connection

### ISSUE THREAD

**Issue by dkotter** [10up/distributor#861]
### Is your enhancement related to a problem? Please describe.

When you go to the Pull screen for an Internal/Network Connection, we default to showing content from all supported post types. You can then filter down to just the post type you want (like Posts).

But for External Connections, we default to showing just Posts and there isn't a way to view content across all post types. This is because historically we were requesting content from a post type specific endpoint, so it was impossible to get content across multiple post types. But with the changes introduced in #811, we can now show content from across all supported post types, mirroring how we do this for Internal Connections.

One thing to note here is if you are on an External Connection that has had no content pulled or skipped yet, we utilize the old approach to grabbing content, from a post type specific endpoint and not the new endpoint introduced in #811. So that will need to be addressed here to fully support his new feature.

<img width="494" alt="Screen Shot 2022-03-08 at 4 17 06 PM" src="https://user-images.githubusercontent.com/916738/157342454-fcd3cbe4-e37a-4729-a302-6c6002d69fbf.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Noting that https://github.com/10up/distributor/tree/feature/861 may be a good start on this, so we'll want to credit @chigozieorunta once this issue gets resolved.

**Comment by peterwilsoncc** [comment]
As work in beginning on Distributor 2.0.0, I've moved this enhancement off the 1.7.0 milestone to allow the point release to focus on bug fixes.

**Comment by mehul0810** [comment]
@jeffpaul I have worked on this with the branch `https://github.com/10up/distributor/tree/feature/861`, tested the functionality and created a PR which is ready for review.

**Comment by ankitrox** [comment]
@mehul0810 This [PR](https://github.com/10up/distributor/pull/1003) is also there, please check if there's something you can spot or helpful.

**Comment by peterwilsoncc** [comment]
I've moved this to 2.0.1 as the REST API endpoint this relies on will be getting modified in 2.0.0.

**Comment by mehul0810** [comment]
@jeffpaul I have reviewed and updated the PR to achieve the functionality as mentioned in the issue. Can you please review?

Also, I noticed that some GH actions for E2E are failing saying no report files. Are we aware of that? If not, we need to tackle that in separate issue. For ref: https://github.com/10up/distributor/actions/runs/9710975272/job/26802811307?pr=1002

PR: https://github.com/10up/distributor/pull/1002

**Comment by jeffpaul** [comment]
@peterwilsoncc probably worth reviewing #1002 and #1003 on this feature to determine optimal path forward.

**Comment by peterwilsoncc** [comment]
@jeffpaul I've reviewed #1002 and I it looks to work with the various rest api changers. There are some similarities between the two pull requests so I think it wise to credit the authors and participants of each on the merged PR.
