### ISSUE TITLE
Author name sync/not distributed

### ISSUE THREAD

**Issue by mapamond** [10up/distributor#868]
### Describe your question

Hi,

The original author name is not distributed with the post from one site to another. 

I have selected the option "Override Author Byline | For linked distributed posts, replace the author name and link with the original site name and link."

Still the original name of the author is not distributed.

Please help.

mapamondnet@yahoo.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sjmwa** [comment]
Adding to this....I'm having the same issue. When checking the override author option it does not send to the distributed post...it uses the authenticated user with access as the author.

Any suggestions on how to fix? Thanks.

**Comment by cadic** [comment]
Experiencing the same. Tested against different themes on WordPress Core 6.0.2 and Distributor 1.7.1

| Theme | Override byline |
|-|-|
| Twenty-Nineteen | ✅ |
| Twenty-Twenty | ❌ |
| Twenty-Twenty-One | ✅ |
| Twenty-Twenty-Two | ❌ |

### Twenty-Nineteen (override works, showing source site name "distributor")
<img width="400" alt="Screenshot 2022-09-22 at 10 43 18" src="https://user-images.githubusercontent.com/288381/191687787-eb912748-13b8-4453-b093-cd38fa031d9d.png">

### Twenty-Twenty (override doesn't work, showing author name)
<img width="400" alt="Screenshot 2022-09-22 at 10 45 20" src="https://user-images.githubusercontent.com/288381/191688174-5e1bb06d-61bd-4021-a079-bfa4c89679f7.png">

### Twenty-Twenty-One (works)
<img width="1018" alt="Screenshot 2022-09-22 at 10 46 53" src="https://user-images.githubusercontent.com/288381/191688481-ec9bd7fb-bb5d-4c7c-87b1-d0cd41bd64ec.png">

### Twenty-Twenty-Two (doesn't work)
<img width="664" alt="Screenshot 2022-09-22 at 10 47 56" src="https://user-images.githubusercontent.com/288381/191688655-2e3cabad-12f5-445c-ac2e-e10cbb7720ed.png">

**Comment by peterwilsoncc** [comment]
It looks like this needs to be duplicated for network connections, reopening to test and create a follow up PR if required. 

https://github.com/10up/distributor/blob/3735ccb3135a9fd21095110b4a3f7c79343272d1/includes/classes/InternalConnections/NetworkSiteConnection.php#L924-L930
