### ISSUE TITLE
Test against WordPress 6.0

### ISSUE THREAD

**Issue by vikrampm1** [10up/distributor#872]
Is your enhancement related to a problem? Please describe.

Once WordPress 6.0 is released, we'll want to test Distributor to see if any incompatibility issues arise.

Describe the solution you'd like

- [ ] test Distributor on WordPress 6.0
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [ ] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release

Designs
n/a

Describe alternatives you've considered
none

Additional context
Related: #833, #568, #624, #735, #774.

**Comment by lukaspawlik** [comment]
@vikrampm1 @jeffpaul I've tested this on 6.0 and all seems to work correctly, I haven't found any issues or problems.

What are next steps with marking this as Tested up to 6.0?

**Comment by jeffpaul** [comment]
@lukaspawlik there's a header value in `readme.txt` and the badge in `README.md`, if you want to open a PR to bump those both to 6.0 that would do it... thanks!
