### ISSUE TITLE
Error when distributing content "No post ID provided."

### ISSUE THREAD

**Issue by joshwilsondotme** [10up/distributor#876]
### Describe the bug

When attempting to distributor a page from a custom post type across all sites within a mutlisite installation, we are receiving an error:

There were some issues distributing the post.
No post ID provided.

### Steps to Reproduce

Go to page of CPT
Under the Distributor Toolbar Select All Sites
Uncheck 'As Draft`
Click Distribute 

### Screenshots, screen recording, code snippet

![Screen Shot 2022-04-25 at 1 29 54 PM](https://user-images.githubusercontent.com/6585864/165146055-23f89f20-3cd2-48cb-a97a-5c80c3102186.png)

### WordPress information

`
### wp-core ###

version: 5.8.4
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: true
user_registration: false
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 348
site_count: 331
network_count: 1
dotorg_communication: true

### wp-dropins (3) ###

advanced-cache.php: true
install.php: true
sunrise.php: true

### wp-plugins-active (53) ###

Advanced CF7 DB: version: 1.8.2, author: Vsourz Digital (latest version: 1.8.7), Auto-updates disabled
Advanced Custom Fields PRO: version: 5.10.2, author: Delicious Brains (latest version: 5.12.2), Auto-updates disabled
Advanced noCaptcha & invisible Captcha: version: 6.1.6, author: WP White Security (latest version: 7.0.6.1), Auto-updates disabled
Akismet Anti-Spam: version: 4.1.12, author: Automattic (latest version: 4.2.2), Auto-updates disabled
Auto Image Attributes From Filename With Bulk Updater: version: 2.1, author: Arun Basil Lal (latest version: 3.1), Auto-updates disabled
Better Search Replace: version: 1.3.4, author: Delicious Brains (latest version: 1.4), Auto-updates disabled
Codestar Framework: version: 2.0.3, author: Codestar, Auto-updates disabled
Contact Form 7: version: 5.4.2, author: Takayuki Miyoshi (latest version: 5.5.6), Auto-updates disabled
Content Blocks (Custom Post Widget): version: 3.2.2, author: Johan van der Wijk, Auto-updates disabled
Custom API: author: (undefined), version: 1.0, Auto-updates disabled
Custom Permalinks: version: 2.2.0, author: Sami Ahmed Siddiqui (latest version: 2.4.0), Auto-updates disabled
Custom Post Type for Pages: author: (undefined), version: 1.0, Auto-updates disabled
Distributor: version: 1.6.7, author: 10up Inc. (latest version: 1.6.9), Auto-updates disabled
Distributor - Edit Remote Post Meta: version: 0.2.0, author: 10up, Auto-updates disabled
Easy Social Icons: version: 3.1.3, author: cybernetikz (latest version: 3.2.4), Auto-updates disabled
GA Google Analytics: version: 20210719, author: Jeff Starr (latest version: 20220124), Auto-updates disabled
iThemes Security Pro: version: 7.0.3, author: iThemes (latest version: 7.1.1), Auto-updates disabled
JWT Authentication for WP-API: version: 1.2.6, author: Enrique Chavez, Auto-updates disabled
Kadence Blocks Pro: version: 1.4.1, author: Kadence WP, Auto-updates disabled
Kadence Blocks – Gutenberg Blocks for Page Builder Features: version: 2.1.12, author: Kadence WP, Auto-updates disabled
Kirki Customizer Framework: version: 3.1.9, author: David Vongries (latest version: 4.0.23), Auto-updates disabled
Multisite API: author: (undefined), version: 1.0, Auto-updates disabled
Multisite Robots.txt Manager | MS Robots.txt: version: 3.0.0, author: tribalNerd, Chris Winters, Auto-updates disabled
NS Cloner - Site Copier: version: 4.1.7, author: Never Settle (latest version: 4.1.9.3), Auto-updates disabled
Post Type Switcher: version: 3.2.1, author: Triple J Software, Inc., Auto-updates disabled
Real-Time Find and Replace: version: 4.0.2, author: Marios Alexandrou, Auto-updates disabled
Redirection: version: 5.1.3, author: John Godley (latest version: 5.2.3), Auto-updates disabled
Regenerate Thumbnails: version: 3.1.5, author: Alex Mills (Viper007Bond), Auto-updates disabled
Review Stream: version: 1.6.4, author: Grade Us, Inc., Auto-updates disabled
Safe SVG: version: 1.9.9, author: Daryll Doyle (latest version: 2.0.1), Auto-updates disabled
Schema: version: 1.7.9.2, author: Hesham (latest version: 1.7.9.4), Auto-updates disabled
Simple Page Ordering: version: 2.3.4, author: Jake Goldman, 10up, Auto-updates disabled
Single Sign On: author: (undefined), version: 1.0, Auto-updates disabled
Smart Slider 3 Pro: version: 3.5.0.11, author: Nextend, Auto-updates disabled
Smush Pro: version: 3.9.0, author: WPMU DEV (latest version: 3.9.8), Auto-updates disabled
Theme Editor: version: 2.6, author: mndpsingh287 (latest version: 2.7), Auto-updates disabled
User Switching: version: 1.5.7, author: John Blackbourn & contributors (latest version: 1.5.8), Auto-updates disabled
Wad Add Custom Schema: author: (undefined), version: 1.0, Auto-updates disabled
Wad Simple Staff List: author: (undefined), version: 99.1.1, Auto-updates disabled
Wad Survey: author: (undefined), version: 1.0, Auto-updates disabled
WordPress Importer: version: 0.7, author: wordpressdotorg, Auto-updates disabled
WordPress MU Domain Mapping: version: 0.5.5.1, author: Donncha O Caoimh, Auto-updates disabled
WP Mail SMTP: version: 3.0.3, author: WPForms (latest version: 3.3.0), Auto-updates disabled
WP Migrate DB Pro: version: 2.2.0, author: Delicious Brains (latest version: 2.3.2), Auto-updates disabled
WP Migrate DB Pro Media Files: version: 2.1.0, author: Delicious Brains, Auto-updates disabled
WP Migrate DB Pro Multisite Tools: version: 1.4.0, author: Delicious Brains (latest version: 1.4.1), Auto-updates disabled
WPMU DEV Dashboard: version: 4.11.3, author: WPMU DEV (latest version: 4.11.12), Auto-updates disabled
WP News and Scrolling Widgets: version: 4.5.2, author: WP OnlineSupport, Essential Plugin (latest version: 4.5.6), Auto-updates disabled
WP Offload Media: version: 2.5.6, author: Delicious Brains, Auto-updates disabled
WP Offload Media - Assets Pull Addon: version: 1.1.2, author: Delicious Brains, Auto-updates disabled
WP Rocket: version: 3.9.4, author: WP Media (latest version: 3.11.0.5), Auto-updates disabled
WP Store Locator: version: 2.2.234, author: Tijmen Smit (latest version: 2.2.235), Auto-updates disabled
Yoast SEO: version: 17.1, author: Team Yoast (latest version: 18.6), Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 200M
upload_max_filesize: 200M
max_effective_size: 200 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, BMP
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 4.14.268-205.500.amzn2.x86_64 x86_64
httpd_software: Apache/2.4.25 (Debian)
php_version: 7.3.2 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 100
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: -1
upload_max_filesize: 200M
php_post_max_size: 200M
curl_version: 7.52.1 OpenSSL/1.0.2q
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.12
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/html/wp-content
WP_PLUGIN_DIR: /var/www/html/wp-content/plugins
WP_MEMORY_LIMIT: 64M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: true
SCRIPT_DEBUG: true
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### wp_mail_smtp ###

version: 3.0.3
license_key_type: lite
debug: No debug notices found.
db_tables: wad_wpmailsmtp_tasks_meta, wad_wpmailsmtp_debug_events
lite_install_date: Sep 20, 2021 @ 11:31pm

### distributor ###

0: 1.6.7
1: 
	Override Author Byline: Yes
	Media Handling: Featured image only

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
@joshwilsondotme Thanks for the report.

I've tested this out a few times and can't reproduce the same issue. Couple questions for you though. Does this only happen on custom post types? Does this only happen if you select all connections? And similarly, does it only happen if the `As Draft` option is unchecked?

Looking through our code, that error should only display if the original post ID isn't being sent during the push request, which I can't think of a scenario where that would happen.

One thing you could look at, if you have time, is if the Distributor data we need is available. On page load, we localize a bunch of data (including the post ID) to a variable called `dt`. If you could load up the edit screen for one of these custom post types, open the browser console and type in `dt` and hit enter, you should see a an object with a bunch of information. Does this object contain a `postId` parameter? And does it correlate correctly with the post ID of the item you're on?

**Comment by joshwilsondotme** [comment]
@dkotter — I am seeing the data mentioned on the edit of a post `nonce: 'e27f489ab7', loadConnectionsNonce: 'a6269b2d56', postId: '3548',`
And the `postId` matches of the post as well.

I also tried distributing the posts `As Draft` and that resulted in the same error.

**Comment by vlastaw** [comment]
Hello, I guess, this may be the same issue as #847 , which was closed without solution. The error in my case is Could not determine remote post id, but the cause is probably the same - no post is generated on target instance, therefore no post id can be determined.

**Comment by joshwilsondotme** [comment]
I went through and did batches of pushing out a post across all of the sites, this appears to work. I then testing manually selecting each site, this resulting in the same error as clicking the 'Select All' button.

**Comment by joshwilsondotme** [comment]
I believe we have identified the issue. We have increased the php `max_input_vars` from 1000 to 4000. This appears to have alleviated the issue.
