### ISSUE TITLE
Conflicting dynamic pre_post_link filter can result in a fatal PHP error

### ISSUE THREAD

**Issue by jeremyfelt** [10up/distributor#879]
### Describe the bug

`pre_post_link` is a WordPress core filter used to [filter the permalink structure for a post before token replacement occurs](https://developer.wordpress.org/reference/hooks/pre_post_link/).

It provides the `$permalink` string, `$post` object, and `$leavename` boolean when fired within `get_permalink()` in WordPress core.

One of the (I believe custom) arguments [that Distributor passes](https://github.com/10up/distributor/blob/6d20a4ce5f7cea4472d48b8f30cab1b57cacaa5e/includes/classes/ExternalConnections/WordPressExternalConnection.php#L562) to `wp_insert_post()` when pulling content from an external connection is `link`, which contains the URL of the external content being pulled and is stored as post meta.

When `wp_insert_post()` fires, all post arguments are sanitized through `sanitize_post()`. In `sanitize_post()`, each field is processed through `sanitize_post_field()`. In `sanitize_post_field()`, non-`post_`-prefixed fields are [passed through a dynamic filter](https://github.com/WordPress/wordpress-develop/blob/5612331504e22efe3e17440580d887279f68913e/src/wp-includes/post.php#L2830), `pre_post_{$field}`.

In the case of the `link` argument used by Distributor, this becomes `pre_post_link`, which conflicts with the filter of the same name in WordPress core.

Other code filtering `pre_post_link` must now defend against the possibility that only one argument is passed, resulting in a fatal error if the function signature expects 2 or 3. It must also be cautious that the `$link` value is formatted like `https://example.org/slug/` rather than a permalink structure like `/%category%/%postname%/`.

It's disappointing that WordPress allows this conflict to happen, but it seems like something that can be worked around through code. It would make sense to me to change the custom post argument to something like `dt_original_post_url` or `dt_link` so that it's prefixed and/or matches the meta key it's stored with. If this can't happen [early in the process](https://github.com/10up/distributor/blob/b11ac0f6183fffaf10ccf09fda6875aa4552f0bf/includes/classes/ExternalConnections/WordPressExternalConnection.php#L1047), then maybe it can be adjusted just in time before passing to `wp_insert_post()`.

### Steps to Reproduce

Add a filter like:

```
add_filter( 'pre_post_link', 'jf_filter_post_link', 10, 3 );

function jf_filter_post_link( $permalink, $post, $leavename ) {
  // do things...

  return $permalink;
}
```

Then attempt to pull a piece of external content via Distributor -> Pull Content in the dashboard.

### Environment information

N/A

### WordPress information

WP 5.9.3 with a lot of plugins and things going on. :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeremyfelt** [comment]
A fairly obvious workaround that I didn't notice the first time around: :)

```
add_filter( 'dt_pull_post_args', 'jf_filter_dt_post_args' );

function jf_filter_dt_post_args( $post_array ) {
	unset( $post_array['link'] );
	return $post_array;
}
```

This removes `link` from the data passed to `wp_insert_post()`. `$post_array['link']` is stored in meta untouched.

This leads me to think even more that `link` should be removed from the list of arguments passed to `wp_insert_post()` as it's not being sanitized there for any real reason.

**Comment by peterwilsoncc** [comment]
Hi @jeremyfelt and thank you for your report.

I've taken a look at this to confirm the bug and noticed same issue applies for both the pushing and pulling of posts.

While using the filter `dt_pull_post_args` can fix the issue for pulling posts, for pushing posts the equivalent is not able to as `dt_push_post_args` is used for two purposes: the remote HTTP request to the push destination and passing the arguments to `wp_insert_post()` on the push destination.

To avoid breaking backward compatibility within the plugin, I think I will filter the arguments through an allow list prior to passing the data to `wp_insert_post()`.
