### ISSUE TITLE
External connection - 

### ISSUE THREAD

**Issue by Groupe-Mgel** [10up/distributor#880]
### Describe your question

Bonjour à tous,
I am carrying out a test for my company, 
but I cannot connect the two sites with distributor.
I have made several attempts but without success.
I am writing to ask for your assistance.

Here are the error messages:
"Could not pull content from connection due to error. Désolé, vous n’avez pas l’autorisation de modifier les entrées dans ce type de publication."
"Limited connection established. Authentication failed due to invalid credentials. Push distribution unavailable. Pull distribution limited to basic content, i.e. title and content body."

Login credentials:
**_EDITED TO REMOVE CREDENTIALS_** <-- by @jeffpaul 

I thank you for your attention and look forward to your reply.
Yours sincerely
Flavio Vicari
service.multimedia@mgel.fr
+33621183020

![Sans-titre-1](https://user-images.githubusercontent.com/105207816/167389592-1ec86423-205c-4e6a-aaf5-571450e6ee57.jpg)
![Sans-titre-2](https://user-images.githubusercontent.com/105207816/167389595-c84a91df-0c4b-43fc-8a97-54e27fd37f92.jpg)
![Sans-titre-3](https://user-images.githubusercontent.com/105207816/167389597-c2295191-12e7-4650-81d0-880983fc497a.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@Groupe-Mgel note that I've removed the credentials posted here and recommend you immediately change those passwords.  I'll take a look at the screenshots you provided and comment shortly with questions/recommendations for next steps to try and resolve your connection issue.

**Comment by jeffpaul** [comment]
@Groupe-Mgel in reviewing the screenshots you provided, it looks like perhaps the `Username` is incorrect on the *fils site where it tries to connect to the *pere site and perhaps the `External Connection URL` may need to strip out the `index.php` portion but I'd recommend trying to fix the username to the correct WP username first to see if that gets the connection working (you'll notice whether the status changes after saving the connection upon changing the username).

**Comment by Groupe-Mgel** [comment]
Good morning Mr. Jeffrey,
Thank you for your response.
The two sites and credentials were two purpose-made tests and submit the
problem to you.
I solved it by testing on a different server, where it worked.
Now that it works we will have to do some new tests to see if the plugin
meets our needs.

Thank you

Le mer. 11 mai 2022 à 04:38, Jeffrey Paul ***@***.***> a
écrit :
