### ISSUE TITLE
WPEngine Security Barriers

### ISSUE THREAD

**Issue by emmawenger** [10up/distributor#881]
### Describe your question

I have multiple sites that are on different WPEngine installs (not a multisite); while trying to set up external connections on the two sites I get these errors:

While trying to set up the external connection automatically:
![Screen Shot 2022-05-16 at 3 28 08 PM](https://user-images.githubusercontent.com/30055176/168667760-c95d1c9d-899c-40f3-aa50-0b533733ed30.png)

After setting up the external connection manually:
![Screen Shot 2022-05-16 at 3 23 05 PM](https://user-images.githubusercontent.com/30055176/168667011-b0528d11-d728-4e86-ac9d-f3df1b079dd2.png)

After chatting with WPEngine support, it sounds like they have security measures in place that deny cross-install manipulations. Do you know if there's any additional actions I can take place to get around this? (I did add application passwords to the correct users) Or can I not progress further since this isn't a multisite and because of WPEngine's security measures?

Thanks!

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@emmawenger could you perhaps put your WP Engine technical contact into an email thread with me (jeff.paul@10up.com) to discuss their platform and how best to ensure Distributor can work across separate WordPress installs there?

**Comment by emmawenger** [comment]
@jeffpaul just looped you into an email coming from emma@usefulgroup.com. Thanks!

**Comment by jeffpaul** [comment]
Closing this as it appears WP Engine got things resolved on their end, though I never got feedback from WP Engine on their changes and uncertain if any updates are needed on Distributor to prevent similar issues in the future.  If WP Engine responds with that info, then let's please re-open this issue to work through any necessary updates on the Distributor side of things.
