### ISSUE TITLE
Unicode characters are not escaped during syndication

### ISSUE THREAD

**Issue by amalajith** [10up/distributor#889]
### Describe the bug

During syndication, both pull and push, if a WordPress Gutenberg block enabled post content has Unicode characters in block attributes, I expect the Unicode characters to be slashed so that WordPress does not remove the slashes when pulling the syndicated posts. At the moment, WordPress strips out the slashes, so it creates invalid text strings in the post content of the syndicated post.

### Steps to Reproduce

1. Create a custom Gutenberg block with the following attributes title, description. 
2. Add some test content and save it so that the post content is now available in the database with the title and description attributes.
3. Replace the attributes with following code snippet which has encoded content in the title and description attributes of the post content.
4. Make the post available for syndication
5. Pull the post on the multisite.
6. WordPress strips of the slashes creating the character encoding issue as shown in the screenshot below.

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/8926037/172546477-3a72364f-17e2-45d0-bfed-fb733a0e75bb.png)

```
 {"title":"Our 11 Objectives","description":"\u003cstrong\u003eEnvironment\u003c/strong\u003e \u003cbr\u003e\u003cbr\u003e\u003cstrong\u003eObjective 01\u003c/strong\u003e \u003cbr\u003eBe carbon neutral for our own operations no later than 2025 and across our supply chain by 2030, and committed to becoming a net zero business well ahead of 2050\u003cbr\u003e\u003cbr\u003e\u003cstrong\u003eObjective 02\u003c/strong\u003e \u003cbr\u003eTransition to 100% renewable electricity by 2025, and electric vehicles by 2030\u003cbr\u003e\u003cbr\u003e\u003cstrong\u003eObjective 03 \u003c/strong\u003e\u003cbr\u003eHelp our clients to save 10m tons of Co2 eq by 2030\u003cbr\u003e\u003cbr\u003e\u003ca Find out more on environmental sustainability\u003c/a\u003e"}

```

### WordPress information

WordPress is managed by the WordPress VIP

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TomaGap** [comment]
Yes Looks good

**Comment by jeffpaul** [comment]
@amalajith welcome to Distributor, thanks for the report, and for the resulting PR!  We'll get the PR through review and get back to you with any questions or concerns, thanks again!
