### ISSUE TITLE
Gutenberg editor requires refresh in order to see Distributor after publishing post

### ISSUE THREAD

**Issue by espechtcfe** [10up/distributor#903]
### Describe your question

We've just added Distributor to a new multisite and we've found that with this site that uses the Gutenberg editor, after publishing a post, we need to manually refresh the page in order to see Distributor.  This was not an issue on our non-Gutenberg site.

Is there a way to make it so that once a post is published that Distributor can show up automatically?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@espechtcfe note that this is a duplicate of #141, so I'm closing this in favor of 141 and recommend subscribing to updates on that issue to see when an update is available that resolve the issue... thanks!
