### ISSUE TITLE
Bump WordPress and PHP minimums

### ISSUE THREAD

**Issue by vikrampm1** [10up/distributor#905]
Bump WP & PHP Minimums to the following
 
- [x] WordPress to 5.7
- [x] PHP to 7.4
- [x] Remove any no-longer-needed conditional code for older version support.
- [x] Take a look at adjusting our testing matrices, if applicable.
- [x] Bump the minimums in plugin documentation and header fields.

Misc
- [x] remove references to gutenberg_get_jed_locale_data
- [x] Application passwords always available (even if they are not enabled)

**Comment by peterwilsoncc** [comment]
I've put this on the 2.0.0 milestone to action early and avoid adding any new code to support older versions of WP or PHP.
