### ISSUE TITLE
Connection issue with External Site

### ISSUE THREAD

**Issue by jedunndigital** [10up/distributor#915]
I am trying to connect two of my sites. I was able to establish a connection from site A to site B, and pull in content. However, when I try to establish a connection from site B to site A, I get this error response:

Unable to connect to site.
cURL error 28: Operation timed out after 5006 milliseconds with 0 bytes received (http_request_failed)

Both sites are set up on the same local server and running identical software/plugins. I was able to use the wizard to establish the first connection after dropping in the Application Passwords code on both sites.

**Comment by jeffpaul** [comment]
@jedunndigital are you able to provide a Site Health export for the two sites for us to compare and see if there's something that appears amiss in those setup details?
