### ISSUE TITLE
Custom post type gets copied as a regular post

### ISSUE THREAD

**Issue by pdewouters** [10up/distributor#919]
### Describe your question

I have 2 sites on a multisite network, with a CPT `nt_course`, but when I "distribute" it, it gets cloned as a `post` , not as a CPT. Any suggestions?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andygagnon** [comment]
Same for me.
Distributed content shows correct correct Post Type in Pulled Content From, but the content shows up in the  Posts Editor.

**Comment by dkotter** [comment]
Thanks for the report! I have a [PR](https://github.com/10up/distributor/pull/922) up to fix this, if anyone here is available to test that and ensure it fixes this issue. Thanks!

**Comment by claycarpenter** [comment]
@dkotter Just ran a handful of quick tests on your PR, and it does indeed seems to fix the issue. Thanks for the quick fix!

Tested on a page and a handful of posts across two different CPTs.
