### ISSUE TITLE
WPBakery / Media IDs 

### ISSUE THREAD

**Issue by pixelpublic** [10up/distributor#920]
### Describe your question

I tried out your plugin yesterday the first time - and it seems to be exactly what I was looking for. But - using WPBakery, I have the same issue as mentioned before: Images are transferred to the media folder of the site which is pulling the content from another site but since WPBakery uses the image/media ID for used images inside the content, the images are broken then. I did not find a solution for this but maybe there is an existing extension or code addon which replaces the old image id with the new one?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Closing in favor of #445 that we're currently targeting to focus on during the 2.2.0 release cycle.
