### ISSUE TITLE
Pages are getting pulled in as posts

### ISSUE THREAD

**Issue by jmstew3** [10up/distributor#921]
Huge issue. Pages are showing up under Distributor > Pull Content > Pages as "Post Type" = Page...

But when I pull them in as draft, they pull in as Posts.

I have replicated this with two different websites/two different External Connections, and have tried to Pull in the reverse (using the Distributor Content website as the receiver...)

This just happened recently. I can't get any of my Pages to pull in as Pages anymore.

**Comment by jmstew3** [comment]
Update: I was using version 1.7.0 and experiencing the issue.

I downgraded to 1.6.4 and I am no longer having the issue.

**Comment by andygagnon** [comment]
I second that.  Pushed/pulled Pages end up in Posts.  Version 1.7.0.  On Multisite.

**Comment by dkotter** [comment]
Thanks for the report! I have a [PR](https://github.com/10up/distributor/pull/922) up to fix this, if anyone here is available to test that and ensure it fixes this issue. Thanks!
