### ISSUE TITLE
Remove application passwords dependency

### ISSUE THREAD

**Issue by pdewouters** [10up/distributor#925]
### Is your enhancement related to a problem? Please describe.

10up install the application passwords plugin, which is abandoned and the feature is included with WP core

### Describe alternatives you've considered

> Package georgestephanis/application-passwords is abandoned, you should avoid using it. No replacement was suggested.

This feature is now in core WordPress, no need to install the plugin.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by peterwilsoncc** [comment]
Hi Paul,

I'm currently working on PR #917 to bump the minimum WordPress and PHP requirements for issue #905. As part of this I've removed the plugin in 5db745c088ec0b9e01e0a46a34387381f5f6466d.

I've moved this issue on to the 2.0.0 milestone to be closed once the pull request is merged.
