### ISSUE TITLE
Could not determine remote post id

### ISSUE THREAD

**Issue by Drmzindec** [10up/distributor#926]
I keep getting the issue: Could not determine remote post id

`{"success":true,"data":{"results":{"internal":[],"external":{"125241":{"date":"August 10, 2022 8:41 am","status":"fail","errors":["Could not determine remote post id."]}}}}}`

What does this even mean? How do I solve this?

**Comment by jeffpaul** [comment]
@Drmzindec what is the context where you're getting this error message?  Can you provide steps where you're able to reproduce this as well as a Site Health export for us to help triage?
