### ISSUE TITLE
Is it possible to Push/Pull only on command?

### ISSUE THREAD

**Issue by chet-tbf** [10up/distributor#927]
### Describe your question

We were hoping to use Distributor in the following way: 

1. Connect One Environment as the Source of Truth.
2. Connect all items which matching Post IDs.
3. Update content on Source of Truth, but not have it distribute until manually pulled.

Is this feasible with Distributor? I have stared exploring the Actions and Filters in the developer documentation, but wanted to also get the opinions of folks here.

Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@chet-tbf you can connect multiple sites and on the non-"Source of Truth" sites use the Distributor Pull functionality to only pull new posts when desired.  Note that unless you sever that Distributor connection between the remote site and your "Source of Truth", any updates on the "Source of Truth" site will automatically sync to those connected remote sites.
