### ISSUE TITLE
 When deleting a distributed post, it should become available for redistribution to that site again.

### ISSUE THREAD

**Issue by adamsilverstein** [10up/distributor#93]
## Description

When deleting a distributed post, it should become available for redistribution to that site again. Currently that does not appear to be the case.

I have distributed my post 'Hello World' from site A to site B. I delete the post from site B. When I view the original post on site A and open the Distributor menu, the connection to site B is disabled - site A won't let me distribute the same post to site B twice, even though I have deleted the distributed copy from site B.

## Steps to reproduce

* Create a post on site A
* Distribute post to site B
* On site B, trash and delete the distributed post
* On site A, open the post again (and refresh)

**Expected behavior:**
The connection to site B should be enabled and I should be able to distribute the post to site B again.

**Actual behavior:**
The connection to site B remains disabled.

**Comment by sillybean** [comment]
This is only partially fixed for internal connections. Site B does show up again in the list of available connections to push from the Site A edit screen. However, on Site B, the trashed post remains in the Pulled list, with "Post deleted." in the date column, and the post isn't available to pull again.

**Comment by adamsilverstein** [comment]
Thanks for the feedback @sillybean, good point. We will investigate and work on fixing this... also pull requests are welcome!

**Comment by barryceelen** [comment]
What happens is that when a post is deleted its ID is still present in the `dt_sync_log..` site setting. The IDs on this list are excluded from the list of posts being made available in the pull screen.

We can:

- Keep it that way but ignore deleted posts from the exclusions list (it will then still show up in the 'pulled' list being marked as deleted
- Remove the post from the `dt_sync_log..` list

I prefer that last option as to me it seems confusing to have the same post show up in the available list _and_ in the pulled list being marked as deleted. The function of the sync log appears to be only to keep track of synced posts to be able to populate the pull screen properly. Proper historical logging of actions would IMHO be better handled by dedicated plugins like [Stream](https://wordpress.org/plugins/stream/).

I'll create a  pull request with a fix.

**Comment by adamsilverstein** [comment]
> I prefer that last option

Also sounds good to me.

> I'll create a pull request with a fix.

Awesome, thank you!

**Comment by barryceelen** [comment]
Issue #83 is related to this issue, just the other way 'round. I've created a pull request #151 that tries to address both of these issues.

**Todo:** Implement fix for this issue for external connections.

**Comment by helen** [comment]
Is this fixed with the merge of #151?

**Comment by jeffpaul** [comment]
@adamsilverstein @barryceelen has this been resolved with the merge of #151?

**Comment by jeffpaul** [comment]
@adamsilverstein @barryceelen can you confirm if this has been resolved with the merge of #151?

**Comment by jeffpaul** [comment]
I'm going to close this as resolved with #151 in the v1.3 release.  If anyone is still seeing this issue, then please comment with steps to replicate it so we can further triage the issue... thanks!
