### ISSUE TITLE
Override author functionality

### ISSUE THREAD

**Issue by sjmwa** [10up/distributor#930]
### Describe your question

Did the override author option go away with latest versions? I see the option to select in documentation and discussion but don't see it when I go to distribute a post.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
@sjmwa Thanks for the question. That option should still be there but note it's located within the Distributor settings page, not something you toggle on/off on an individual post. Within the admin of your site, there should be a Distributor menu item in the left. If you go to that, there should be a Settings menu within and on that page is this option.
