### ISSUE TITLE
Divi page background and media NOT getting pushed

### ISSUE THREAD

**Issue by GenooSource** [10up/distributor#931]
My site is using Divi and a Divi child theme.  I have a page with a video background hero image.  When I push that page to another site, the media is NOT transferring - so there is no background, and I am unable to edit the section background within Divi Builder on the receiving site - it is frozen, locked out, cannot edit or change it.

Also, once I push the page to the specific site, I apparently cannot push any updates for that page again - it's grayed out.  I had to revoke my distributor connection (external connection) and reset it for it to allow another push of the page.

**Comment by jeffpaul** [comment]
Closing this in favor favor of #348 as Divi and other page builders are a known compatibility issue that we're working to resolve as part of our 2.0.0-2.2.0 set of releases.
