### ISSUE TITLE
Custom field meta data not copying over properly

### ISSUE THREAD

**Issue by nineplanets** [10up/distributor#932]
### Describe the bug

I am trying to pull posts from a custom post type, with custom fields created via the Advanced Custom Fields plugin.  Most of them are copying over, but some of them are showing up as blank when the source they pulled from had them filled in.  I suspect it might have to do with the structure of the custom field types.  

We have a repeater group, and inside that is a dropdown with 2 static options (OSLC Scientist or Other), and that copies over fine.  The next is a multi-select menu (field type in ACF is Post Object) listing Scientists (another custom post type), which conditionally shows up depending on if you selected OSLC Scientist in the first menu.  This is the one that's not copying over properly.  And the last one is a text field that shows up if you selected Other in the first menu, and this one also copies over fine.  We have that same structure 3 times on the post type we're pulling over, and on each of them the Scientist field loses it's selections.  The Scientist post type was already pulled over first and has the same list of Scientists as the source site.

### Steps to Reproduce

1. Set up custom post type
2. Set up custom fields with ACF plugin: a repeating group, and a multi-select Post Object field pulling a list of other post types
3. Pull the content from one site to another

### WordPress information

`
### wp-core ###

version: 6.0.1
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: true
user_registration: false
blog_public: 0
default_comment_status: open
environment_type: production
site_count: 2
network_count: 1
user_count: 5
dotorg_communication: true

### wp-dropins (2) ###

advanced-cache.php: true
object-cache.php: true

### wp-active-theme ###

name: Astra Child (astra-child)
version: 1.0.0
author: Brainstorm Force
author_website: http://wpastra.com/about/
parent_theme: Astra (astra)
theme_features: core-block-patterns, astra_hooks, widgets-block-editor, align-wide, automatic-feed-links, title-tag, post-thumbnails, html5, post-formats, custom-logo, customize-selective-refresh-widgets, editor-style, woocommerce, rank-math-breadcrumbs, amp, editor-color-palette, fl-theme-builder-headers, fl-theme-builder-footers, fl-theme-builder-parts, widgets, menus
theme_path: /home/oslcorg/domains/oslc.nineplanetsllc.com/public_html/wp-content/themes/astra-child

### wp-parent-theme ###

name: Astra (astra)
version: 3.9.1
author: Brainstorm Force
author_website: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
theme_path: /home/oslcorg/domains/oslc.nineplanetsllc.com/public_html/wp-content/themes/astra

### wp-themes-inactive (1) ###

Twenty Twenty-Two: version: 1.2, author: the WordPress team

### wp-mu-plugins (2) ###

Oregon Social Learning Center: version: 0.0.1, author: Joe di Stefano
WP Time Capsule: author: Revmakx, version: (undefined)

### wp-plugins-active (17) ###

Advanced Custom Fields PRO: version: 5.12.3, author: Delicious Brains
Advanced Editor Tools (previously TinyMCE Advanced): version: 5.6.0, author: Automattic
Antispam Bee: version: 2.11.1, author: pluginkollektiv
Astra Bulk Edit: version: 1.2.6, author: Brainstorm Force
Astra Pro: version: 3.9.1, author: Brainstorm Force
Backup and Staging by WP Time Capsule: version: 1.22.11, author: Revmakx
Beaver Builder Plugin (Pro Version): version: 2.5.5.3, author: The Beaver Builder Team
Beaver Themer: version: 1.4.2.2, author: The Beaver Builder Team
Custom Post Type UI: version: 1.12.1, author: WebDevStudios
Distributor: version: 1.7.0, author: 10up Inc.
EWWW Image Optimizer: version: 6.7.0, author: Exactly WWW
Formidable Forms: version: 5.4.4, author: Strategy11
iThemes Security Pro: version: 7.1.2, author: iThemes
LiteSpeed Cache: version: 5.2, author: LiteSpeed Technologies
SEOPress: version: 5.8.0.5, author: SEOPress (latest version: 5.9)
SEOPress PRO: version: 5.8.0.1, author: SEOPress (latest version: 5.9)
Ultimate Addons for Beaver Builder: version: 1.34.6, author: Brainstorm Force

### wp-plugins-inactive (22) ###

Advanced Custom Fields Multilingual: version: 1.10.3, author: OnTheGoSystems
Better Search Replace: version: 1.4.1, author: Delicious Brains
Bulk Page Creator: version: 1.1.4, author: Dagan Lev
HappyFiles Pro: version: 1.7, author: Codeer
Import / Export Customizer Settings: version: 1.0.6, author: Brainstorm Force
InfiniteWP - Client: version: 1.9.8, author: Revmakx
Media File Renamer (Pro): version: 5.4.0, author: Jordy Meow
Meta Box: version: 5.6.6, author: MetaBox.io
Meta Box AIO: version: 1.15.8, author: MetaBox.io
NP Custom Post Type: version: 1.0, author: Nine Planets, LLC
Post Type Switcher: version: 3.2.1, author: Triple J Software, Inc.
Query Monitor: version: 3.9.0, author: John Blackbourn
Simple Page Ordering: version: 2.4.1, author: Jake Goldman, 10up
UpdraftPlus - Backup/Restore: version: 1.22.14, author: UpdraftPlus.Com, DavidAnderson
User Switching: version: 1.7.0, author: John Blackbourn & contributors
WordPress Importer: version: 0.7, author: wordpressdotorg
WP All Import - ACF Add-On: version: 3.3.7, author: Soflyy
WP All Import Pro: version: 4.7.3, author: Soflyy
WPML All Import: version: 2.3.0, author: OnTheGoSystems
WPML Media: version: 2.7.0, author: OnTheGoSystems
WPML Multilingual CMS: version: 4.5.8, author: OnTheGoSystems
WPML String Translation: version: 3.2.1, author: OnTheGoSystems

### wp-media ###

image_editor: EWWWIO_Imagick_Editor
imagick_module_version: 1808
imagemagick_version: ImageMagick 7.1.0-20 Q16-HDRI x86_64 2022-01-22 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: File uploads is turned off
post_max_size: 32M
upload_max_filesize: 32M
max_effective_size: 32 MB
max_file_uploads: 20
gd_version: 2.2.5
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 4.18.0-348.20.1.lve.1.el8.x86_64 x86_64
httpd_software: LiteSpeed
php_version: 7.4.30 64bit
php_sapi: litespeed
max_input_variables: 1000
time_limit: 120
memory_limit: 512M
max_input_time: -1
upload_max_filesize: 32M
php_post_max_size: 32M
curl_version: 7.71.0 OpenSSL/1.1.1p
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.4.25-MariaDB-cll-lve-log
client_version: mysqlnd 7.4.30
max_allowed_packet: 268435456
max_connections: 150

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/oslcorg/domains/oslc.nineplanetsllc.com/public_html/wp-content
WP_PLUGIN_DIR: /home/oslcorg/domains/oslc.nineplanetsllc.com/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 64M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### distributor ###

0: 1.7.0
1: No
2: N/A
3: 
	Override Author Byline: Yes
	Media Handling: Featured image and attached images
4: 
	Oregon Social Learning Center: 
- Blog ID: 1
- URL: https://oslc.nineplanetsllc.com
- Registered: 2022-05-10 14:33:27
- Last updated: 2022-08-12 18:18:20
5: N/A

`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Closing this in favor of #81, as ACF is a known compatibility issue with Distributor that we're working towards resolving in our 2.0.0-2.2.0 set of releases.
