### ISSUE TITLE
[Repo config] Protect branch `develop-v1`

### ISSUE THREAD

**Issue by peterwilsoncc** [10up/distributor#943]
### Is your enhancement related to a problem? Please describe.

Please protect the `develop-v1` branch.

To allow for future 1.x releases while version 2.0.0 is being worked on, I've created the `develop-v1` branch.

This will allow us to do cherry-pick releases, for example to include #937 without including the minimum requirement bump in the minor release.

The branch was created from e0f54107b80dd4ddea46b0711d930cd722fc7bd3 (the merge of the 1.7.1 release PR).

### Describe alternatives you've considered

YOLO merging. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
This has been done
