### ISSUE TITLE
Update usages of `blacklist` to be more inclusive

### ISSUE THREAD

**Issue by dkotter** [10up/distributor#960]
### Is your enhancement related to a problem? Please describe.

We have a handful of places that still use the term `blacklist` (mostly in our utilities). We should look to update these to use something like `excluded` instead.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by peterwilsoncc** [comment]
Reopening due to incorrect use of `apply_filters_deprecated`, PR incoming
