### ISSUE TITLE
How to automatically unlink on pull or push?

### ISSUE THREAD

**Issue by garman22** [10up/distributor#965]
### Describe your question

I'd like to be able to automatically unlink all posts that are pulled from one site to another. Basically I would like all posts to be unlinked by default. 

I'm making a (poor) attempt at trying to make use of the hooks available and have come up with the following to add to my functions.php file :  

`add_action( 'dt_push_post', 'auto_unlink' );
add_action( 'dt_pull_post', 'auto_unlink' );
function auto_unlink( $new_post_id ) {
do_action( 'dt_unlink_post', $post_id ); 
}`

Needless to say, it doesn't work.  What do I need to add to my functions.php file so that **all pulled (or pushed) posts are unlinked by default**? 
Thanks! 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by peterwilsoncc** [comment]
Hi @garman22, you can use the `dt_after_set_meta` action to automatically unlink posts. This will apply to posts that have been both pushed and pulled.

```php
/**
 * Auto unlink distributor posts automatically.
 * 
 * Runs on the `dt_after_set_meta` hook.
 * 
 * @param mixed $meta          All received meta for the post
 * @param mixed $existing_meta Existing meta for the post
 * @param mixed $post_id       Post ID
 * @return void 
 */
function garman22_auto_unlink_distributed_posts( $meta, $existing_meta, $post_id ) {
	$post = get_post( $post_id );

	if ( ! $post ) {
		return;
	}

	$is_distrubuted = get_post_meta( $post->ID, 'dt_original_post_id', true ) ? true : false;

	if ( ! $is_distrubuted ) {
		return;
	}

	update_post_meta( $post->ID, 'dt_unlinked', true );
}
add_action( 'dt_after_set_meta', 'garman22_auto_unlink_distributed_posts', 10, 3 );
```

Distributor includes two filters that allow plugins to prevent Distributor from setting any meta data, `dt_pull_post_meta` and `dt_push_post_meta`.

If another plugin has modified these filters to prevent the setting of meta data, then the above code sample will fail. It's unlikely that is the case though. In the remote event it has happened, you may be able to modify the code above to make use of the [WordPress action `wp_after_insert_post`](http://developer.wordpress.org/reference/hooks/wp_after_insert_post/).

Please let me know how you go.

**Comment by garman22** [comment]
Works perfectly @peterwilsoncc big thanks!  Is it worth including this one in the snippets for others to use?

**Comment by peterwilsoncc** [comment]
I'm glad to hear it worked for you.

I've created #971 to add an example for setting/modifying meta data using the `dt_after_set_meta` to modify adding or removing custom meta data.

I'll close this ticket off and consider further the bet way to document an example.
