### ISSUE TITLE
Taxonomy as Filter in Pull Menu

### ISSUE THREAD

**Issue by salamalala** [10up/distributor#972]
Hi there, 

I was wondering whether its possible to also use a taxonomy as a filter in the pull menu. I was looking through the documentation but couldn't find anything pointing to that. 

Thanks for your help!
Nina

**Comment by peterwilsoncc** [comment]
Hi @salamalala 

There are a couple of filters you can use to limit the pull screen to display posts with a specific term applied or containing any term from a specific taxonomy: `dt_remote_get_query_args` for internal (Multisite) connections and `dt_get_pull_content_rest_query_args` for external connections.

In my testing it does not prevent you from pushing posts without the term/taxonomy applied. It only affects the pulling of content. I was not seeing any affect other actions but I'd recommend double checking that on your own systems.

```php
function distributor_972_add_taxonomy_query_to_pull_listings( $args ) {
	// Ignore if getting a specific post or posts.
	if (
		isset( $args['post__in'] ) ||
		isset( $args['p'] ) ||
		isset( $args['page_id'] ) ||
		isset( $args['pagename'] ) ||
		isset( $args['name'] ) ||
		isset( $args['post_name__in'] )
	) {
		return $args;
	}

	// Limit to Post with a specific term.
	$args['tax_query'] = [
		[
			'taxonomy' => 'post_tag',
			'field'    => 'slug',
			'terms'    => [ 'tag-1' ],
		],
	];

	// OR: Use this instead to limit to posts with terms on a specific taxonomy.
	// $args['tax_query'] = [
	// 	[
	// 		'taxonomy' => 'post_tag',
	// 		'operator' => 'EXISTS',
	// 	],
	// ];

	return $args;
}

// Limit for network (Multisite) connections.
add_filter( 'dt_remote_get_query_args', 'distributor_972_add_taxonomy_query_to_pull_listings' );
/*
 * Limit for external connections.
 *
 * This is intended to run on the server from which queries are being pulled.
 */
add_filter( 'dt_get_pull_content_rest_query_args', 'distributor_972_add_taxonomy_query_to_pull_listings' );
```

Please let me know if this helps your use case. I'll leave the ticket open for now awaiting your feedback.
