### ISSUE TITLE
ACF blocks - missing images after pull

### ISSUE THREAD

**Issue by lightson** [10up/distributor#973]
### Describe your question

New user, really liking the functionality, nice work!

I'm using Distributor in a multisite setup and have media handling set to "Process the featured image and any attached images."

An issue I'm running into is that we use ACF blocks for much of our site content. All blocks are being copied over along with and their text content, but images within them are not. I'm not seeing any error messaging or indication that something has gone wrong.

Am I correct that this falls under the Post Meta Associations known issue?

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@lightson there is a known issue with ACF, so I'm closing this in favor of #81 where you'll be better served subscribing and watching for updates there on a planned future Distributor release to handle this issue... thanks!

**Comment by lightson** [comment]
Ah apologies @jeffpaul, hadn't spotted that ticket. Will sub.
