### ISSUE TITLE
Distributed articles aren't causing Nitropack to clear the cache on the page

### ISSUE THREAD

**Issue by espechtcfe** [10up/distributor#978]
### Describe the bug

Since we just upgraded our Wordpress to 6.1.1 we've noticed an issue where a distributed article is not causing Nitropack to auto-clear the cache.  I've been communicating with their support and running many tests and we've determined that the issue only exists when it is a distributed article.  If I unlink the article and make a change, I see that change reflected when not logged into wordpress.  But if the article is linked and we change it at the main site - the content gets updated as expected in the backend of the other site, but for some reason Nitropack is not clearing the cache.  If I manually clear the Nitro cache for the page, I see the change reflected.
I tried to get some info from them on what causes the cache to be auto-cleared, but they didn't tell me.  The issue is intermittent - it does work on occasion, but 90% of the time it isn't clearing the cache for the page.  I just spoke with WPEngine support and they aren't seeing any errors related to this when I try to reproduce the issue.
We're using version 1.8.0 of the Distributor plugin.  Please let me know if you have any suggestions.

### Steps to Reproduce

I make a change on an article that has already been distributed.
The changes show when previewing the article while logged in, but most of the time the change doesn't show when not logged in.
If I manually purge the Nitro cache for the page, I see the change.
If I unlink that article and make the change directly on it on that site, then the cache clears for the page as expected.

### Environment information

Wordpress 6.1.1
Distributor 1.8.0
Nitropack 1.5.17
Hosted on WPEngine

### WordPress information

Wordpress 6.1.1
Distributor 1.8.0
Nitropack 1.5.17
Hosted on WPEngine

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@espechtcfe this sounds like whatever WP core hook Nitrocache is using is not properly catching the way in which Distributor updates content.  You might ask them to validate what they're hooking into to help further triage things here.
