### ISSUE TITLE
Problem using Foxiz theme

### ISSUE THREAD

**Issue by ronaldomarcos** [10up/distributor#979]
### Describe the bug

I'm not looking for a solution, just a warning, the plugin cannot connect to sites that are using the Foxiz theme. I installed the theme, no more plugins, for testing, and it doesn't connect either, I tried a few more things to no avail.

The first time I encountered this problem I had several plugins installed, the site was already being used for a while, so I decided to try a "clean" site. I'll keep looking where I can try to solve this, I've already posted to warn anyone who has encountered the problem or who wants to use Foxiz with it.

Foxis uses Elementor, but on the test install I didn't install anything other than the theme.

### Steps to Reproduce

1. Installing Wordpress
2. Installing Foxiz Theme
3. Installing Distributor
4. Try remote connection

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Closing in favor of the broader Page Builder issue #348.
