### ISSUE TITLE
Release 1.8.0 requires an abandoned package

### ISSUE THREAD

**Issue by mattradford-sage** [10up/distributor#980]
### Describe the bug

Release 1.8.0 contains an outdated `composer.json`, which results in loading a deprecated package.

- `composer.json` was [last updated September 8th](https://github.com/10up/distributor/commit/41fff260e9411690118c8ddc35d35d34384ab65a)
- `georgestephanis/application-passwords` was removed in [the previous commit on August 3rd ](https://github.com/10up/distributor/commit/5db745c088ec0b9e01e0a46a34387381f5f6466d)
- Release 1.8.0 was [released on September 29th](https://github.com/10up/distributor/releases/tag/1.8.0)

Running `composer update` or `install` that includes Distributor 1.8.0 results in the `application-password` package being installed and the warning:
`Package georgestephanis/application-passwords is abandoned, you should avoid using it. No replacement was suggested.`

Since the minimum WordPress requirement for Distributor is 5.7 and application passwords were added to core in 5.6, the package `georgestephanis/application-passwords` can safely be removed.

Could you please push a bugfix release in order to remove `georgestephanis/application-passwords` as a requirement. Thank you :)

### Steps to Reproduce

1. Download https://github.com/10up/distributor/releases/tag/1.8.0
2. Note that `composer.json` contains the repository and requirement for `georgestephanis/application-passwords`
3. Adding `"10up/distributor": "1.8.0"` as a dependency to a composer file results in the composer abandoned warning.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/95643968/205052006-023fcef9-023b-42e7-a86f-ae20ff3ffce7.mov

### Environment information

 - Macbook 16" (2019)
 - macOS 12.6.1

### WordPress information

WP 6.0.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by peterwilsoncc** [comment]
Hi @mattradford-sage and thanks for raising the issue.

The currently stable version of Distributor supports WordPress versions 4.7 and later, so still requires the applications-passwords composer pacakge. Within the plugin it's loaded conditionally to avoid running the code in WordPress versions including the feature natively.

We are currently working on version 2.0.0 which will bump the minimum WordPress requirements and allow for the applications passwords fallback to be removed. See #905 and #925.

I am seeing another warning about an abandoned package so will investigate fixing that for the 2.0.0 release.

**Comment by mattradford-sage** [comment]
Thanks for the detailed response @peterwilsoncc.
