### ISSUE TITLE
Ensure Distributor to work across connected intranet sites (especially ones protected by RSA)

### ISSUE THREAD

**Issue by vikrampm1** [10up/distributor#986]
A question came in on the RSA page:
Does this plug-in enable Application password to be used ?
We have a multi site install and we use the 10up Syndication plug-in between sites external sites. With the restricted site access enabled the syndication can no longer authenticate on our primary site to initiate the connection.

Need Solution: Allow Distributor to still function when the Restricted Site Access is active on the site.  

More details: https://10up.slack.com/archives/C84M9AA06/p1670264664916879

**Comment by jeffpaul** [comment]
Closing in favor of https://github.com/10up/restricted-site-access/issues/237 likely being the better course of action for resolving this issue.
