### ISSUE TITLE
Unpublish ditributed post

### ISSUE THREAD

**Issue by pdewouters** [10up/distributor#990]
### Describe your question

Distributor 1.9.0
WP 6.1.1

Created a post on source/original site, and distribute to destination site. Publish it on destination site, and attempt to switch back to draft. The modal is disabled

![Screenshot 2023-01-04 at 09 41 44](https://user-images.githubusercontent.com/30460/210534433-f80f87b6-c345-4e8b-8bd4-a22bda38cef0.JPG)

How can I unpublish a distributed post?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by peterwilsoncc** [comment]
Hi Paul,

I'm able to reproduce this issue.

I could work around the bug using the following steps

1. Unlink the distributed post
2. Switch to draft, confirmation modal is active.
3. Relink the distributed post, it remains in draft. This is to ensure updates continue to be received, the post will remain in draft.

While it's intended that much of the post edit screen be disabled on linked posts, this seems like it might be a use-case in which it's helpful to allow the site owner to make some changes. I'll discuss this with some of the product owners and investigate the possibilities.

**Comment by pdewouters** [comment]
thanks @peterwilsoncc :)
