### ISSUE TITLE
Easiest way to distribute to an existing Post of a connected site

### ISSUE THREAD

**Issue by aaronware** [10up/distributor#992]
### Describe your question

We have a few sites that were historically _not_ connected using distributor but they previously were cloned versions of an original site. Many of the post IDs are the same however there are many that are not. Is there a way (maybe using the CLI or using another method) where you can force a mapping between posts on each site if you know the Post ID of the original post and the Post ID of the Post you want to connect to?

Site A : Push Post 123 -> Site B Post ID 124 (overriding any content that is on 124 as needed)

It's OK to overwrite the post on the receiving side in this scenario. Currently, if we try to distribute to a receiving site, we would create a New post of the same name.

I looked through the documentation but nothing jumped out at me and I didn't see any issues that used similar terminology to what I was using in this issue.

Any help/shove in the right direction is greatly appreciated. @jeffpaul if this is something that I should reach out to you directly let me know.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by peterwilsoncc** [comment]
Hi Aaron, 

At the moment Distributor doesn't have any WP-CLI commands built in, nor a way to do this via the UI.

The only thing I can think of that might work is to manually add the post meta required at either end for connecting to the each post.

1. Connect the two sites
2. On Site A (source) add the meta data items `dt_subscriptions` and `dt_connection_map`
3. On Site B (distributed) add the meta data items `dt_original_post_url`, `dt_original_site_name`, `dt_original_site_url`, `dt_subscription_signature`, `dt_original_post_id`, `dt_original_source_id`

This is presuming external connections based on your comment about the sites been cloned.

The data for creating subscriptions and subscription signatures can be found in `includes/subscriptions.php`. The connections map is created in `includes/classes/API/SubscriptionsController.php`.

You may also be able to use the custom rest data in `includes/rest-api.php` to assist with creating the meta data.

**Comment by aaronware** [comment]
Hey @peterwilsoncc this is awesome information and a great shove in the right direction.

What I might experiment with (if there are hooks available) is to extend the grey dropdown area on the front-end admin bar to allow for either a manual xhr search of a given post type and post title or possibly based on the title of the post they are currently on. While the Post IDs are not 💯 matches. The titles of the posts typically are. If there aren't any related hooks within the frontend UI. I'll probably just cook up a similar UI since it's something that probably will be ongoing since it's 5+ sites that are being distributed to

**Comment by peterwilsoncc** [comment]
We're generally happy to add hooks to the plugin so if you find yourself one action or filter short of been able to do something, drop a note here and we'll consider it.

Please let us know how you get on, we're always interested to see any plugins created to extend the core functionality of the plugin.
