### ISSUE TITLE
Attachment images not getting transferred

### ISSUE THREAD

**Issue by yogeshbeniwal** [10up/distributor#993]
### Describe the bug

Images used within posts are not transferred to destination website even when `Process the featured image and any attached images.` is enabled on both sites.

### Steps to Reproduce

1. Connect Site A and Site B as external connection from Site A
2. Configure settings on both sites as shown below

![Screenshot](https://user-images.githubusercontent.com/7325107/211127703-e66507f8-5805-4af4-9b24-e2778aef16be.png)

4. Push a post (With featured image and in article images) from Site A to Site B as Draft
5. Publish post on site B manually
6. Observe that only featured image is pushed to media library of site B, in article images are not pushed to site B media library and are used with site A URL.

### WordPress information

Provided as comment to this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yogeshbeniwal** [comment]
### wp-core ###

version: 6.1.1
site_language: en_US
user_language: en_US
timezone: Asia/Kuala_Lumpur
permalink: /%category%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 2
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/pub.dhakadmedia.com/htdocs
wordpress_size: 50.28 MB (52718190 bytes)
uploads_path: /var/www/pub.dhakadmedia.com/htdocs/app/uploads
uploads_size: 222.19 MB (232988184 bytes)
themes_path: /var/www/pub.dhakadmedia.com/htdocs/app/themes
themes_size: 4.78 MB (5012326 bytes)
plugins_path: /var/www/pub.dhakadmedia.com/htdocs/app/plugins
plugins_size: 106.68 MB (111863624 bytes)
database_size: 58.50 MB (61341696 bytes)
total_size: 442.43 MB (463924020 bytes)

### wp-dropins (1) ###

object-cache.php: true

### wp-active-theme ###

name: Newspack (newspack-theme)
version: 1.65.3
author: Automattic
author_website: https://newspack.com
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, automatic-feed-links, title-tag, post-thumbnails, menus, html5, custom-logo, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-style, editor-font-sizes, editor-color-palette, editor-gradient-presets, custom-spacing, responsive-embeds, amp, post-subtitle, web-stories, widgets
theme_path: /var/www/pub.dhakadmedia.com/htdocs/app/themes/newspack-theme
auto_update: Disabled

### wp-themes-inactive (1) ###

Twenty Twenty-Three: version: 1.0, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (26) ###

Cloudflare: version: 4.11.0, author: Cloudflare, Inc., Auto-updates disabled
Co-Authors Plus: version: 3.5.7, author: Mohammad Jangda, Daniel Bachhuber, Automattic, Auto-updates disabled
Co-Authors Plus Social Pack: version: 0.1, author: Automattic, Auto-updates disabled
Code Snippets: version: 3.2.2, author: Code Snippets Pro, Auto-updates disabled
Distributor: version: 1.9.0, author: 10up Inc., Auto-updates disabled
Edit Flow: version: 0.9.7, author: Daniel Bachhuber, Scott Bressler, Mohammad Jangda, Automattic, and others, Auto-updates disabled
Enable Media Replace: version: 4.0.1, author: ShortPixel, Auto-updates disabled
iThemes Security: version: 8.1.4, author: iThemes, Auto-updates disabled
My Private Site: version: 3.0.11, author: David Gewirtz, Auto-updates disabled
Newspack Blocks: version: 1.59.1, author: Automattic, Auto-updates disabled
Newspack Newsletters: version: 1.55.1, author: Automattic, Auto-updates disabled
Nginx Helper: version: 2.2.2, author: rtCamp, Auto-updates disabled
Perfmatters: version: 2.0.2, author: forgemedia, Auto-updates disabled
Performance Lab: version: 1.8.0, author: WordPress Performance Team, Auto-updates disabled
PublishPress Checklists: version: 2.7.3, author: PublishPress, Auto-updates disabled
PublishPress Series: version: 2.10.1, author: PublishPress, Auto-updates disabled
Redirection: version: 5.3.6, author: John Godley, Auto-updates disabled
Redis Object Cache: version: 2.2.2, author: Till Krüss, Auto-updates disabled
Simple Local Avatars: version: 2.7.1, author: Jake Goldman, 10up, Auto-updates disabled
Stream: version: 3.9.1, author: XWP, Auto-updates disabled
WordPress Ping Optimizer: version: 2.35.1.3.0, author: Pankaj Jha, Auto-updates disabled
WP External Links: version: 2.57, author: WebFactory Ltd, Auto-updates disabled
WPForce Logout: version: 1.5.0, author: Sanjeev Aryal, Auto-updates disabled
YaySMTP - Simple WP SMTP Mail: version: 2.2.9, author: YayCommerce, Auto-updates disabled
Yoast SEO: version: 19.13, author: Team Yoast, Auto-updates disabled
Yoast SEO Premium: version: 18.8, author: Team Yoast, Auto-updates disabled

### wp-plugins-inactive (2) ###

Newspack Listings: version: 2.12.2, author: Automattic, Auto-updates disabled
Web Stories: version: 1.28.1, author: Google, Auto-updates disabled

### code-snippets (5) ###

snippet-3: name: PWA, scope: front-end, modified: 2022-05-26 12:07:24
snippet-5: name: Security, scope: front-end, modified: 2021-07-23 02:31:21
snippet-6: name: Ux/UI, scope: front-end, modified: 2022-04-22 06:47:34
snippet-7: name: SEO, scope: front-end, modified: 2022-05-26 12:06:57
snippet-11: name: Distributor, scope: global, modified: 2023-01-06 15:34:59

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: File uploads is turned off
post_max_size: 100M
upload_max_filesize: 100M
max_effective_size: 100 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JBG, JBIG, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMV, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, AVIF, XPM
ghostscript_version: 9.50

### wp-server ###

server_architecture: Linux 5.4.0-135-generic x86_64
httpd_software: nginx/1.22.1
php_version: 8.2.0 64bit
php_sapi: fpm-fcgi
max_input_variables: 20000
time_limit: 300
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 300
upload_max_filesize: 100M
php_post_max_size: 100M
curl_version: 7.68.0 OpenSSL/1.1.1f
suhosin: false
imagick_availability: true
pretty_permalinks: true

### wp-database ###

extension: mysqli
server_version: 10.6.11-MariaDB-1:10.6.11+maria~ubu2004-log
client_version: mysqlnd 8.2.0
max_allowed_packet: 67108864
max_connections: 100

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/pub.dhakadmedia.com/htdocs/app
WP_PLUGIN_DIR: /var/www/pub.dhakadmedia.com/htdocs/app/plugins
WP_MEMORY_LIMIT: 128M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: false
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### publishpress-modules (6) ###

settings: on [/var/www/pub.dhakadmedia.com/htdocs/app/plugins/publishpress-checklists//modules/modules/settings]
checklists: on [/var/www/pub.dhakadmedia.com/htdocs/app/plugins/publishpress-checklists//modules/modules/checklists]
permalinks: on [/var/www/pub.dhakadmedia.com/htdocs/app/plugins/publishpress-checklists//modules/modules/permalinks]
yoastseo: on [/var/www/pub.dhakadmedia.com/htdocs/app/plugins/publishpress-checklists//modules/modules/yoastseo]
permissions: on [/var/www/pub.dhakadmedia.com/htdocs/app/plugins/publishpress-checklists//modules/modules/permissions]
reviews: on [/var/www/pub.dhakadmedia.com/htdocs/app/plugins/publishpress-checklists//modules/modules/reviews]

### distributor ###

0: 1.9.0
1: Yes
2: XXXX@gmail.com
3: 
	Override Author Byline: No
	Media Handling: Featured image and attached images
4: N/A
5: 
	Dhakad Media: 
- URL: https://www.dhakadmedia.com/wp-json/
- Version: 1.9.0
- Status: valid
- Auth method: Username / Password
- Username: yogesh
- Roles Allowed to Push: administrator, editor
- Additional data: {"errors":[], "can_post":["post", "page", "attachment", "nav_menu_item", "wp_block", "wp_template", "wp_template_part", "wp_navigation", "guest-author", "block_pattern"], "can_get":["post", "page", "attachment", "nav_menu_item", "wp_block", "wp_template", "wp_template_part", "wp_navigation", "guest-author", "block_pattern"], "endpoint_suggestion":false, "is_authenticated":"yes"}
	TheAccSense: 
- URL: https://www.theaccsense.com/wp-json/
- Version: 1.9.0
- Status: valid
- Auth method: Username / Password
- Username: yogesh
- Roles Allowed to Push: administrator, editor
- Additional data: {"errors":[], "can_post":["post", "page", "attachment", "nav_menu_item", "wp_block", "wp_template", "wp_template_part", "wp_navigation", "product", "guest-author", "newspack_ad_codes", "newspack_nl_cpt", "newspack_popups_cpt", "jp_pay_order", "jp_pay_product"], "can_get":["post", "page", "attachment", "nav_menu_item", "wp_block", "wp_template", "wp_template_part", "wp_navigation", "product", "guest-author", "newspack_ad_codes", "newspack_nl_cpt", "newspack_popups_cpt", "jp_pay_order", "jp_pay_product"], "endpoint_suggestion":false, "is_authenticated":"yes"}
	Malgeek: 
- URL: https://www.malgeek.com/wp-json/
- Version: 1.9.0
- Status: valid
- Auth method: Username / Password
- Username: yogesh
- Roles Allowed to Push: administrator, editor
- Additional data: {"errors":[], "can_post":["post", "page", "attachment", "nav_menu_item", "wp_block", "wp_template", "wp_template_part", "wp_navigation", "product", "guest-author", "newspack_ad_codes", "newspack_nl_cpt", "newspack_popups_cpt", "jp_pay_order", "jp_pay_product"], "can_get":["post", "page", "attachment", "nav_menu_item", "wp_block", "wp_template", "wp_template_part", "wp_navigation", "product", "guest-author", "newspack_ad_codes", "newspack_nl_cpt", "newspack_popups_cpt", "jp_pay_order", "jp_pay_product"], "endpoint_suggestion":false, "is_authenticated":"yes"}

**Comment by peterwilsoncc** [comment]
Hi Yogesh,

We've been able to reproduce this issue and are tracking it for a fix in issue #975.

I'm going to close this issue as a duplicate to allow any discussion to remain on the original ticket.

Cheers,
Peter
